apache/tinkerpop

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/GraphBinaryWriter.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/BindingSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/BulkSetSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/ByteCodeSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/CollectionSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/CustomTypeSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/EdgeSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/GraphSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/LambdaSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/MapSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/MetricsSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/PathSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/TraversalMetricsSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/TraversalStrategySerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/TraverserSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/TreeSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/VertexPropertySerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/VertexSerializer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/binary/TypeSerializerFailureTests.java
https://issues.apache.org/jira/browse/TINKERPOP-2154
Ensures that reference counts of allocated buffers are set to 0 when there is a failure during serialization.
Includes a test for memory allocation when introducing failures.
VOTE +1
> TINKERPOP-2154 GraphBinary: Release working buffers on failure

- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
Changed loop break check to break out of the connection creation loop if greater than or equal to the expected amount of connections are created. A situation exists where unless exactly the expected amount of connections are made when checked, an infinite loop of connections may be opened.
> Changed loop break check to break out of the connection creation loop

- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/graph.js
I'm going through the process of creating typescript definitions for the javascript library, and I noticed a bug in Path#toString(). It incorrectly attempts to call a non-existant local `objects` variable instead of calling the class property `this.objects`.
> fix: Path#toString() variable reference bug

- docs/src/tutorials/gremlins-anatomy/index.asciidoc
New contributor here. I was reading through the "Gremlin's Anatomy" tutorial and noticed some typos and confusing (to me) wording. Please let me know if I should open up an issue for this PR.
> Fix typos and wording

- CHANGELOG.asciidoc
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java
- gremlin-python/src/main/jython/gremlin_python/statics.py
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV2d0.py
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/jython/setup.py
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV2d0.py
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py
https://issues.apache.org/jira/browse/TINKERPOP-1435
Implemented `Duration`, `Char`, `ByteBuffer`, `Byte`, `BigInteger` and `BigDecimal` which were the most critical ones right now. Tried to do `InetAddress` but there didn't seem to be anything in Python suitable to handled that type except for `ip_address` but it wouldn't parse things like "localhost" and other things that Java will so it seemed a bit incompatible. Also ignored all the `java.time.*` things for now...wonder if those shouldn't just be deprecated....
Builds with `mvn clean install && mvn verify -pl gremlin-python`
VOTE +1
> TINKERPOP-1435 GraphSON extended module support for gremlin-python

- docs/site/home/downloads.html
I didn't bother to create a ticket for this as it's more of a administrative thing, but I've reworked the download page to have a dropdown list of the archived versions. In that way, the page doesn't scroll so much and other content lower in the page is more immediately visible. This should also make our release days a bit less error prone in retiring old versions to archives as it's now just a matter of editing the dropdown to include the archived versions - easier that cut/paste.
What I have is functional though perhaps not awesome in terms of jquery/bootstrap/js so if this can be improved please let me know. I feel like I've tested pretty well, but it would be great if a few folks could `bin/generate-home.sh` and try the mechanics out directly.
VOTE +1
> Improve download page

- CHANGELOG.asciidoc
- pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2134
I bumped this a long time ago - actually started with 2.5.5, but that version seemed to do something unstable to spark for some reason?? before i had time to really investigate 2.5.6 came out so I figured I'd just try that. The spark issue stopped but then there was other build problems with docker so I laid off issuing the PR again. After a number of investigations/fixes around the docker failures which seemed unrelated to this Groovy change, I've finally gotten some consecutive clean docker runs. Still not completely sure that Groovy ever had anything to do with the problem. I'd appreciate if reviewers could do some docker runs themselves to see what their environments show, but other than that, I'm going to go with:
All tests pass …
> TINKERPOP-2134 Bump to Groovy 2.5.6

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/JavaTranslator.java
https://issues.apache.org/jira/browse/TINKERPOP-2163
Every time I think there's nothing else to squeeze out of this class I find something new. This time I cached results of `Method.getParameters()` as well as varargs checks. The former offered the bigger benefit as calls to that method forced a `clone()` of the parameter array, but the latter also helped.
Prior to the change on `tp33` we were getting:
```text
Benchmark                                             Mode  Cnt        Score       Error  Units
JavaTranslatorBenchmark.testTranslationLong          thrpt   20    25812.057 ±   504.233  ops/s
JavaTranslatorBenchmark.testTranslationMedium        thrpt   20   316019.034 ± 13852.097  ops/s
JavaTranslatorBenchmark.testTranslationShort         thrpt   20  1403109.145 ± 41460.176  ops/s …
```
> TINKERPOP-2163 Improved performance of JavaTranslator method selection

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bytecode.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/BytecodeTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2164
> TINKERPOP-2164: Reduce chance of hash collisions in Bytecode and its inner classes

- CHANGELOG.asciidoc
- gremlin-console/pom.xml
- gremlin-console/src/main/static/LICENSE
- gremlin-console/src/main/static/NOTICE
- gremlin-console/src/main/static/licenses/slf4j
- gremlin-server/src/main/static/LICENSE
- gremlin-server/src/main/static/licenses/slf4j
- gremlin-test/pom.xml
- hadoop-gremlin/pom.xml
- pom.xml
Didn't bother to create a JIRA ticket for this as these are basically a batch of lesser version bumps and other pom maintenance type updates. Unified the commons-codec version throughout TinkerPop and setup more reusable dependencyManagement configuration in the parent pom. Updated license/notice as needed given these changes.
VOTE +1
> Bump dependencies for httpclient, commons-codec, slf4j

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/ProfilingAware.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupSideEffectStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ProfileStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/finalization/ProfileStrategy.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1992
Not sure if this the best way to do this but basically introduced an interface called `ProfilingAware` that makes it so that `ProfileStrategy` can notify that step that "profiling" is happening so that the step has a chance to get its life in order. For this particular problem, that meant that `group()` needed to reset its reducing barrier step (if present) for its value traversal (i.e. second `by()` modulator) so that it could internally start the profile timer (which doesn't happen otherwise. 
Tested manually for both OLTP and OLAP and it all worked.
VOTE +1
> TINKERPOP-1992 count has negative time in profile

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/PSerializer.java
- gremlin-tools/gremlin-benchmark/src/main/java/org/apache/tinkerpop/gremlin/driver/GraphBinaryReaderWriterBenchmark.java
https://issues.apache.org/jira/browse/TINKERPOP-2166
Implement a cache for the search of the method in P deserialization.
Includes a micro benchmark:
Before:
```
Benchmark                                 Mode  Cnt      Score      Error  Units
GraphBinaryReaderWriterBenchmark.readP1  thrpt   20  74574.850 ± 2466.040  ops/s
```
With this patch:
```
Benchmark                                 Mode  Cnt        Score       Error  Units
GraphBinaryReaderWriterBenchmark.readP1  thrpt   20  1483588.719 ± 77339.678  ops/s
```
VOTE +1
> TINKERPOP-2166 Cache expression to obtain the method in PSerializer

- CHANGELOG.asciidoc
- docker/Dockerfile
- docker/hadoop/Dockerfile.template
- gremlin-console/Dockerfile
- gremlin-server/Dockerfile
https://issues.apache.org/jira/browse/TINKERPOP-2174
- use least privileged user:group -  `gremlin`
- use the dynamic tag to get the latest image: `openjdk:8-jre-alpine`
also snuck in some non-security ones:
- replaced deprecated `MAINTAINER` with `LABEL maintainer...`
- use  `--no-cache` instead of `rm -rf /var/cache/apk/*`
Tested gremlin-console and gremlin-server images.
VOTE +1
> TINKERPOP-2174 Improve Docker Image Security

- CHANGELOG.asciidoc
- docs/src/reference/compilers.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- sparql-gremlin/src/main/java/org/apache/tinkerpop/gremlin/sparql/process/traversal/dsl/sparql/SparqlTraversalSource.java
- sparql-gremlin/src/main/java/org/apache/tinkerpop/gremlin/sparql/process/traversal/strategy/SparqlStrategy.java
- sparql-gremlin/src/test/java/org/apache/tinkerpop/gremlin/sparql/process/traversal/dsl/sparql/SparqlTraversalSourceTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2171
Allows `sparql()` step to be followed by Gremlin steps:
```text
gremlin> g.sparql("SELECT * WHERE { }").out("knows").values("name")
==>vadas
==>josh
```
VOTE +1
> TINKERPOP-2171 Allow sparql() to be extended with Gremlin steps.

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategy.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategyProcessTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2172
Fix PartitionStrategy to apply to traversal started with addE step. I cherry-picked from #1078 to get this on `tp33` and fix up some other odds/ends.
VOTE +1
> TINKERPOP-2172 Fix PartitionStrategy to apply to AddEdgeStartStep

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Host.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/ClientConnectionIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2169
https://issues.apache.org/jira/browse/TINKERPOP-2173
Similar pull request associated with master branch: #1081  
This pull request corresponds to branch tp33.
**Problem**
1. On receiving a CorruptedFrameException, the current code does not decrement the borrowed count on the connection and marks the connection for destruction. However, the connection never gets destroyed since the it can only be destroyed when the borrowed count is 0. This leads to unnecessary connections waiting in the bin to be cleared.
2. If a connection is serving multiple requests and one of the requests gets a CorruptedFrameException, Netty closes the underlying channel and thus, other requests on the same channel receive a ChannelClosed exception. The current …
> TINKERPOP-2169 Responses exceeding maxContentLength cause subsequent queries to hang

- gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/CopyOnWriteCollection.cs
- gremlin-dotnet/src/Gremlin.Net/Properties/AssemblyInfo.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/CopyOnWriteCollectionTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2135
https://issues.apache.org/jira/browse/TINKERPOP-2148
A Custom copy-on-write (COW) collection is used to store the connections instead of a `ConcurrentBag`. This collection is heavily inspired by the `CopyOnWriteList` in the DataStax C# Driver for Apache Cassandra.
This collection allows for an efficient removal of closed connections which fixes TINKERPOP-2135. Some other operations like `Count` or the removal of all connections are also more efficient.
This new `CopyOnWriteCollection` also enables round-robin scheduling of requests over connections instead of searching for the least used connection which required iterating over all connections and led to
problems when multiple threads in parallel got the same connection and reached the …
> TINKERPOP-2135/2148 Fix removal of closed connections and add round-robin scheduling

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/InetAddressSerializer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/PSerializer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SerializationExceptionTest.java
Same as #1083 but with some minor changes to some errors thrown in the GraphBinary serialization.
I did a `merge -s ours` of the branch `TINKERPOP-2179` to this branch first and then added another commit https://github.com/apache/tinkerpop/commit/00954a92fec41eb19626f050585ad1f300dbd9bf. A merge without the `-s ours` was causing conflicts in all the pom.xml for some reason?
> TINKERPOP-2179: Have SerializationException extend IOException [master]

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/GremlinGroovysh.groovy
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Mediator.groovy
https://issues.apache.org/jira/browse/TINKERPOP-2181
Pretty self-explanatory:
```text
gremlin> java.util.stream.IntStream.range(0, 10000).iterator()
==>0
==>1
==>2
==>3
==>4
...
==>348
==>349
==>350
==>351
==>352
Execution interrupted by ctrl+c
==>353
gremlin> Thread.sleep(5000)
Execution interrupted by ctrl+c
sleep interrupted
Type ':help' or ':h' for help.
Display stack trace? [yN]n
gremlin> g = TinkerGraph.open().traversal()
gremlin> g.addV().as('a').addE('link').to('a')
==>e[1][0-link->0]
gremlin> g.V().repeat(out('link'))
Execution interrupted by ctrl+c
org.apache.tinkerpop.gremlin.process.traversal.util.TraversalInterruptedException
Type ':help' or ':h' for help.
Display stack trace? [yN]n
gremlin> :remote connect …
```
> TINKERPOP-2181 Allow ctrl+c to break a command in Gremlin Console

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-console/pom.xml
- gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/jsr223/UtilitiesGremlinPlugin.java
https://issues.apache.org/jira/browse/TINKERPOP-2182
Pretty straightforward. Made sure that the upgrade docs explained how to continue to use this feature if that is needed. 
VOTE +1
> TINKERPOP-2182 Removed gperfutils dependencies in Console

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
- sparql-gremlin/src/main/java/org/apache/tinkerpop/gremlin/sparql/SparqlToGremlinCompiler.java
- sparql-gremlin/src/main/java/org/apache/tinkerpop/gremlin/sparql/process/traversal/strategy/SparqlStrategy.java
https://issues.apache.org/jira/browse/TINKERPOP-2193
Unclear why this wasn't done originally. As noted in the JIRA we already had the `TraversalSource` passed to the created `Traversal` only to pick and choose bits/pieces we wanted to keep rather than the `TraversalSource` itself.  
VOTE +1
> TINKERPOP-2193 Allow a Traversal to know what TraversalSource it spawned from

- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/TransactionTest.java
The graph thread should be refreshed to observe the result of the committed transaction (see the discussion here https://groups.google.com/forum/#!topic/gremlin-users/2JhAtXcCucE).
> Fix threaded transaction tests. 

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/trait/MultiMetaNeo4jTrait.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2112
Also optimizes a bit to capture additional possible folds to the "AddElementStep" that would have been otherwise missed before. This should enhance performance of certain mutation traversals depending on the positioning and parameterization of the `property()` steps as more folding will occur.
Note that the folding would work properly if the `T.id` was set in the first call to `property()` and that led to:
```text
gremlin> g.addV("person").
......1>   property(T.id , "id").
......2>   property(VertexProperty.Cardinality.single, "k", "v").
......3>   property(VertexProperty.Cardinality.list, "l", 1).
......4>   property("x", "y").
......5>   property(VertexProperty.Cardinality.list, "l", 2).
......6>   property("m", "m", "mm", "mm"). …
```
> TINKERPOP-2112 Fold property() so that T values can work in any order

- CHANGELOG.asciidoc
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/client-test.js
* It is currently possible to configure [opProcessor](https://tinkerpop.apache.org/docs/current/reference/#opprocessor-configurations) by creating custom `RequestMessage` in Gremlin-Java/Groovy, Gremlin.Net and Gremlin-Python
* It [was possible](https://github.com/jbmusso/gremlin-javascript/blob/master/gremlin-client/README.md#usage) to configure opProcessor in Gremlin-JavaScript 2.7.0 before API change
* For consistency, this PR adds an option to configure [opProcessor](https://tinkerpop.apache.org/docs/current/reference/#opprocessor-configurations) in new Gremlin Javascript API
* This is useful, for example, to connect to [Gremlin Server Cypher Plugin](https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-server-plugin#usage)
> Allow to configure processor in Gremlin-JavaScript

- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
https://issues.apache.org/jira/browse/TINKERPOP-2090
Going through the commit history, it looks like the comparison changed in this PR used to be correct but was erroneously flipped after several modifications.
_poolSize is the maximum number of connections in the pool and NrConnections is the actual number of connections currently open. The comparison would previously always be true, causing EnsurePoolIsPopulatedAsync() to always early exit and never repopulate the pool as connections in it were disposed of and removed.
> TINKERPOP-2090: Fix Sign for Checking if Connection Pool Needs to be Repopulated

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategy.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategyProcessTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2196
If includeMetaProperties is enabled and vertex label set then an error would follow because T.label was not being properly accounted for. You can't check cardinality for T.
Built with `mvn clean install -DincludeNeo4j`
VOTE +1
> TINKERPOP-2196 Fixed PartitionStrategy when setting vertex label

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
prevent query like
```
g.addV().as("first").repeat(__.addE("next").to(__.addV()).inV()).times(5).addE("next").to(__.select("first"))
```
from failing static type checking when gremlin server use security sandbox
> TINKERPOP-2201: Change the typing of from() and to() to accept wildcard instead of Vertex

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/jsr223/DriverRemoteAcceptor.java
https://issues.apache.org/jira/browse/TINKERPOP-2203
Passes the console timeout to the server on each `:submit`:
```text
gremlin> :remote config timeout 50
==>Set remote timeout to 50ms
gremlin> :> Thread.sleep(1000);"back"
Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 50 ms or evaluation was otherwise cancelled directly for request [Thread.sleep(1000);"back"]
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.util.concurrent.TimeoutException: Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 50 ms or evaluation was otherwise cancelled directly for request [Thread.sleep(1000);"back"]
at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$1(GremlinExecutor.java:315)
at …
```
> TINKERPOP-2203 Added console remote timeout to each request

- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
https://issues.apache.org/jira/browse/TINKERPOP-2204
The current implementation may lead to a client waiting indefinitely from a response from the server. This occurs in cases when the exceptions that occurred while generating status attributes or generating metadata in the TraversalOpProcessor are consumed in the catch block without sending a response back to the client.
> TINKERPOP-2204 Do not consume the exception while generating metadata

- gremlin-console/pom.xml
I believe having an uber jar for the console might make things easier
for Graph providers, because one can pull in a single jar with all the
dependencies satisfied.
`mvn clean install && mvn verify -pl gremlin-console -DskipIntegrationTests=false` passes
> Create uber jar for gremlin-console

- CHANGELOG.asciidoc
- gremlin-javascript/glv/TraversalSource.template
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/graph-serializer.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/type-serializers.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/graphson-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2206
Seems like javascript arrays were being serialized as naked JSON objects rather than g:List. Java serialization seemed to forgive that for some reason, but prevented certain operations to really work right in the process like P.within() logic from TINKERPOP-2199 which was also fixed in this change.
There may be nicer ways to correct these issues from a javascript programming perspective - I just kinda hammered something in there. Happy to hear better ways to do things.
Builds with `mvn clean install`:
VOTE +1
> TINKERPOP-2206 Fixed g:List serialization

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/RemoteConnection.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/BytecodeUtil.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoVersion.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/BytecodeUtilTest.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestOptions.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Tokens.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnectionTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2211
Support `RequestOptions` with the Java driver using `TraversalSource.with()`. This PR replaces #1109
```text
g = traversal().withRemote(...);
g.with(ARGS_SCRIPT_EVAL_TIMEOUT, 500L).V().has(...).out().....
```
VOTE +1
> TINKERPOP-2211 Add API which allows per-request option for bytecode

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedPath.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferencePath.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedFactoryTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceFactoryTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2212
If the Path contained a Collection it would not properly detach the objects within the collection.
VOTE +1
> TINKERPOP-2212 Fixed detachement problem in Path

- gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
https://issues.apache.org/jira/browse/TINKERPOP-2217
Fix potentially harmful timing issue: _writeInProgress could be observed by BeginSendingMessages to indicate that the loop in SendMessagesFromQueueAsync is still "in flight" while in reality, it has already exited.
> TINKERPOP-2217

- CHANGELOG.asciidoc
- gremlin-console/src/main/static/NOTICE
- gremlin-server/src/main/static/NOTICE
- pom.xml
- spark-gremlin/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2219
**Testing**
gremlin-driver: mvn clean install -DskipIntegrationTests=false
gremlin-server: mvn clean install -DskipIntegrationTests=false
> TINKERPOP-2219 Upgrade Netty dependency to 4.1.32

- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/PluggedIn.groovy
- gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/jsr223/DriverRemoteAcceptor.java
- gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/jsr223/MockGroovyGremlinShellEnvironment.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/console/GremlinShellEnvironment.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Tokens.java
JIRA link: https://issues.apache.org/jira/browse/TINKERPOP-2216
There are a lot of alternative ways to approach this.  I'm just opening this PR, with this specific approach, because it illustrates the suggested feature a bit more clearly than the prose in the JIRA issue description.
This adds a new `Tokens` string literal with the value `"warnings"`.  The console's `DriverRemoteAcceptor` checks for this status attribute every time it receives a remote resultset, printing the value above the results (to `err` when available).  If the value is a list, each element gets passed through `String#valueOf` and printed on a separate line.  Otherwise, it's just passed through `String#valueOf` and printed once.
Testing this in isolation seems a bit tricky.  I've been testing this coupled with a …
> TINKERPOP-2216 add status attribute for warnings

- CHANGELOG.asciidoc
- docs/src/dev/provider/index.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/NotStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalUtil.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/iterator/StoreIteratorCounter.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/NotStepTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/IgnoreIteratorLeak.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/algorithm/generator/CommunityGeneratorTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/algorithm/generator/DistributionGeneratorTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphComputerTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoaderVertexProgramTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalInterruptionTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/FilterTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/WhereTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SubgraphTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategyProcessTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoTest.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/step/sideEffect/TinkerGraphStep.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphIterator.java
https://issues.apache.org/jira/browse/TINKERPOP-2224
During the execution of the query the underlying provider layer might open some resources such as cursors or iterators which should be closed on completion of execution of the query. This is largely done by calling Traversal.close() method at the end of the traversal.
However, there are bugs in the query processor which lead to a leak of these resources. 
As an example, consider the following query:
`g.V().not(__.V().out()).fold().unfold()`
The implementation of not() step creates a child traversal which would open an iterator(aka resource) at the storage layer but due to a bug in TraversalUtil.java, it will never close this traversal (even on calling Traversal.close() on the global Traversal). This leads to open resources on the …
> TINKERPOP-2224 Detect and fix iterator leaks

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
- gremlin-test/features/map/Match.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchTest.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2230
Fixed a bug where `MatchStep()` didn't determine the correct start step properly.
**Before**
```
gremlin> g.V().match(
......1>     __.as('a').out('knows').as('b'),
......2>     __.as('b').out('created').as('c'))
==>[a:v[1],b:v[4],c:v[5]]
==>[a:v[1],b:v[4],c:v[3]]
gremlin> g.V().match(
......1>     __.as('b').out('created').as('c'),
......2>     __.as('a').out('knows').as('b'))
The provided match pattern is unsolvable: [[MatchStartStep(a), VertexStep(OUT,[knows],vertex), MatchEndStep(b)], [MatchStartStep(b), VertexStep(OUT,[created],vertex), MatchEndStep(c)]]
```
**Now**
```
gremlin> g.V().match(
......1>     __.as('a').out('knows').as('b'),
......2>     __.as('b').out('created').as('c'))
==>[a:v[1],b:v[4],c:v[5]] …
```
> TINKERPOP-2230 Fixed bug in match() step

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStartStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/Parameters.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ParametersTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2099
See the upgrade documentation in the PR itself for more details on the fix. Note that this is a breaking change as the behavior for the well used `addV()` has changed when `null` is a property value. 
VOTE +1
> TINKERPOP-2099 Consistent behavior of property() in relation to null values

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
old discussion and suggestion here:  https://github.com/apache/tinkerpop/pull/1127
issue here: https://issues.apache.org/jira/browse/TINKERPOP-2241
> Fix bug where client/server exception mismatch when server throw StackOverflowError

- docs/site/home/index.html
I didn't think "heterogenous" was a word, but I looked it up, and it is!  :-)  But "heterogeneous" was intended here, right?
In the Community Contributions section, I think either of the constructions
represent both [this] and [that]
or
represent [this] as well as [that]
would be fine (but not "represent both [this] as well as [that]").
Are the proposed added hyphens in "Cypher to Gremlin traversal" -> "Cypher-to-Gremlin traversal" okay?
> Proposed typo fix and minor grammatical stuff

- docs/src/reference/gremlin-applications.asciidoc
Did I target this fix to the correct branch?  A notification email I received containing a message from Stephen Mallette re my first pull request mentioned that 3.3.x is currently maintained on the tp33 branch, 3.4.x on tp34, and 3.5.0 (unreleased) on master, and said it'd be nice if I could target future PRs to the earliest branch to show the problem, so I checked the tp33 branch to see if the typo was there, and it was.  But I didn't check for anything earlier (tp32?) ... should I have?  Or is tp33 the earliest one to check?  Thanks!
> Typo fix to tp33

- docs/src/tutorials/getting-started/index.asciidoc
Misc. notes on the changes proposed here:
1.  Inserted "(JVM)" after first mention of "Java Virtual Machine" (since, later in the document, the abbreviation appears alone).
2.  Removed "etc." from end of list introduced by "e.g." (since the "etc." is implied by the use of "e.g.").
3.  Broke up the sentence that says to "recall that `id` is "reserved" for special usage in TinkerPop and is a member of the enum, `T`" into two sentences. Rationale: the reader is asked to "recall" two things (that `id` is reserved, and that it's a member of `T`), but only the first of those two things have been stated up to this point in the document (unless I've missed the other!).  :-)
4.  Slightly reworded a couple of sentences ("Think of it" -> "Think of `'id`) in a way that seems clearer to me.  (Unless …
> Misc. edits, minutes 6 thru 30

- CHANGELOG.asciidoc
- gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/jsr223/DriverRemoteAcceptor.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestOptions.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Tokens.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnectionTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2243
This allows graph providers to tailor their error messages to the client.
> TINKERPOP-2243 Add userAgent to RequestOptions.

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Handler.java
https://issues.apache.org/jira/browse/TINKERPOP-2248
Relying only on the `Connection.isDead()` check to determine connection replacement seemed to introduce a regression as of 2cd84ff1f3944d67d44cbba5bb032a1c57377975 The `shouldBlockRequestWhenTooBig` was failing somewhat randomly since that change. Not sure if there is a better way to make `isDead()` be the only check needed for connection replacement in this context, but this change brings the logic back that checks exception types that were forcing replacement prior to this change. 
@divijvaidya would you mind having a look at this change? perhaps you are aware of better solutions or perhaps I misinterpreted something in my analysis that you could correct?
VOTE +1
> TINKERPOP-2248 Force replacement of connections on certain errors

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/PredicateTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/BranchStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/ChooseStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/UnionStep.java
- gremlin-test/features/branch/Branch.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/ComplexTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/BranchTest.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1084
Allow predicates and traversals to be used as options in `BranchStep`.
```
gremlin> g = TinkerFactory.createModern().traversal()
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], standard]
gremlin> g.V().hasLabel("person").
......1>   project("name", "age", "comments").
......2>     by("name").
......3>     by("age").
......4>     by(branch(values("age")).
......5>          option(any, bothE().count()).
......6>          option(29, constant("almost old")).
......7>          option(__.is(32), constant("looks like josh")).
......8>          option(lt(29), constant("pretty young")).
......9>          option(lt(35), constant("younger than peter")).
.....10>          option(gte(30), constant("pretty old")).fold()) …
```
> TINKERPOP-1084 Branch option tokens should be allowed to be traversals

- CHANGELOG.asciidoc
- docs/src/reference/implementations-neo4j.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-server/pom.xml
- neo4j-gremlin/pom.xml
* I think I've got dependency conflicts figured out. At least basic queries are executed ok and `mvn clean install -DincludeNeo4j` passes. Please clarify if I'm missing something.
* Upgrade to Neo4j  `3.4` (not `3.5`), because this is the latest available version in  `neo4j-tinkerpop-api-impl`. Migration to `3.5` will require some efforts.
* Upgrade Neo4j `3.2.3` → `3.4.11` should be straightforward. Added release notes anyway.
* Looks like #1042 could be merged after this
> Upgrade to neo4j-tinkerpop-api-impl `0.9-3.4.0`

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js
- gremlin-test/features/sideEffect/Aggregate.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateTest.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/io/graphson/AbstractTinkerGraphGraphSONTranslatorProvider.java
https://issues.apache.org/jira/browse/TINKERPOP-1553
`store('x')` can now be accomplished with `aggregate(local,'x')` and `aggregate('x')` is `aggregate(global,'x')`. this is a non-breaking change, just deprecation to consider for now. See comments on the JIRA for more details on the choices made on the way to this PR.
VOTE +1
> TINKERPOP-1553 Deprecate store(String) for aggregate(Scope,String)

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-javascript/glv/GraphTraversalSource.template
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal-strategy.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/graph-serializer.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/type-serializers.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js
https://issues.apache.org/jira/browse/TINKERPOP-2020
Was able to remove all the test ignores around this. When merging forward I hope the remaining "computer" ignores can also drop: 
https://github.com/apache/tinkerpop/blob/f7aeac4320bc673ec1c875bd781a1e5eb65ff634/gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js#L84-L98
Builds with `mvn clean install -pl gremlin-javascript`
VOTE +1
> TINKERPOP-2020 Added withComputer() in javascript.

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/jsr223/GephiTraversalVisualizationStrategy.groovy
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateLocalStep.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateGlobalStepTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateLocalStepTest.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/optimization/TinkerGraphCountStrategy.java
https://issues.apache.org/jira/browse/TINKERPOP-2254
Now they are consistent with other `Scope` steps like `max(Scope)` given the recently added `aggregate(Scope,String)`.
VOTE +1
> TINKERPOP-2254 Renamed StoreStep and AggregateStep

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateStep.java
https://issues.apache.org/jira/browse/TINKERPOP-2256
I follow the usage of hasProcessedOnce in ReducingBarrierStep and i think AggregateStep doesn't need the done() function.
> TINKERPOP-2256 TINKERPOP-2256 processAllStarts of AggregateStep should only be called when barrier is empty

- CHANGELOG.asciidoc
- docs/src/dev/io/graphson.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV2d0.py
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV2d0.py
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py
https://issues.apache.org/jira/browse/TINKERPOP-2264
Got timezone of the local system out of the derser mix and standardized around what's always been expected in Java's `Date.getTime()`.
Builds with `mvn clean install :pl gremlin-python`
VOTE +1
> TINKERPOP-2264 Fixed g:Date serialization for python.

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/PluggedIn.groovy
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Preferences.groovy
This PR adds a new gremlin-console preference controlling the display of server-originated warnings:
```
:set warnings true // the default; all warnings displayed
:set warnings false // all warnings suppressed
```
https://issues.apache.org/jira/browse/TINKERPOP-2271
> TINKERPOP-2271 Add warnings=true|false console preference (tp34)

- CHANGELOG.asciidoc
- gremlin-python/glv/GraphTraversalSource.template
- gremlin-python/glv/TraversalSource.template
- gremlin-python/glv/generate.groovy
- gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
- gremlin-python/src/main/jython/gremlin_python/process/traversal.py
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV2d0.py
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
https://issues.apache.org/jira/browse/TINKERPOP-2272
Used the standard underscore suffix on these problems. Didn't document a bunch purposely because the intention is to retain the old conflicting steps/tokens for the time being (both are currently present in the library so as to be backward compatible in 3.3.x and 3.4.x). In 3.5.0 all tests will be modified, documentation updated and the old conflicting names completely removed. So, for now at least the new methods are present for use and we don't have a breaking change to be concerned about.
VOTE +1
> TINKERPOP-2272 Renamed steps/tokens conflicting with global function names

- CHANGELOG.asciidoc
- gremlin-python/src/main/jython/gremlin_python/driver/connection.py
Make `gremlinpython` more friendly to scenarios which use multiple processes model like `Celery`.
> Postpone the timing of transport creation to `connection.write`

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GraphStep.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/step/sideEffect/TinkerGraphStep.java
Fix GraphStep.java & TinkerGraphStep.java ids null bug
https://issues.apache.org/jira/browse/TINKERPOP-2283?focusedCommentId=16916883&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel
> fix GraphStep.ids null bug

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/AbstractExplanation.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/ImmutableExplanation.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalExplanation.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV2d0.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV3d0.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalExplanationTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2291
Added the notion of `ImmutableExplanation` which allows the deserialization to occur. As an immutable object the recalculation of the `TraversalExplanation` does not need to occur from the raw data. In fact, if it did it would be "wrong" as it would recalculate on the client rather than the server and server side strategies may not be applied. That said, the design choices here in the class hierarchy are a bit odd in that `ImmutableExplanatio`n should really extend `AbstractExplanation`, but to avoid breaking changes in derser in gryo/graphson it seemed best to go with the slightly less optimal approach. Perhaps a future release branch were breaking changes are allowed can rectify this.
Builds with `mvn clean install && mvn verify -pl …
> TINKERPOP-2291 Added GraphSON support for deserialization of TraversalExplanation

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AddPropertyStep.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2159
Fixed multi-valued property handling in `EventStrategy` / `AddPropertyStep`. The `EventStrategy` output for the traversals added in `TinkerGraphPlayTest.testPlayDK()` is as follows:
```
Vertex [v[1]] added to graph [tinkergraph[vertices:1 edges:0]]
Vertex [v[1]] property [vp[name->null]] change to [name1] in graph [tinkergraph[vertices:1 edges:0]]
Vertex [v[1]] property [vp[name->name1]] change to [name2] in graph [tinkergraph[vertices:1 edges:0]]
Vertex [v[1]] property [vp[name->name2]] change to [name2] in graph [tinkergraph[vertices:1 edges:0]]
Vertex [v[2]] added to graph [tinkergraph[vertices:2 edges:0]]
Vertex [v[2]] property [vp[name->null]] change to [name1] in graph [tinkergraph[vertices:2 edges:0]]
Vertex [v[2]] property …
```
> TINKERPOP-2159 EventStrategy doesn't handle multi-valued properties

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ElementMapStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/T.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ElementMapStepTest.java
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs
- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/DirectionDeserializer.cs
- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/GraphSONReader.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/CommonSteps.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONReaderTests.cs
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/graph-serializer.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/type-serializers.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js
- gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/jython/radish/feature_steps.py
- gremlin-test/features/map/ElementMap.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ElementMapTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2284
Given that we only return reference objects for graph elements now, there is a lot of extra `project()`/`valueMap()` work to do for the simple and common need to return all the structure of a graph element. `elementMap()` simplifies all that to a single step without a ton of options and added features.
VOTE +1
> TINKERPOP-2284 Added elementMap() step

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-javascript/src/main/javascript/gremlin-javascript/index.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/response-error.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/remote-connection-tests.js
https://issues.apache.org/jira/browse/TINKERPOP-2285
`ResponseError` in javascript is akin to `ResponseException` in java. It includes more direct access to protocol lever server error information such as the status code and status attributes which means we don't need to pack that information into the error message itself at all. Kept that old style to the error messages just in case users were parsing those in prior versions - didn't want to break that.
Builds with `mvn clean install -pl gremlin-javascript`
VOTE +1
> TINKERPOP-2285 Added ResponseError in gremlin-javascript

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/function/Lambda.java
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Lambda.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/StringBasedLambda.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalSourceTests.cs
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV2d0.py
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
https://issues.apache.org/jira/browse/TINKERPOP-1810
To support this we needed to better detect the number of arguments that a lambda has so that we can properly deserialize to BinaryOperator or UnaryOperator. We also needed to better cast arguments for groovy given withSack() overlaods that aren't easily detected during eval() and generate errors otherwise. The method for detecting arguments isn't super nice - just some string parsing, but since Gremlin really only ever expects zero, one or two arg lambdas the risk of taking this approach seems low. Note that users who want to distinguish arguments must specify them with a full groovy closure syntax or else it will assume "unknown" as it always has.
VOTE +1
> TINKERPOP-1810 Support for withSack() that use Lambdas with remotes

- CHANGELOG.asciidoc
- docker/gremlin-server/gremlin-server-integration-secure.yaml
- docker/gremlin-server/gremlin-server-integration.yaml
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestOptions.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Tokens.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnectionTest.java
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutorTest.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2295
This setting was previously deprecated in 3.3.9 and is no longer needed.
VOTE +1
> TINKERPOP-2295 Removed scriptEvaluationTimeout configurations

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/AbstractWarningVerificationStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/EdgeLabelVerificationStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/ReservedKeysVerificationStrategy.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/ReservedKeysVerificationStrategyTest.java
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Verification/EdgeLabelVerificationStrategy.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Verification/ReservedKeysVerificationStrategy.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalSourceTests.cs
- gremlin-python/src/main/jython/gremlin_python/driver/protocol.py
- gremlin-python/src/main/jython/gremlin_python/process/strategies.py
- gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2280
Abstracted out a "warning" style verification strategy that ended up being used by this new strategy and EdgeLabelVerificationStrategy. If this ReservedKeysVerificationStrategy is added it will prevent the specified keys from being used in property keys. Providers can choose to implement this strategy if they have keywords they wish to prevent use of and users can of course use it as needed for their own conventions. By default, the strategy blocks use of "id" and "label" as a convention.
VOTE +1
> TINKERPOP-2280 Add ReservedKeysVerificationStrategy

- CHANGELOG.asciidoc
- hadoop-gremlin/pom.xml
- spark-gremlin/pom.xml
**CVE-2018-11771**
According to sourceclear:
https://www.sourceclear.com/vulnerability-database/security/denial-of-service-dos-/java/sid-7319
`commons-compress` is vulnerable to denial of service (DoS) attacks.
Although it looks like `hadoop-gremlin` does not use the library directly, but still may be worth upgrading it.
Run `docker/build.sh -t -i` on my local, and the Reactor Summary reports `BUILD SUCCESS`.
> Upgrade commons-compress to version 1.19 due to CVE-2018-11771

- CHANGELOG.asciidoc
- giraph-gremlin/pom.xml
- gremlin-shaded/pom.xml
- neo4j-gremlin/pom.xml
- spark-gremlin/pom.xml
**CVE-2019-14379, CVE-2019-14540, CVE-2019-16335**
According to sourceclear, `jackson-databind` has the following CVE issues:
CVE-2019-14379
https://www.sourceclear.com/vulnerability-database/security/remote-code-execution-rce-/java/sid-20928
CVE-2019-14540
https://www.sourceclear.com/vulnerability-database/security/deserialization-of-untrusted-data/java/sid-21522
CVE-2019-16335
https://www.sourceclear.com/vulnerability-database/security/deserialization-of-untrusted-data/java/sid-21523
* Upgraded `jackson-databind` to 2.9.10 due to CVE-2019-14379, CVE-2019-14540, CVE-2019-16335.
* Adjusted Dependency convergence errors due to the upgrade of `jackson-databind` with the following changes:
- Aligned `jackson-annotations` to 2.9.10.
- Aligned `jackson-module-scala_2.11` to 2.9.10.
- Bumped …
> Upgrade jackson due to CVE issues

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bytecode.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/BytecodeTest.java
I think it is a simple bug and and could  recurrent easily,
I both fix two position and add one test case.
old jira here:
https://issues.apache.org/jira/browse/TINKERPOP-2298?jql=reporter%20in%20(currentUser())
> Fix Bytecode.addSource  arguments is null bug

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ElementMapStep.java
Adds a getter for `onGraphComputer`.  This is intended to support strategies that replace this step but want to preserve this state across replacement.
https://issues.apache.org/jira/browse/TINKERPOP-2302
> TINKERPOP-2302 add `ElementMapStep#isOnGraphComputer()` (tp34)

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ElementMapStep.java
Adds a getter for `onGraphComputer`.  This is intended to support strategies that replace this step but want to preserve this state across replacement.
https://issues.apache.org/jira/browse/TINKERPOP-2302
> TINKERPOP-2302 add `ElementMapStep#isOnGraphComputer()` (master)

- gremlin-dotnet/glv/Gremlin.Net.csproj.template
- gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj
- gremlin-javascript/src/main/javascript/gremlin-javascript/README.md
- gremlin-python/src/main/jython/README
https://issues.apache.org/jira/browse/TINKERPOP-2293
Landing pages are what are published for each languages package manager (e.g. pypi). Made it clear that Gremlin Server or a Remote Gremlin Provider was required for these GLVs to work properly. Added enough information to explain how to create "g" in case folks aren't at all familiar with any aspect of Gremlin and wonder what that variable is. Added some more links as I didn't want to repeat information that can be found in the reference docs and ultimately we need users to head over there to get familiar with them anyway. I would have liked to have done more with .NET so that it was more like js and python but nuget isn't to robust in displaying project descriptions so there isn't much flexibility there. To my surprise, a sparse/rough …
> TINKERPOP-2293 Improved landing pages for all GLVs

- .travis.yml
- CHANGELOG.asciidoc
- gremlin-python/src/main/jython/setup.py
- gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
https://issues.apache.org/jira/browse/TINKERPOP-2309
Removed a test that started failing after the version bump. I assume it no longer is necessary given that the error is "Cannot run the event loop while another loop is running" and I've taken to mean that since asyncio is automatically use when available the test is no longer relevant.
I'm not sure if other work should be done as a result of this upgrade. I came across this comment on ipython while researching the test error I was receiving:
https://github.com/jupyter/notebook/issues/3397#issuecomment-519283894
Not sure I know enough at this time about tornado/asyncio to know what should be done to improve our implementation. If anyone cares to comment or help by making a PR, it would be appreciated.
Builds with `mvn clean install -pl …
> TINKERPOP-2309 Bump to Tornado 5.x

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraversalVertexProgram.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/TraversalVertexProgramStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/decoration/VertexProgramStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/RequirementsStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SideEffectStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/StandardVerificationStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalStrategies.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/EmptyTraversalStrategies.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalExplanation.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/TraversalStrategiesTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProfileTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/EarlyLimitStrategyProcessTest.java
- spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkStarBarrierInterceptor.java
- spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/SparkInterceptorStrategyTest.java
- spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/SparkSingleIterationStrategyTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2310
https://issues.apache.org/jira/browse/TINKERPOP-2311
A few added refactoring opportunities were noticed as a result of TINKERPOP-1568. Basically, `TraversalStrategies` now implements `Iterable` and the semantics of `Traversal.isRoot()` have been narrowed to only check for `EmptyStep` rather than also checking for `null`.
VOTE +1
> TINKERPOP-2310 and TINKERPOP-2311 Folllow up refactoring after TraversalStrategy changes

- CHANGELOG.asciidoc
- docs/src/recipes/appendix.asciidoc
- docs/src/recipes/centrality.asciidoc
- docs/src/recipes/duplicate-edge.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/ElementValueTraversal.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/ElementValueTraversalTest.java
- gremlin-test/features/map/Project.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProjectTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2314
Also improve errors around incorrect types that might be called using this modulator overload. See upgrade docs for reasoning and examples of what's happening here.
VOTE +1
> TINKERPOP-2314 Employ by(String) for Map when possible

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/HasContainer.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/ElementHelper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/util/ElementHelperTest.java
- gremlin-test/features/filter/Has.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedPropertyTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2313
https://issues.apache.org/jira/browse/TINKERPOP-1733
https://issues.apache.org/jira/browse/TINKERPOP-2318
Currently, an exception will be thrown for this query: `XxProperty cannot be cast to Element`
> TINKERPOP-1733 Support g.E().properties().hasKey('xx') & hasValue('xx')

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/TestClientFactory.java
- gremlin-server/src/test/resources/conf/remote-objects.yaml
i found Cluster.open() method can not load the yaml file that stored in project‘s resource dir,
therefore i want to submit this code to make this happen for  those who stored yaml file in there classpath based dir
> make Cluster be able to open file in classpath resource dir

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
a new PR for https://github.com/apache/tinkerpop/pull/1226
We miss to put requestId and userAgent in bytecode query submission while they are available in requestOptions. This commits fix the issue.
I ran the tests locally and it worked fine. Please let me know if the change any issue. Thanks.
> update requestId and userAgent in RequestMessage with RequestOptions

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2262
Allows the channel on the driver to be reused rather than replaced. Interestingly no additional error handling seemed to be needed as all tests passed.
VOTE +1
> TINKERPOP-2262 Prevented channel close by server on protocol error

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
https://issues.apache.org/jira/browse/TINKERPOP-2266
If nothing writes to the Connection then keep alive doesn't start which might let it die in the pool if it is not used at some point.
VOTE +1
> TINKERPOP-2266 Start keep alive polling on Connection construction

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-dotnet/glv/GraphTraversal.template
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
- gremlin-javascript/glv/GraphTraversalSource.template
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
- gremlin-python/glv/GraphTraversalSource.template
- gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
- gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
https://issues.apache.org/jira/browse/TINKERPOP-2315
Hard to believe we didn't have `clone()` in place across the board. There might have been some more idiomatic ways to implements this per language but I decided to stick with `clone()` as it is in Java for all languages. Just felt like it should be consistent. Happy to hear other opinions on that matter, but besides that:
VOTE +1
> TINKERPOP-2315 Implement clone() for all GLVs

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
https://issues.apache.org/jira/browse/TINKERPOP-2175
Pretty much implemented as described in the JIRA - make sense to me to check for an active channel in addition to writeability.
VOTE +1
> TINKERPOP-2175 Better manage the executor thread on close.

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphml/GraphMLReader.java
This pull request is a revised one from https://github.com/apache/tinkerpop/pull/1230.
Some provider wants to use XMLInputFactory with more secure configurations. This change makes it possible to pass XMLInputFactory when instantiating GraphMLReader.
I don't add any tests right now, I want to first confirm if this direction is OK. If yes, please suggest any tests that I need to add. Thanks !
> TINKERPOP-2320 allow to pass custom XmlInputFactory when instantiating GraphMLReader

- gremlin-javascript/glv/PackageJson.template
- gremlin-javascript/src/main/javascript/gremlin-javascript/package.json
Update dependencies as long as those work with Node.js 6+ runtime.
https://issues.apache.org/jira/browse/TINKERPOP-2329
VOTE +1
> TINKERPOP-2329 JavaScript GLV: upgrade ws dependency

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DedupGlobalStep.java
- gremlin-test/features/filter/Dedup.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DedupTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2107
This is a bit of a workaround that really only resolved itself properly as a result of TINKERPOP-2318 which only went to `master` and 3.5.0. 
VOTE +1
> TINKERPOP-2107 Fixed property re-attachment

- gremlin-javascript/src/main/javascript/gremlin-javascript/index.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/graph-serializer.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/client-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/exports-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2330
Adds GraphSON2 and GraphSON3 writer/readers for backward compatibility, something that I've missed when introducing GraphSON3 support in #858.
> TINKERPOP-2330 JavaScript GLV: Export GraphSON2 and 3 writers/readers

- gremlin-dotnet/glv/Gremlin.Net.csproj.template
- gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj
Bump `System.Net.WebSockets.Client` dependency to `4.3.2` in Gremlin.Net.
https://issues.apache.org/jira/browse/TINKERPOP-2339
VOTE +1
> TINKERPOP-2339 Bump System.Net.WebSockets.Client dependency

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SettingsTest.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
This PR adds a little bit more flexibility to the usage of different store types between keystore and truststore. For example, `jks` in keystore and `pkcs12` in truststore.
It preserves the original behavior, such that if the user does not define the `trustStoreType`, it would use the `keyStoreType`.
----
- Ran `mvn clean install` successfully
- Ran `docker/build.sh -i -t` successfully
> Add trustStoreType such that keystore and truststore can be different type

- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/GraphSONWriter.cs
Changed Gremlin.Net.Structure.IO.GraphSON.GraphSONWriter.TryGetSerializerFor method to not use out parameter because iOS platform cannot handle these. Original TryGetSerializerFor(out IGraphSONSerializer serializer, type) causes System.NotImplementedException: byref delegate System.Linq.Expressions.Interpreter.LightLambda.CreateCustomDelegate exception on iOS platform
> Fix to iOS platform

- CHANGELOG.asciidoc
- docs/src/dev/provider/index.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2336
This one has been basically done for a while now - just got delayed a bit because of 3.4.6. Made a few minor tweaks to docs after reviewing the last day or so, but other than that it's unchanged.
Deprecated the "close" message for sessions along with its driver setting. The driver should stay compatible with older server versions, but the server now closes sessions with the close of the connection and there no longer is a block while all messages return from the server after a `Client.close()`.
VOTE +1
> TINKERPOP-2336 Added getMaxWaitForClose java driver setting.

- CHANGELOG.asciidoc
- gremlin-shaded/pom.xml
No automated test, but I published a small project to reproduce the issue [here](https://github.com/olim7t/dummy-jpms).
It's actually only a warning when run from the command line, but I get an error in IntelliJ IDEA.
> TINKERPOP-2347 Remove invalid service descriptors from gremlin-shaded

- gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketConnection.cs
For large result sets, this will release a little bit of GC pressure.
> Reuse a byte buffer instead of re-allocating it on every loop.

- .travis.yml
- docker/Dockerfile
- docs/src/dev/developer/development-environment.asciidoc
- gremlin-dotnet/glv/Gremlin.Net.Template.csproj.template
- gremlin-dotnet/src/Gremlin.Net.Template/Gremlin.Net.Template.csproj
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.Template.IntegrationTest/Gremlin.Net.Template.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Gremlin.Net.UnitTest.csproj
https://issues.apache.org/jira/browse/TINKERPOP-2335
This updates `3.3-dev` (and subsequently the other release branches) to .NET Core 3.1 so that we only need to have **one .NET Core SDK version installed which will be 3.1** after this PR is merged. 3.1 is the newest version right now and it is also an LTS version.
As already said on #1260, this basically only affects our build process / environment, but not users:
> This has no effect on users of Gremlin.Net as that targets .NET Standard which doesn't need to be changed at all. The only change affecting users is the update in Gremlin.Net.Template, but that is a good thing in my opinion as the template is only used to create a completely new project and then using the latest LTS version sounds like the best approach to me.
After this is …
> TINKERPOP-2335 Update to .NET Core 3.1

- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-dotnet/glv/Gremlin.Net.csproj.template
- gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj
https://issues.apache.org/jira/browse/TINKERPOP-2335
This handles the .NET part of TINKERPOP-2335 by removing support for .NET Standard 1.3. This makes it easier for us to use newer .NET features in the future.
I also updated all .NET Core versions to the latest LTS version which is 3.1 right now. This includes the test projects, the dotnet template, the Travis file and our Docker build.
Unfortunately, I cannot try the Docker build right now as it isn't working for me on `master` at the moment. I'll add results of that once the Docker build is working again for me.
> TINKERPOP-2335 Drop support for .NET Standard <2.0

- docs/src/reference/the-traversal.asciidoc
When reading the reference documentation for the `path()` step I didn't realize you could use `to()` or `from()`, which are very useful features. This change adds in an example of their usage.
> Add in example of using path with to or from modulators to the documentation

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Order.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/OrderTest.java
- gremlin-test/features/map/Order.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2351
This seemed like an easy fix. Can't think of any bad side-effects. Not sure if there are other special cases we should consider, but at least this common case is solved.
```text
gremlin> g.V().valueMap(true).order(local).by(keys,desc)
==>[name:[marko],label:person,id:1,age:[29]]
==>[name:[vadas],label:person,id:2,age:[27]]
==>[name:[lop],lang:[java],label:software,id:3]
==>[name:[josh],label:person,id:4,age:[32]]
==>[name:[ripple],lang:[java],label:software,id:5]
==>[name:[peter],label:person,id:6,age:[35]]
gremlin> g.V(1).valueMap(true).order(local).by(keys,desc).next()[T.id]
==>1
gremlin> g.V(1).valueMap(true).order(local).by(keys,desc).next()[T.label]
==>person
```
When this merges forward to `3.4-dev` I will modify the test to use …
> TINKERPOP-2351 Fixed bug in Order when enum is a key in Map

- CHANGELOG.asciidoc
- gremlin-python/glv/GraphTraversalSource.template
- gremlin-python/glv/TraversalSource.template
- gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
- gremlin-python/src/main/jython/gremlin_python/process/traversal.py
- gremlin-python/src/main/jython/tests/process/test_traversal.py
https://issues.apache.org/jira/browse/TINKERPOP-2350
We weren't deep copying bytecode before. Added a test to verify things are working as expected and manually tested the failing example in the JIRA:
```text
>>> g = traversal().withRemote(DriverRemoteConnection('ws://localhost:8182/gremlin','g'))
>>> t0 = g.V().hasLabel('x')
>>> t0
[['V'], ['hasLabel', 'x']]
>>> t1 = t0.clone()
>>> t1
[['V'], ['hasLabel', 'x']]
>>> t1.has('name','y')
[['V'], ['hasLabel', 'x'], ['has', 'name', 'y']]
>>> t0
[['V'], ['hasLabel', 'x']]
>>> 
VOTE +1
> TINKERPOP-2350 Fixed bug in Traversal.clone() in gremlin-python

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
https://issues.apache.org/jira/browse/TINKERPOP-2353
The `null` checks seem necessary as failures in `GraphManager` initialization can leave Gremlin Server in a state where it is partially setup so that when shutdown starts those components that were not initialized end up being null and calls to their shutdown methods end up failing.
VOTE +1
> TINKERPOP-2353 Added some checks for null in shutdown of server

- CHANGELOG.asciidoc
- gremlin-dotnet/glv/GraphTraversal.template
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/GraphTraversalSourceTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2350
This is basically the same fix for .NET as #1268 for Python. This also includes the commit from #1268 so I'll rebase this once that PR is merged.
VOTE +1
> TINKERPOP-2350 Fixed bug in Traversal.clone() in Gremlin.NET

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONReader.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypeResolverBuilder.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/util/DependencyGrabberIntegrateTest.java
- gremlin-shaded/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2356
This moves us off the CVE flooded 2.9.x. Changes were pretty minimal. I suppose we could backport if we really wanted to but this was mostly done to see what the impact would be as we look forward to hopefully going to Jackson 3.0 before TP 3.5.0 releases.
VOTE +1
> TINKERPOP-2356 Bump to Jackson 2.10

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/Scoping.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MathStep.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/CoreTraversalTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2345
This problem really only applies to 3.4.x since by() didn't modulate Map traversers in 3.3.x. This change does also however fix the error message for non-Number objects trying to be passed into a math() expression, but the error is at least more understandable than the NullPointerException - on 3.3.x we get "java.lang.String cannot be cast to java.lang.Number" which while not perfect is probably good enough for that older version. It didn't seem like a big enough problem to add the enhancement there.
VOTE +1
> TINKERPOP-2345 Improved error message for bad value for math()

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/ClsCommand.groovy
- gremlin-console/src/main/resources/org/apache/tinkerpop/gremlin/console/commands/ClsCommand.properties
https://issues.apache.org/jira/browse/TINKERPOP-2357
This change was implemented a while ago but I didn't issue the PR immediately as I requested on the ML that folks test it on different platforms to make sure it works. The confirmations came in fast and then I accidentally forgot to get this into review.
I purposely didn't target `3.3-dev` here as it's a new feature and I didn't want to make any more mistakes related to putting anything other than bug fixes there. 
VOTE +1
> TINKERPOP-2357 Added :cls command to clear console screen

- CHANGELOG.asciidoc
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV2d0.py
- gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/jython/tests/driver/test_client.py
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV2d0.py
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py
https://issues.apache.org/jira/browse/TINKERPOP-2360
python integer support 64bit, but java integer only 32bit in server,  so server may throw deserializer error when get a big integer value from `python sdk`.
```
org.apache.tinkerpop.shaded.jackson.databind.JsonMappingException: Could not deserialize the JSON value as required. Nested exception: org.apache.tinkerpop.shaded.jackson.core.JsonParseException: Numeric value (851401972585122) out of range of int
at [Source: (byte[])"{"op": "bytecode", "requestId": {"@type": "g:UUID", "@value": "a3660cfd-a531-4b92-8a0d-f65388675f63"}, "args": {"gremlin": {"@type": "g:Bytecode", "@value": {"step": [["V"], ["has", "customer_id", {"@type": "g:Int32", "@value": 851401972585122}]]}}, "aliases": {"g": "g"}}, "processor": "traversal"}"; line: 1, …
```
> TINKERPOP-2360 gremlin-python: fix up serializer out of range of int

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/LazyBarrierStrategy.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/LazyBarrierStrategyTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProfileTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2365
LazyBarrierStrategy was improperly adding a barrier step to the end of a traversal when profile() was called. This wasn't noticeable in testing because of an overly zealous choice to disable the strategy in testing if profile() was present. Modified the strategy to more properly handle this situation and to limit the removal of LazyBarrierStrategy to ProfileTest only.
VOTE +1
> TINKERPOP-2365 Prevented extra barrier being added with profile()

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bytecode.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalTest.java
- gremlin-dotnet/glv/GraphTraversal.template
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Bytecode.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/DefaultTraversal.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/ITraversal.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/GraphTraversalSourceTests.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/BytecodeGraphSONSerializerTests.cs
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/bytecode.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/traversal-test.js
- gremlin-python/glv/TraversalSource.template
- gremlin-python/src/main/python/gremlin_python/process/traversal.py
- gremlin-python/src/main/python/tests/process/test_traversal.py
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2361
No more use of "g" spawned child traversals. It was always a convention to use `__` but now its enforced. Wasn't sure of the best way to do this, but the most consistent way seemed to be by way of bytecode construction. .NET was slightly different because it didn't construct traversals in the same fashion as the other languages. 
VOTE +1
> TINKERPOP-2361 Enforced anonymous child traversals.

- docker/gremlin-server.sh
- docker/gremlin-server/Dockerfile.template
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV2d0.py
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py
The datetime conversion tests didn't pass when running on a Mac in London, so they've been updated to use `calendar.timegm` just like the code under test was in the [original PR for TINKERPOP-2264](https://github.com/apache/tinkerpop/pull/1165).
Also, in order to run & debug the integration tests I updated gremlin-python's pom.xml to refer to a `python` executable rather than `python2`.  Since [Docker on Mac runs in its own VM](https://docs.docker.com/docker-for-mac/docker-toolbox/#the-docker-desktop-on-mac-environment) I updated the integration test `gremlin-server.sh` to explicitly publish its ports using `-p`.  Happy to revert these if they're too environment-specific.
`gremlin-python` install target builds clean using IntelliJ Maven support (I get a javadoc-related error building from …
> TINKERPOP-2264 update gremlin-python tests to be timezone/system-independent, related minor Docker changes

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
- gremlin-test/features/filter/Has.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2383
That has() was using PropertiesStep, but properties() doesn't process T values.
```text
gremlin> g.V().has(label, is('software'))
==>v[3]
==>v[5]
gremlin> g.V().has(id, is(6))
==>v[6]
```
VOTE +1
> TINKERPOP-2383 Fixed bug in has(T,Traversal)

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Order.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/Seedable.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/CoinStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/SampleGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderLocalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SampleLocalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SeedStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/util/TraverserSet.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoVersion.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/util/IndexedTraverserSetTest.java
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Decoration/SeedStrategy.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
- gremlin-python/src/main/python/gremlin_python/process/strategies.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SeedStrategyProcessTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/TranslationStrategy.java
https://issues.apache.org/jira/browse/TINKERPOP-2014
Went with a strategy rather than another configuration option the the `TraversalSource` (e.g. `withSeed()`) as this seemed like the kind of feature we didn't need to run into the Gremlin language itself. 
```text
gremlin> g.V().values('name').fold().order(local).by(shuffle)
==>[josh,marko,vadas,peter,ripple,lop]
gremlin> g.V().values('name').fold().order(local).by(shuffle)
==>[vadas,lop,marko,peter,josh,ripple]
gremlin> g.V().values('name').fold().order(local).by(shuffle)
==>[peter,ripple,josh,lop,marko,vadas]
gremlin> g.withStrategies(new SeedStrategy(22323)).V().values('name').fold().order(local).by(shuffle)
==>[lop,peter,josh,marko,vadas,ripple]
gremlin> g.withStrategies(new …
```
> TINKERPOP-2014 SeedStrategy to specify the seed for traversal randoms

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/TraversalSelectStep.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/GraphBinaryRemoteGraphComputerProvider.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/GraphSONRemoteGraphComputerProvider.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/GryoRemoteGraphComputerProvider.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GryoRemoteGraphGroovyTranslatorComputerProvider.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/GremlinProcessRunner.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SideEffectTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2384
Without this change side-effects don't propogate to the key traversal and they can't be accessed. Generalized VerificationException errors for remote tests so that the Ignore list didn't have to be so long for those tests.
VOTE +1
> TINKERPOP-2384 Added key traversal to local children

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/SampleGlobalStep.java
https://issues.apache.org/jira/browse/TINKERPOP-2376
This change came externally from a file attached to the JIRA by the person who first posted it. I've just turned it into a PR since it has sat a while. In some basic tests the change did seem to improve the sampling as described in the ticket.
VOTE +1
> TINKERPOP-2376 Improved probability distribution on global sample()

- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/client-test.js
The goal of this PR is to provide a capability to specify arguments on query submission via JS Client. In our use case we would like to be able to specify `scriptEvaluationTimeout` argument for certain queries (which we expect to be slow and we want to prevent accidental timeouts). 
I am by no means a JS expert, hence probably adding extraArgs as an argument to the `submit` function is not ideal, but with this change we can write something like this to increase the timeout:
```js
const gremlin = require('gremlin');
const traversal = gremlin.process.AnonymousTraversalSource.traversal;
const p = gremlin.process.P;
const DriverRemoteConnection = gremlin.driver.DriverRemoteConnection;
const Client = gremlin.driver.Client;
const client = new Client('<endpoint>','gmodern')
client.open(); …
```
> Add support to provide extra arguments to the Client.submit()

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
https://issues.apache.org/jira/browse/TINKERPOP-2406
**Motivation**
Netty client has two thread pools. Event loop thread pool which is responsible for handling socket events and another is a worker thread pool which is used to delegate busy work from event loop threads so that they can continue handling socket events. When programming in Netty, ideally, the event loop should never be blocked and must be kept free to respond to events.
In case of exceptional completion of readComplete which could be triggered by a server sending an error code in the response, the event loop thread is used to perform the clean up logic which could involve an expensive replaceConnection. This blocks the event loop.
**Change**
Delegate handling of erroneous response from the server (which might involve …
> TINKERPOP-2406 Delegate processing from event loop to worker threads

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/HasContainer.java
https://issues.apache.org/jira/browse/TINKERPOP-2408
**Change**
Close the iterator to release resources. If the iterator is not closed, due to short circuit return, it could lead to iterator leaks in the underlying storage.
**Deployment**
Added ChangeLog
> TINKERPOP-2408 Fix iterator leak in HasContainer

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-python/src/main/python/gremlin_python/structure/io/graphbinaryV1.py
- gremlin-python/src/main/python/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/python/gremlin_python/structure/io/util.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
https://issues.apache.org/jira/browse/TINKERPOP-2407
Allows a traversal like the following to work for python:
```text
gremlin> g.V().has('person', 'name', 'marko').elementMap("name").groupCount().next()
==>{id=1, label=person, name=marko}=1
```
All tests pass with `mvn clean install -pl gremlin=python`
VOTE +1
> TINKERPOP-2407 Support for dict as key in python

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-python/src/main/jython/gremlin_python/driver/tornado/transport.py
https://issues.apache.org/jira/browse/TINKERPOP-2405
Set some defaults for the tornado timeouts and given existing methods for supplying a custom `TransportFactory` it's then possible for users to easily set custom values for those timeouts.
```python
g = traversal().withRemote(
DriverRemoteConnection('ws://localhost:8182/gremlin','g',
transport_factory=lambda: TornadoTransport(read_timeout=10, write_timeout=10)))
```
All tests pass with `mvn clean install -pl gremlin=python`
VOTE +1
> TINKERPOP-2405 Provide method to configure tornado timeouts

- docs/src/reference/gremlin-variants.asciidoc
- gremlin-dotnet/README.md
- gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj
- gremlin-dotnet/src/index.md
- gremlin-javascript/src/main/javascript/gremlin-javascript/README.md
- gremlin-python/src/main/jython/README.rst
https://issues.apache.org/jira/browse/TINKERPOP-2392
This issue was about javascript but really might have applied to all GLVs. With the recent change of ae95dbe9c33b380555ee32716e56ec12b56c3f6c it seemed to make sense to expand this change to all GLVs and to improve upon it. I could have probably just CTR'd this in but thought it would be better to get some review on sample variety and syntax (as these changes will affect artifact repositories descriptions...nuget, pypi, npm...and I'm not sure there is a nice way to validate links/changes without a release deployment.
VOTE +1
> TINKERPOP-2392 Improved GLV starting docs

- .gitignore
- gremlin-javascript/pom.xml
- gremlin-javascript/src/main/javascript/gremlin-javascript/package.json
- pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2335
Upgraded frontend plugin and centralized configuration a bit. 
VOTE +1
> TINKERPOP-2335 Set node.js support at 10 for 3.5.0

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DropStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStartStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStartStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AddPropertyStep.java
https://issues.apache.org/jira/browse/TINKERPOP-2415
This change adds some defensive checks to avoid creating additional detached objects when not required.
> TINKERPOP-2415 Avoid unnecessary detached objects if not required

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/SampleGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/TailGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/NoOpBarrierStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/AbstractStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/CollectingBarrierStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ExpandableStepIterator.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/function/TraverserSetSupplier.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/util/function/TraverserSetSupplierTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2396
This change makes it possible for providers to be able to extend the `TraverserSet`. Can't quite get the generics right since steps are constructed with a `Traversal` without parameterization. It thus forces a bit of an ugly cast to establish the `TraverserSet`. I looked at `TraverserSet` implementation uses in OLAP use cases, but didn't make any changes there as I wasn't sure it was necessary. The issue here is with optimizes OLTP based traversals further and I'm not sure what gains we can get with OLAP by furthering this change there. If we develop such a need I suppose we can dig into that when the time comes. 
VOTE +1
> TINKERPOP-2396 TraverserSetSupplier

- CHANGELOG.asciidoc
- docs/site/home/gremlin.html
- docs/src/dev/provider/index.asciidoc
- docs/src/recipes/centrality.asciidoc
- docs/src/recipes/olap-spark-yarn.asciidoc
- docs/src/reference/compilers.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/reference/implementations-hadoop-start.asciidoc
- docs/src/reference/implementations-neo4j.asciidoc
- docs/src/reference/implementations-spark.asciidoc
- docs/src/reference/implementations-tinkergraph.asciidoc
- docs/src/reference/intro.asciidoc
- docs/src/reference/the-graph.asciidoc
- docs/src/reference/the-graphcomputer.asciidoc
- docs/src/reference/the-traversal.asciidoc
- docs/src/tutorials/getting-started/index.asciidoc
- docs/src/tutorials/gremlin-language-variants/index.asciidoc
- docs/src/tutorials/the-gremlin-console/index.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/AnonymousTraversalSource.java
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/anonymous-traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/graph.js
https://issues.apache.org/jira/browse/TINKERPOP-2413
Deprecated `withGraph()` on `AnonymousTraversalSource` in favor of `withEmbedded()`. Didn't really alter tests so as to keep testing running through the old deprecated method which basically just proxies to `withEmbedded()`. GLVs didn't need much change since there really is no "embedded" option there. For python and .NET, i changed nothing since there is no embedded version. For javascript I explicitly deprecated `withGraph()` and fixed up jsdoc a bit. Modified documentation to better promote `withEmbedded()` - not sure why we didn't do that for `withGraph()` long ago (perhaps the idea was to wait for 3.5.0, but in a way I'm sorta glad we didn't as we've now deprecated.
VOTE +1
> TINKERPOP-2413 withEmbedded()

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONReader.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypeResolverBuilder.java
- gremlin-shaded/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2401
On merge, there may need to be some polish up of CHANGELOG and JIRAs so that things dont look confusing as to when they occurred. Other than that, I couldn't find any real breaking changes here so decided to bring 3.4-dev all the way up to 2.11.x.
VOTE +1
> TINKERPOP-2401 Backported bump of jackson to 2.11.x to 3.4.x

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/iterator/MultiIterator.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/util/iterator/MultiIteratorTest.java
As described in the [JIRA](https://issues.apache.org/jira/browse/TINKERPOP-2416), currently `MultiIterator` does not implement `AutoCloseable`. This potentially introduces resource leak when we have multiple iterators that implement `AutoCloseable` and combine them using `IteratorUtils#concat`. The caller may expect all iterators to be closed automatically by calling `CloseableIterator#closeIterator` but right now `MultiIterator` doesn't implement AutoCloseable so even the underlying iterators are auto-closeable, they are never be closed.
This simple PR just adds AutoCloseable implementation to MultiIterator, close all inner iterators if they implement AutoCloseable.
> [TINKERPOP-2416] MultiIterator should implement AutoCloseable

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-javascript/glv/GraphTraversalSource.template
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal-strategy.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/translator-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2054
This was much easier to do than I thought. A shame it wasn't done earlier actually. The serialization was already done to support `withComputer()` so all I needed to do was add the strategy classes. Javascript users will be happy to get this - it's come up over and over again.
Builds with `mvn clean install -pl gremlin-javascript`:
VOTE +1
> TINKERPOP-2054 Added traversalstrategy support to Javascript

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Handler.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketGremlinResponseDecoder.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/AbstractClient.java
https://issues.apache.org/jira/browse/TINKERPOP-2427
We have some incorrect configuration in the code such as:
1. https://github.com/apache/tinkerpop/blob/3.4-dev/gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketGremlinResponseDecoder.java#L59 (MessageToMessageDecoder automatically decreases the reference count).
1. https://github.com/apache/tinkerpop/blob/3.4-dev/gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Handler.java#L270 (SimpleChannelInboundHandler automatically decreases the reference count).
which are fixed by hardcoding values such as:
* https://github.com/apache/tinkerpop/blob/3.4-dev/gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java#L89
* Do not release reference count in …
> TINKERPOP-2427 Simplify Netty reference counting

- gremlin-javascript/glv/GraphTraversalSource.template
- gremlin-javascript/glv/generate.groovy
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal-strategy.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/type-serializers.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/client-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/traversal-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2421
Like #1329 for python this PR offers the same features for Javascript. It also fixes bad bugs with the `TraversalStrategy` implementation recently merged in #1328. I introduced some breaks to the API of the `Connection.submit()` method but folks shouldn't be using that low level class so I sense it was worth taking that break to refactor and simplify some of the tangle of code in there going back to when we sorta pushed in scripts and sessions. Hopefully, what I've modified is considered a good improvement there. 
This PR is missing documentation/changelog and I intend to add that as CTR since I want to build on the content of #1329 when that merges. 
Builds with `mvn clean install -pl gremlin-javascript`. 
VOTE +1
> TINKERPOP-2421 Added request option setting javascript

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/StringFactory.java
https://issues.apache.org/jira/browse/TINKERPOP-2364
Didn't really add any tests here as it was a small change and we don't really test the `toString()` outputs all that much. Would have pushed this change through as CTR but wanted to see if there were any concerns about changing the output by any graph providers. I can't quite imagine why this would mess anyone up but I'll leave this out here for the next few days to see if anyone has concerns. 
For comparison, here is the old output:
```text
gremlin> g.V().local(out().fold()).profile()
==>Traversal Metrics
Step                                                               Count  Traversers       Time (ms)    % Dur
============================================================================================================= …
```
> TINKERPOP-2364 Hide  injected profile() steps in metrics output

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
https://issues.apache.org/jira/browse/TINKERPOP-2410
Consider a situation where the server has sent some results back to the client and is waiting for Netty channel to be writable again before sending rest of the results. Let's assume that the client dies (or is closed) at this instant without consuming the entire set of results. In this case, the server threads will continue to wait for the channel to become writable (which it never will since client is dead) until the timeout is hit.
With this change, if the connection becomes inactive, the loop will break and free up the threads.
We don't have any test mechanism to check the number of busy server threads. Hence, no tests are added to repro this case. Any suggestions on how to add tests for such scenarios are welcome!
> TINKERPOP-2410 Release server threads waiting on connection if the connection is dead. 

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
https://issues.apache.org/jira/browse/TINKERPOP-2425
**Motivation**
In `HttpGremlinEndpointHandler` we close the connection when sending out an error in the response even if keepAlive is set as true on the request. 
**Changes**
We close the connection based on whether the keep alive is set to true or not in the request header.
> TINKERPOP-2425 Do not close HTTP connection if keep alive set to true

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ClusterBuilderTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SettingsTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SimpleSocketServer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2426
Let Netty perform the underlying WebSocket related stuff such as handshake, handling ping/pong etc. instead of writing the code ourselves.
1. Use Netty's `WebSocketClientProtocolHandler` instead of writing a custom implementation at `WebSocketClientHandler`.
1. Introduce `WsHandshakeTimeout` as a configurable parameter. Set default to 15s.
1. Rename `SimpleWebSocketServer` to more appropriately reflect its functionality in tests.
**Note**: There is no significant functionality change other than increasing handshake time from 10s to 15s. This is increased because Netty's default value for SslHandshake itself is 10s, hence WsHandshake should be larger than that. 
gremlin-driver `mvn clean install -DskipIntegrationTests=false …
> Tinkerpop-2426 Delegate WS internal handling to Netty

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-dotnet/glv/GraphTraversalSource.template
- gremlin-dotnet/glv/generate.groovy
- gremlin-dotnet/src/Gremlin.Net/Driver/Remote/DriverRemoteConnection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/Tokens.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Docs/Reference/GremlinVariantsTests.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Tokens.java
https://issues.apache.org/jira/browse/TINKERPOP-2420
Added per request options in .NET. Opted to not create `RequestOptions` like functionality in .NET since the way the client is exposed allows you to construct a bare `RequestMessage` with reasonable niceness - documented that approach a bit better. Also added documentation for the old GLVs that recently got this feature. 
VOTE +1
> TINKERPOP-2420 Per Request Options in .NET

- CHANGELOG.asciidoc
- gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/jsr223/DriverRemoteAcceptorIntegrateTest.java
- gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/ast/GremlinASTChecker.groovy
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutorOverGraphTest.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/ast/GremlinASTCheckerTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthKrb5IntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2438
There are sometimes things you want to know about what a script is doing before it goes to `eval()`. The immediate purpose is to extract timeouts passed using `with()` so that they can be applied to a request as an override to the server timeout. In this way, users who make the mistake of using this method (meant for remote bytecode requests initially) with script submission accidentally aren't left wondering why it didn't work as expected.
Performance doesn't appear to suffer too much from this added processing. I wrote this little benchmark:
```text
gremlin> baseScript = 'g.with("evaluationTimeout",1).V().out("$a").in().where(outE().has("weight",$b).count().is($c)).order().by("name",desc).limit($d).project("x","y").by("name").by(outE() …
```
> TINKERPOP-2438 Added AST preprocessing for scripts

- CHANGELOG.asciidoc
- docs/preprocessor/awk/init-code-blocks.awk
- docs/src/recipes/anti-patterns.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/BytecodeCommand.groovy
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslator.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/PythonTranslator.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslatorTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/PythonTranslatorTest.java
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorProvider.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GryoRemoteGraphGroovyTranslatorProvider.java
https://issues.apache.org/jira/browse/TINKERPOP-2442
Better testing is coming on https://issues.apache.org/jira/browse/TINKERPOP-2443 but for now I think this is about as much as we had before in a sense. More reasoning for this change can be found in the JIRA itself. 
On merge to `master` I sense we will need some additional changes as we removed Jython completely. Some documentation updates may be necessary. I will look to review those sorts of things carefully.
VOTE +1
> TINKERPOP-2442 Moved Translators to gremlin-core.

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/ClientConnectionIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2441
Support WebSocket compression extension on server and clients. The compression was standardized in https://tools.ietf.org/html/rfc7692 and Netty provides out of the box implementation for it. Note that the compression goes through a negotiation (via HTTP headers) and in cases when the server supports it but the client doesn't, it would fall back. Vice versa is also true and hence, it is a backward compatible functionality.
> TINKERPOP-2441 Add support for WebSocket compression

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2440
Java driver can be simplified by delegating the keepAlive logic to Netty's IdleStateHandler instead of maintaining and writing our own custom code. 
Note that this implementation is backward compatible for 3.4.x series as the existing keepAlive logic should still continue to work for Channelizers other than `WebSocketChannelizer` (notice the if statement in the code that checks for channelizer class before scheduling keepAlive). For `WebSocketChannelizer`, the number of Ping frames sent to the server is still the same except that it is now handled by Netty.
1. Added a new unit test
2. gremlin-server `mvn clean install -DskipIntegrationTests=false -DincludeNeo4j`
3. gremlin-driver `mvn clean install -DskipIntegrationTests=false …
> TINKERPOP-2440 Simplify driver by delegating keepAlive logic to Netty

- CHANGELOG.asciidoc
- gremlin-python/glv/GraphTraversalSource.template
- gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
- gremlin-python/src/main/jython/tests/process/test_traversal.py
https://issues.apache.org/jira/browse/TINKERPOP-2435
Seems like less of a problem in practice as most Python users wouldn't improperly do g.V().__len__ but debugging tools might do such things on code introspection as PyCharm does with its debugger. That of course would build unexpected Gremlin and will typically return no values (as any traversal ending with values() and a key that doesnt exist will just filter out).
All tests pass with `mvn clean install -pl gremlin-python`
VOTE +1
> TINKERPOP-2435 Ignored python magic methods in Gremlin sugar

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Handler.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultSet.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/AbstractResultQueueTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ResultSetTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2437
##Motivation
We do not complete the statusAttribute future if the underlying `readCompleted` is completed exceptionally.
##Testing
grenlin-server `mvn clean install -DskipIntegrationTests=false -DincludeNeo4j`
> Tinkerpop-2437 Do not leave statusAttributes future dangling

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/type-serializers.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/graphson-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2001
Pretty straightforward - follows the same pattern as python basically. No need to support native javascript lambdas at this time (anymore than there is a future need to support native python lambdas at this time) as there is no legitimate execution engine for them (though that would be neat as you could write much more fluent Gremlin in javascript that way). 
This change enabled almost 30 tests that were just being ignored and paves the way for us to write more advanced GLV tests for other purposes. 
Builds with `mvn clean install`:
VOTE +1
> TINKERPOP-2001 Add lambda support in gremlin-javascript

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-python/src/main/jython/gremlin_python/driver/tornado/transport.py
https://issues.apache.org/jira/browse/TINKERPOP-2453
Compression tests show similar results to what we saw on #1344 when we did this for Java
VOTE +1
> TINKERPOP-2453 Enable websocket compression for python

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/TraversalFilterStep.java
As a graph provider, we need `HasStep` followed by `with()` options. Right now `HasStep` doesn't implement `configuring` so we encounter `ClassCastException`. 
This commit simply adds a configuring implementation same as other steps like `PropertiesStep`.
> HasStep implements configuring

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/Serializers.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/ServerSerializers.java
https://issues.apache.org/jira/browse/TINKERPOP-2445
Remove deprecated methods.
Initialization of GraphsonV1.0 is a major contributor (~28%) to initialize a client with a single connection.
> TINKERPOP-2445 Remove unnecessary initialization of serializers

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/BytecodeCommand.groovy
- gremlin-console/src/main/resources/org/apache/tinkerpop/gremlin/console/commands/BytecodeCommand.properties
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV2d0.java
https://issues.apache.org/jira/browse/TINKERPOP-2479
https://issues.apache.org/jira/browse/TINKERPOP-2478
Also fixes TINKERPOP-2478 where whitespace was a problem with the from/translate options. See doc changes for more information on the changes along with examples.  Note that `Date` is fine now and works by default without use of the new `config` option:
```text
gremlin> :bc from g.V().property('d', new Date())
==>{"@type":"g:Bytecode","@value":{"step":[["V"],["property","d",{"@type":"g:Date","@value":1605795962056}]]}}
```
Tested manually - we don't have a good way to test these kinds of commands.
VOTE +1
> TINKERPOP-2479 Adds config/reset options to :bytecode command

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
https://issues.apache.org/jira/browse/TINKERPOP-2445
**Problem**: Client init and shutdown takes ~2s with 100 connections even if we aren't sending any queries at all (against a locally running server w/o ssl).
**Reason**: 95% of the time is taken by shutdown. More specifically, [this line](https://github.com/apache/tinkerpop/blob/3.4-dev/gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java) where we close Netty's event loop group. The default setting for closing the event loop group contains a "quiet time" of 2s, during which it will allow more requests to be handled by the executor. Thus, it will always wait at least 2s before shutting down. This 2s is configurable and we could change it instead of using the default.
**Change**: We are changing the quiet time to …
> TINKERPOP-2445 Remove quiet time when shutting down Java client

- docs/src/reference/gremlin-variants.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ClusterBuilderTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SettingsTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2482
Rename wsConnectionTimeout to connectionSetupTimeout. This is a newly introduced parameter in https://github.com/apache/tinkerpop/pull/1335 which is not released yet (scheduled to be released in 3.4.9). 
The new name represents the functionality of the parameter better which includes both ssl and websocket handshake duration.
> TINKERPOP-2482 Rename wsConnectionTimeout to connectionSetupTimeout

- CHANGELOG.asciidoc
- gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/ast/GremlinASTChecker.groovy
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutorOverGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2438
Used CompileStatic annotation and introduced a lightweight check to validate that there was reason to accept the expense of parsing. It's a bit of a hack in a sense but after some analysis it seems that there are no easy fixes. Everything ends in fairly advanced refactoring and extension of GremlinGroovyScriptEngine and GremlinGroovyClassLoader (with possible pull requests to Groovy). That seems like a fair bit of effort for what this feature is and I'm not sure it's worth it. The typical use case for timeout setting should not encounter the performance problem that would ensue from parsing to the Groovy AST.
> TINKERPOP-2438 Improved performance of GremlinASTChecker

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinScriptChecker.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinScriptCheckerTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2438
Even though TINKERPOP-2438 is already done this is a bit of a follow on to that change. The GremlinScriptChecker performs the same exact task as the GremlinAstChecker but it does so with regex parsing which should be faster than processing a full AST. I've left the GremlinASTChecker where it is because I wonder if there isn't yet some usage for more rigorous sort of checks we might come up with in the future or perhaps have checks that only work well with AST processing. It can be removed in the future if we like.
VOTE +1
> TINKERPOP-2438 Introduce GremlinScriptChecker

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/GremlinDslProcessor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalStrategies.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalStrategiesTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2473
Don't think that this is a major change in the sense that it's unlikely that anyone was relying on the old behavior. The code now just better enforces what was expected to happen.
VOTE +1
> TINKERPOP-2473 Prevented assignment of more than one strategy of the same type.

- docker/Dockerfile
After pip version is updated to 21.0 or up, `docker/build.sh -t -i -n` would have the following error:
```
Step 19/28 : RUN pip install virtualenv virtualenvwrapper
---> Running in 543385b5721a
Traceback (most recent call last):
File "/usr/local/bin/pip", line 7, in <module>
from pip._internal.cli.main import main
File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
^
SyntaxError: invalid syntax
The command '/bin/sh -c pip install virtualenv virtualenvwrapper' returned a non-zero code: 1
```
This is due to `pip` dropping support of python 2 starting from version 21.0
https://pip.pypa.io/en/stable/news/#id4
https://github.com/pypa/pip/issues/6148
> Update Dockerfile: set pip version below 21.0 due to drop support of python 2

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
https://issues.apache.org/jira/browse/TINKERPOP-2455
We deprecated the custom keep-alive functionality in the java driver back in 3.4.9 as it now relies more directly on netty. Removed it wholly for 3.5.0. 
VOTE +1
> TINKERPOP-2455 Remove previously deprecated keep-alive in driver

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/TraversalSerializersV3d0.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2168
Cached reflective method calls as they occur as was done with GraphBinary. Didn't bother to take this back to GraphSON 2.0.
VOTE +1
> TINKERPOP-2168 Optimized P GraphSON deserialization

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/IgnoreException.cs
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/gremlin.js
- gremlin-python/src/main/python/gremlin_python/structure/io/util.py
- gremlin-python/src/main/python/radish/feature_steps.py
- gremlin-python/src/main/python/radish/gremlin.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-test/features/sideEffect/GroupCount.feature
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupCountTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2395
Lists can now be keys in python dicts given this change. This change added a test that doesn't pass in .NET however. It fails more because of limitations in the Gherkin suite though in .NET and not because of incorrectness. Created https://issues.apache.org/jira/browse/TINKERPOP-2518 to deal with that.
VOTE +1
> TINKERPOP-2395 Support list as keys in Map for python

- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal.js
example is `P.within(["a", "b"])` predicate where ["a", "b"] is an array. In such case toString() must return `within("a","b")` and not within(a,b)
> fix toString() for P class when value is array

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2514
The driver throws an error if the same request id is already pending in the queue which is the solution suggested on the ticket. I think that largely solves this specific problem. I suppose there might be ways to still to trick out the server but I wonder if we need to try to account for that as this doesn't seem like a normal operating condition. Perhaps this is a good enough fix.
All tests pass with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE +1
> TINKERPOP-2514 Prevent two request ids to be pending at same time

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStartStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AddPropertyStep.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2513
Focused mostly on addE() with property() cardinality and improper from()/to() usage. This is a bit of a patch for the exact issues described in the JIRA, but probably needs to be implemented more generally as described in TINKERPOP-800. I targetted 3.5.0 with this since it does introduce some new exceptions which could be helpful to users but might also make their upgrades more challenging. As we look to release 3.5.0 shortly and likely focus more efforts there this seems like a safe move. 
VOTE +1
> TINKERPOP-2513 Improved error messaging in Gremlin construction.

- CHANGELOG.asciidoc
- docs/src/dev/provider/index.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/reference/the-graph.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/TemporaryException.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/message/ResponseStatusCode.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/DefaultTemporaryException.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2517
Implemented `TemporaryException` as an interface which means we can't really try-catch it but this approach is probably easier for providers who already have existing exception hierarchies and would just like to be able to hook into Gremlin Server's `TemporaryException` to `ResponseStatusCode.SERVER_ERROR_TEMPORARY` mapping and to not introduce breaks into embedded mode implementations where certain hierarchies are already expected.
Targeted `master` rather than `3.4-dev` as I have some concerns about serialization of enums and compatibility there. Also, this feels like a new enough piece of functionality (though a simple implementation in TinkerPop) that it should come with a minor upgrade. 
All tests pass with `docker/build.sh -t -n …
> TINKERPOP-2517 Added a TemporaryException and ResponseStatusCode

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV1d0.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV2d0.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV1d0.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerGremlinV2d0Test.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV1d0Test.java
Supersedes #1394 
@spmallette I'm not sure about the other serializers, but I've checked the:
```
AbstractGryoMessageSerializerV1d0 (& GryoMessageSerializerV1d0)
AbstractGryoMessageSerializerV3d0 (& GryoMessageSerializerV3d0)
GraphBinaryMessageSerializerV1
``` 
It's ok with the null message. If you mean some other serializers, please let me know.
> Fixed NPE during the ResponseMessageDeserializer#createObject

- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/remote-connection.js
https://issues.apache.org/jira/browse/TINKERPOP-2506
Exposes the underlying WS connection status as a property of the client. Will send a separate PR to update the type definition.
> TINKERPOP-2506 Expose WS connection status in JavaScript driver

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/NoOpBarrierStep.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/NoOpBarrierStepTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2532
This change allows vendors to use the configured barrier sizes to enable and improve batch processing (e.g. [Janusgraph-2514](https://github.com/JanusGraph/janusgraph/issues/2514)).
I also added a test class because no class existed for `NoOpBarrierStep`. I hope my implementation of `getTraversals()` does what it is expected to do. If anyone has more experience with tests for `Step` classes and would like to issue changes, please let me know.
> TINKERPOP-2532 Add public getter for maxBarrierSize

- CHANGELOG.asciidoc
- docs/src/dev/developer/for-committers.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-console/pom.xml
- gremlin-driver/pom.xml
- gremlin-driver/src/main/static/LICENSE
- gremlin-driver/src/main/static/NOTICE
- gremlin-driver/src/main/static/licenses/jcabi-log
- gremlin-driver/src/main/static/licenses/jcabi-manifests
- gremlin-driver/src/main/static/licenses/kryo
- gremlin-driver/src/main/static/licenses/minlog
- pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2476
Shades all dependencies to avoid conflicts packaging the TinkerPop code and all its dependencies. Easy enough. 
Builds with `mvn clean install -pl gremlin-driver` and I inspected the jar's contents at `target/gremlin-driver-3.5.0-SNAPSHOT-uber.jar` and it looks right including all the LICENSE/NOTICE stuff (noticed some of our other LICENSE/NOTICE stuff is out of date and will be fixing that now).
VOTE +1
> TINKERPOP-2476 Added shaded uberjar for gremlin-driver

- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/ConnectionPoolTests.cs
Link to Jira ticket: https://issues.apache.org/jira/browse/TINKERPOP-2531
DESCRITPTION:
If the server becomes unavailable for a period of time the connection pool might not be able to recreate a connection right after it closes. Even with a few retries with a backoff to recrete the connections, it might not be enough and the connections end up being removed from the _deadConnections array and never end up as valid ones in the _connections array.
This change tries to account for that, and, despite the caller getting a ServerUnavailableException, if the caller chooses to continue using the GremlinClient it already has, the ConnectionPool will try to restore itself.
Alternatives considered:
- Once the server is deemed unavailable we could leave it up to the caller to handle it and …
> TINKERPOP-2531:  Make sure connection pool is restored and brought back to health if server is temporarily unavailable.

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV1d0.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV2d0.java
Very simple changes. I just want a way to retrieve GraphSONMapper from these Serializer.
Background:
Our implementation is heavily inspired by [HttpGremlinEndpointHandler.java](https://github.com/apache/tinkerpop/blob/6c7be04be215f7877cca12b2d681d8cd81b7fb2f/gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java) and we can retrieve MessageTextSerializer there, but this can only serialize / deserialize the whole response message.
I want to have capability to serialize / deserialize any element (e.g. some Vertex or Edge only) in the graph in HttpHandler and right now I define the same GraphSONMapper separately. But if I can just grab the GraphSONMapper I already setup for MessageTextSerializer, it would be good.
This mapper object can't be …
> add getter method for GraphSONMessageSerializer

- bin/generate-home.sh
- docs/gremlint/package.json
- docs/src/dev/developer/development-environment.asciidoc
- docs/src/dev/developer/for-committers.asciidoc
https://issues.apache.org/jira/browse/TINKERPOP-2544
Updates the `bin/generate-home.sh` script to build the gremlint web page to an optimized production build which can be hosted by a static server and then copy it from `docs/gremlint/build` to `target/site/home/gremlint`.
If I understand the `bin/generate-home.sh` script correctly, it uses `rsync` to do the file copying if it is available. I've tested the script with and without `rsync`, and in both cases I've tested it with and without the page having previously been generated. I've only tested on a Linux machine.
I'll need some help to test if the `bin/publish-home.sh` script will simply just work, or if it needs modification to properly publish the built gremlint web page.
> TINKERPOP-2544: Modify site publishing scripts to include gremlint

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- gremlin-python/src/main/python/gremlin_python/process/translator.py
- gremlin-python/src/main/python/gremlin_python/process/traversal.py
- gremlin-python/src/main/python/tests/process/test_translator.py
https://issues.apache.org/jira/browse/TINKERPOP-2527
This code adds a Translator class to the Python client that will convert traversals back to Gremlin Groovy. I also included 100 or so unit tests. I have tried to cover bot step instructions and source instructions so things like strategies as well as basic Gremlin steps should get converted. This has been a common ask from Python users for a few use cases including 
1.  Writing to logs
2. Dropping out of bytecode to use sessions
3. Debugging machine generated traversals
> TINKERPOP-2527 Python->Groovy Translator

- CHANGELOG.asciidoc
- gremlin-python/src/main/jython/gremlin_python/driver/client.py
- gremlin-python/src/main/jython/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/jython/gremlin_python/driver/tornado/transport.py
- gremlin-python/src/main/jython/tests/driver/test_client.py
https://issues.apache.org/jira/browse/TINKERPOP-2457
I'm not sure how this will merge to `master` at the moment, or whether that merge is relevant there given the work to move from tornado to aiohttp. I sense this work will merge before that, so we'll see how it becomes relevant or not.
VOTE +1
> TINKERPOP-2457 Added max_content_length as Python driver config

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SimpleSocketServer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2550
This change fixes a potential deadlock issue on `Client` initialization and may have some impact on https://issues.apache.org/jira/browse/TINKERPOP-2504 as well. I won't re-document the points of this change here as I went to considerable lengths to explain it in code comments. Please see the rationale for the changes there.
VOTE +1
> TINKERPOP-2550 Fixed bug in java Client initialization

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
https://issues.apache.org/jira/browse/TINKERPOP-2562
This was retained to support much older drivers. No driver sends Bytecode this way anymore so it should be safe to remove. It probably should have been done in 3.5.0, but was missed. The UnifiedHandler never supported this message form.
VOTE +1
> TINKERPOP-2562 Removed support for GraphSON 2 based string in Request Message for TraversalOpProcessor

- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.Template.IntegrationTest/Gremlin.Net.Template.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Gremlin.Net.UnitTest.csproj
https://issues.apache.org/jira/browse/TINKERPOP-2577
This removes the unused code coverage packages mentioned in TINKERPOP-2577 that we haven't been using for anything, as well as two xUnit tools that were needed a long time ago, but aren't needed any more. I split this into two commits as both changes are independent of each other, although they are somewhat related since they both remove test dependencies that we don't need any more (hence a single PR for both).
VOTE +1
> TINKERPOP-2577 Remove unused test dependencies from Gremlin.NET

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.6.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/ElementHelper.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/iterator/AbortiveMultiIterator.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/util/iterator/AbortiveMultiIteratorTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/CoreTraversalTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphTest.java
- hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/HadoopGraph.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jGraph.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphIdManagerTest.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2507
Upgrade docs in this commit explain this change fairly well. There doesn't seem to be a need to be so prescriptive about the types that can be filtered on and it should be up to each graph to decide how they handle such input. Removed the general exception, tests and updated the behavior of graphs to support the change.
Decided to put this on 3.6.0 rather than bring what amounts to a behavior change in the middle of 3.4.x/3.5.x. 
VOTE +1
> TINKERPOP-2507 Allowed graph filters with mixed id types

- CHANGELOG.asciidoc
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java
- gremlin-python/glv/TraversalSource.template
- gremlin-python/src/main/jython/gremlin_python/process/traversal.py
- gremlin-python/src/main/jython/setup.py
- gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py
https://issues.apache.org/jira/browse/TINKERPOP-2578
This change sets up `P` to better serialize instances to the form expected for different serialization types.
VOTE +1
> TINKERPOP-2578 Coerced set to list for P within/without in Python

- CHANGELOG.asciidoc
- gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/IConnection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/ProxyConnection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketConnection.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/ConnectionPoolTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2358
If the `ConnectionPool` was disposed while it was in parallel creating new connections (e.g., to replace closed connections), those
connections could be leaked. `Dispose()` could not dispose them yet as they were not completely established so they could be added to the pool.
We now check after creating new connections whether the pool has been disposed in the meantime and then dispose these connections directly again.
In addition to that, the pool now also has a `CancellationTokenSource` which allows us to cancel all active creations of new connections in `Dispose()`. So we don't have to wait until they are created only so we can then dispose them if we can already cancel the connection establishment.
VOTE +1
> TINKERPOP-2358 Stop leaking connections on Dispose in Gremlin.NET driver

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyProcessTest.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2568
https://issues.apache.org/jira/browse/TINKERPOP-2579
This should have been there at 3.5.0 but we didn't have tests to enforce the behavior. We have those tests now though so it will be enforced going forward. Also fixes TINKERPOP-2579.
VOTE +1
> TINKERPOP-2568 Pushed the Graph instance into child traverals 

- CHANGELOG.asciidoc
- docker/gremlin-server.sh
- docker/gremlin-server/docker-entrypoint.sh
- docker/gremlin-server/gremlin-server-integration.yaml
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/reference/the-traversal.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bytecode.java
- gremlin-javascript/pom.xml
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/remote-connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/anonymous-traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/bytecode.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/transaction.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal-strategy.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/package-lock.json
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/session-client-tests.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/traversal-strategy-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/traversal-test.js
- gremlin-server/src/test/scripts/generate-all.groovy
- gremlin-server/src/test/scripts/test-server-start.groovy
- pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2557
Updated documentation. Modified the Gremlin Server setup within maven to react to -DincludeNeo4j so that it is possible to test transactions in language variants. Modified docker/gremlin-server.sh to dynamically include neo4j so that it matches the test server options when doing -DincludeNeo4j with maven. The build infrastructure is now present for other GLVs to add the `tx()` functionality so .NET and Python should be able to focus on just building the feature itself.
VOTE +1
> TINKERPOP-2557 Added support for g.tx() in gremlin-javascript

- gremlin-python/src/main/jython/setup.py
The Python build is currently broken which is apparently caused by this peer dependency in version 21.
Pinning it to 20.9 seems to fix the build.
We can remove this pinning later when the problem is gone (so the builds goes through without this pinning) or when we drop 3.4-dev as the problem seems to be limited to that branch (probably Python 2).
I think we get this dependency through our dependency on `importlib-metadata` which is why I added the dependency before that package.
This could have been a CTR commit but I wasn't sure if this is the right way to solve this.
@spmallette Feel free to merge this if you agree with this change.
VOTE +1
> Fix Python build by pinning peer dependency packaging to 20.9

- docs/src/dev/developer/development-environment.asciidoc
- docs/src/dev/developer/release.asciidoc
- gremlin-console/pom.xml
- gremlin-server/pom.xml
This adds my lessons learned from the release process. I also noticed that we tag the docker images on `3.4-dev` with `latest` which we shouldn't do anymore now that we have 3.5.z releases as those should always be the latest release. So this removes the `latest` tag from the `3.4-branch` and I'll open another branch to target `3.5-dev` which keeps the `latest` tag there.
The deployment of Docker images failed for me through Maven so I had to manually posh the images. This seems to be a known issue for our Maven plugin: spotify/dockerfile-maven#344.
If I'm the only one affected by this, then we don't need to do anything from my side, but if others also run into this problem, then we should probably check whether we can replace that Maven plugin as it's also not actively maintained any …
> Document lessons learned releasing 3.4.12/3.5.1

- docs/gremlint/config-overrides.js
- docs/gremlint/package-lock.json
- docs/gremlint/package.json
- docs/gremlint/src/App.tsx
- docs/gremlint/src/components/CenteredContainer.tsx
- docs/gremlint/src/components/Footer.tsx
- docs/gremlint/src/components/StyleGuideRule.tsx
- docs/gremlint/src/components/View.tsx
https://issues.apache.org/jira/browse/TINKERPOP-2591
**Install gremlint from npm rather than from OyvindSabo/gremlint**
Previously the gremlint website installed the gremlint library from the old gremlint repo (OyvindSabo/gremlint). Now that it's available on npm it can be installed from there.
**Add footer displaying current gremlint version and copyright notice**
The footer is always positioned below the view content of the website, but it sticks to the bottom of the screen if there is not enough content to push it out of the screen. I avoided using any of the approaches which depend on a fixed footer height, as that could cause weird behavior for users with narrow screens where the footer text wraps.
The gremlint version is pulled from the `package-lock.json` file. Displaying the …
> TINKERPOP-2591: Administrative adjustments to gremlint site

- CHANGELOG.asciidoc
- docs/src/dev/developer/contributing.asciidoc
- docs/src/dev/developer/development-environment.asciidoc
- docs/src/recipes/olap-spark-yarn.asciidoc
- docs/src/reference/implementations-hadoop-start.asciidoc
- hadoop-gremlin/pom.xml
- hadoop-gremlin/src/test/resources/log4j-silent.properties
- hadoop-gremlin/src/test/resources/log4j-test.properties
- pom.xml
- spark-gremlin/pom.xml
- spark-gremlin/src/test/resources/log4j-silent.properties
- spark-gremlin/src/test/resources/log4j-test.properties
Had to bring back log4j configs for purpose of hadoop which seems tightly bound to log4j 1.x. These configurations should not be used for any other purpose nor should we rely on log4j elsewhere as 1.x has CVEs associated with it.
VOTE +1
> Bump to Spark 3.1.2 and Hadoop 3.3.1

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/AbstractLambdaTraversal.java
Graph provider should be able to access bypassTraversal when analyzing traversal for query execution.
> Added getter method for bypassTraversal in AbstractLamdaTraversal

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
https://issues.apache.org/jira/browse/TINKERPOP-2597
The clean-up method was looking to call a method on the AtomicInteger which was not instantiated. This change instantiates it before any connections are made and increments for every successful Connection created instead of setting it after all of them are created.
> TINKERPOP-2597 Fix NPE due to CompletionException in ConectionPool

- CHANGELOG.asciidoc
- docker/gremlin-server/gremlin-server-integration-krb5.yaml
- docker/gremlin-server/gremlin-server-integration-secure.yaml
- docker/gremlin-server/gremlin-server-integration.yaml
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPoolSettings.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/Remote/DriverRemoteConnection.cs
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-server/conf/gremlin-server-classic.yaml
- gremlin-server/conf/gremlin-server-modern-readonly.yaml
- gremlin-server/conf/gremlin-server-modern.yaml
- gremlin-server/conf/gremlin-server-neo4j.yaml
- gremlin-server/conf/gremlin-server-rest-modern.yaml
- gremlin-server/conf/gremlin-server-rest-secure.yaml
- gremlin-server/conf/gremlin-server-secure.yaml
- gremlin-server/conf/gremlin-server-spark.yaml
- gremlin-server/conf/gremlin-server.yaml
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
- gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
Changed the defaults where it appeared to have a corresponding setting to one in Java with a different value.
Was mentioned that the specific default changes should be mentioned in the changelog using 3.5.1 as a template in this file:  https://github.com/apache/tinkerpop/blob/3.5-dev/docs/src/upgrade/release-3.5.x.asciidoc but there didn't seem to be an apparently appropriate place to put it under 3.5.2 looking at the 3.5.1 template.
> TINKERPOP-2379 Make defaults consistent with Java

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/reference/the-traversal.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/CoreImports.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/GenericLiteralVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslator.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/DatetimeHelper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/GeneralLiteralVisitorTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslatorTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/util/DatetimeHelperTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2596
Added GroovyTranslator support by way of a new type serializer - in this way, standard Date/Timestamp translation of old can be preserved.
VOTE +1
> TINKERPOP-2596 Added datetime() to gremlin-language

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.6.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/NumberHelper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/util/NumberHelperTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2610
It is now possible to return byte/short explicitly rather than promoting to int. See the upgrade docs for examples and further explanation.
VOTE +1
> TINKERPOP-2610 Fixed inconsistency in NumberHelper return types

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/exception/NoHostAvailableException.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSslIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2616
NoAvailableHostException now contains the context for what caused it. A limitation to this is that it takes the last failed ConnectionPool initialization as its cause. Alternatively I considered adding a list of exceptions to NoAvailableHostException so that the user could see every failure - not sure if this is desirable though - let me know if this is something that is thought of as a good idea and I can update this PR.
Also, some of the exception handling needed some care, specifically there was a lot of `catch (Exception e)` blocks which were unnecessarily wrapping RuntimeExceptions, and any children Exceptions, in a new RuntimeException when they could be directly returned to the user.
> TINKERPOP-2616: Provide better exceptions with SSL related failures

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/ClientConnectionIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2486
The method to select the least used connection is now synchronized and now includes the increment on its usage count so that it will not be fetched by multiple threads if it is not the least used connection. It now instead will decrement the usage if we deem that it will not be used. 
Also, simplified and cleaned-up some logic currently using unnecessary `while (true)` loops.
> TINKERPOP-2486 Fix load balancing across connections

- CHANGELOG.asciidoc
- docker/gremlin-server/gremlin-server-integration-krb5.yaml
- docker/gremlin-server/gremlin-server-integration-secure.yaml
- docker/gremlin-server/gremlin-server-integration.yaml
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/GremlinLangScriptEngine.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/GremlinLangScriptEngineFactory.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/GremlinScriptEngine.java
- gremlin-core/src/main/resources/META-INF/services/org.apache.tinkerpop.gremlin.jsr223.GremlinScriptEngineFactory
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/jsr223/GremlinLangScriptEngineTest.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestOptions.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/ServerGremlinExecutor.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
- gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
https://issues.apache.org/jira/browse/TINKERPOP-2583
`GremlinLangScriptEngine` uses the grammar to eval the Gremln scripts. Only enabled its usage for the test server yaml files. Not expecting to enable it along 3.5.x but wanted the functionality here in case folks want to play with it a bit. This change obviously doesn't satisfy TINKERPOP-2583, but it is a first step. 
VOTE +1
> TINKERPOP-2583 Added GremlinLangScriptEngine

- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/StreamExtensions.cs
- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/Types/BigIntegerSerializer.cs
https://issues.apache.org/jira/browse/TINKERPOP-2646
They can now also be used by users and driver providers who implement their own custom GraphBinary types.
I decided to change the signature of `ReadAsync()` a bit as it's easier to use if only the number of bytes to read has to be provided instead of a buffer that needs to have the correct length.
VOTE +1
> TINKERPOP-2646 Make StreamExtensions accessible

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslator.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslatorTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2649
When running Gremlin queries through the translator Dates and Timestamps need to be long's, not int's
The gremlin-console supports both so this fix is mainly for runnig the translated queries in Java
edit:
forgot to mention that `docker/build.sh -t -i -n` passes all tests
> TINKERPOP-2649 use long's to construct dates and timestamps for java

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/CloseableIterator.java
https://issues.apache.org/jira/browse/TINKERPOP-2626
This is not a complete fix for this issue but does get rid of the premature close. Opted to try to close the Traversal as part of hasNext() as in a sense it is a way to complete iteration of the traversal. Without that change certain tests begin to fail so some additional change besides removing the premature close had to be added.
VOTE +1
> TINKERPOP-2626 Prevent premature close of traversal

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/PythonTranslator.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/PythonTranslatorTest.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2656
This PR implements two changes to the python translator
1. The `SymbolHelper` map has been updated to include the missing
reserved words/global functions differences for built in Python keywords
https://tinkerpop.apache.org/docs/3.5.1/reference/#gremlin-python-differences
2. A new translator type, `NoSugarTranslator`, has been added which
translates the Gremlin query without using any of the syntax sugar.
Given the following query:
```
g.V().range(0, 10).has("person", "name", "marko").limit(2).values("name")
```
Default translator:
```
g.V()[0:10].has('person','name','marko')[0:2].name
```
No sugar translator:
```
g.V().range_(0,10).has('person','name','marko').limit(2).values('name')
```
docker/build.sh -t -i -n passes all tests
> TINKERPOP-2656 update python translator to provide an option for non synantic sugar translations

- CHANGELOG.asciidoc
- gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/Tokens.cs
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
- gremlin-python/src/main/python/gremlin_python/driver/client.py
https://issues.apache.org/jira/browse/TINKERPOP-2660
Adding them back may just be temporary, so the message remains deprecated on the server side. Session semantics needs better definition going forward at which point the final disposition for this message can be established.
VOTE +1
> TINKERPOP-2660 Added back close message to drivers

- CHANGELOG.asciidoc
- docs/src/dev/developer/for-committers.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/GenericLiteralVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/GremlinBaseVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/GremlinStringConstantsVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/StructureElementVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalFunctionVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalMethodVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalPredicateVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceSelfMethodVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslator.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/GeneralLiteralVisitorTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/StructureElementVisitorTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalPredicateVisitorTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslatorTest.java
- gremlin-language/src/main/antlr4/Gremlin.g4
https://issues.apache.org/jira/browse/TINKERPOP-2663
This is helpful for `addE()` with `from()` and `to()` to be consistent with `Vertex` object signatures.
VOTE +1
> TINKERPOP-2663 Allowed for Vertex/ReferenceVertex in grammar

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
This is a bit of a follow on to the previous PR on this issue. The closed state prevents further iteration on a traversal when it has been exhausted and resources have been released. This change is non-breaking but should likely be refactored when merged to branch that can take a breaking change.
VOTE +1
> TINKERPOP-2626 Added explicit closed state to DefaultTraversal

- CHANGELOG.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/RemoteCommand.groovy
- gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/jsr223/DriverRemoteAcceptor.java
- gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/jsr223/DriverRemoteAcceptorTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
Additional minor fixes for https://issues.apache.org/jira/browse/TINKERPOP-2569 based on comments in https://github.com/apache/tinkerpop/pull/1476. 
Added user friendly message in Gremlin console when creating remote connection to hosts that are unavailable.
Added a `remote.close()` in `RemoteCommand.groovy` when `RemoteException` are thrown during connection in `do_connect` to fix possible leak.
> TINKERPOP-2569: Additional Fixes

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/GremlinAntlrToJava.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/GremlinBaseVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceTxVisitor.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceTxVisitorTest.java
- gremlin-language/src/main/antlr4/Gremlin.g4
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinSessionTxIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2671
Adding tx() support to gremlin-language brings its grammar/parser closer in line with what is possible now with bytecode and with Groovy scripts. From the user's perspective there is now a clear way for them to signify that their transaction is closed with either rollback or commit. Support for begin() is present for consistency in the API but technically it is just a no-op. Documentation will arrive around gremlin-language for https://issues.apache.org/jira/browse/TINKERPOP-2644 - for now this lands a bit under the radar for 3.5.13.
VOTE +1
> TINKERPOP-2671 Added tx() support in gremlin-language

- .github/workflows/build-test.yml
- docker/Dockerfile
- docs/src/dev/developer/development-environment.asciidoc
- gremlin-dotnet/src/Gremlin.Net.Template/Gremlin.Net.Template.csproj
- gremlin-dotnet/src/pom.xml
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.Template.IntegrationTest/Gremlin.Net.Template.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Gremlin.Net.UnitTest.csproj
- gremlin-dotnet/test/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2651
Note that this only affects our build process and the Gremlin.Net.Template. Users of Gremlin.Net will not be affected by this change as that still targets .NET Standard 2.0 (and additionally .NET Standard 1.3 in `3.4-dev`).
This does not necessarily have to be merged before code freeze for 3.4.13/3.5.2/3.6.0. I'm just opening the PR now as I have the contribution ready, but I can also simply retarget this on `3.5-dev` if we don't get it merged before code freeze.
I verified that the Docker build also still works with `docker/build.sh -t`.
VOTE +1
> TINKERPOP-2651 Update to .NET 6

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/NumberHelper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/CompareTest.java
Since there is no such concept of "Infinite" number in BigDecimal, a comparison between a BigDecimal and a Float.INFINITE or Double.INFINITE causes a parsing exception.
Example:
```java
Vertex alice = g.addV("person").property("hair", Double.POSITIVE_INFINITY ).next();
Vertex bob = g.addV("person").property("hair", 500 ).next();
String query =“g.V().has('hair',500.00)”;
```
For more information: https://github.com/ArcadeData/arcadedb/issues/289
> Fixed issue on comparing BigDecimal with Double/Float infinite numbers

- docs/src/dev/io/graphbinary.asciidoc
Enum like types (Barrier, Cardinality, Column, Direction, Operator, Order, Pick, Pop, Scope, T) should provide enum element name as a fully-qualified string, i.e. as `{type_code}{type_info}{value_flag}{value}`.
> docs: Fix GraphBinary enum like types specification

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-dotnet/src/Gremlin.Net/CompatibilitySuppressions.xml
- gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionFactory.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketConnection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketSettings.cs
- gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj
- gremlin-dotnet/test/Gremlin.Net.Benchmarks/CompressionBenchmarks.cs
- gremlin-dotnet/test/Gremlin.Net.Benchmarks/Gremlin.Net.Benchmarks.csproj
- gremlin-dotnet/test/Gremlin.Net.Benchmarks/Program.cs
https://issues.apache.org/jira/browse/TINKERPOP-2695
WebSocket support was only added in .NET 6 which made it necessary to explicitly add .NET 6 as an additional target framework. Compression will now be enabled by default on .NET 6 as it's only available there. This made it necessary to add conditional compilation based on the target framework.
I also enabled [package validation](https://docs.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview) so we a) notice if we introduce breaking changes by accident and b) ensure that our code compiled against .NET Standard 2.0 can also be run against .NET 6. This already helped me to keep the breaking change here to a minimum. It's just an added optional parameter here to be able to disable compression. We could refactor the …
> TINKERPOP-2682 Enable WS compression in .NET

- docs/src/dev/io/graphbinary.asciidoc
Mentioned List and Set are expected to be fully qualified according to the
actual behaviour of gremlin-server.
> docs: Fix GraphBinary Path type spec typo

- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/TypeSerializerRegistry.cs
- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/GraphSONWriter.cs
Return true from GraphSONWriter.IsDictionaryType not only when the type is an actual Dictionary<,>, but even if it's something else that implements IEnumerable<KeyValuePair<,>>. This is useful when an instance of an ImmutableDictionary is passed as Bindings to a RequestMessage.
> Open up 'IsDictionaryType' to recognize more actual types

- CHANGELOG.asciidoc
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/python/gremlin_python/driver/remote_connection.py
- gremlin-python/src/main/python/gremlin_python/process/graph_traversal.py
- gremlin-python/src/main/python/tests/driver/test_client.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-python/src/main/python/tests/process/test_traversal.py
https://issues.apache.org/jira/browse/TINKERPOP-2707
Not closing these sessions could end in a leak if a user opts to get a little loose with the expected API calls for properly handling sessions. This change should prevent accidents.
VOTE +1
> TINKERPOP-2707 Close of parent connection also calls close on spawned child sessions.

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
...because, as it states a few lines below:
Returns:
the traversal with an appended AggregateGlobalStep
> Fix reference docs for aggregate without parameters

- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Direction.cs
Using `=>` instead of `=` also makes these properties instead of fields which is more consistent with the other properties there.
These directions were only added in #1555 which wasn't released yet, so this is not breaking anything.
VOTE +1
> TINKERPOP-2681 Use PascalCase for added Directions

- gremlin-python/src/main/python/gremlin_python/driver/client.py
driver.Client.submitAsync is not returning the result of self.submit_async, so the future is not being passed forward to the caller.
While it's understood this interface is deprecated, it should still behave as it previously did in 3.4 until it is removed.
> return future when Client.submitAsync is called

- CHANGELOG.asciidoc
- gremlin-python/src/main/python/gremlin_python/process/translator.py
- gremlin-python/src/main/python/tests/process/test_translator.py
https://issues.apache.org/jira/browse/TINKERPOP-2726
This ensures that the GroovyTranslator in Python creates valid boolean values `true` /  `false` instead of `True` / `False`.
VOTE +1
> TINKERPOP-2726 Fix boolean translation in Python

- gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionFactory.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/Exceptions/ConnectionClosedException.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/IClientWebSocket.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/ProxyClientWebSocket.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketConnection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketSettings.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/ConnectionTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2717
Per [RFC 6455 WebSocket](https://datatracker.ietf.org/doc/html/rfc6455#section-1.4), either peer in a websocket an initiate a close handshake by sending a close message frame. In practical terms, a Gremlin server can send a close message to the client and the client should notify in-flight requests and acknowledge the closure.
Currently, Gremln.NET does not check for a `WebSocketMessageType.Close`, resulting in a `NullReferenceException` when attempting to deserialize an empty message body.
Change addresses this in the following way:
1. Adds `ConnectionClosedException` that includes CloseStatus and CloseDescription properties that a WebSocket close message can return.
2. Checks for `WebSocketMessageType.Close` in …
> TINKERPOP-2717 handle websocket close message and add ConnectionClosedException in Gremlin.NET

- docs/src/dev/developer/administration.asciidoc
The Apache Reporter Service now seems to be the preferred way to submit board reports, but Whimsy is also a good alternative.
I've removed the template for the report because I've just changed the format in the last report according to what's suggested by the reporter service so we now have two different formats that we've used.
I also think that anybody who might at any point submit such a report has already read enough other reports so that they know the format and have enough older reports as a reference.
VOTE +1
@spmallette: I could have probably committed this via CTR, but I wanted to give you a chance to review this at least.
> Update board reports docs

- docs/site/home/gremlin.html
I was reading the [Introduction to Gremlin](https://tinkerpop.apache.org/gremlin.html) doc and found a few typos. One of them is very misleading because it uses "on the left/right" to refer to code boxes but the relative positions are wrong. The others are just minor typos that don't affect readability.
> [docs] Fix typos in Intro to Gremlin page

- gremlin-go/driver/connection.go
- gremlin-go/driver/protocol.go
- gremlin-go/driver/resultSet.go
- Fixed a potential deadlock that would occur whenever reading from the server fails in a fashion that is not specific to a specific request, e.g. the connection is dead
- Fixed a potential edge case where a ResultSet would not return an error (it would only log it) alongside an incomplete set of results
> Fix deadlock on non response-specific read errors

- docs/src/reference/gremlin-variants.asciidoc
- gremlin-go/driver/anonymousTraversal.go
- gremlin-go/driver/bytecode.go
- gremlin-go/driver/bytecode_test.go
- gremlin-go/driver/client.go
- gremlin-go/driver/connection_test.go
- gremlin-go/driver/driverRemoteConnection.go
- gremlin-go/driver/error_codes.go
- gremlin-go/driver/graphBinary.go
- gremlin-go/driver/graphTraversal.go
- gremlin-go/driver/graphTraversalSource.go
- gremlin-go/driver/request.go
- gremlin-go/driver/serializer.go
- gremlin-go/driver/strategies.go
- gremlin-go/driver/strategies_test.go
- gremlin-go/driver/traversal.go
- gremlin-go/driver/traversal_test.go
Exported the Bytecode struct and methods for use with creating custom DSL in gremlin-go, which are minor edits that make up majority of the changes. 
Examples of how to use DSL in go has been added to the gremlin variants ascii documentation.
> Gremlin-Go: Add DSL support documentation 

- docs/src/dev/developer/development-environment.asciidoc
This change adds to the note of the Windows Build in `development-environment.asciidoc` to include details on making the local build of Hadoop Gremlin work as expected on Windows.
Issue: [TINKERPOP-2749](https://issues.apache.org/jira/browse/TINKERPOP-2749)
> TINKERPOP-2749: Hadoop Gremlin Windows Build Note

- .github/workflows/build-test.yml
- gremlin-javascript/pom.xml
- gremlin-javascript/src/main/javascript/gremlin-javascript/.eslintrc.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/package-lock.json
- gremlin-javascript/src/main/javascript/gremlin-javascript/package.json
- gremlin-server/src/test/scripts/test-server-start.groovy
- gremlint/pom.xml
Currently, Tinkerpop does not build on Windows. Running `mvn clean install` causes errors in `gremlin-javascript` and other modules.
This PR fixes the errors caused by `gremlin-javascript`. It also adds a Windows build check to the GitHub Actions workflows.
Issues addressed:
1. Fixed an issue where groovy script defined in `gremlin-javascript/pom.xml` receives an incorrectly formatted path for Windows. Single `\` characters are invalid in groovy and using `${project.basedir}` returns a string with non-escaped `\` characters.
2. Fixed an issue where lint/line-break checks would fail with message: `Expected linebreaks to be 'LF' but found 'CRLF'`
3. Fixed an issue where relative addressing is used, which was causing `'.' is not recognized as an internal or external command, operable program …
> TINKERPOP-2749: Gremlin Javascript, Gremlint Windows build error fixes

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Handler.java
https://issues.apache.org/jira/browse/TINKERPOP-2740
Replaced getCanonicalHostName() with getHostName() to to get rid of slow reverse DNS lookup
> [TINKERPOP-2740] first request suspend more than 9s when using gremlin-java-driver

- .github/workflows/build-test.yml
- spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/AbstractIoRegistryCheck.java
Spark Build on Windows Causes Errors along the lines of:
```
[ERROR] Failures: 
[ERROR] org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck.shouldSupportGraphSONIoRegistry(org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck)      
[INFO]   Run 1: PASS
[ERROR]   Run 2: SparkIoRegistryCheck.shouldSupportGraphSONIoRegistry:67->AbstractIoRegistryCheck.checkGraphSONIoRegistryCompliance:98
[INFO]
[ERROR] org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck.shouldSupportGryoV1d0IoRegistry(org.apache.tinkerpop.gremlin.spark.structure.io.SparkIoRegistryCheck)      
[INFO]   Run 1: PASS
[ERROR]   Run 2: SparkIoRegistryCheck.shouldSupportGryoV1d0IoRegistry:57->AbstractIoRegistryCheck.checkGryoV1d0IoRegistryCompliance:75
[INFO]
[ERROR] …
```
> TINKERPOP-2749: Spark Gremlin Windows Build Error Fixes

- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-python/src/main/python/gremlin_python/driver/serializer.py
- gremlin-python/src/main/python/setup.py
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2631
Since ujson is an optional dependency, hard enforcing a version may cause problems for users.
Instead, a version >= 2.0.0 is specified to be automatically resolved by the Python package manager if someone were to use install gremlin-python with ujson enabled. A warning is also given when using a version below 2.0.0 is detected.
> Specify ujson version of 2.0.0 or greater

- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/UnifiedHandler.java
A fix to the error message on session close reported in https://issues.apache.org/jira/browse/TINKERPOP-2735. 
Session `close` request will output `Unrecognized content` error message in 3.5.x server, the fix is in 3.6.0 where `UnifiedHandler` has an added [check](https://github.com/apache/tinkerpop/blob/225035c0b943a532152073da393cdb466b311693/gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/UnifiedHandler.java#L141) to handle close requests, whereas the 3.5.x server does not, and that causes the request to fall through into the exception [here](https://github.com/apache/tinkerpop/blob/287499e207faef9bea28ec20234026e132b63d33/gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractSession.java#L844) with a null content type for the gremlin …
> TINKERPOP-2735: Backport fix to close request error in UnifiedChannelizer to 3.5-dev

- gremlin-dotnet/src/Gremlin.Net/Driver/Messages/ResponseStatusCode.cs
Add missing response status codes to the enum in .NET. Currently, it is not possible to use the new fail()-operator since it'll 
return a new status code (595) which makes the `IndicatesError` method throw.
@FlorianHockmann Maybe this justifies an out-of-band release of a patched Gremlin.NET ?
> Complete ResponseStatusCodeEnum in .NET (3.6-dev)

- gremlin-dotnet/src/Gremlin.Net/Driver/Messages/ResponseStatusCode.cs
Analog to #1698 but for 3.5-dev and without the status code 595.
> Complete ResponseStatusCodeEnum in in .NET (3.5-dev)

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/Gremlin.java
- pom.xml
- use a more specific key to avoid race on version
- see: https://github.com/JanusGraph/janusgraph/discussions/3004
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2761
> TINKERPOP-2761: fix version key race in Manifest

- docs/src/reference/gremlin-variants.asciidoc
- gremlin-go/docker/gremlin-server-integration-secure.yaml
- gremlin-go/docker/gremlin-server-integration.yaml
- gremlin-go/driver/connection_test.go
- gremlin-go/driver/request.go
The issue that triggered this change is that per-request options were not working with gremlin-go. For instance setting a per-request timeout this way:
```go
result, err := g.With("evaluationTimeout", 5000).V().Count().Next()
if err != nil {
// Handle error.
}
```
A very similar problem was described some time ago for the Python GLV in the JIRA issue [TINKERPOP-2296](https://issues.apache.org/jira/browse/TINKERPOP-2296) and solved in the pull-request [apache/tinkerpop#1329](https://github.com/apache/tinkerpop/pull/1329).
Stephen Mallette explains the root cause of the issue in a comment in JIRA:
> There is no real strategy application in GLVs - the strategies are simply shipped to the server as bytecode configurations. By that point, it's already bypassed the point where the server will …
> gremlin-go: support per-request arguments in bytecode

- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractSession.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateWithUnifiedChannelizerTest.java
Link to issue: [TINKERPOP 2751](https://issues.apache.org/jira/browse/TINKERPOP-2751)
If a transaction is attempted on a graph that does not support transactions, the client hangs as it waits for a response from the server. The change in this PR handles that case and responds to the client with a `transactionNotSupported()` exception.
Ideally, we would want the client to fail at `tx.begin()` but this would involve a much bigger change on the server and across the GLVs. For now, users should be notified that they need to use a transaction-enabled graph when attempting to perform a graph operation (rollback or commit)
> TINKERPOP-2751: Throw exception if transaction attempted on non transaction supported Graph

- docs/src/reference/the-traversal.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/Attachable.java
Related to #1657
Demo:
```
gremlin> v1 = g.addV().property("feature0", "0.0").property("feature0", "1.1").next()
==>v[0]
gremlin> g.V().valueMap()
==>[feature0:[0.0,1.1]]
gremlin> g.io("graph.json").write().iterate()
gremlin> g.V().drop()
gremlin> g.io("graph.json").read().iterate()
WARN  org.apache.tinkerpop.gremlin.structure.util.Attachable  - feature0 has SINGLE cardinality but with more than one value: [vp[feature0->0.0], vp[feature0->1.1]]. Only last value will be retained.
gremlin> g.V().valueMap()
==>[feature0:[1.1]]
```
> TINKERPOP-2742: Warn users of vertex property cardinality mismatch

- gremlin-go/docker-compose.yml
- gremlin-go/run.sh
The current `docker-compose.yml` file is not compatible with the docker-compose version packaged by some widely used Linux distributions. For instance, Debian bullseye (current stable) [packages docker-compose 1.25.0](https://packages.debian.org/bullseye/docker-compose).
docker-compose 1.25.0 [supports up to compose file format 3.7](https://github.com/docker/compose/releases/tag/1.25.0) and requires the version to be explicitly set in the `docker-compose.yml` file.
By setting the version of the `docker-compose.yml` file to 3.7 we support docker-compose 1.22.0+ and the only required change is adding the "version" field. Also, [version 3 has not been deprecated](https://docs.docker.com/compose/compose-file/compose-versioning/).
Finally, `run.sh` accepts a gremlin-server version as argument, …
> gremlin-go: improve docker-compose compatibility, fix run.sh command line parsing

- gremlin-dotnet/src/pom.xml
- gremlin-dotnet/test/pom.xml
- gremlin-javascript/pom.xml
- gremlin-python/pom.xml
- gremlin-server/src/test/scripts/test-server-start.groovy
- gremlint/pom.xml
Pathing changes introduced to support the windows build of `gremlin-javascript`, `gremlin-dotnet`, and `gremlint` would make it so that building Tinkerpop or its modules from anywhere other than the Tinkerpop root would not work. 
The changes in this PR would make it so that maven commands such as `install`, `verify`, `compile` and so on would work as expected from outside the root.
> Improved pathing changes made for Windows Build Support

- gremlin-go/driver/protocol.go
- gremlin-go/driver/protocol_test.go
Fix a deadlock when a remote connection is closed and, at the same time, the connection fails. The following call graphs illustrate the issue:
goroutine run by main:
```
(*DriverRemoteConnection).Close
(*Client).Close
(*loadBalancingPool).close
(*connection).close
(*gremlinServerWSProtocol).close
(*WaitGroup).Wait
```
gremlin-go's readLoop goroutine:
```
(*gremlinServerWSProtocol).readLoop
readErrorHandler
(*connection).errorCallback-fm
(*connection).errorCallback
(*gremlinServerWSProtocol).close
(*WaitGroup).Wait
(*WaitGroup).Done
```
`protocol.closed` is only modified by `(*gremlinServerWSProtocol).close`. If it is true it means that `(*WaitGroup).Wait` has already been called, so it should not be called again.
> gremlin-go: fix deadlock on (*DriverRemoteConnection).Close

- gremlin-go/driver/error_codes.go
Move the initialization of the localizer to an init function, so no data race happens because multiple goroutines call `NewError` during its initialization.
The following stack trace shows an instance of this problem (beware, some pending PRs have been applied, so line numbers could differ):
```
WARNING: DATA RACE
Read at 0x00c0026a9580 by goroutine 2515:
github.com/nicksnyder/go-i18n/v2/i18n.(*Bundle).getMessageTemplate()
/home/n/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.2.0/i18n/bundle.go:139 +0x1e8
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).getMessageTemplate()
/home/n/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.2.0/i18n/localizer.go:175 +0x18a
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).LocalizeWithTag() …
```
> gremlin-go: fix data race on localizer initialization

- docs/src/reference/gremlin-variants.asciidoc
Add documentation that explains how to workaround gremlin-python's need to use asyncio event loops for asynchronous applications that already have an event loop running. This issue has been reported multiple times (most recently in https://issues.apache.org/jira/browse/TINKERPOP-2755).
> Add documentation for gremlin-python event loop issue workarounds.

- gremlin-go/driver/graphBinary.go
- gremlin-go/driver/graphBinary_test.go
Patching the go GraphBinary serializer with these 3 types. 
Serializing `int8` as Short, since there is no signed 8-bit integer type in GraphBinary I/O ([Byte](https://tinkerpop.apache.org/docs/3.6.0/dev/io/#_byte_3) is an unsigned 8-bit integer). Serializing both `uint` and `uint64` as BigIntegers, as they don't fit into Long.
> Gremlin-Go: Add int8, uint, and uint64 serialization

- gremlin-python/src/main/python/gremlin_python/statics.py
- gremlin-python/src/main/python/tests/test_statics.py
Added missing return statements in SingleByte and SingleChar classes (e.g. `SingleByte(2)` will return `None` without the `return`), and fixed bug in SingleChar `if` check.
> Gremlin-Python: added return in SingleByte and SingleChar & fixed if check bug

- gremlin-go/docker-compose.yml
- gremlin-go/driver/graphTraversal.go
- gremlin-go/run.sh
GHA was not capturing the exit code from `docker-compose up` because `docker-compose down` was executed separately. Now exiting upon the compose up exit code at the end of `run.sh`, and GHA should correctly capture failed golang tests.
Fixed the failing golang test related to recent [PR](https://github.com/apache/tinkerpop/pull/1743) that was missed due to the above mistake. 
Doubled the wait-for-server retry count as sometimes neo4j takes longer to get installed in GHA, to prevent premature exit of the tests.
> Gremlin-Go: Fixed bug for GHA, increased server wait retries & fixed traversal int casting

- docs/site/home/gremlin.html
The Gremlin example of declarative traversal on the TinkerPop website is incorrect, as the graph pattern specified does not yield the correct results. This PR fixes the example.
Screenshot of how the example looks _before_ this edit:
Screenshot of how the example looks _after_ this edit:
I tested these changes by creating a [minimal example on Gremlify](https://gremlify.com/1xjysyo1wzt/1), you can use it to verify that the new query example is correct.
I also removed a random space in the imperative traversal example which looked weird on the site.
> Fix declarative Gremlin example on the TinkerPop website

- .github/workflows/build-test.yml
- gremlin-go/Dockerfile
- gremlin-go/docker-compose.yml
- gremlin-go/driver/README.md
- gremlin-go/pom.xml
- gremlin-server/pom.xml
With these changes, users should be able to run `mvn clean install` in Windows with 3.5-dev successfully. 
Main changes are:
1. The removal of the plugin `dockerfile-maven-plugin`, as it is fails on Windows without clear resolution, we are using raw docker build execution in server for image building.
2. The use of `docker-compose` directly instead of the `run.sh` script, as bash script will not work in Windows. The `run.sh` script will remain as an optional tool in gremlin-go for uses to run the tests. 
A flag `-DskipImageBuild` is introduced to allow skipping the image building on incompatible platforms. Currently GHA Windows Servers fails when building linux based images (alpine jdk), and so the server image building have been disabled in Spark windows GHA while we investigate …
> Gremlin-Go: Update CI to run on Windows

- docker/scripts/build.sh
- docs/src/dev/developer/development-environment.asciidoc
To avoid the Docker-in-Docker issue when a user tries to run Docker Integration with `docker/build.sh`, we'd like to remove the gremlin-go build from the build script for now. 
A note is added in the documentations to direct users to run Gremlin-Go in Docker separately as instructed under `gremlin-go/driver/README.md`. 
Progress involved in resolving this issue and re-enabling gremlin-go will be tracked under https://issues.apache.org/jira/browse/TINKERPOP-2737.
> Gremlin-Go: skipping gremlin-go in TinkerPop Docker build integration

- pom.xml
As per reported https://issues.apache.org/jira/browse/TINKERPOP-2771.
> TINKERPOP-2771: bump commons.configuration.version to 2.8.0 to fix vulnerability

- gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
Attempting to reach localhost on Windows with a client can be resolved with IPv6 and IPv4 addresses. The WebSocket client tries to establish a connection to the IPv6 address with a timeout of 1 sec and attempts to do this 2 times. Gremlin Server does not accept connection for IPv6, so it refuses it. Then the client connects to IPv4 address.
With 0.0.0.0 server will accept all connections, including IPv6.
> Allow connections from IPv6 for `test-server-start.groovy` server

- README.asciidoc
- docs/src/dev/developer/development-environment.asciidoc
Added instructions to download the required winutils binaries on Windows to build Hadoop and Spark.
> Update documentations for Windows build

- docs/src/reference/gremlin-variants.asciidoc
Outdated limitations which weren't caught before.
> Gremlin-Go: Go driver limitations update

- .github/workflows/build-test.yml
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/MessagesTests.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/ConnectionTests.cs
Enabled running dotnet tests on Windows on GitHub Actions.
Fixed dotnet tests for Windows GHA:
- test ShouldUseSpecifiedEvaluationTimeout. The test checks that EvalTimeout parameter works. Usual test request waiting time on server before execution is ~10-25 seconds, so I increased timeout to have time to spare.
- test ShouldHandleCloseMessageForInFlightRequestsAsync. In dotnet driver, sending requests and reading responses is carried out in different threads without synchronization. If an error occurs, it is processed by the reading thread (Connection.NotifyAboutConnectionFailure method), so there is a race condition between the two threads to read/update the connection.NrRequestsInFlight property (based on _callbackByRequestId field).
> Fix dotnet tests for Windows GHA

- CHANGELOG.asciidoc
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
An issue occurs when the GremlinGroovyScriptEngine is called from multiple threads to evaluate bytecode that contains lambdas. The default translator is not thread-safe which results in queries being interlaced with one another. This is fixed by creating a new instance of the translator per translation so that the translation process isn't interfered with. This primarily affects the UnifiedChannelizer because it currently uses the same instance of the translator from multiple threads.
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2765
> TINKERPOP-2765 Fix concurrency issue during script translation in the GremlinGroovyScriptEngine.

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Context.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractSession.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/MultiTaskSession.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SingleTaskSession.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
Add handling for situations where a task that is supposed to respond to the client is cancelled before it runs because it times out.
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2769
> TINKERPOP-2769: Add server response for tasks that never run because of timeout.

- gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js
Temporary fix for the [TINKERPOP-2779](https://issues.apache.org/jira/browse/TINKERPOP-2779). 
Slowdown appears to be coming from the Gremlin Server that is spun up to run the Cucumber tests. On logging some information from the server, I was able to verify that the server receives and processes the Connected Component Traversal ([Link to log line](https://github.com/L0Lmaker/tinkerpop/runs/7755756716?check_suite_focus=true#step:4:11942)).
Breakdown of what happens in the order it happens:
1. Client sends traversal to the server from Cucumber Step (Note: Cucumber Steps currently have a default timeout of 5s).
2. Server receives the request and starts processing the traversal.
3. Slowdown on the Server causes traversal to be processed much longer than usual.
4. 5s threshold on Cucumber …
> TINKERPOP-2779: Setting Cucumber timeout to 10s for Floating Errors on Windows on GitHub Actions

- gremlin-go/driver/connection_test.go
- gremlin-go/driver/result.go
- gremlin-go/driver/resultSet.go
The `Result` struct does not allow for any assigning of data, which makes it impossible to mock out for testing. While the `ResultSet` interface and its methods can be mocked out, they must match the original function signature, and return the `Result` type. Since you cannot assign to the unexported `Result` type, it is not possible to mock out returning data from the various methods of `ResultSet`.
> Export Data field

- .travis.install-maven.sh
Requested by @spmallette [here](https://github.com/apache/tinkerpop/pull/1792).   
Updates the source from which maven is installed, required as original CDN no longer hosts the relevant binary.
- CDN Link that no longer works: https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/
- Archive CDN Link: https://archive.apache.org/dist/maven/maven-3/3.8.5/binaries/
> Updated Maven Download url. Now points to Archive domain

- .github/workflows/build-test.yml
- .gitignore
- CHANGELOG.asciidoc
- docker/gremlin-test-server/Dockerfile
- docker/gremlin-test-server/krb5.conf
- docs/src/dev/developer/development-environment.asciidoc
- gremlin-console/pom.xml
- gremlin-console/src/test/python/docker/Dockerfile
- gremlin-go/driver/README.md
- gremlin-go/pom.xml
- gremlin-javascript/pom.xml
- gremlin-python/docker-compose.yml
- gremlin-python/pom.xml
- gremlin-python/src/main/python/radish/terrain.py
- gremlin-python/src/main/python/setup.cfg
- gremlin-python/src/main/python/setup.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_client.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection_threaded.py
- gremlin-python/src/main/python/tests/process/test_traversal.py
- pom.xml
Dockerized `gremlin-python` build and testing. Building, testing, and packaging of the python GLV are now executed inside of Docker, and python installation is no longer a system requirement. Outputs and distribution packages and are placed in the `target/` folder as before. Deployment of python still requires local Python installations. 
Dockerized `gremlin-console` python-based integration tests. Python 3.8 is used for the image because the version of pytest used isn't compatible with later versions of Python. Building our own Docker image also allows for greater control over the version of Python and Java used.
The location of the python test output was changed in order to fit better with the bind mounted volume for Docker.
Minor documentation updates included. We will be looking at …
> Dev Environments: Dockerize Testing for Python and Gremlin Console (Python-based tests only)

- docker/build.sh
- docker/scripts/build.sh
- docs/src/dev/developer/development-environment.asciidoc
- gremlin-go/run.sh
NOTE: This PR depends on PR#1797 and needs to be rebased once those changes are merged.
Only changes starting [here](https://github.com/apache/tinkerpop/pull/1800/commits/3664b9db8971e7a917c859608c889dcc646fca0e) are relevant
The non-Java GLVs have changed to use docker-compose for integration
testing which creates a Docker in Docker issue when run through the
build.sh script. To prevent this issue, the GLVs are split away and run
individually using their docker-compose files.
To increase the usability of the script for developers who only work on
a portion of TinkerPop, options were added to include only a subset of
the modules to the build.
> Dev Environments: Update docker/build.sh to work with docker-compose changes.

- CHANGELOG.asciidoc
- pom.xml
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2796
> TINKERPOP-2796: Bump snakeyaml to 1.32 due to security vulnerability

- gremlin-console/src/test/python/docker/Dockerfile
- gremlin-python/docker-compose.yml
Docker containers run and create files with root permission by default. Adding `chown` to change permission of Docker created files to current user, so `sudo` isn't needed for maven operations.
> Fix permission issues with Docker generated files

- docs/src/dev/developer/development-environment.asciidoc
- gremlin-console/Dockerfile
- gremlin-console/pom.xml
- gremlin-server/Dockerfile
https://issues.apache.org/jira/browse/TINKERPOP-2808
Compatibility fixes for ARM based Macs
Updated base images for gremlin-server and gremlin-console docker images to support arm64:
The previously used adopt openjdk11 alpine linux image does not support arm64. In fact none of the major openjdk distributions maintain a jdk11 alpine image for arm64. Changed base image to alpine and installed oracle openjdk 11. Oracle openjdk 11 was chosen as it is already maintained in the APK community repository.
Added jansi as an explicit dependency of gremlin-console. Previously it was a dependency of jline which itself is a dependency of groovy. The console is able to run just fine on x64 architectures but it cannot run on arm JDK's without importing Jansi directly. This change resolves …
> TINKERPOP-2808 Improving ARM Compatibility

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-dotnet/src/Gremlin.Net.Template/Gremlin.Net.Template.csproj
- gremlin-dotnet/src/Gremlin.Net.Template/Program.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/Log.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/Remote/DriverRemoteConnection.cs
- gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Bytecode.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Instruction.cs
- gremlin-dotnet/src/pom.xml
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Docs/Reference/GremlinVariantsTests.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/DriverRemoteConnectionTests.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientTests.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/MockedLoggerExtensions.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/ConnectionPoolTests.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/BytecodeTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2471
It's a bit unfortunate that I had to add loggers to the constructors of `GremlinClient` as well as `DriverRemoteConnection`, but I don't see a way around that as both are ways to initialize the driver.
VOTE +1
------
edit: Some additional short information about the implementation:
We are using [compile-time logging source generation](https://learn.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator) for logging as it provides a highly performant logging implementation.
> TINKERPOP-2471 Add logging to .NET

- gremlin-python/src/main/python/setup.py
Requirement had been >=3.8.0,<=3.8.1 in order to avoid a bug in versions <=3.7.4, but in the meantime, newer versions have been released.
> TINKERPOP-2810 allow newer aiohttp versions

- CHANGELOG.asciidoc
- docs/src/dev/provider/index.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/UserAgent.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SettingsTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/TestWSGremlinInitializer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Context.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WsUserAgentHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/MetricManager.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/TestChannelizer.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/UnifiedTestChannelizer.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketTestChannelizer.java
Progress towards [TINKERPOP-2480](https://issues.apache.org/jira/browse/TINKERPOP-2480)
Adds a user agent to gremlin-driver which is sent during the web socket handshake.
User agent follows the form of [Application Name] [GLV Name].[Version] [Language Runtime Version] [OS].[Version] [CPU Architecture]
This behaviour is enabled by default but can be disabled by setting the enableWsHandshakeUserAgent configuration to false.
> TINKERPOP-2480 Add User-Agent request header to Java Driver and Server

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPoolSettings.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketConnection.cs
- gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketSettings.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Utils.cs
Progress towards [TINKERPOP-2480](https://issues.apache.org/jira/browse/TINKERPOP-2480)
Adds a user agent to gremlin-dotnet which is sent as a request header during the web socket handshake.
User agent follows the form of [Application Name] [GLV Name].[Version] [Language Runtime Version] [OS].[Version] [CPU Architecture]
This behavior is enabled by default but can be disabled by setting the ConnectionPoolSettings.EnableUserAgentOnConnect configuration to false.
Note: There are no tests included as part of this PR. My intention is to add integration tests to ensure that the user agent is being sent correctly once [TINKERPOP-2819](https://issues.apache.org/jira/browse/TINKERPOP-2819) has been merged. The existing dotnet glv tests are sufficient to show that this change does not introduce …
> TINKERPOP-2480 Add User-Agent to Dotnet Driver

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/connection.py
- gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/python/gremlin_python/driver/useragent.py
Progress towards [TINKERPOP-2480](https://issues.apache.org/jira/browse/TINKERPOP-2480)
Adds a user agent to gremlin-python which is sent as a request header during the web socket handshake.
User agent follows the form of [Application Name] [GLV Name].[Version] [Language Runtime Version] [OS].[Version] [CPU Architecture]
This behavior is enabled by default but can be disabled by setting the enable_user_agent_on_connect configuration to false.
Note: There are no tests included as part of this PR. My intention is to add integration tests to ensure that the user agent is being sent correctly once [TINKERPOP-2819](https://issues.apache.org/jira/browse/TINKERPOP-2819) has been merged. The existing python glv tests are sufficient to show that this change does not introduce any faults into the …
> TINKERPOP-2480 Add User-Agent to Python Driver

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/TestSupport.java
This patch gives ~50X acceleration to load all the test data specified in AbstractFileGraphProvider.java. Before this optimization, it takes 15s to finish. After applying this patch, it takes ~216ms.
> TINKERPOP-2833 Read/Write optimization in TestSupport

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/NoOpWebSocketServerHandler.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/TestHttpServerInitializer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/TestWSNoOpInitializer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
Resolves https://issues.apache.org/jira/browse/TINKERPOP-2814
Note: The default timeouts were increased because they may be too low and can contribute to connection exceptions. This increase can be removed if it is deemed that the defaults shouldn't be changed in 3.5-dev.
> TINKERPOP-2814 Add configuration for SSL handshake timeout.

- spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java
- spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkCloneVertexProgramInterceptor.java
- spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkCloneVertexProgramInterceptorTest.java
The current CloneVertexProgram does nothing in its execute method, and the SparkGraphComputer needs to run general VertexProgram which requires a shuffle stage, which can be removed. Here a shortcut is implemented. When I exported two big graph, the overall exporting time was improved a lot. See the following table. 
```
-----------------------------
|Graph 1 |Graph 2
-----------------------------
Before fix |3.6h    |22min
-----------------------------
After fix  |2.4h    |16min
```
Graph 1 has 15 billion vertice and 23 billion edges. Graph 2 has 130 million vertices and 650 million edges.
> TINKERPOP-2834 Optimize CloneVertexProgram through SparkGraphComputer

- .github/workflows/build-test.yml
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
Adds a new job to github actions which will run the integration tests for the java driver.
The effect of this new GHA job is demonstrated by https://github.com/apache/tinkerpop/pull/1890
> [TINKERPOP-2836] Fix Java Driver Integration Tests Not Running in GHA

- .github/workflows/build-test.yml
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
This resolves an issue where previously java integration tests were not being run. See [TINKERPOP-2836].
> [TINKERPOP-2836] Fix Java Driver Integration Tests Not Running in GHA For 3.6

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionFactory.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Host.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/exception/NoHostAvailableException.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ClientTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/ClientConnectionIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2813
Summarized the major points of the change in the Upgrade Docs. Might be best to start there if reviewing this. Made some other adjustments to log better data for debugging purposes with the `ConnectionPool`.  Ended up making a number of adjustments to the thread pools to which various jobs were being submitted. Untangling that led to the addition of two pools which helped bring back parallel host initialization and got rid of random usage of the fork/join pool. I sense that something could be done to eliminate some of these pools but I believe it will come at the cost of a much larger refactoring effort to untangle how some of these jobs get scheduled up. I dunno.....not super pleased with it but gotta go pencils down at some point. …
> TINKERPOP-2813 Make gremlin-driver more optimistic about host availability

- CHANGELOG.asciidoc
- gremlin-go/driver/request.go
- gremlin-go/driver/request_test.go
- gremlin-python/src/main/python/gremlin_python/driver/connection.py
I believe this fix is small enough for review to be done in CTR fashion. If any commiter agrees with this I would like to merge this in without a lengthy initial review.
Fixes a bug where python and go glv's were not using the correct request_id when overriden. This is detailed in TINKERPOP-2841 and TINKERPOP-2844. This commit is not sufficient to close those tickets as further investigation is needed to ensure the other per-request settings work as intended, this commit provides an immediate fix to the broken request_id functionality.
Also fixes a typo in the python reference docs.
> Fix RequestId Override

- gremlin-dotnet/docker-compose.yml
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/ConfigProvider.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientBehaviorIntegrationTests.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Util/SocketServerSettings.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/appsettings.json
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
- gremlin-go/docker-compose.yml
- gremlin-go/driver/client_test.go
- gremlin-go/go.sum
- gremlin-javascript/src/main/javascript/gremlin-javascript/docker-compose.yml
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/helper.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/client-behavior-tests.js
- gremlin-python/docker-compose.yml
- gremlin-python/src/main/python/setup.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_web_socket_client_behavior.py
- gremlin-tools/gremlin-socket-server/conf/test-ws-gremlin.yaml
- gremlin-tools/gremlin-socket-server/src/main/java/org/apache/tinkerpop/gremlin/socket/server/TestWSGremlinInitializer.java
[TINKERPOP-2819](https://issues.apache.org/jira/browse/TINKERPOP-2819)
Modifies the GLV's docker compose files to additionally run gremlin-socket-server during integration testing.
Configures each of the GLVs to import the default config yaml for gremlin socket server.
Adds at least one reference test in each GLV which demonstrates it's use.
Also modifies gremlin-socket-server slightly to allow for any of graphSON2, graphSON3, or graphBinaryV1 to be used. Previously gremlin socket server only used graphSON2.
It's worth noting that the tests implemented here are quite basic as this PR was mostly focused on setting up the configuration to enable the tests. Even so several bugs were discovered when creating these tests. More tests which emulate network errors or connection issues would be a …
> [TINKERPOP-2819] Adds gremlin socket server tests in GLVs

- CHANGELOG.asciidoc
- gremlin-go/driver/graphTraversalSource.go
- gremlin-go/driver/graphTraversalSource_test.go
Fix for incorrect implementation for `GraphTraversalSource.With` in gremlin-go
https://issues.apache.org/jira/browse/TINKERPOP-2849
> [TINKERPOP-2849] fix for GraphTraversalSource.With

- gremlin-go/LICENSE
- gremlin-go/NOTICE
Just a quick update to license files. Adding LICENSE and NOTICE to gremlin-go as per recent discussion in the dev list. Also a minor fix to filepaths referenced in the root LICENSE file.
> Add LICENSE and NOTICE files for gremlin-go

- CHANGELOG.asciidoc
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinScriptChecker.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinScriptCheckerTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2842
Pretty straightforward - just added another thing to parse with the `GremlinScriptChecker`. Did some basic tests to make sure there was no real performance change as a result of this. cc/ @rdtr
VOTE +1
> TINKERPOP-2842 Parsed requestId in GremlinScriptChecker

- docs/src/dev/provider/gremlin-semantics.asciidoc
- docs/src/reference/the-traversal.asciidoc
Adds a section in the gremlin-semantics docs for the dedup step.
Main purpose of this is to highlight some extra considerations with dedup implementation which are somewhat beyond the scope of the reference docs.
> Adds additional docs for dedup step

- CHANGELOG.asciidoc
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2847.
Storing and comparing the request IDs in lower case prevents issues that arise when the supplied ID and returned ID are using different cases to represent the hex values of the UUID.
> TINKERPOP-2847 Compare and store request UUIDs as lower case strings in gremlin-javascript.

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/Gremlin.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/UserAgent.java
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/utils.js
It was observed in the java driver that the UserAgent class could fail to load if the manifest file was excluded from the jar. This is because the user agent relies on the manifest to extract the current version of gremlin. This PR adds a bit of extra error handling and will insert a value of "NotAvailable" in case of any failures. A similar issue was also present in JS which is also fixed here.
This PR also updates Gremlin.version() to return "VersionNotFound" if the manifest read fails as this is preferable to the current behavior of throwing a ExceptionInInitializerError.
Thanks @kenhuuu for discovering this issue.
> Improved user agent handling of cases where gremlin version is not available

- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientBehaviorIntegrationTests.cs
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Util/SocketServerSettings.cs
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/client-behavior-tests.js
- gremlin-python/src/main/python/tests/driver/test_web_socket_client_behavior.py
- gremlin-tools/gremlin-socket-server/conf/test-ws-gremlin.yaml
- gremlin-tools/gremlin-socket-server/src/main/java/org/apache/tinkerpop/gremlin/socket/server/SocketServerSettings.java
- gremlin-tools/gremlin-socket-server/src/main/java/org/apache/tinkerpop/gremlin/socket/server/TestWSGremlinInitializer.java
https://issues.apache.org/jira/browse/TINKERPOP-2844
Creates a test where a driver sends a request to gremlin-socket-server with all per-request settings set. gremlin-socket-server extracts these arguments and returns them in a string to the driver.
I expanded the scope of the ticket a bit and added this test to Java, .net, and JS in addition to Python. Go is excluded from this commit as the test is failing and needs additional work. The go per request settings issue is being tracked by [TINKERPOP-2841](https://issues.apache.org/jira/browse/TINKERPOP-2841)
> [TINKERPOP-2844] Adds tests for per-request-settings in GLV's

- .github/workflows/codeql.yml
- gremlin-go/driver/result.go
Adds new workflow which runs CodeQL vulnerability scanning on any pushes or pull requests to master, 3.5-dev, or 3.6-dev.
Also includes a small fix in go to prevent a possible lossy type conversion.
CodeQL will result in a failing check if a push or PR introduces a new vulnerability. It will not fail the checks for vulnerabilities which were pre-existing in the branch. Existing vulnerabilities are tracked and listed in Github under Security -> Vulnerability and Alerts -> Code scanning (Only visible to committers)
There are 3 vulnerabilities which have been found in the initial scan. I would ask that a committer dismiss the go warning as a "false positive". The warning is due to a potentially unsafe type conversion from a uint64 to a uint. During it's initialization, the size of the uint64 …
> Adds CodeQL vulnerability scanning to Github Actions

- gremlin-javascript/src/main/javascript/gremlin-javascript/.eslintrc.js
Unlocks language features such as `.?` and `??` which have been available since node v14 but have been blocked by eslint. According to https://node.green/#ES2021, node v16.13 (which is the current version in tinkerpop 3.6.x) fully supports ecma 2021.
> Bumped eslint to ecmaVersion 2021

- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/TypeSerializerRegistry.cs
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphBinary/Types/Sample/SamplePersonSerializerTests.cs
Fixes: https://issues.apache.org/jira/browse/TINKERPOP-2853
When reading a non-registered custom type with GraphBinary, a generic exception is thrown:
System.Collections.Generic.KeyNotFoundException: The given key 'janusgraph.RelationIdentifier' was not 
present in the dictionary. 
Now the following exception gets thrown instead:
System.InvalidOperationException: No serializer found for type 'janusgraph.RelationIdentifier'
This is the same exception and message that gets throw when _writing_ a non-registered custom type. 
The change has been verified by writing two new tests:
- One to document the added _read_ behaviour
- One to document the existing _write_ behaviour (which was undocumented)
And running the `Gremlin.Net` test suite
> TINKERPOP-2853: Throw explaining exception when reading unsupported GraphBinary type

- hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/graphson/GraphSONRecordReader.java
- hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/RecordReaderWriterTest.java
- hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/graphson/GraphSONV3d0RecordReaderFilterTest.java
- hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/gryo/GryoRecordReaderFilterTest.java
The GraphSONRecordReader does not provide the GraphFilter to filter vetex during deserialization. This PR fixed it. In addition, two UTs for vertex filtering of both GraphSONRecordReader and GryoRecordReader were added.
> TINKERPOP-2857 add GraphFilter support for GraphSONRecordReader

- bin/validate-distribution.sh
It came to my attention that the Go GLV was missing from validate-distribution.sh. Pushing a quick update here to fix that.
I've also added a bit of configuration to make the mac user experience a little smoother. If this is not desirable I will remove it and only add the Go fix.
> Added Go GLV verification to validate-distribution.sh

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractSession.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
https://issues.apache.org/jira/browse/TINKERPOP-2767
The existing error handling in TraversalOpProcessor and SessionOpProcessor during bytecode iteration was catching all exceptions sending an appropriate error response to the client. The OpProcessor however was not catching a StackOverflowError which could be induced by running a query which contains a large repeat step. This Error was being caught by FutureTask.run() but GremlinServer never wait's on this task or checks the results which caused this Error to be lost. A similar issue was found to exist in AbstractSession.process().
This PR adjusts the existing error handling code to catch any Throwable during bytecode iteration so clients will receive error messages and codes for server errors as well as exceptions. Any errors are …
> [TINKERPOP-2767] Fix server not handling StackOverflowError in bytecode traversals

- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractSession.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
Cherry picking previously approved changed to 3.6-dev to resolve conflicts.
Fixes TINKERPOP-2767.
The existing error handling in TraversalOpProcessor and SessionOpProcessor during bytecode iteration was catching all exceptions sending an appropriate error response to the client. The OpProcessor however was not catching a StackOverflowError which could be induced by running a query which contains a large repeat step. This Error was being caught by FutureTask.run() but GremlinServer never wait's on this task or checks the results which caused this Error to be lost. A similar issue was found to exist in AbstractSession.process().
This commit adjusts the existing error handling code to catch any Throwable during bytecode iteration so clients will receive error messages and codes for server …
> [TINKERPOP-2767] Fix server not handling StackOverflowError in bytecode traversals [For 3.6]

- CHANGELOG.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/GremlinGroovysh.groovy
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/PluggedIn.groovy
Adding imports by providing the CompilerConfiguration with an ImportCustomizer greatly improves performance because the imports won't be resolved again for each complete line in a script.
> TINKERPOP-2526 Add imports to the Console via an ImportCustomizer.

- CHANGELOG.asciidoc
- gremlin-go/driver/authInfo.go
- gremlin-go/driver/client.go
- gremlin-go/driver/client_test.go
- gremlin-go/driver/connection.go
- gremlin-go/driver/connection_test.go
- gremlin-go/driver/driverRemoteConnection.go
- gremlin-go/driver/driverRemoteConnection_test.go
- gremlin-go/driver/gorillaTransporter.go
- gremlin-go/driver/protocol.go
- gremlin-go/driver/protocol_test.go
- gremlin-go/driver/strategies_test.go
- gremlin-go/driver/transporter.go
This creates an `AuthInfoProvider` interface with the methods necessary to read credential/header information, changes the `AuthInfo` signature slightly to satisfy that interface, and updates call sites so that each call site calls the necessary interface method to re-read the credentials.
The interface looks like:
```go
type AuthInfoProvider interface {
GetHeader() http.Header
GetBasicAuth() (ok bool, username, password string)
}
```
It also adds a new `NewDynamicAuth(f func() AuthInfoProvider)` helper function that creates a generator based `AuthInfoProvider`, so that each time `GetHeader()` or `GetBasicAuth()` methods are called the given function is called to get a brand new `AuthInfoProvider` (which itself can be `AuthInfo` or something else) and the results are relayed to the …
> TINKERPOP-2747 Separate AuthInfo struct vs AuthInfoProvider interface for dynamic credentials

- gremlin-dotnet/src/Gremlin.Net/Process/Utils.cs
I can only assume the first call to GetExecutingAssembly should have been GetEntryAssembly, whereas for the driverVersion, GetExecutingAssembly should be used (for reasons described in the ticket).
> Attempt to fix TINKERPOP-2918.

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/FilterRankingStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelperTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2919
Shortcut some of the recursion in the strategy with a cache that basically captures `TraversalParent` information formerly calculated and recalculated. Reduced execution time of the sample traversal I had from about 1 minute 48 seconds to just a few milliseconds.
VOTE +1
> TINKERPOP-2919 Improve performance of FilterRankingStrategy

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/CountStrategy.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/CountStrategyTest.java
Fixed optimization of `count` step inside `CountStrategy`.
queries like
` g.V().where(__.in().count().is(eq(-3)))` and  `g.V().where(__.in().count().is(eq(-2)))` are now correctly optimized as `g.V().where(__.in().limit(0).count().is(eq(-2)))`
https://issues.apache.org/jira/browse/TINKERPOP-2891
> [TINKERPOP-2891] Improved handling for negative values in CountStrategy

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/B_LP_O_P_S_SE_SL_Traverser.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/B_LP_O_S_SE_SL_Traverser.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/LP_O_OB_P_S_SE_SL_Traverser.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/LP_O_OB_S_SE_SL_Traverser.java
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2899
In some instances, a graph may contain elements whose Ids are sequentially increasing integers. Because the hashCode for Path implementations are calculated based on these same Ids, you run into a situation where both parts of the hashCode calculation are related by some constant. H(A)-H(B)=C where C is a constant. In this case, XOR is a bad candidate for creating the final hashCode because XOR will reduce to some small pool of potential output. This occurs because the most significant bits will be the same for H(A) and H(B) which will cause them to become 0 when XOR'd. This commit changes the algorithm to be a more standard algorithm for this case which is m * H(A) + H(B).
Some quick performance numbers using Kelvin's air-routes …
> TINKERPOP-2899 Changed hashCode implementation for LP/P traversers.

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/traversal/AbstractRemoteTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/AbstractLambdaTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/EmptyTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphComputerTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2855
https://issues.apache.org/jira/browse/TINKERPOP-2888
Removed some recursion. Added `Traversal.lock()` to offer a formal way to finalize a traversal. Offers a significant performance improvement. Removed expectation that Graph and related metadata for a `Traversal` is available in child traversals.
On TINKERPOP-2855 the script demonstrating the slowdown was running at 9.1 seconds on my system for 3.5.5. With this change it is executing at 1.7 seconds. 
VOTE +1
> TINKERPOP-2855 Refactored strategy application

- .github/workflows/codeql.yml
I think many of us have observed many random CI failures stemming from Java CodeQL. In my observations these failures have always been during the autobuild phase (typically when trying to load the antlr runtime as part of gremlin-language). This PR switches Java codeQL to use a manual build instruction instead and restricts it to only building gremlin-core, gremlin-groovy, gremlin-driver, gremlin-server, and tinkergraph-gremlin.
I believe this will resolve the unreliable build failures while retaining the existing vulnerability scanning.
> Improve Java CodeQl Reliability

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/CoalesceStep.java
_This PR implements part of https://github.com/apache/tinkerpop/pull/2027 . Close this PR without merging in case https://github.com/apache/tinkerpop/pull/2027 is merged._
This PR will make possible to extend `CoalesceStep` which is needed for https://github.com/JanusGraph/janusgraph/issues/2996 . This will help creating a replacement step for original CoalesceStep with optimizations in place.
Related issue: https://issues.apache.org/jira/browse/TINKERPOP-2927
> Make CoalesceStep extensible

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProjectStep.java
_This PR implements part of https://github.com/apache/tinkerpop/pull/2027 . Close this PR without merging in case https://github.com/apache/tinkerpop/pull/2027 is merged._
The intention of this PR is to provide getter methods to ProjectStep along with a constructor which accepts TraversalRing which is needed for https://github.com/JanusGraph/janusgraph/issues/3559 . This will help creating a replacement step for original ProjectStep with optimizations in place.
Related issue: https://issues.apache.org/jira/browse/TINKERPOP-2927
> Make ProjectStep extensible

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PropertyMapStep.java
_This PR implements part of #2027 . Close this PR without merging in case #2027 is merged._
The intention of this PR is to provide getter methods to `PropertyMapStep` along with a constructor which accepts `TraversalRing` which is needed for https://github.com/JanusGraph/janusgraph/issues/2444 . This will help creating a replacement step for original PropertyMapStep with optimizations in place. 
Related issue: https://issues.apache.org/jira/browse/TINKERPOP-2927
> Add PropertyMapStep getters and a constructor with TraversalRing

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/CountStrategy.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/CountStrategyTest.java
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2893
Predicates that contain negative numbers aren't handled correctly by the current CountStrategy implementation. In particular, the use of the highRange to determine when to use not() or to remove the count().is() doesn't account for these cases. This leads to the optimization being applied when it shouldn't be. This commit temporarily solves this by disabling the optimization in these cases. Further work could be done to selectively apply the optimization as there are some cases even with predicates that contain negative numbers where it could be applied.
> TINKERPOP-2893 Remove CountStrategy optimizations for predicates with negative numbers

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/traversal-test.js
- gremlin-python/src/main/python/gremlin_python/process/traversal.py
- gremlin-python/src/main/python/radish/feature_steps.py
- gremlin-python/src/main/python/tests/process/test_traversal.py
- gremlin-python/src/main/python/tests/structure/io/test_graphbinaryV1.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV2d0.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV3d0.py
https://issues.apache.org/jira/browse/TINKERPOP-2925
Issue in gremlin-javascript arose due to Direction aliases `from_` and `to` not properly returning `Direction.OUT` and `Direction.IN`.
Also found similar issue in gremlin-python, where `Direction.from_` and `Direction.to` were not added to the `Direction` enum. They can now be used directly without the need to declare `from_ = Direction.OUT` and `to = Direction.IN`.
The existing Gherkin test as `g_mergeEXlabel_knows_out_marko_in_vadasX_aliased_direction` covers the case, although customized alias maps in feature-steps masked the issue in python and javascript, which are now removed.
This issue doesn't seem to appear in gremlin-go and gremlin-dotnet.
> TINKERPOP-2925 mergeE() in javascript producing an error

- CHANGELOG.asciidoc
- docs/src/dev/developer/development-environment.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-console/pom.xml
- gremlin-server/pom.xml
- pom.xml
Replaces spotify plugin with io.fabric8 docker-maven-plugin. The new plugin has the benefit of supporting multi-arch images through buildx for deployments and it is an actively maintained plugin as opposed to the spotify plugin.
The new plugin continues to fetch auth credentials from the same location so no changes to the release environment will be necessary.
I have tested the full set of .Net gherkin and integration tests against the new server image with no issues. I have also used [container-diff](https://github.com/GoogleContainerTools/container-diff) to compare the new image to the one that we currently build using the mvn exec plugin and docker compose. These are the results:
```
-----File-----
These entries have been added to colegreer/tinkerpop:server-3.5.6-SNAPSHOT: None
These …
```
> TINKERPOP-2852 Deploying multi-arch docker images

- CHANGELOG.asciidoc
- docs/src/dev/developer/development-environment.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-console/pom.xml
- gremlin-server/pom.xml
- pom.xml
Cherry picking from https://github.com/apache/tinkerpop/pull/2007 for 3.6. Only notable difference is the latest tag is added back for this branch.
>   TINKERPOP-2852 Deploying multi-arch docker images for 3.6

- hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/ObjectWritable.java
- hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/ObjectWritableTest.java
Reduce the toString() of ObjectWritable to avoid OOM for running OLAP queries on Spark.
> [TINKERPOP-2934] Shrink the content of ObjectWritable.toString()

- CHANGELOG.asciidoc
- docs/src/dev/provider/gremlin-semantics.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/FilterStep.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessLimitedStandardSuite.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/TernaryBooleanLogicsTest.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/step/sideEffect/TinkerGraphStep.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/step/sideEffect/TinkerGraphStepTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2901
One of the optimizations done by TinkerGraphStepStrategy is push down `has()` steps into HasContainer's within TinkerGraphStep. When this occurs, the normal binary reduction of ternary boolean states gets skipped. This PR addresses this by replicating the binary reduction logic within TinkerGraphStep when the filtering is performed.
This PR addresses cases where `GremlinTypeErrorException` is able to leak to the user.
Fixes 2 cases:
1: If has step gets merged into a TinkerGraphStep by TinkerGraphStepStrategy, the evaluation
of the has containers will still be guarded by the same ternary boolean binary reduction logic
as in FilterStep class.
2: If the parent step is not a FilterStep and thus is not equipped to handle a …
> [TINKERPOP-2901] Incorrect result caused by has(key, predicate)

- CHANGELOG.asciidoc
- gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
https://issues.apache.org/jira/browse/TINKERPOP-2944
This should fix the memory leak described in TINKERPOP-2944 caused by not cleaning up the cancellation token registrations which contain a reference to the `RequestMessage`.
VOTE +1
> TINKERPOP-2944 Dispose Cancellation callbacks to fix memory leak

- gremlin-console/pom.xml
- gremlin-console/src/main/static/LICENSE
- gremlin-console/src/main/static/NOTICE
- gremlin-console/src/main/static/licenses/antlr4
- gremlin-driver/pom.xml
- gremlin-driver/src/main/static/NOTICE
- gremlin-driver/src/main/static/licenses/antlr4
- gremlin-server/src/main/static/LICENSE
- gremlin-server/src/main/static/NOTICE
- gremlin-server/src/main/static/licenses/antlr4
- gremlin-shaded/pom.xml
- gremlin-shaded/src/main/static/LICENSE
- gremlin-shaded/src/main/static/NOTICE
- gremlin-shaded/src/main/static/licenses/kryo
- gremlin-shaded/src/main/static/licenses/minilog
Fixing some issues found during the release of 3.5.6/3.6.4.
Additionally adding static NOTICE and licenses files for gremlin-shaded for inclusion in the shaded jar. Also updates notices for console and server as their distributions include gremlin-shaded.
> 3.6: fixing licenses/NOTICE for console and server distributions

- CHANGELOG.asciidoc
- pom.xml
- spark-gremlin/pom.xml
This upgrade is necessary for TINKERPOP-2703 (Build on JDK17).
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2731
> TINKERPOP-2731 Bump Spark to 3.3.2.

- gremlin-console/pom.xml
- gremlin-console/src/main/static/NOTICE
- gremlin-console/src/main/static/licenses/antlr4
- gremlin-driver/pom.xml
- gremlin-driver/src/main/static/LICENSE
- gremlin-driver/src/main/static/NOTICE
- gremlin-driver/src/main/static/licenses/antlr4
- gremlin-server/src/main/static/LICENSE
- gremlin-server/src/main/static/NOTICE
- gremlin-server/src/main/static/licenses/antlr4
- gremlin-shaded/pom.xml
- gremlin-shaded/src/main/static/LICENSE
- gremlin-shaded/src/main/static/NOTICE
- gremlin-shaded/src/main/static/licenses/kryo
- gremlin-shaded/src/main/static/licenses/minilog
Fixing missing entries in console and server distributions which were found during the 3.5.6 release
Adding static NOTICE and licenses files for gremlin-shaded for inclusion in the shaded jar. Also updates notices for console and server as their distributions include gremlin-shaded.
Also fixing missing entries in the gremlin-driver shaded jar
> fixing licenses/NOTICE Master

- gremlin-console/pom.xml
- gremlin-console/src/main/static/NOTICE
- gremlin-console/src/main/static/licenses/antlr4
- gremlin-console/src/main/static/licenses/mockito-core
- gremlin-driver/pom.xml
- gremlin-driver/src/main/static/LICENSE
- gremlin-driver/src/main/static/NOTICE
- gremlin-driver/src/main/static/licenses/antlr4
- gremlin-server/src/main/static/LICENSE
- gremlin-server/src/main/static/NOTICE
- gremlin-server/src/main/static/licenses/antlr4
- gremlin-server/src/main/static/licenses/mockito-core
- gremlin-shaded/pom.xml
- gremlin-shaded/src/main/static/LICENSE
- gremlin-shaded/src/main/static/NOTICE
- gremlin-shaded/src/main/static/licenses/kryo
- gremlin-shaded/src/main/static/licenses/minilog
Fixing some issues found during the release of 3.5.6/3.6.4.
Noteworthy that mockito-core is being added to the licenses folder as it is currently included in the lib directory in the distributions for both console and server. I believe this inclusion is likely a mistake and should be investigated and removed at a later date. I have opted to leave it in and correct the licensing for now as I don't believe such a change should be made right before the 3.6.4 patch release gets made.
Additionally adding static NOTICE and licenses files for gremlin-shaded for inclusion in the shaded jar. Also updates notices for console and server as their distributions include gremlin-shaded.
> fixing licenses/NOTICE for console and server distributions

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/upgrade/release-3.6.x.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketGremlinRequestEncoder.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphBinaryMessageSerializerV1.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV1d0.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV2d0.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV3d0.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/MessageTextSerializer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/TestWSGremlinInitializer.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV1d0Test.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV2d0Test.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/binary/GraphBinaryMessageSerializerV1Test.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractSession.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/GremlinResponseFrameEncoder.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/TextPlainMessageSerializer.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/util/TextPlainMessageSerializerTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2947
```text
$ curl -H "Accept:text/plain" -X POST -d "{\"gremlin\":\"g.V()\"}" "http://localhost:8182"
==>v[1]
==>v[2]
==>v[3]
==>v[4]
==>v[5]
==>v[6]
```
VOTE +1
> TINKERPOP-2947 Added text/plain and text serialization for GraphBinary for HTTP

- CHANGELOG.asciidoc
- hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/Constants.java
- spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java
- spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkHadoopGraphProvider.java
- spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkCloneVertexProgramInterceptorTest.java
In production environment, it is dangerous to delete a folder which is not empty. In order to avoid any wrong operations, it is better ask user to delete it manually if it is not empty.
> [TINKERPOP-2941] Stop deleting the output location if it is not empty

- gremlin-python/src/main/python/README.rst
- gremlin-python/src/main/python/example.py
- gremlin-python/src/main/python/gremlin_python/process/graph_traversal.py
- gremlin-python/src/main/python/gremlin_python/process/traversal.py
`gremlin-python` internally calls deprecated methods. This PR fixes that.
> (fix) (gremlin-python) don't use deprecated methods

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/decoration/VertexProgramStrategy.java
- gremlin-server/pom.xml
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/AbstractFeatureTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/GraphBinaryRemoteComputerFeatureTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/GraphBinaryRemoteFeatureTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/GraphSONRemoteComputerFeatureTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/GraphSONRemoteFeatureTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/RemoteWorld.java
- gremlin-server/src/test/resources/META-INF/services/io.cucumber.core.backend.ObjectFactory
Runs the Feature tests with cucumber against a driver and server. These same tests are currently run in tinkergraph-gremlin but as an embedded graph. Running it in this configuration enables testing of proper serialization and proper creation of bytecode requests.
> Run feature tests against a driver/server configuration.

- .github/workflows/build-test.yml
- CHANGELOG.asciidoc
- docs/src/dev/developer/development-environment.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-go/README.md
- gremlin-go/docker-compose.yml
- gremlin-go/driver/README.md
- gremlin-go/example/go.mod
- gremlin-go/go.mod
Upgrading go as 1.17 is past end of life. Users have already been notified of this upcoming change here: https://tinkerpop.apache.org/docs/current/upgrade/#_deprecation_warning_for_node_10_and_go_1_17.
There are no breaking changes from this upgrade.
VOTE +1
> upgrade Go to 1.20

- gremlin-dotnet/src/pom.xml
- gremlin-dotnet/test/pom.xml
- gremlin-go/pom.xml
- gremlin-python/pom.xml
Creates new profiles in the glv poms which will simply echo out a warning message if a profile is skipped due to a missing .glv file.
> Adds Missing .glv file warnings to maven

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/tutorials/getting-started/index.asciidoc
- gremlin-console/src/main/bin/gremlin-java8.bat
The gremlin.bat file no longer works for users of Java 8 due to some changes in how pathing is determined in Groovy. This bat file finds all jars in lib and ext rather than using the * wildcard as that no longer works in Groovy. Because of the hard limit on the length of a variable for commands, relative paths had to be used instead of absolute paths. Although the use of relative paths for the -cp option is discouraged by Java, it is necessary in this case.
> Add gremlin-java8.bat for Java 8 Windows Console users.

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Context.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
I noticed extreme memory usage in recent versions of TinkerPop. After some investigation I found that this was because the task that is scheduled to cancel the query if it doesn't complete in time is not cancelled when the query completes.
This means that if the timeout is large and you have high throughput on the graph, memory starts adding up. On my laptop with Aerospike Graph, I was seeing ~1 GB per second growth in memory until it hit about 10 GB and then my system would slow down and eventually OOME.
I added a cancel for this in this PR to fix this issue and tested it and the memory growth does not happen. (I tested with changes on 3.6-dev but then brought those to 3.5-dev since the problem is rooted there).
> TINKERPOP-2958 Added cancel for query timeout task when query completes.

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/ValueTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PropertyMapStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/ProductiveByStrategy.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategyProcessTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2920
`ProductiveByStrategy` was interacting badly with `SubgraphStrategy` and altering a child traversal in `PropertyMapStep` that it probably shouldn't have been.
VOTE +1
> TINKERPOP-2920 Fixed bug in SubgraphStrategy when key not present

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV1d0.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/SerTokens.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/Serializers.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
Users/Providers who wish to use GraphSON-1.0 in text format should make serializer 
`GraphSONMessageSerializerV1d0` default serializer. Alternatively introduce new mimeType `application/vnd.gremlin-v1.0+json;sparse=true` to let users/providers use GraphSON-1.0 in text format without changing defaults.
> [TINKERPOP-2963] Introduce new mimeType to use Graphson-1.0 text serializer

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/LabelStep.java
In JanusGraph we would like to make some optimizations to `LabelStep` (https://github.com/JanusGraph/janusgraph/issues/3813).
We need to extend `LabelStep` with additional logic. Even so it's quite simple to implement our own `LabelStep`, it's a little bit dangerous because TinkerPop's `LabelStep` may be used in some optimization strategies (including user-provided optimization strategies). If we replace `LabelStep` with something which doesn't extend `LabelStep` then we may risk breaking some strategies.
For example, here are the places in TinkerPop where `step instanceof LabelStep` is checked:
1) https://github.com/apache/tinkerpop/blob/f00cfe5592ef45e64fb45737a16ec5877a824958/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/ByModulatorOptim …
> Remove final class declaration for LabelStep

- CHANGELOG.asciidoc
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/ImportGroovyCustomizer.java
- gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTest.java
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2953
The latest Groovy upgrade to 2.5.22 seems to have changed how enums are imported which led to the __ static methods which have the same name to not be found.
Thanks to bmsq on Discord who suggested this fix.
VOTE+1
> TINKERPOP-2953 Update how enums are imported in ImportGroovyCustomizer.

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONStreamConstraintsTest.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV1d0.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV2d0.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ClusterConfigTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV1d0Test.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV2d0Test.java
- gremlin-shaded/pom.xml
- pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2948
This PR is meant to supersede https://github.com/apache/tinkerpop/pull/2061.
This PR includes a version bump for jackson, a bump for the shade plugin (required due to jackson 2.15.0 being a multi-release jar containing some java 17 and java 20 classes), as well as additional configuration options for graphSON serializers.
Jackson 2.15.0 adds new StreamReadConstraints which set a max length for numbers, strings, and a max nesting depth. These have been configured to 10 000, 20 000 000, and 1000 by default in TinkerPop. New serializer configs for `maxNumberLength`, `maxStringLength`, and `maxNestingDepth` have been added to graphSON serializers to adjust these values if needed.
VOTE +1
> TINKERPOP-2948 bump jackson databind to 2.15.0

- CHANGELOG.asciidoc
- docs/src/dev/io/graphson.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/upgrade/release-3.7.x.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/BytecodeCommand.groovy
- gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/jsr223/gremlin-server-integration.yaml
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapper.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV3.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONXModuleV2.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONXModuleV3.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperPartialEmbeddedTypeTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
- gremlin-tools/gremlin-benchmark/src/main/java/org/apache/tinkerpop/gremlin/driver/GraphSONMapperBenchmark.java
- gremlin-tools/gremlin-io-test/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypedCompatibilityTest.java
- gremlin-tools/gremlin-io-test/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONUntypedCompatibilityTest.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/AbstractGraphSONMessageSerializerV2.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/GraphSONUntypedMessageSerializerV3.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/SerTokens.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/Serializers.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/GraphSONMessageSerializerV2Test.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/GraphSONMessageSerializerV3Test.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/GraphSONUntypedMessageSerializerV3Test.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphGraphSONSerializerV2Test.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/io/graphson/GraphSONTranslator.java
https://issues.apache.org/jira/browse/TINKERPOP-2967
Essentialy exposes untyped GraphSON 3.0 which is basically the untyped GraphSON 1.0. Had to refactor the GraphSONModule slightly to handle this by passing TypeInfo through it to the serializers which needed to know whether they were serializing that way or not.
VOTE +1
> TINKERPOP-2967 Added untyped GraphSON 3.0

- CHANGELOG.asciidoc
- docs/src/reference/implementations-neo4j.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/jsr223/Neo4jGremlinPlugin.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/traversal/LabelP.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/traversal/step/sideEffect/CypherStartStep.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/traversal/step/sideEffect/Neo4jGraphStep.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/traversal/strategy/optimization/Neo4jGraphStepStrategy.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/util/Neo4jCypherIterator.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jEdge.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jElement.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jGraph.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jGraphVariables.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jHelper.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jProperty.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jVertex.java
- neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jVertexProperty.java
Based on dev list discussion, a decision was made to deprecate neo4j-gremlin. It will remain in the repo for foreseeable future and we will continue to maintain compatibility when possible. If the effort to maintain neo4j-gremlin becomes unreasonable in the future, a decision to remove it may be made at that time.
See DISCUSS thread on the dev list for more details: (https://lists.apache.org/thread/lxn4s9fs8rzggm0jlnffnphfpqnpn3h8)
VOTE +1
> Add deprecation notice for Neo4j-Gremlin

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphComputer.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphFilter.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraph.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/TraversalStrategiesTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphComputerTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/ranking/pagerank/PageRankVertexProgramTest.java
- hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/process/computer/AbstractHadoopGraphComputer.java
- spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/structure/SparkTest.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/computer/TinkerGraphComputer.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/computer/TinkerGraphComputerView.java
GraphComputer has vertexFilter and edgeFilter, but not yet a filter for vertex properties. Many vertex programs don't need many if not all vertex properties. PageRank, for example, does not need any vertex properties at all. Having a vertex property filter can greatly reduce memory/disk usage.
> [TINKERPOP-2973] Enable vertex properties filtering for GraphComputer

- CHANGELOG.asciidoc
- docs/src/reference/implementations-tinkergraph.asciidoc
- gremlin-dotnet/docker-compose.yml
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTransactionTests.cs
- gremlin-go/docker-compose.yml
- gremlin-go/driver/traversal_test.go
- gremlin-go/pom.xml
- gremlin-javascript/src/main/javascript/gremlin-javascript/docker-compose.yml
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
- gremlin-python/docker-compose.yml
- gremlin-python/pom.xml
- gremlin-python/src/main/python/tests/process/test_traversal.py
As we are switching to TinkerTransactionGraph, we can run transaction tests by default and no longer need the environment flag `TEST_TRANSACTIONS` to run tests only when Neo4j plugin is installed. This flag and its usage is now removed from all GLVs.
> Remove TEST_TRANSACTIONS flag from GLVs

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MergeEdgeStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MergeVertexStep.java
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/test/features/map/MergeEdge.feature
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/test/features/map/MergeVertex.feature
Fixed MergeE/MergeV steps to always throw exception for invalid `onMatch` option.
Now exception is thrown only if the element is not present.
Jira https://issues.apache.org/jira/browse/TINKERPOP-2939
> TINKERPOP-2939 Fixed MergeE/MergeV steps to always throw exception for invalid `onMatch` option.

- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Optimization/CountStrategy.cs
This change has originally been done in f08d44fc5c8649658fd775289f0a49ec1816306d.
> Rename RangeByIsCountStrategy to CountStrategy in Gremlin.NET.

- CHANGELOG.asciidoc
- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/TypeSerializerRegistry.cs
- gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/GraphSONWriter.cs
https://issues.apache.org/jira/browse/TINKERPOP-2976
In rare cases users could get an `InvalidOperationException` if the dictionary of `_serializerByType` was modified while another thread in parallel iterated over the keys of this dictionary. Just creating a copy of the supported types and then iterating over that should fix this.
The problem was reported for GraphBinary, but the GraphSONWriter had the same problem so I also fixed it there.
VOTE +1
Since we are currently in code freeze, we can simply merge this after that has been lifted.
> TINKERPOP-2976 Fix modification while iterating

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraph.java
SparkGraphComputer uses StarGraph to represent an in-memory graph. EdgeFilter can be configured by users to drop unneeded edges, but the edge properties aren't dropped. This fixes this bug and greatly reduces memory footprint.
> TINKERPOP-2986: [StarGraph] Drop edge properties when dropping edges

- gremlin-go/driver/translator.go
- gremlin-go/driver/translator_test.go
This PR, add the capability to the gremlin-go driver to translate Bytecode into a string gremlin-groovy query. 
This addresses the following [ticket](https://issues.apache.org/jira/browse/TINKERPOP-2951)
> TINKERPOP-2951: Add translator to the Go GLV

- docs/src/reference/gremlin-variants.asciidoc
Fixes Direction in the Common Imports section at https://tinkerpop.apache.org/docs/current/reference/#gremlin-javascript-imports
> Fix JS Direction import

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslator.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslatorTest.java
- gremlin-python/docker-compose.yml
- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-python/src/main/python/gremlin_python/driver/serializer.py
- gremlin-python/src/main/python/gremlin_python/process/translator.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection_http.py
- gremlin-python/src/main/python/tests/process/test_translator.py
https://issues.apache.org/jira/browse/TINKERPOP-3006
Adding experimental feature for python to connect via HTTP. This is relying on the python translator, for which additional types were added. There shouldn't be any breaking changes.
Connecting to remote can be done via
`remote_conn = DriverRemoteConnection('http://localhost':8182/, 'g')`
and for traversals
`g = traversal().with_remote(remote_conn)`
One note, in addition to the integration test, I ran the feature test suite (radish tests) locally with the HTTP endpoint for 3.6 and all tests passed. One exception is that `g.inject(null, null)` test will fail due to combination of Groovy script issue that throws NPE with 2nd nulls and server HTTP handler hanging upon NPEs. 
VOTE +1
> [TINKERPOP-3006] Enable remote connection over HTTP for gremlin python

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ElementIdStrategy.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ElementIdStrategyProcessTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2811
Since HasContainer rolls up sequential has() steps checking the first item in the HasContainer only might not catch the id that needs to be replaced.
VOTE +1
> TINKERPOP-2811 Fixed bug with hasId() order for ElementIdStrategy

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/binary/types/EdgeSerializer.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/binary/types/VertexSerializer.java
Elements properties can have parent element not set, PR fix this
> Fixed deserialization of element properties for GraphBinary

- CHANGELOG.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/GremlinGroovysh.groovy
https://issues.apache.org/jira/browse/TINKERPOP-2999
Fixes issue where multiline commands would throw error on the first line, caused by upgrade to Groovy 4.  Handling pulled from Groovysh.groovy
> TINKERPOP-2999 3.7.0 Remote Console Sends Incomplete Queries

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/PathFilterStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/WherePredicateStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PathStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProjectStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/TreeStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/TreeSideEffectStep.java
Fixed bug in `replaceLocalChild` where child traversal was not correctly integrated.
https://issues.apache.org/jira/browse/TINKERPOP-2964
> [TINKERPOP-2964] Fixed bug in `replaceLocalChild`.

- CHANGELOG.asciidoc
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerElementContainer.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerTransaction.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerTransactionGraph.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerTransactionalIndex.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerTransactionGraphTest.java
Fix for issue when `TinkerTransactionGraph` used without transaction. A situation is possible when the value read before by another client in the same thread is returned.
Something like
Client1 in Thread1 read Vertex1, value cashed for consistent read.
Tx created for this request commit all changes, but for read operation it's nothing to do.
Client2 in Thread2 modify Vertex1 and commit changes.
Client3 got same Thread1 for his request, but cashed Vertex1 still used.
https://issues.apache.org/jira/browse/TINKERPOP-3016
> [TINKERPOP-3016] Fix for reading value from different read operation

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpGremlinRequestEncoder.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpGremlinResponseDecoder.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV3d0Test.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/binary/GraphBinaryMessageSerializerV1Test.java
- gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection_http.py
- gremlin-server/conf/gremlin-server-rest-modern.yaml
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpHandlerUtil.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/TextPlainMessageSerializer.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/HttpDriverIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/handler/HttpHandlerUtilTest.java
Added Gremlin bytecode support for HTTP requests for Java and Python GLV's without translation to Gremlin script.
Added serialization for entire RequestMessage.
Payload type distinguished by Content-Type header .
> Bytecode support for HTTP requests

- CHANGELOG.asciidoc
- docs/src/upgrade/release-4.x.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Operator.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/NumberHelper.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/util/NumberHelperTest.java
For some integer operations the result is not checked for overflow, which can lead to unexpected results.
For example
```
gremlin> __.inject(Long.MAX_VALUE,Long.MAX_VALUE,2).sum()
==>0
```
In this PR I added throwing `ArithmeticException` for overflow cases. 
More details in https://issues.apache.org/jira/browse/TINKERPOP-2877
> [TINKERPOP-2877] Added integer overflow checks

- gremlin-core/pom.xml
> [TINKERPOP-3014] Reorder the jcl-over-slf4j dependency to avoid the dependency conflict.

- docs/src/dev/provider/gremlin-semantics.asciidoc
- docs/src/reference/the-traversal.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AsStringGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AsStringLocalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ConjoinStep.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AsStringGlobalStepTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AsStringLocalStepTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ConjoinStepTest.java
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/test/features/map/AsString.feature
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/test/features/map/Conjoin.feature
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/test/features/map/ToUpper.feature
The handling of null values in some recently implemented Steps were inconsistent. This addresses that issue by making conjoin() behave like concat() and asString() like the other String functions.
> Update conjoin() and asString() null handling.

- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalTest.java
The random strings generated for method arguments can sometimes contain duplicate, which will fail the new requirement for project step to have unique keys only (introduced in https://github.com/apache/tinkerpop/pull/2217). 
This PR adds processing to remove duplicates after the string args are generated.
(Note this is not needed for the current release).
> Fix flaky traversal test due to duplicated key generated for project step

- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs
Handling of null values has been changed in #2351 for `asString()` and `conjoin()` to return `null` for `null` values instead of the string `"null"`.
Just to clarify: I don't consider this change important enough to stop the current release process. This can just be included in the next line of releases.
> Update nullability for AsString(), Conjoin() in Gremlin.Net

- CHANGELOG.asciidoc
- gremlin-console/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-3021
Enables multi-architecture AMD64/ARM64 docker images in gremlin-console deployment. This was previously disabled due to observed instabilities in the image. Previously the ARM image was plagued by severe latency and widespread freezing and crashing. These issues were stemming from the docker engine as the console has run natively on arm flawlessly for several releases now. With recent improvements to docker, I am unable to find any issues with the console images. The arm console container is now snappy, responsive, and stable in my testing.
VOTE +1
> [TINKERPOP-3021] Add ARM64 console docker images

- CHANGELOG.asciidoc
- gremlin-python/src/main/python/gremlin_python/structure/io/graphsonV2d0.py
- gremlin-python/src/main/python/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/python/tests/driver/test_client.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV2d0.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV3d0.py
Adds the `gx:Int16` graphson type to the gremin-python graphson serializers.
> Add missing int16 serialization type to graphson in gremlin-python

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpGremlinResponseDecoder.java
- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection_http.py
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpBasicAuthorizationHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpHandlerUtil.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/HttpDriverIntegrateTest.java
HTTP errors are returned as JSON without requestId. The requestId is required in order to form a ResponseMessage that can be properly deserialized by the Java driver.
Not release blocking.
> Add requestIds to server HTTP error response.

- gremlin-server/src/main/docker/docker-entrypoint.sh
JIRA: https://issues.apache.org/jira/browse/TINKERPOP-2950.  Handles SIGTERM when shutting down docker container by sending SIGINT to server processes.
> TINKERPOP-2950 Add docker shutdown handling to close containers gracefully

- CHANGELOG.asciidoc
- docs/src/reference/the-traversal.asciidoc
- docs/src/upgrade/release-3.7.x.asciidoc
Provides notice in release notes that none() will be renamed to discard() in https://github.com/apache/tinkerpop/pull/2377.
> Notice for renaming `none()` to `discard()`

- CHANGELOG.asciidoc
- gremlin-python/src/main/python/gremlin_python/process/graph_traversal.py
https://issues.apache.org/jira/projects/TINKERPOP/issues/TINKERPOP-3025?filter=allopenissues Added missing l_trim/r_trim, deprecated ltrim/rTrim, and minor consistency fixes to python.
> [TINKERPOP-3025] Add missing l_trim() and r_trim() to python

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.6.x.asciidoc
- gremlin-dotnet/src/Gremlin.Net/Process/Traversal/DefaultTraversal.cs
https://issues.apache.org/jira/browse/TINKERPOP-3029
`IEnumerable<T>.Current` has been changed in .NET 8. Before .NET 8, it simply returned `null` if `MoveNext()` wasn't called first. With .NET 8 however it throws an exception.
Since this has apparently already been undefined behavior before, we should fix this irrespective of .NET 8:
https://github.com/dotnet/runtime/issues/85243#issuecomment-1521085177
The problem can be reproduced by executing the Gherkin tests with .NET without the change in `DefaultTraversal` (by changing the `TargetFramework` in `Gremlin.Net.IntegrationTest.csproj` to `net8.0`). .NET 8 needs to be installed for this of course.
VOTE +1
> TINKERPOP-3029 Fix enumeration for .NET 8

- gremlin-python/src/main/python/examples/requirements.txt
Merges dependabot PRs #2401 #2402 #2403 #2404 #2405, verified that the upgrades cause no issues.
> Bump gremlin-python dependencies

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Contains.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/BulkSet.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/ContainsBulkSetTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/BulkSetTest.java
Improved within test check for bulkset with elements (i.e., Vertex, Edge, VertexProperty) by using contains method. Due to changes w.r.t. Gremlin comparison semantics (cf. https://tinkerpop.apache.org/docs/3.7.0/dev/provider/#gremlin-semantics-concepts) this check was no longer done efficiently, which led to some regressions (see query/example below). In some cases, we can however ensure that the contains of the bulkset (using hash code and Object.equals) leads to the same results as the GremlinValueComparator.COMPARABILITY.equals. In fact, for elements, both checks are only be done with the ids of these elements.
This change re-enables an efficient check for elements (if the bulkset also contains these elements and only contains these kind of elements). This is realized via a transient …
> Improved contains check for bulkset with elements

- .github/workflows/build-test.yml
- docker/Dockerfile
- docs/src/dev/developer/development-environment.asciidoc
- gremlin-dotnet/Examples/BasicGremlin/BasicGremlin.csproj
- gremlin-dotnet/Examples/Connections/Connections.cs
- gremlin-dotnet/Examples/Connections/Connections.csproj
- gremlin-dotnet/Examples/ModernTraversals/ModernTraversals.csproj
- gremlin-dotnet/docker-compose.yml
- gremlin-dotnet/src/Gremlin.Net.Template/Gremlin.Net.Template.csproj
- gremlin-dotnet/test/Gremlin.Net.Benchmarks/Gremlin.Net.Benchmarks.csproj
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.Template.IntegrationTest/Gremlin.Net.Template.IntegrationTest.csproj
- gremlin-dotnet/test/Gremlin.Net.UnitTest/Gremlin.Net.UnitTest.csproj
https://issues.apache.org/jira/browse/TINKERPOP-3030
I've also noticed that the examples used camel casing for some method names which I switched to pascal casing to stay idiomatic in C#.
I had to update the Docker image to Ubuntu 20.04 because .NET 8 is not available for Ubuntu 18.04. Since 18.04 is out of support since June already, this update makes sense in general [1].
I verified that the Docker build is still working with:
```sh
./docker/build.sh --dotnet
```
VOTE +1
[1]: https://wiki.ubuntu.com/Releases
> TINKERPOP-3030 Update to .NET 8

- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpHandlerUtil.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
The HttpGremlinEndpointHandler will now chunk responses for both script and bytecode traversals. Much of the implementation is taken from the StandardOpProcessor/TraversalOpProcessor/UnifiedHandler.
Note that there are test failures due to the change in error handling which is not reflected in the GLVs so certain GLV integration tests will be failing. This will be updated in the future when the GLVs are updated to handle the new error mechanism sent by the server.
> Add chunked transfer encoding to HTTP Channelizer.

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestOptions.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnectionTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/ClientWithOptionsIntegrateTest.java
Refactored `DriverRemoteConnection.getRequestOptions()` to be a public static method in `RequestOptions` so that `Client.submitAsync()` can get and pass along options with it.  This fixes the issue where aliased clients submitting traversals containing `with()` configurations would ignore sending these options as part of the request in https://issues.apache.org/jira/browse/TINKERPOP-3039.
> Allow aliased client to pass along options when submitting traversals

- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/test/features/map/Select.feature
A new SelectStep test is failing in JDK8 tests due to a difference in hashing between Java 8 and 11.  In Java 8, the hash used to identify the traverser to be removed from the no-op barrier is recomputed at removal, and can't find a match due to other traversal branches having added vertices to the bulkset, thus changing its potential hash value.  Java 11 simply uses the hash field stored at creation instead of recomputing it which avoids this problem.  
This additional barrier step is a temporary fix that helps the query wait until all the vertices have been added to the bulkset before adding traversals to the no-op barrier so that hashing stays consistent.
> Temporary fix to failing JDK8 test

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/HttpChannelizer.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpHandlerUtil.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpRequestIdHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpRequestMessageDecoder.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/StateKey.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/handler/HttpRequestIdHandlerTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/handler/HttpRequestMessageDecoderTest.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/Tokens.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/message/RequestMessageV4.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/message/ResponseMessage.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/AbstractGraphSONMessageSerializerV4.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/binary/RequestMessageSerializerV4.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/message/RequestMessageV4Test.java
Request IDs are now generated by the server and returned as a header. This handler handles both of these operations to centralize the implementation.
> Introduce Netty handler for managing request IDs.

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestOptions.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Context.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpRequestMessageDecoder.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/message/RequestMessageV4.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/message/RequestMessageV4Test.java
evaluationTimeout and materializeProperties should be allowed to be set from the request body as it affects how the server should execute the query.
> Add back evaluationTimeout and materializeProperties

- gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/jsr223/DriverGremlinPlugin.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Result.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
- gremlin-tools/gremlin-benchmark/src/main/java/org/apache/tinkerpop/gremlin/driver/SerializationBenchmark.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/message/ResponseMessageV4.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/message/ResponseResultV4.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/AbstractGraphSONMessageSerializerV4.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/binary/ResponseMessageSerializerV4.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/GraphSONMessageSerializerV4Test.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/binary/types/sample/SamplePersonSerializerTest.java
The V4 version changes the data to be List<Object> rather than just a plain Object since the server will always wrap the result in a List anyway. The GraphSON representation will now contain an empty array instead of a null when there are no results.
> Replace ResponseResult with ResponseResultV4.

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DropStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStartStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStartStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MergeEdgeStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MergeVertexStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AddPropertyStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/event/EventUtil.java
This will allow to reuse callback registration logic for extended classes of mutation steps.
Related discussion where the conclusion was made to relax individual steps based on necessity: https://lists.apache.org/thread/vjbjh29kwjhd5lcmkqqqqrhw7rw2ynh9
> Refactor mutation events registration by moving reusable code from relevant steps to EventUti

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/NoOpBarrierStep.java
This will make it possible to extend and overwrite `NoOpBarrierStep`.
Reason for this change: https://github.com/JanusGraph/janusgraph/pull/4456#issuecomment-2118854247
Related discussion (Discord thread about `barrier` + `drop` step usage): https://discord.com/channels/838910279550238720/1241219665376706603
Related discussion where the conclusion was made to relax individual steps based on necessity: https://lists.apache.org/thread/vjbjh29kwjhd5lcmkqqqqrhw7rw2ynh9
> Open NoOpBarrierStep for extensibility

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/DisjunctStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/IntersectStep.java
For Vendors implementing these steps, the members of these step classes need to be accessible. Thus adding getters over their members.
> Adding Getter for fields of IntersectStep and DisjunctStep.

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
CAUSE:
In some cases when credentials expire, or servers encounters a
blip and closes all connections. The driver gets close message on all
connections. While processing those close messages, the driver was
getting into race conditions, where in multiple threads were trying to
close connections and trying to update the connections object i.e. list
of connections in the pool. This was leading to uncaught exceptions and
stale connections in the pool. These connections are never cleanedup
post this.
FIX:
Iterate the connections list while creating the connectionPool Info.
Since the list used is copyOnWrite, the iterator API creates a clone
and uses that clone for referring the element. Thus providing thread
safe interface.
However the information provided by this iteration is a bit stale, …
>  Fixing connection cleanup in case of mass connection breaking.

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SubstringGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SubstringLocalStep.java
For external vendor implementation of these steps, the internal fields of these steps need to be accessible. Thats why added the getters here.
> Getters for internal fields of SubstringLocalStep, SubstringGlobalStep

- CHANGELOG.asciidoc
- spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/Spark.java
- spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/structure/SparkTest.java
It should allow overriding the Spark App name if user wants to. If user does not specify the Spark app name, we will provide the default one. This is useful for user to see different Spark App if there are many Gremlin Servers sharing the same Spark cluster.
> [TINKERPOP-3082] Allow specifying a customized Spark AppName

- gremlin-javascript/examples/browser/yarn.lock
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/graph.ts
- Improve structures type definitions
```ts
type Person = Vertex<"person", { name: string; age: number }>;
type Pet = Vertex<"pet", { name: string; age: number }>;
type Owns = Edge<Person, "owns", Pet, { since: Date }>;
```
> feat: typescript utilities

- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/connection.py
- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-python/src/main/python/gremlin_python/driver/request.py
- gremlin-python/src/main/python/gremlin_python/driver/resultset.py
- gremlin-python/src/main/python/gremlin_python/driver/serializer.py
- gremlin-python/src/main/python/gremlin_python/structure/io/graphbinaryV1.py
- gremlin-python/src/main/python/gremlin_python/structure/io/graphbinaryV4.py
- gremlin-python/src/main/python/gremlin_python/structure/io/graphsonV2d0.py
- gremlin-python/src/main/python/gremlin_python/structure/io/graphsonV3d0.py
- gremlin-python/src/main/python/gremlin_python/structure/io/util.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_client.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection_http.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection_threaded.py
- gremlin-python/src/main/python/tests/driver/test_serializer.py
- gremlin-python/src/main/python/tests/driver/test_web_socket_client_behavior.py
- gremlin-python/src/main/python/tests/structure/io/test_functionalityio.py
- gremlin-python/src/main/python/tests/structure/io/test_graphbinaryV4.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV2d0.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV3d0.py
- gremlin-server/conf/gremlin-server-modern.yaml
Updated python HTTP connection to use the new 4.0 request/response message formats. Reformatted existing tests to use HTTP server (tests passed with local HTTP server), but will need to further modify docker set up for GH actions. There remains a couple of client tests that need investigation. All old WS sockets are currently disabled, and will be removed at a later point along with related implementations. 
Next step is to enable chunked transfer, tests for new message formats will be added then.
> Python driver basic connectivity to HTTP server

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WebSocketAuthorizationHandler.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthzIntegrateTest.java
Issue is that when using authentication traversal arguments  (for example evaluationTimeout do not propagate, leading to failures in the traversal and unexpected behavior. This fixes that problem
> TINKERPOP-3081 Fix traversal argument propagation under authentication

- CHANGELOG.asciidoc
- gremlin-go/driver/graphBinary.go
- gremlin-go/driver/graphBinary_test.go
There are two optimization points for the readmap function:
1. Map key cannot be an incomparable type, otherwise it will cause a panic, but the function does not distinguish 
2. When the key is an incomparable type, adjusted to fmt.Sprint(k) to avoid unreadable output
> improvement: optimization of readmap function

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ConcatStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ConjoinStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SplitGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SplitLocalStep.java
> Add getter for private fields to Concat, Conjoin, SplitGlobal/Local Step

- CHANGELOG.asciidoc
- gremlin-go/driver/graphBinary.go
- gremlin-go/driver/graphBinary_test.go
https://issues.apache.org/jira/browse/TINKERPOP-3096
I encountered a log message missing necessary parameters while using the 'Containing' function. The detailed log information is as follows:
2024/07/14 16:27:28 Error occurred during operation gremlinServerWSProtocol.readLoop(): 'E0703: expected string Key for map, got type='0x%!x(MISSING)''
2024/07/14 16:27:28 Read loop error 'E0703: expected string Key for map, got type='0x%!x(MISSING)'', closing read loop.
2024/07/14 16:27:28 Connection error callback invoked, closing protocol.
> TINKERPOP-3096: improvement: add necessary parameters for logging to fix '%!x(MISSING)' output issue in gremlin-go

- CHANGELOG.asciidoc
- gremlin-console/src/main/bin/gremlin-java8.bat
- gremlin-console/src/main/bin/gremlin.bat
Default logging level for Gremlin Console in Windows is set to the same WARN level as for Linux.
Add command line option `-l` to change logging level for Gremlin Console in Windows.
https://issues.apache.org/jira/browse/TINKERPOP-3098
> [TINKERPOP-3098] added configuration for logging level for Gremlin Console in Windows

- gremlin-python/docker-compose.yml
- gremlin-python/src/main/python/examples/requirements.txt
- gremlin-python/src/main/python/setup.cfg
- gremlin-python/src/main/python/setup.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV2d0.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV3d0.py
The Python package no longer uses the six library, but still installs it as a dependency. Let's remove it to make installs a bit quicker and smaller.
Also universal wheels are for supporting both Python 2 and 3, so is no longer needed.
Do you still support Python 3.4? I don't think so, but couldn't find the min version documented. Well, this can be also removed if not:
```python
if sys.version_info < (3, 5):
install_requires += ['pyparsing>=2.4.7,<3.0.0']
```
> Remove redundant six dependency

- CHANGELOG.asciidoc
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/python/gremlin_python/driver/remote_connection.py
- gremlin-python/src/main/python/gremlin_python/driver/request.py
- gremlin-python/src/main/python/gremlin_python/process/graph_traversal.py
- gremlin-python/src/main/python/gremlin_python/process/translator.py
- gremlin-python/src/main/python/gremlin_python/process/traversal.py
- gremlin-python/src/main/python/gremlin_python/structure/graph.py
- gremlin-python/src/main/python/tests/driver/test_client.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-python/src/main/python/tests/process/test_gremlin_lang.py
- gremlin-python/src/main/python/tests/process/test_translator.py
- gremlin-python/src/main/python/tests/process/test_traversal.py
Replaced bytecode with gremlin lang scripts in gremlin-python, similar to what's been implemented in gremlin-java. 
Groovy translators are no longer needed, as well as some other code left over from WebSocket; will be cleaning them up along with bytecode codes in a separate PR after this is merged. 
Some TODOs are pending core changes, e.g. bulking, transactions. 
Local unit and integration tests pass, next step is to implement authentication interface, and modifying docker-compose set up to enable tests during build/GitHub actions.
~~Also added set in gremlin-java gremlin lang as set is now supported in grammar (can separate that into different PR/CTR if preferred).~~ Will open set changes for gremlin-java in separate PR due to additional changes needed.
> Bytecode removal in gremlin-python

- CHANGELOG.asciidoc
- gremlin-server/src/main/bin/gremlin-server.sh
- gremlin-server/src/main/docker/docker-entrypoint.sh
Fixes what seems to be a regression of [TINKERPOP-2950.](https://issues.apache.org/jira/browse/TINKERPOP-2950). Originally fixed in #2397.
With this change, the gremlin-server process will end up as PID 1 and receive all the signals, specifically SIGTERM, and allow the server to shutdown gracefully (and e.g. write a graph to a volume).
> Regression: Graceful shutdowns for GremlinServer

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceSelfMethodVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Operator.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateGlobalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AggregateLocalStep.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/ComputerVerificationStrategy.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceSelfMethodVisitorTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/OperatorTest.java
- gremlin-language/src/main/antlr4/Gremlin.g4
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/test/features/sideEffect/Aggregate.feature
Support all Operators in AggregateGlobalStep and AggregateLocalStep.
https://issues.apache.org/jira/browse/TINKERPOP-3080
> [TINKERPOP-3080] AggregateGlobalStep accepts all pre-defined Operators

- CHANGELOG.asciidoc
- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/gremlin_python/driver/auth.py
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-python/src/main/python/gremlin_python/driver/request.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_auth.py
- gremlin-python/src/main/python/tests/driver/test_client.py
Referencing the Java driver, added an interface for authentication with HTTP, with basic and SigV4 auth as reference implementations. e.g. `username='stephen', password='password'` is replaced by `auth=basic('stephen', 'password')`.
Local tests pass, will be updating the docker compose set-up as next step for integration tests.
> Add pluggable auth in gremlin-python with HTTP

- gremlin-console/src/test/python/tests/test_console.py
I noticed that the gremlin console integration tests were all failing due changes in the plugin activation text in the console header. This PR simply fixes the tests by updating it to reflect the plugins which are currently loaded by default. Consideration into which plugins should be activated by default may be warranted.
The current console header looks like this:
```
\,,,/
(o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.remote
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.sugar
plugin activated: tinkerpop.credentials
plugin activated: tinkerpop.tinkergraph
gremlin> 
```
> Fix console integration tests

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/binary/GraphBinaryWriter.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/binary/types/MapSerializer.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/binary/types/SimpleTypeSerializer.java
- gremlin-python/src/main/python/gremlin_python/structure/io/graphbinaryV4.py
- gremlin-python/src/main/python/tests/structure/io/test_graphbinaryV4.py
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/AbstractRoundTripTest.java
Changes:
* Add ordered `value_flag` `0x02` to Map serializers in Java and Python drivers.
Note this branch was based off of [graphbinary-add-datetime](https://github.com/apache/tinkerpop/tree/graphbinary-add-datetime) feature branch, as such the PR is to that branch to minimize file diff and facilitate review. Target branch will be changed to `master-http` once the feature branch is merged in https://github.com/apache/tinkerpop/pull/2776.
> Update Map serializer according to GraphBinaryV4 IO specs

- CHANGELOG.asciidoc
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
Jira link: https://issues.apache.org/jira/browse/TINKERPOP-3112
This PR fixes a memory leak in the case the server responds with an error.
I observed the leak in our environment, took heap snapshots and traced it down to not removing response handlers in case of a server error.
> [TINKERPOP-3112] Javascript: fix memory leak on server error

- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuditLogIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthzIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/AbstractGremlinServerChannelizerIntegrateTest.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/AbstractGraphSONMessageSerializerV4.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/SerTokens.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/GraphSONMessageSerializerV4Test.java
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/GraphSONUntypedMessageSerializerV4Test.java
There might be potential additions to the `result` object in the response so adding back the `data` list just in case.
> Add data list back to result object in GraphSONv4.

- docs/src/dev/io/graphson.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV4.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperTest.java
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/no-prop-edge-v4.json
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/tinker-graph-v4.json
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/traversal-edge-v4-no-types.json
- gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/traversal-edge-v4.json
- gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/structure/io/AbstractUntypedCompatibilityTest.java
Moved id, label into the inV and outV as this logically makes more sense as its the correct representation of a reference/detached vertex.
> Update GraphSONv4 format for edge's vertex reference.

- CHANGELOG.asciidoc
- gremlin-go/driver/error_codes.go
- gremlin-go/driver/gorillaTransporter.go
- gremlin-go/driver/gorillaTransporter_test.go
- gremlin-go/driver/resources/error-messages/en.json
https://issues.apache.org/jira/browse/TINKERPOP-3076
Gorilla has an implicit frame size limit imposed by WriteBufferSize. Requests which exceed this limit cannot be parsed by gremlin server and currently lead to cryptic errors in the server. This PR simply adds a client side check to throw a more descriptive error to the user. The resulting behaviour is very similar to how `maxContentLength` functions in the java driver.
VOTE +1
> [TINKERPOP-3076] Throw better error if request exceeds WriteBufferSize in Go

- docs/src/dev/future/index.asciidoc
The Future docs for TP4 has been outdated since we've released 3.7.x. This is to update the Future section to align with the TP4 features that has been in discussion or have been brought up at various points. 
I based this on master since it is around TP4, but can rebase to 3.7.x if we want this published into the latest docs. 
Note I added some formatting to the features doc, so opening the file in rendered view might be easier to review.
> Update Future docs for TinkerPop 4

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SettingsTest.java
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
https://issues.apache.org/jira/browse/TINKERPOP-2700
Use of compression with sensitive data may make users vulnerable to attacks such as CRIME/BREACH. .Net and Go already had options which allowed users to configure the use of compression. This PR is adding such configuration to the remaining drivers.
Note: There is a corresponding PR to 3.7 which adds additional tests making use of GremlinSocketServer (https://github.com/apache/tinkerpop/pull/2833)
> [TINKERPOP 2700] Make WS Compression Configurable in Remaining GLVs

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SettingsTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/helper.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/client-behavior-tests.js
- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-python/src/main/python/tests/driver/test_web_socket_client_behavior.py
- gremlin-tools/gremlin-socket-server/conf/test-ws-gremlin.yaml
- gremlin-tools/gremlin-socket-server/src/main/java/org/apache/tinkerpop/gremlin/socket/server/SocketServerSettings.java
- gremlin-tools/gremlin-socket-server/src/main/java/org/apache/tinkerpop/gremlin/socket/server/TestWSGremlinInitializer.java
https://issues.apache.org/jira/browse/TINKERPOP-2700
Use of compression with sensitive data may make users vulnerable to attacks such as CRIME/BREACH. .Net and Go already had options which allowed users to configure the use of compression. This PR is adding such configuration to the remaining drivers.
Note: There is a corresponding PR to 3.6 which is missing the GremlinSocketServer tests (https://github.com/apache/tinkerpop/pull/2832)
> [TINKERPOP 2700] Make WS Compression Configurable in Remaining GLVs 3.7

- docs/src/reference/gremlin-variants.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpGremlinResponseDecoder.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/interceptor/PayloadSerializingInterceptor.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/SimpleHttpClient.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ClusterTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/TestClientFactory.java
The GraphSONv4 MessageSerializer doesn't support chunking so the HttpObjectAggregator is added back and the
HttpGremlinResponseStreamDecoder is replaced with the original, non-streaming version. This is mainly for debugging and testing purposes so lowered performance is expected.
VOTE +1
> Re-enable GraphSON message serializer for debugging.

- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ParametersTest.java
One flaky test shouldAllowNullValues is found using Nondex. This PR now fixes it without introducing new plugins / dependencies. The test was found to be flaky when running the following command:
```
mvn -pl gremlin-core \
edu.illinois:nondex-maven-plugin:2.1.7:nondex \
-Dtest=org.apache.tinkerpop.gremlin.process.traversal.step.util.ParametersTest#shouldAllowNullValues \
-Drat.numUnapprovedLicenses=200
```
The `params` array contains retrieved keys and value from a HashMap, that may lead to inconsistent test results due to the non-deterministic ordering of elements in a HashMap. 
The expected keys and values are now stored in a new array 'expected'. Sort both 'params' and 'expected'. The comparison between 'params' and 'expected' has consistent results.
> fix flaky tests in ParametersTest

- CHANGELOG.asciidoc
- gremlin-python/src/main/python/setup.py
This adds `async_timeout` to `gremlin-python`'s `setup.py` as a runtime dependency which is required when using python >= 3.11
> [TINKERPOP-3116] async_timeout not declared in gremlinpython dependencies

- docs/src/reference/gremlin-variants.asciidoc
- docs/src/upgrade/release-4.x.x.asciidoc
- gremlin-python/src/main/python/gremlin_python/driver/client.py
- gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py
- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-python/src/main/python/radish/terrain.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_client.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-python/src/main/python/tests/driver/test_protocol.py
- gremlin-python/src/main/python/tests/process/test_traversal.py
- gremlin-python/src/main/python/tests/structure/io/test_functionalityio.py
The message_serializer is split into the request_serializer and the response_serializer to allow for setting the request_serializer to None which prevents payload serialization. This makes it easier for the user to modify the payload. Auth is not combined with interceptor as it requires refactoring to provide the URL in protocol and simplifies usage compared to the Java driver albeit at the cost of flexibility.
VOTE+1
> Added request interceptor to gremlin-python.

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpGremlinRequestEncoder.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/IdleConnectionHandler.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/InactiveChannelHandler.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/util/ConfigurationEvaluator.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/util/ProfilingApplication.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ClusterBuilderTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ConnectionPoolTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SettingsTest.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/handler/IdleConnectionHandlerTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/ClientConnectionIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
Changed connection pooling to reflect having switched from long lived web socket connections to short lived http connections:
- sped up obtaining a new connection by removing method-level synchronization of getAvailableConnection and introducing a separate set for available connections
- introduced cleanup of idle connections to release resources
- removed minSize since idle connections are now cleaned up and the pool can become empty if there is no traffic
- increased maxSize default to 128
- increased core pool size of ScheduledThreadPoolExecutor that is used for creating new connections to number of available processors
- added logging to help troubleshoot connection related integration tests failures
ProfilingApplication throughput results of master-http prior to these changes (with …
> HTTP connection pooling

- gremlin-python/docker-compose.yml
- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/gremlin_python/driver/connection.py
- gremlin-python/src/main/python/gremlin_python/driver/protocol.py
- gremlin-python/src/main/python/gremlin_python/driver/serializer.py
- gremlin-python/src/main/python/radish/terrain.py
- gremlin-python/src/main/python/tests/conftest.py
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
Updated to handling aggregating results as GraphSON doesn't deserialize streams, re-enabled GraphSON testing in tests, and updated GraphSON class naming to be more consistent.
> Re-enable GraphSON testing for gremlin-python

- gremlin-python/src/main/python/gremlin_python/process/traversal.py
- gremlin-python/src/main/python/gremlin_python/statics.py
- gremlin-python/src/main/python/gremlin_python/structure/io/graphsonV4.py
- gremlin-python/src/main/python/tests/structure/io/test_functionalityio.py
- gremlin-python/src/main/python/tests/structure/io/test_graphbinaryv4model.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonV4.py
- gremlin-python/src/main/python/tests/structure/io/test_graphsonv4model.py
- gremlin-python/src/main/python/tests/test_statics.py
Added a value property to BigDecimal so it can be properly serialized in Gremlin Lang to the server for GraphBinary. 
Added a `to_bigdecimal` function to help creating BigDecimal in python and for GraphSON. 
Currently targeting the test branch, will rebased once that PR is merged.
> Update BigDecimal in gremlin-python statics to be consistent with server definition

- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
- gremlin-python/src/main/python/setup.py
This removes the async_timeout dependency for python 3.11 and newer
This came from the conversation in https://github.com/apache/tinkerpop/pull/2844
To test this locally I attempted the following by looking at the GitHub Actions workflows, but it didn't succeed. Any recommendations to build and test the python package would be great - or pointers to docs that I missed. Thanks
```bash
brew install temurin@11
export JAVA_HOME=$(/usr/libexec/java_home -v 11)
export PATH=$JAVA_HOME/bin:$PATH
mvn clean install -DskipTests -Dci --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
mvn clean install -pl gremlin-server -DskipTests -DskipIntegrationTests=true -Dci -am
docker save --output gremlin-server.tar tinkerpop/gremlin-server
touch …
```
> chore(gremlinpython): remove async_timeout for python 3.11 and newer

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WsAndHttpChannelizerHandler.java
The log entry here is necessary because when an exception thrown by
Netty reaches exceptionCaught(), if the error is not printed, the
server side will not be able to know what has happened.
For example, if the maxContentLength in JanusGraph's Gremlin-Server
configuration is set to 65536, and the client sends data over this
size via WebSocket, the JanusGraph server logs will appear normal,
but the client will experience a disconnection, making it difficult
to immediately identify the cause of the issue.
> Add log entry in WsAndHttpChannelizerHandler

- gremlin-console/pom.xml
- gremlin-driver/pom.xml
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/auth/Auth.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/auth/Sigv4.java
- gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/auth/Sigv4Test.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java
Updated SigV4 interceptor to use the latest version of software.amazon.awssdk and removed old dependency on aws-java-sdk-core. Since latest version of SignedRequest has headers that support multiple values for the same header via Map<String,List> I added validation checks that the expected signed headers only have 1 value.
> Update SigV4 interceptor to use latest aws sdk version

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IdentityRemovalStrategy.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IdentityRemovalStrategyTest.java
RepeatEndStep has the same treatment as EndStep under ComputerAwareStep
> RepeatEndStep has the same treatment as EndStep under ComputerAwareStep

- docs/src/dev/io/graphson.asciidoc
- docs/src/dev/provider/index.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- docs/src/reference/intro.asciidoc
- docs/src/upgrade/release-4.x.x.asciidoc
Please look over this documentation change for either inaccurate information or missing information.
VOTE +1
> Update documentation around TinkerPop HTTP API and serializers.

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectStep.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ConjoinStepTest.java
`org.apache.tinkerpop.gremlin.process.traversal.step.map.ConjoinStepTest.testReturnTypes` was found to be flaky using nondex:
```
[ERROR]   ConjoinStepTest.testReturnTypes:58 expected:<1[0.11.12]> but was:<1[1.12.10]>
```
This flakiness can be reproduced with command:
```
mvn -pl gremlin-core edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.apache.tinkerpop.gremlin.process.traversal.step.map.ConjoinStepTest#testReturnTypes -Drat.skip=true
```
The test was flaky due to the use of an unordered collection (`HashSet`), that caused assertion failures under different iteration orders. This PR fixed this flakiness by replacing the `HashSet` with `LinkedHashSet`
`org.apache.tinkerpop.gremlin.process.traversal.strategy.optimization.PathProcessorStrategyTest` was wound to be flaky for four …
> Fix Flaky Tests in /gremlin-core

- CHANGELOG.asciidoc
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
Enable TCP Keep-Alive to detect if the remote peer is still reachable. Keep-Alive sends periodic probes to check if the remote peer is still active. If the remote peer is unreachable, the connection will be closed, preventing resource leaks and avoiding the maintenance of stale connections.
> Avoid the issue of connections not being released.

- CHANGELOG.asciidoc
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/sasl-authentication-tests.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/socket-connection-tests.js
This PR helps provide more information to the end user when a websocket unexpected-response is encountered. This is particularly helpful for using AWS Neptune, which sometimes encounters an "unexpected-response" status code, with a body describing the issue.
This is the same PR as https://github.com/apache/tinkerpop/pull/2935 just targeting the correct base branch.
> Add unexpected-response handler to gremlin-javascript connection websocket

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-applications.asciidoc
- docs/src/upgrade/release-3.7.x.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/util/ProfilingApplication.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractSession.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/FrameMessageSizeEstimator.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/MetricManager.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/ServerGremlinExecutor.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-3124
Improved logging around channel pauses. Added new metrics for Gremlin Server around channels and pauses. Added some extra capabilities to the java driver profiling tool.
VOTE +1
> TINKERPOP-3124 Added custom MessageSizeEstimator to cover Frame

- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/GremlinError.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
Alters the servers response to bad queries from `500 Internal Server Error` to `400 Bad Request`. Note that malformed groovy scripts may still produce `500 Internal Server Error` as groovy is unable to statically verify correct gremlin syntax.
VOTE +1
> Change server response to 400 for malformed queries

- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.ts
The `unexpected-response` listener needs to use `.on` and `.off` because the `ws` package's `addEventListener` only accepts certain event types
Ref: https://github.com/websockets/ws/blob/8.16.0/lib/event-target.js#L202-L241
Additionally PR #2936 had slightly different logic for the body chunk return, so I have updated that here too.
> Use .on and .off for unexpected-response listener

- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WebSocketAuthorizationHandler.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthzIntegrateTest.java
Hello,
This PR fixes TINKERPOP-3120 that I just created.
Session support seems to have been dropped from the main branch, so this is for 3.7-dev only.
Best regards,
> Fixes TINKERPOP-3120

- CHANGELOG.asciidoc
- docs/src/upgrade/release-4.x.x.asciidoc
- gremlin-console/pom.xml
- gremlin-console/src/main/static/LICENSE
- gremlin-core/pom.xml
- gremlin-driver/pom.xml
- gremlin-driver/src/main/static/LICENSE
- gremlin-server/src/main/static/LICENSE
- gremlin-tools/gremlin-socket-server/pom.xml
- gremlin-util/pom.xml
- hadoop-gremlin/pom.xml
- hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/HadoopConfiguration.java
- pom.xml
- spark-gremlin/pom.xml
- sparql-gremlin/pom.xml
Updated all logging dependencies. Required minor changes to configuration with slf4j 2.0 as static logger approach has been removed in favor of service loader. 
VOTE +1
> Bumped slf4j and other logging related infrastructure.

- CHANGELOG.asciidoc
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
- gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Mediator.groovy
TINKERPOP: https://issues.apache.org/jira/browse/TINKERPOP-3038
Added if statement in console.groovy to check for invalid plugins in plugins.txt (outputs invalid plugin and incorrect plugin name on console)
Added check to skip empty lines in plugins.txt on Mediator.groovy.
> TINKERPOP-3038: Console plugins file can't accept empty lines

- CHANGELOG.asciidoc
- gremlin-console/src/main/bin/gremlin.sh
https://issues.apache.org/jira/browse/TINKERPOP-3070
If the current working directory contains spaces, gremlin.sh does not handle it properly when launching the console, and the JVM will search for an incorrect main class and fail.
For example if I simply rename the standard console distribution directory to `foo bar`:
foo bar/ $ bin/gremlin.sh                                                                                                                                                                                                                                            
Error: Could not find or load main class bar
Caused by: java.lang.ClassNotFoundException: bar
Added quotations around directory path in order to ensure spaces in directory name are not considered two separate strings
> TINKERPOP-3070 Cannot run console if working directory contains spaces

- CHANGELOG.asciidoc
- docs/src/reference/gremlin-variants.asciidoc
- gremlin-python/src/main/python/gremlin_python/process/graph_traversal.py
Tinkerpop: https://issues.apache.org/jira/browse/TINKERPOP-3024
has_key_() was added to python because it was reserved on Dictionary but that was removed in python 3. since TinkerPop doesn't support python 2 anymore there is little need for this difference anymore. deprecate the underscore suffixed version and add the property has_key() version.
> [TINKERPOP-3024] Deprecate has_key_() for has_key() in python

- gremlin-go/driver/response.go
- gremlin-go/driver/serializer.go
- gremlin-go/driver/serializer_test.go
Fixes for the Golang driver feature branch related to failures with the `serializer_test.go` test.
* Removed tests for custom type serialization. 
* Removed response id as it is no longer used. 
* Adjusted expected serialized request bytes according to TP4 format. 
* Adjusted bytes for testing deserialization according to TP4 format. 
* Removed serializer unwrapping of single item results as it was causing serialization test to fail.
> Fix serializer_test.go for feature branch

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
https://issues.apache.org/jira/browse/TINKERPOP-3015
Update hasId(P) signature to accept P<?> instead of P<Object>. This allows for types such as P<String> which are not subtypes of P<Object> to be passed directly to this method, instead of going through the hasId(Object) overload and then casting to a P raw type. Note that the P special case handling still exists in hasId(Object) to cover any cases in which the correct overload is not identifiable at compile-time.
All of the above applies equivalently for hasValue().
This is non-breaking and targeting 3.7-dev as all it is doing is allowing more predicates to go into hasId(P) directly, and skipping the cast to the P raw-type.
My vote is VOTE +1
> TINKERPOP-3015 Use wildcard instead of Object for hasId/hasValue predicates

- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/features/StepDefinition.java
Allow for floating point rounding errors in Java Feature test assertions by backporting https://github.com/apache/tinkerpop/commit/6a534d1ddfbd9b12183953717906561da9d09dfc into 3.7-dev branch.
> Allow for floating point rounding errors in Java Feature test assertions

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/IndexStep.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/IndexStepTest.java
Fixed serialization and deserialization of `IndexStep` by moving non-serializable lambdas to serializable implementations of the functional interface. This code pattern is similar to that of other steps like `GroupCountStep`, `MeanGlobalStep`, etc. Added unit tests to test round trip serialization->deserialization.
https://issues.apache.org/jira/browse/TINKERPOP-3139
> TINKERPOP-3139 Fixed serialization and deserialization of IndexStep

- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
https://issues.apache.org/jira/browse/TINKERPOP-3144
Close traversal on execution failure or interruption in order to release all its resources. Currently the traversal gets closed only when its consumed entirely, but it will not get closed on failures.
`StandardOpProcessor` is kinda in question still as it requires to read bindings and close all traversals.
> TINKERPOP-3144 Close traversal on failure

- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/util/ProfilingApplication.java
It has been observed in some environments that integration tests such as `GraphBinaryGroovyRemoteFeatureTest` can encounter 16 second delays between test executions. Investigation shows this can occur if one thread is attempting to obtain a connection and another thread is creating or releasing a connection at the same time. It is possible for the thread releasing or creating a connection to signal the `hasAvailableConnection` condition after the other thread has determined there are no available connections but before calling `await` on the condition. Thus the thread obtaining the connection will wait for default timeout of 16 seconds before attempting to retrieve a connection again, causing the observed delays.
This fix involves locking the `waitLock` before obtaining and potentially …
> Fix connection pool bug which can cause delays in obtaining a connection

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Operator.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/OperatorExceptionTest.java
[TINKERPOP-3155](https://issues.apache.org/jira/browse/TINKERPOP-3155) 
Fixed typo for Operator.addAll to check that all args are collections instead of just the first and added unit test.
> TINKERPOP-3155 Fixed typo for Operator.addAll to check that all args are collections instead of just the first

- CHANGELOG.asciidoc
- gremlin-server/pom.xml
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/SSLStoreFilesModificationWatcher.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/util/SSLStoreFilesModificationWatcherTest.java
- pom.xml
This PR introduces support for dynamic reloading of SSL certificates:
- Adds a file watcher that monitors certificate files for changes every minute. When changes are detected, the certificates are reloaded.
- Integrates the (Apache License) [Hakky54/sslcontext-kickstart](https://github.com/Hakky54/sslcontext-kickstart?rgh-link-date=2025-03-24T16%3A26%3A36Z) library (as [suggested by the TinkerPop community](https://discord.com/channels/838910279550238720/1330896099749396620/1331763442918359120)) to enable hot-reloading of SSL certificates.
Addresses https://issues.apache.org/jira/browse/TINKERPOP-3146
> [TINKERPOP-3146] Support hot reloading of SSL certificates

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.8.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/ArgumentVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/DefaultGremlinBaseVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/GenericLiteralVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/ParseTreeContextCastHelper.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/StructureElementVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalMethodVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalPredicateVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceSelfMethodVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceSpawnMethodVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalStrategyVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/AnonymizedTranslatorVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/DotNetTranslateVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/GoTranslateVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/GroovyTranslateVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/JavaTranslateVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/JavascriptTranslateVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/PythonTranslateVisitor.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/TranslateVisitor.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/ArgumentVisitorTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/GeneralLiteralVisitorTest.java
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/Gremlin.cs
- gremlin-go/driver/cucumber/gremlin.go
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/gremlin.js
- gremlin-language/src/main/antlr4/Gremlin.g4
- gremlin-python/src/main/python/radish/gremlin.py
Renaming a bunch of types in the grammar to improve consistency and descriptiveness. Some types were redundant and have been removed.
The new names all follow the pattern `<baseType>(<CollectionType>)?(Nullable)?(Literal|Argument)(Varargs)?`
Previously, many types in the grammar used the suffix `List`, when in practice these were varargs as they did not nest arguments in brackets. These have all been renamed to varargs for consistency.
The full list of changes is listed below:
Renamings:
`genericLiteralArgument` -> `genericArgument`
`structureVertex` -> `structureVertexLiteral`
`stringLiteralVarargsArgument` -> `stringNullableArgumentVarargs`
`genericLiteralMapArgument` -> `genericMapArgument`
`genericLiteralMapNullable` -> `genericMapNullableLiteral`
`genericLiteralMapNullableArgument` …
> Rename grammar types to improve descriptiveness and consistency

- CHANGELOG.asciidoc
- gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-3167
There is a chance that the Client.hostConnectionPools can land in a state where it has zero hosts present which leads to the returned ConnectionPool itself to be null. Borrowing a Connection then leads to a NullPointerException. Specifically, the `pool` ends up null [here](https://github.com/apache/tinkerpop/blob/3a48401d83656a31c459f541550b62be67084970/gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java#L520) and then the NPE happens next line on `borrowConnection`.  
By preferring a check during init of actual connection pool creation the Client avoids a state where it could grab a null pool. This change doesn't address some of the synchronization issues that likely contributed to allowing the NPE in the first …
> TINKERPOP-3167 Fixed NPE when borrowing a connection

- CHANGELOG.asciidoc
- gremlin-python/src/main/python/gremlin_python/driver/aiohttp/transport.py
Back in the [tornado transport days we had set the max content length in python to 10MB](https://github.com/apache/tinkerpop/blob/3.4-dev/gremlin-python/src/main/jython/gremlin_python/driver/tornado/transport.py#L29). 10MB is consistent with the default max frame length in gremlin-server. It seems the 10MB default was lost in the migration to AiohttpTransport, and we've inherited a reduced 4MB limit from AioHTTP.  Bumping it back to 10MB for consistency with gremlin-server.
VOTE +1
> Increase default `max_content_length`/`max_msg_size` in python to 10MB

- CHANGELOG.asciidoc
- gremlin-console/src/main/bin/gremlin.sh
https://issues.apache.org/jira/browse/TINKERPOP-3162
```
gremlin> g = traversal().withEmbedded(graph)
gremlin> g.io('data/tinkerpop-modern.kryo').read()
gremlin> g
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], standard]
gremlin> g.V()
==>v[1]
==>v[2]
==>v[3]
==>v[4]
==>v[5]
==>v[6]
```
> TINKERPOP-3162 fixed JDK 17 field accessor in gremlin-console

- CHANGELOG.asciidoc
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerElementContainer.java
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerTransactionGraph.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerTransactionGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-3141
Account for the scenario of dropping and re-adding a vertex within the same transaction by adding a new `unmarkDeleted` method to the `TinkerElementContainer` and calling `unmarkDeleted` from `addVertex` if it is detected that the vertex had been previously deleted. Added logic to reference the previously deleted vertex version when adding the vertex back to avoid transaction conflict error.
> TINKERPOP-3141 Allow drop add vertex in same transaction

- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalTest.java
- gremlin-tools/gremlin-benchmark/src/main/java/org/apache/tinkerpop/gremlin/process/ApplyStrategiesBenchmark.java
- gremlin-tools/gremlin-benchmark/src/main/java/org/apache/tinkerpop/gremlin/process/TraversalLockBenchmark.java
https://issues.apache.org/jira/browse/TINKERPOP-3100
Drastically improves the performance of lock() as you lose the excessive recursion and avoid having to reidentify steps repeatedly.
```
Benchmark                                  Mode  Cnt   Score    Error   Units
TraversalLockBenchmark.testLockTraversal  thrpt   10  ≈ 10⁻⁴           ops/ms
```
after
```
Benchmark                                  Mode  Cnt   Score   Error   Units
TraversalLockBenchmark.testLockTraversal  thrpt   10  18.784 ± 0.334  ops/ms
```
Messily merged this to 3.7-dev with https://github.com/apache/tinkerpop/commit/98ffa44fc27f6326f259265372bb17240162d6c5 and removed the "deep" traversal tests/benchmarks because jdk8 wouldn't compile that code for some reason. works fine for jdk11/17. code is good for jdk8 when the …
> TINKERPOP-3100 Fix problem in recursive calls to Traversal lock()

- CHANGELOG.asciidoc
- docs/src/reference/implementations-tinkergraph.asciidoc
- tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerElementContainer.java
- tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerTransactionGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-3142
Changed `TinkerElementContainer` to no longer consider element reads as being 'used in a transaction' which should be reserved for element add/update/delete only. This is appropriate for `TinkerTransactionGraph` because the isolation level is 'read committed'. With this isolation level, we do not need to protect against 'unrepeatable reads' or 'phantom reads'.
Prior to this change, a read-only thread could cause a 'Conflict: element modified in another transaction' error in a separate thread which was attempting add/drop/update.
> Transaction reads should not interfere with add/update/delete

- CHANGELOG.asciidoc
- docs/javadoc/overview.html
- docs/src/upgrade/release-3.0.x-incubating.asciidoc
- docs/src/upgrade/release-3.1.x-incubating.asciidoc
- docs/src/upgrade/release-3.2.x-incubating.asciidoc
- docs/src/upgrade/release-3.3.x.asciidoc
- docs/src/upgrade/release-3.4.x.asciidoc
- docs/src/upgrade/release-3.5.x.asciidoc
- docs/src/upgrade/release-3.6.x.asciidoc
- docs/src/upgrade/release-3.7.x.asciidoc
https://issues.apache.org/jira/browse/TINKERPOP-3174
Fixed broken image links in documentation which were referencing the github domain and blocked by apache when viewing the tinkerpop website.
> Fixed broken image links in documentation

- CHANGELOG.asciidoc
- docs/src/upgrade/release-3.8.x.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/P.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TextP.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/PTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStepTest.java
`P.getOriginalValue()` is not providing much value and it often confused with `P.getValue()`. I would argue that all existing usages of originalValue in P and TextP are incorrect as they lead to very strange behaviour after `P.setValue()` is called:
```
gremlin> predicate = P.eq(5)
==>eq(5)
gremlin> predicate.equals(P.eq(5))
==>true
gremlin> predicate.setValue(10)
==>null
gremlin> predicate.equals(P.eq(5))
==>true
gremlin> predicate.equals(P.eq(10))
==>false
gremlin> predicate.test(5)
==>false
gremlin> predicate.test(10)
==>true
gremlin> predicate.toString()
==>eq(5)
```
The only other usage in our code is in MatchStepTest which is unaffected by switching to `P.getValue()`. My vote is to get rid of `originalValue` altogether as it is not offering any value and just leads to unnecessary …
> Remove P.getOriginalValue()

- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/CallStepContract.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/CallStepPlaceholder.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/CallStepTest.java
- gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/util/GraphFactoryTest.java
Added CallStep tests, fixed bugs, removed unnecessary code from placeholder. Allowed MockGraph to have a mocked or stubbed service registry.
> Added CallStep tests, fixed bugs, removed unnecessary code

- CHANGELOG.asciidoc
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/binary/types/PathSerializer.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV2.java
- gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV3.java
- gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
- gremlin-go/driver/connection_test.go
- gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/graph.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/client-tests.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/graphbinary/PathSerializer-test.js
- gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/graphson-test.js
- gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
- gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Context.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinResultSetIntegrateTest.java
- gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSerializationIntegrateTest.java
- gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/SerializationTest.java
- gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/Tokens.java
https://issues.apache.org/jira/browse/TINKERPOP-3182
`Path` objects were being forcibly detached by reference in GraphSON v1/v2 which put it at odds with v1 untyped. Inclusion or removal of properties should be controlled via `materializeProperties` only.
There's still a bit of weirdness here for Javascript particularly if you note the assertions in our tests. That should be resolved separately with a breaking change: [TINKERPOP-3186](https://issues.apache.org/jira/browse/TINKERPOP-3186).
VOTE +1
> TINKERPOP-3182 Fixed inconsistency in Path GraphSON serialization
