gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/GraphTraversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/step/filter/DedupGlobalStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/step/filter/SampleGlobalStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/step/map/MaxGlobalStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/strategy/DedupOptimizerStrategy.java
* replaced `Double.MIN_VALUE` with `-Double.MAX_VALUE` in `MaxGlobalStep` cause `Double.MIN_VALUE` is just the smallest **positive** number
* renamed `DedupStep` to `DedupGlobalStep` and `SampleStep` to `SampleGlobalStep` so that these steps are in line with the other steps that support a global and a local scope
=> minor fixes

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/TraversalPerformanceTest.java
Added performance tests for more complex steps (`match()` and `subgraph()`).
tinkerpop/tinkerpop3#231
=> Added performance tests for more complex steps

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/util/metric/DependantMutableMetrics.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/util/metric/MutableMetrics.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/kryo/KryoMapper.java, gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/graph/traversal/step/sideEffect/GroovyProfileTest.groovy, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/step/sideEffect/ProfileTest.java
=> Fix missing kryo registrations for AtomicLong and DependantMutibleMetrics

gremlin-groovy-test/src/test/java/org/apache/tinkerpop/gremlin/process/computer/util/ScriptEngineLambdaTest.java
For context, this is a redo of a PR from the old repo: https://github.com/tinkerpop/tinkerpop3/pull/525
=> Add unit test for ScriptEngineLambda

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SideEffectCapStep.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/TraversalPerformanceTest.java, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP3-615
=> TINKERPOP3-615 cap(String, String...) to require at least one side effect key

gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineOverGraphTest.java
Remove hard coded id from groovy script that causes graphs other then TinkerGraph to fail.
=> TINKERPOP3-630

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/JsonMessageSerializerV1d0.java
https://issues.apache.org/jira/browse/TINKERPOP3-682
=> TINKERPOP3-682 JsonMessageSerializerV1d0 throws RuntimeException instead of SerializationException

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WsGremlinTextRequestDecoder.java
Fixes TINKERPOP3-686 WebSocket serialization fails for JSON
=> TINKERPOP3-686 WebSocket serialization fails for JSON

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/RangeLocalStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/TailLocalStep.java, gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyRangeTest.groovy, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeTest.java
This PR makes range, limit, and tail more consistent.
tinkergraph-gremlin tests pass
hadoop-gremlin tests pass
=> TINKERPOP3-673: range/limit local with single element should eschew List

gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
https://issues.apache.org/jira/browse/TINKERPOP3-722
=> fix for TINKERPOP3-722 Garbled characters in Gremlin Console help screen on Windows

docs/src/the-traversal.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ConstantStep.java, gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyConstantTest.groovy, gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessComputerSuite.java, gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessStandardSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ConstantTest.java
Passed TinkerFactory and Hadoop-Gremlin tests.
=> TINKERPOP3-723 constant step

pom.xml
=> Added a contributor

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/MutableMetrics.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/ProfileTest.java
=> TINKERPOP3-697 Add hooks to MutableMetrics to manually set counts and duration.

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/GraphFactory.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/GraphFactoryClass.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/util/GraphFactoryTest.java
Added @GraphFactoryClass annotation to support locating a factory class when constructing a graph via GraphFactory.
=> TINKERPOP3-778 Added @GraphFactoryClass annotation 

gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
I added the tests I had around this change. These pass:
```
mvn clean install -DincludeNeo4j
mvn clean -DskipIntegrationTests=false -DincludeNeo4j --projects gremlin-server verify
```
The driver end tests pass perfectly. It's looking good.
=> added tests around single channel in session and sessionless requests

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/NioGremlinBinaryRequestDecoder.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WsGremlinBinaryRequestDecoder.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WsGremlinCloseRequestDecoder.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WsGremlinTextRequestDecoder.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP3-910
Test via:
```text
mvn clean install -DincludeNeo4j
mvn clean -DskipIntegrationTests=false -DincludeNeo4j --projects gremlin-server verify
```
The summary for this change is in the comments of this commit:
https://github.com/apache/incubator-tinkerpop/commit/43f64c2a4aad965343ef87ce5407cb0b79d96714
VOTE: +1
=> TINKERPOP3-910 - In session transaction opened from sessionless request

docs/src/developer-contributing.asciidoc, docs/src/developer-release.asciidoc, docs/src/developer.asciidoc, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP3-922
Moved CONTRIBUTING and RELEASE to the developer book.  Docs seem to publish fine with this change.  Here are the developer docs on 3.1.0-SNAPSHOT:
http://tinkerpop.incubator.apache.org/docs/3.1.0-SNAPSHOT/developer.html
+1
=> TINKERPOP3-922 Created developer book.

hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/HadoopGraph.java
https://issues.apache.org/jira/browse/TINKERPOP3-917
Damn simple 3 lines of code addition.
VOTE: +1
=> TINKERPOP3-917: Add HadoopGraph.open(String)

docs/src/the-traversal.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/AdjacentToIncidentStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IncidentToAdjacentStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalExplanation.java, gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroovyExplainTest.groovy, gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessComputerSuite.java, gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessStandardSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/ExplainTest.java, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/browse/TINKERPOP3-679
We now have a pretty-print `TraversalExplanation` object that can be created for any `Traversal` via `Traversal.explain()`. An example is below:
```
gremlin> g.V().outE().identity().inV().count().is(gt(5))
==>6
gremlin> g.V().outE().identity().inV().count().is(gt(5)).explain()
==>Traversal Explanation
=================================================================================================================================================
Original Traversal                 [GraphStep([],vertex), VertexStep(OUT,edge), IdentityStep, EdgeVertexStep(IN), CountGlobalStep, IsStep(gt(5))]
ConnectiveStrategy           [D]   [GraphStep([],vertex), VertexStep(OUT,edge), IdentityStep, EdgeVertexStep(IN), CountGlobalStep, IsStep(gt(5))] …
```
=> TINKERPOP3-679: Debuggable Traversal

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Property.java, neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jEdge.java, neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jGraphVariables.java, neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/trait/MultiMetaNeo4jTrait.java, neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/trait/NoMultiNoMetaNeo4jTrait.java
Added root cause to exceptions where a root cause is available
To make the decision of where to add root cause, I looked the impl (neo4j, hadoop, spark and orientDB) and add it when the root cause is available.
=> Fix fo TINKERPOP3-945

gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyAddEdgeTest.groovy, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexPropertyTest.java
Converted integer value to string to maintain type
https://issues.apache.org/jira/browse/TINKERPOP3-990
=> TINKERPOP3-990 Removed mixed typing in VertexPropertyTest

docs/src/reference/the-graph.asciidoc
https://issues.apache.org/jira/browse/TINKERPOP3-952 
I added an example of adding a property with a list cardinality along with an explanation.  @rjbriody if you get a chance, let me know if this is along the lines of what you were thinking.  I checked things out by doing a dry run of the docs generation.
=> TINKERPOP3-952 Adding example of a property with list cardinality.

bin/validate-distribution.sh
**Invalid version:**
```
daniel@cube /projects/apache/dev/incubator-tinkerpop (TINKERPOP-976) $ bin/validate-distribution.sh 3.0.2-incubating
Validating binary distributions
* downloading Apache Gremlin Console (apache-gremlin-console-3.0.2-incubating-bin.zip)... Failed to download Apache Gremlin Console
```
**Valid version:**
```
daniel@cube /projects/apache/dev/incubator-tinkerpop (TINKERPOP-976) $ bin/validate-distribution.sh 3.1.0-incubating
Validating binary distributions
* downloading Apache Gremlin Console (apache-gremlin-console-3.1.0-incubating-bin.zip)... OK
* validating signatures and checksums ... 
* PGP signature ... OK
* MD5 checksum ... OK
* SHA1 chacksum ... OK
* unzipping Apache Gremlin Console ... OK
* validating Apache Gremlin Console's docs ... OK
* validating Apache …
```
=> TINKERPOP-976 Fail earlier if invalid version is supplied in validate-distribution.sh

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/SackFunctions.java, gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroovySackTest.groovy, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SackTest.java
Integrated `NumberHelper` in `SackFunctions`.
* `mvn clean install`: passed
* integration tests: passed
VOTE: +1
=> TINKERPOP-824 Do we need runtime BigDecimal in more places?

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/FeatureSupportTest.java
"EdgeFunctionalityTest.shouldSupportAddVertexPropertyIfItCanBeAdded" should be "EdgeFunctionalityTest.shouldSupportAddEdgePropertyIfItCanBeAdded".
=> Fixed test name.

docs/preprocessor/preprocess.sh
Tried with Gremlin Server running and the preprocessor was cancelled with a nice error message. Tried with Gremlin server not running and and the preprocessing worked as usual.
VOTE:  +1
=> TINKERPOP-943 Warn if Gremlin Server is running prior to generating docs

CHANGELOG.asciidoc, data/script-input.groovy, docs/src/reference/implementations.asciidoc, gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/structure/io/script/script-input-grateful-dead.groovy, gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/structure/io/script/script-input.groovy, hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/script/ScriptRecordReader.java
Previous PR + discussion: https://github.com/apache/incubator-tinkerpop/pull/219
=> TINKERPOP-1137 Deprecate ScriptElementFactory and make star graph globally available

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Host.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
Check the value of reconnectionAttempt and create scheduled task as a 2 step process.
Surely there is a more JDK-1.7 way of doing this, but this is working for me.
=> TINKERPOP-1126

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
https://issues.apache.org/jira/browse/TINKERPOP-1106
Both types of errors were causing problems.  For commit errors, the last message from iteration was already sent back to the client as a terminating message so failure on commit after that was ignored by the driver because it had already received the terminator for that request.  Serialization errors didn't break the result iteration loop - they were being handled, but the result iteration was allowed to continue. I'm not so sure that those types of failures weren't leaking transactions either - that should be fixed now too.
This stuff is hard to write tests for with Gremlin Server as I dont' know how to force raise a commit exception for Neo4j.  I was able to test externally with graphs that were easier to force that condition.
I will …
=> TINKERPOP-1106 Better handled commit and serialization errors in Gremlin Server.

appveyor.yml, gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/ScriptEnginesTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/TestHelper.java, hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/HadoopGraphProvider.java, pom.xml, spark-gremlin/pom.xml, spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/io/SparkContextStorage.java
Same as https://github.com/apache/incubator-tinkerpop/pull/207
But target on tp31
=> TINKERPOP-1041

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/ServerGremlinExecutor.java
This refers to PR #246 and bases the changes on the branch tp31.
=> Make the GraphManager instance injectable into ServerGremlinExecutor based on tp31

docs/src/reference/the-traversal.asciidoc
https://groups.google.com/d/msg/gremlin-users/V9wHagF2SvY/FBwe1zkbAwAJ
=> improve predicate doc

neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jGraph.java
Version of #288 targeting tp31
=> Fix TINKERPOP-1252 (Supersedes #288)

hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/script/ScriptRecordReader.java
This update precompiles an input script and then reads the input file using the compiled script instead of repeatedly calling the engine.eval().  This should cut down on the time spent repeatedly eval-ing the input script. 
I ran a quick and dirty benchmark on my measly macbook with SparkGraphComputer, 2 workers.  `g.V().count()` on a test file with 250,000 vertices and a simple `.groovy` script to read it in.
Average of 10 runs
-------------------------
before (TP 3.2.0 - engine.eval): 14975.7 ms
after (TP-1295 - w/ compiled script): 10163.6 ms
`mvn clean install` success
VOTE: +1
=> TINKERPOP-1295 Precompile ScriptInputFormat scripts once during initialization of ScriptRecordReader

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupSideEffectStep.java, gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroovyGroupTest.groovy, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupTest.java, hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/HadoopGraph.java, spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkStarBarrierInterceptor.java, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1307
When an OLAP traversal has a `group()` that contains, nested another `group()`, the latter `group()` is OLTP, but due to transient declarations, a null pointer can arise. To rectify this, `GroupStep.GroupBiOperator` no longer passes around `Traversal` and instead, 4 types: `Traverser`, `TraverserSet`, `Pair<TraverserSet,Object`, `Object`, where `Object` is the current barrier of an internal `Barrier`. Two complex nested group tests were added to demonstrate that things function as expected and there are no longer NPEs.
This change made `group()` a bit slower, but not by much and now the code is safer. For a play test I have, the OLTP speed (which is the important one) went from 436ms to 456ms. Again, no biggie.
CHANGELOG
```
* Fixed a …
```
=> TINKERPOP-1307: NPE with OLTP nested group() in an OLAP group() traversal

hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/script/ScriptInputFormat.java, hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/script/ScriptOutputFormat.java
Hi @dkuppitz here is the TINKERPOP-1301 ported to tp31 branch :)
=> TINKERPOP-1301 Provide Javadoc for ScriptInput/OutputFormat's ported to tp31 branch

docs/src/dev/provider/index.asciidoc, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1317
=> TINKERPOP-1317: use graph class as root class to find temporary directory

CHANGELOG.asciidoc, docs/src/reference/implementations-hadoop.asciidoc, giraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/giraph/process/computer/GiraphGraphComputer.java, hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/process/computer/AbstractHadoopGraphComputer.java, hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/groovy/plugin/HadoopGremlinPluginCheck.java, spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java
https://issues.apache.org/jira/browse/TINKERPOP-1331
It's now possible to have DFS paths in `HADOOP_GREMLIN_LIBS`.
VOTE: +1
=> TINKERPOP-1331 HADOOP_GREMLIN_LIBS can only point to local file system

docs/src/reference/implementations-neo4j.asciidoc
https://issues.apache.org/jira/browse/TINKERPOP-939
I manually tested this with a local 3 node cluster both in Gremlin Console and in Gremlin Server. Everything seems to work fine. I basically just wrote some basic docs for how to setup but since TinkerPop is really just a pass through for configuration options, most of the docs for "how" are on the Neo4j side.
I don't know that there is a way to do testing for this on our current framework or if there is a ton of value to doing so as this is all pass through - we don't even use a separate "HA Graph instance" like we did in Blueprints. Thoughts welcome on that matter....
Personally, I think the docs are enough for now to close this old issue. If we really want tests we could open a new issue to write some "integration" tests that do some …
=> TINKERPOP-939 Added docs for Neo4j HA configuration.

gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphFilter.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PageRankVertexProgramStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PeerPressureVertexProgramStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/ProgramVertexProgramStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/TraversalVertexProgramStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalExplanation.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalExplanationTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1332
`TraversalExplanation.toString()` now supports word wrapping and `GraphFilter` information.
*First, here is word wrap in action*:
```
gremlin> g.V().out().out().out().out().count().explain()
==>Traversal Explanation
=======================================================================================================================================
Original Traversal                 [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
VertexStep(OUT,vertex), CountGlobalStep]
ConnectiveStrategy           [D]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), VertexStep(OUT,vertex), VertexStep(OUT,vertex),
VertexStep(OUT,vertex), CountGlobalStep]
RangeByIsCountStrategy       [O] …
```
=> TINKERPOP-1332: Improve .explain() Dialogue

gremlin-variant/src/main/jython/setup.py
also import \_\_version\_\_ in setup.py instead of eval-ing it
=> add license boilerplate to __version__

CHANGELOG.asciidoc, docs/src/upgrade/release-3.1.x-incubating.asciidoc, gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/plugin/dsl/credential/CredentialGraphTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyProcessTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/EdgeTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/FeatureSupportTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/PropertyTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexPropertyTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1319
Passed `mvn clean install -DincludeNeo4j` and integration tests cleanly.
May be CTR worthy. Let me know.
VOTE: +1
=> TINKERPOP-1319: fix incorrect FeatureRequirement annotations

docs/src/dev/developer/contributing.asciidoc, docs/src/dev/provider/index.asciidoc, docs/src/reference/gremlin-applications.asciidoc, docs/src/reference/implementations-neo4j.asciidoc, docs/src/reference/preface.asciidoc, docs/src/reference/the-graphcomputer.asciidoc, docs/src/reference/the-traversal.asciidoc, docs/src/upgrade/release-3.1.x-incubating.asciidoc
=> Tp31: Minor word and link cleanup

docs/src/dev/developer/contributing.asciidoc, docs/src/dev/provider/index.asciidoc, docs/src/reference/gremlin-applications.asciidoc, docs/src/reference/implementations-neo4j.asciidoc, docs/src/reference/preface.asciidoc, docs/src/reference/the-graphcomputer.asciidoc, docs/src/reference/the-traversal.asciidoc, docs/src/upgrade/release-3.1.x-incubating.asciidoc
=> Minor word and link cleanup

docs/src/tutorials/gremlin-language-variants/index.asciidoc
I noticed a few possible errors while reading the "Gremlin Language Variants" tutorial.
=> tweaks in gremlin language variants doc

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/TailGlobalStep.java, gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyTailTest.groovy, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/TailTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1379
VOTE: +1
=> TINKERPOP-1379 remove excess bulk in tail buffer

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraph.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraphTest.java
See:
* old PR #372
* JIRA issue https://issues.apache.org/jira/browse/TINKERPOP-1397
=> TINKERPOP-1397 StarGraph filtering with self edges

CHANGELOG.asciidoc, docs/src/reference/gremlin-applications.asciidoc, docs/src/upgrade/release-3.2.x-incubating.asciidoc, gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Colorizer.groovy, gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy, gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/GremlinGroovysh.groovy, gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Preferences.groovy, gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/GremlinSetCommand.groovy
Stephen did all the hard work.
- Added option -C to disable ANSI colors just in case.
- Colorized the gremlin ascii art.
- Added bold red to some, but probably not all, error messages
- Snuck in the help text for TINKERPOP-1246
=> TINKERPOP-1037 Made life more colorful

gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
Forgot to test this one. Fixed now.
=> Fixed empty result

gremlin-server/src/assembly/distribution.xml
Fixed distribution scripts target directory.
=> TP31: Server missing scripts directory 

bin/update-current-docs.sh
Added a separate script to update the "current" docs.
=> TINKERPOP-1383 publish-docs.sh might publish to current too early

docs/src/reference/the-graphcomputer.asciidoc
Added a warning message for BLVP.
=> TINKERPOP-1264 Improve BLVP docs

docs/src/reference/implementations-neo4j.asciidoc
Added note to the doc as discussed in https://issues.apache.org/jira/browse/TINKERPOP-1430
=> Added note on Grape configuration for Gremlin-Neo4j

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/VertexProgram.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/ProgramVertexProgramStep.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphComputerTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/TranslationStrategy.java
=> TINKERPOP-1280 VertexPrograms should declare traverser requirements

docs/src/reference/the-graphcomputer.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerGremlinV2d0.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV2d0.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
Enclose filter steps and side-effect steps in `RangeByIsCountStrategy` when `NotStep` is used to wrap part of the traversal.
VOTE: +1
=> TINKERPOP-1391 issue with where filter

CHANGELOG.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1442
see #412 for more description
All unit tests and gremlin-server integration tests are passing on this branch.
VOTE +1
=> TINKERPOP-1442 Improved session cleanup on client close [master]

docs/src/reference/the-traversal.asciidoc
https://issues.apache.org/jira/browse/TINKERPOP-1115
Let's get this merged. I'll keep the ticket open and add the `GraphTraversalSource` stuff later.
VOTE: +1
=> TINKERPOP-1115 Improve GraphTraversal and GraphTraversalSource Reference Docs

docs/src/reference/the-traversal.asciidoc
Query produces 2 results since 3.0.0
=> Fix store step documentation

CHANGELOG.asciidoc, docs/src/upgrade/release-3.1.x-incubating.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Handler.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultQueue.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthOldIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1467
This work was from `tp31` and was pretty heavily conflicted so I decided on a separate PR. Please see #441 for more information.
VOTE +1
=> TINKERPOP-1467 Corrected a number of problems in close() operations for the driver [master]

CHANGELOG.asciidoc, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/plugin/dsl/credential/CredentialGraph.java
Using lowest complexity 4 (was 10).
=> TINKERPOP-1189 Increased performance of CredentialGraph authentication

spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkExecutor.java
SparkExecutor.executeVertexProgramIteration was written in such a way
that an empty RDD partition would cause it to invoke
VertexProgram.workerIterationStart without ever invoking
VertexProgram.workerIterationEnd.  This seems like a contract
violation.  I have at least one VP that relies on
workerIterationStart|End to allocate and release resources.  Failing
to invoke End like this causes a leak in that VP, as it would for any
VP that uses that resource management pattern.
=> TINKERPOP-1525 Avoid starting VP worker iterations that never end

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/UnfoldStep.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/UnfoldStepTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1211
Unfold step now handles unfolding of arrays.
VOTE +1.
=> TINKERPOP-1211: UnfoldStep should unfold arrays.

CHANGELOG.asciidoc, gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/main/java/Service.java, gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/java/ServiceTest.java, gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/resources/gremlin-server.yaml, gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/groovy/plugin/gremlin-server-integration.yaml, gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/groovy/plugin/remote.yaml, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.java, gremlin-python/pom.xml, gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py, gremlin-python/src/test/resources/org/apache/tinkerpop/gremlin/python/driver/gremlin-server-modern-secure-py.yaml, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/RemoteGraphProvider.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerPerformanceTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinAdditionPerformanceTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinResultSetIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthOldIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinTraversalPerformanceTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/TestClientFactory.java, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/driver/remote/gremlin-server-integration.yaml, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-performance.yaml
See #491
Had to do a separate PR as the merge from tp31 was not clean. Required additional changes for tests to pass.
VOTE +1
=> TINKERPOP-1538 [tp32]

CHANGELOG.asciidoc, gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/main/java/Service.java, gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/java/ServiceTest.java, gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/resources/gremlin-server.yaml, gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/groovy/plugin/gremlin-server-integration.yaml, gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/groovy/plugin/remote.yaml, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.java, gremlin-python/pom.xml, gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py, gremlin-python/src/test/resources/org/apache/tinkerpop/gremlin/python/driver/gremlin-server-modern-secure-py.yaml, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/RemoteGraphProvider.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinResultSetIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthOldIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/TestClientFactory.java, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/driver/remote/gremlin-server-integration.yaml, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-performance.yaml
See #491
Had to do a separate PR as the merge from tp32 was not clean. Required additional changes for tests to pass.
VOTE +1
=> TINKERPOP-1538 [master]

CHANGELOG.asciidoc, docs/src/reference/gremlin-applications.asciidoc, docs/src/reference/gremlin-variants.asciidoc, docs/src/tutorials/gremlin-language-variants/index.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bindings.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bytecode.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/optimization/GraphFilterStrategyTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/BytecodeTest.java, gremlin-python/src/main/groovy/org/apache/tinkerpop/gremlin/python/GraphTraversalSourceGenerator.groovy, gremlin-python/src/main/groovy/org/apache/tinkerpop/gremlin/python/TraversalSourceGenerator.groovy, gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py, gremlin-python/src/main/jython/gremlin_python/process/traversal.py, gremlin-python/src/main/jython/tests/process/test_traversal.py
https://issues.apache.org/jira/browse/TINKERPOP-1573
The solution to this problem uses `ThreadLocal`. It sucks, but I don't know of any other way of doing this. Whats funny is that I knew this problem existed as in my notes, the `ThreadLocal` solution is what I came up with back then. We just never had a test case the demonstrated the anonymous traversal bindings problem and thus, I never implemented the "solution."
VOTE +1.
=> TINKERPOP-1573: Bindings don't work in coalesce

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/ComplexTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1539
Added 2 more tests, one for OLTP only and one for OLTP+OLAP. More tests should not be added as part of this PR; we can add more later whenever a good traversal appears on the mailing list or somewhere else in the real world.
`docker/build.sh -t -i -n` succeeded.
VOTE: +1
=> TINKERPOP-1539 Create a ComplexTraversalTest with crazy nested gnarly traversals.

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IncidentToAdjacentStrategy.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IncidentToAdjacentStrategyTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1545
Implemented changes as discussed in https://github.com/apache/tinkerpop/pull/486.
VOTE: +1
=> TINKERPOP-1545 IncidentToAdjacentStrategy is buggy

docs/src/tutorials/gremlin-language-variants/index.asciidoc
change 'gremlin_python' to 'gremlinpython'
https://pypi.python.org/pypi/gremlinpython/3.2.3
=> fix wrong python package name

gremlin-python/src/main/jython/setup.py
As previously discussed. Now targeted for the correct branch. Thanks for the help guys.
=> remove tests from setup.py

docs/src/reference/gremlin-applications.asciidoc, gremlin-console/src/main/static/LICENSE, gremlin-groovy/pom.xml, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/plugin/dsl/credential/CredentialGraph.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/auth/SimpleAuthenticator.java, gremlin-server/src/main/static/LICENSE
targeting tp31 branch for this version bump of jbcrypt to 0.4
=> TINKERPOP-1633 use official jbcrypt 0.4 in maven central

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/AbstractGremlinScriptEngineFactory.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/BindingsGremlinPlugin.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/DefaultBindingsCustomizer.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/DefaultGremlinScriptEngineManager.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/LazyBindingsCustomizer.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/AbstractImportCustomizerProvider.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/CompilerCustomizerProvider.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/DefaultImportCustomizerProvider.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/EmptyImportCustomizerProvider.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/ImportCustomizerProvider.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/NoImportCustomizerProvider.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineFactory.java, gremlin-server/scripts/spark.groovy, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/jsr223/BindingsScriptEngineTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/jsr223/MockGremlinScriptEngine.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/jsr223/MockGremlinScriptEngineFactory.java, gremlin-test/src/main/resources/META-INF/services/org.apache.tinkerpop.gremlin.jsr223.GremlinScriptEngineFactory, gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/jsr223/bindings-init.groovy, hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/jsr223/HadoopGremlinPlugin.java, hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/jsr223/HadoopGremlinPluginTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1631
This PR is a bit in the weeds. You can read the JIRA issue if you want a few more details, but basically most of this is driven by the work being done in master to get rid of gremlin-groovy-test.
Builds fine with docker.
VOTE +1
=> TINKERPOP-1631 Improvements to BindingsGremlinPlugin

CHANGELOG.asciidoc, docs/src/reference/gremlin-applications.asciidoc, docs/src/upgrade/release-3.2.x-incubating.asciidoc, gremlin-groovy/pom.xml, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/ScriptEngines.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/CompilationOptionsCustomizer.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyCompilerGremlinPlugin.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/CompilationOptionsCustomizerProvider.java, gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineCompilationOptionsTest.java, gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTest.java, gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyCompilerGremlinPluginTest.java, gremlin-server/pom.xml, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/MetricManager.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/ServerGremlinExecutor.java
https://issues.apache.org/jira/browse/TINKERPOP-1644
This PR was started on #567 which was submitted by @BrynCooke. I've made some basic modifications and included various metrics about compilation that will be helpful in debugging things. Those metrics are reported up through Gremlin Server through the standard metric reporting system.
Builds to success with `docker/build.sh -t -i -n`.
VOTE +1
=> TINKERPOP-1644 Improve script compilation process and include metrics

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
typo: rename fnfe to cnfe in GremlinServer#createChannelizer
=> typo: rename fnfe to cnfe in GremlinServer#createChannelizer

CHANGELOG.asciidoc, gremlin-shaded/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-1654
Did a build with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false` but expect to do a full build with docker for all branches this merges too after vote. 
VOTE +1
=> TINKERPOP-1654 Bumped to Jackson 2.8.7

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/ElementHelper.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraph.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/util/ElementHelperTest.java
StarVertexProperty will check meta-properties are valid.
=> TINKERPOP-1664 StarVertexProperty will check meta-properties are valid.

CHANGELOG.asciidoc, docs/src/dev/io/graphson.asciidoc, docs/src/upgrade/release-3.2.x-incubating.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/AbstractObjectDeserializer.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONReader.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV2d0.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypeDeserializer.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/JavaTimeSerializersV2d0.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/TraversalSerializersV2d0.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedEdge.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedElement.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedVertex.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedVertexProperty.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedEdgeTest.java, gremlin-tools/gremlin-io-test/src/test/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/_3_3_0/path-v2d0-no-types.json, gremlin-tools/gremlin-io-test/src/test/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/_3_3_0/path-v2d0-partial.json, gremlin-tools/gremlin-io-test/src/test/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/_3_3_0/property-v3d0.json, gremlin-tools/gremlin-io-test/src/test/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/_3_3_0/standardresult-v3d0.json, gremlin-tools/gremlin-io-test/src/test/resources/org/apache/tinkerpop/gremlin/structure/io/graphson/_3_3_0/stargraph-v3d0.json, tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerIoRegistry.java, tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerIoRegistryV1d0.java, tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerIoRegistryV2d0.java
https://issues.apache.org/jira/browse/TINKERPOP-1676
Had to do a separate PR for this as we've made changes in testing IO on master - see #613 for more details on what this PR is about.
Builds with `docker/build.sh -t -i -n`
VOTE +1
=> TINKERPOP-1676 (master) GraphSON Performance

docs/src/reference/the-traversal.asciidoc
https://issues.apache.org/jira/browse/TINKERPOP-1708
Added a `Note on Scopes` section to the `the-traversal.asciidoc`.
VOTE +1
=> TINKERPOP-1708: Add a "Note on Scopes" document

CHANGELOG.asciidoc, docs/src/upgrade/release-3.3.x.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bindings.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java, gremlin-python/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-1721
The deed has been done. Mam, these bindings won't be bothering you any longer.
<ride off into sunset/>
VOTE +1.
=> TINKERPOP-1721: Remove deprecated Bindings related code

CHANGELOG.asciidoc, docs/src/reference/gremlin-applications.asciidoc, docs/src/upgrade/release-3.2.x-incubating.asciidoc, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WsAndHttpChannelizer.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAndHttpBasicAuthenticationHandler.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAuthenticationHandler.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WebSocketHandlerUtil.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WsAndHttpChannelizerHandler.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/AbstractGremlminServerChannelizerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/HttpChannelizerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/NioChannelizerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/WsAndHttpChannelizerIntegrateTest.java
@spmallette I think this is pretty much the cleanest I get history with the fixes etc needed for master.
=> Add combined handler master

gremlin-groovy/pom.xml, spark-gremlin/pom.xml, spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/io/gryo/GryoRegistrator.java, spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/io/gryo/GryoSerializer.java
That required:
- more spark conflicting dependency exclusion in pom.xml
- more spark and scala classes registration in tinkerPop gryo
=> TINKERPOP-1715: update spark version to 2.2

CHANGELOG.asciidoc, docs/src/upgrade/release-3.2.x-incubating.asciidoc, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1770
VOTE +1
=> TINKERPOP-1770 Enable timeouts for remote traversals

docker/Dockerfile, docker/build/Dockerfile.template, docker/scripts/build.sh
https://issues.apache.org/jira/browse/TINKERPOP-1731
Build seems to work in full now.
VOTE +1
=> TINKERPOP-1731 Build for .NET working in docker

CHANGELOG.asciidoc, gremlin-console/src/main/static/NOTICE, gremlin-server/src/main/static/NOTICE, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-1835
Latest bug-fix release.  No new deps.
Building...
=> TINKERPOP-1835 Bump Netty 4.0.53

gremlin-dotnet/src/Gremlin.Net/Process/Traversal/DefaultTraversal.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-1837
(The new Travis job comes in handy to validate features like this one :) )
VOTE +1
=> TINKERPOP-1837 Gremlin .NET: Provide type coercion between IDictionary<K, V> instances

CHANGELOG.asciidoc, docs/src/reference/the-traversal.asciidoc, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/Dsl/DslTest.cs
https://issues.apache.org/jira/browse/TINKERPOP-1734
Provided tests and documentation for implementing DSLs in .Net. No changes were needed to the code base for this - just used C# extension methods as suggested by @jorgebay . Only downside was anonymous traversals are a little weird because C# doesn't let you extend static classes and extensions methods can't be used on them either. The only recourse is to wrap static methods in the extending class which is a lot of extra boilerplate. I opted to just recommend that users create their own class for spawning anonymous traversals that just works independently of `__`. 
VOTE +1
=> TINKERPOP-1734 DSL for Gremlin .NET

gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyValueMapTest.groovy, gremlin-python/src/main/jython/radish/feature_steps.py, gremlin-test/features/map/ValueMap.feature, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ValueMapTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1860
Somewhat surprised we didn't have tests for this variation of `valueMap()`.  There will be a separate PR for master.
VOTE +1
=> TINKERPOP-1860 Added tests for valueMap(true) variations

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/NumberHelper.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MaxGlobalStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MinGlobalStep.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/util/NumberHelperTest.java, gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyMinTest.groovy, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MinTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1873
Made the reducer for `min()` and `max()` not depend on an Integer seed value. It now uses `Double.NaN` again, but `Double.NaN` also got some special handling in `NumberHelper`, so that results for the reducing steps are not forced to be of type `Double`.
```
$ docker/build.sh -t -i
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache TinkerPop ................................... SUCCESS [02:18 min]
[INFO] Apache TinkerPop :: Gremlin Shaded ................. SUCCESS [ 21.891 s]
[INFO] Apache TinkerPop :: Gremlin Core ................... SUCCESS [01:26 min]
[INFO] Apache TinkerPop :: Gremlin Test ................... SUCCESS [ 12.415 s]
[INFO] Apache TinkerPop :: …
```
=> TINKERPOP-1873 min() and max() work only in the range of Integer values

CHANGELOG.asciidoc, gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy, gremlin-console/src/test/python/tests/test_console.py
https://issues.apache.org/jira/browse/TINKERPOP-1879
Builds with `mvn clean install -pl gremlin-console -DskipIntegrationTests=false`
VOTE +1
=> TINKERPOP-1879 Fixed gremlin.sh handling of = in flags

CHANGELOG.asciidoc, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-1884
VOTE +1
=> TINKERPOP-1884 Bump to Netty 4.0.56.Final

CHANGELOG.asciidoc, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-1884
I won't bother to submit a separate pull request for master as this should merge through just fine.
Builds with mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false
VOTE +1
=> TINKERPOP-1884 Bump to Netty 4.1.21.Final

docs/src/dev/future/index.asciidoc
Based on the discussion here:  
[TINKERPOP-1909](https://issues.apache.org/jira/browse/TINKERPOP-1909)
=> Uniform object model for GraphSON response for client drivers

gremlin-dotnet/glv/Enum.template, gremlin-dotnet/glv/generate.groovy, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Barrier.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Cardinality.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Column.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Direction.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/EnumWrapper.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphSONVersion.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GryoVersion.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Operator.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Order.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Pick.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Pop.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Scope.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/T.cs, gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/GraphSONReader.cs, gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/TDeserializer.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/CommonSteps.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONReaderTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-1866
Issuing this PR for @FlorianHockmann now that TINKERPOP-1865 has merged. 
Builds with ` mvn clean install -DskipTests && mvn verify -pl :gremlin-dotnet-tests -DskipIntegrationTests=false`
VOTE +1
=> TINKERPOP-1866 Support g:T for .NET

docs/src/reference/transpilers.asciidoc
added link to the sparql-gremlin logo, will continue with documentation next.
=> testing logo

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalEngine.java
Fixed typo in JavaDoc: TraversalEngine
=> Fixed typo in JavaDoc: TraversalEngine

CHANGELOG.asciidoc, docs/src/recipes/shortest-path.asciidoc, docs/src/reference/the-traversal.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/TraversalSelectStep.java, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs, gremlin-test/features/map/Select.feature, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/AbstractGremlinProcessTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectTest.java, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1628
This PR adds a `TraversalSelectStep` which supports the selection of dynamic / runtime-generated keys.
VOTE: +1
=> TINKERPOP-1628 Implement TraversalSelectStep

gremlin-javascript/src/main/javascript/gremlin-javascript/index.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/exports-test.js
Export `DriverRemoteConnection`.
https://issues.apache.org/jira/browse/TINKERPOP-1944
VOTE +1
=> TINKERPOP-1944 Export DriverRemoteConnection

.travis.yml
https://issues.apache.org/jira/browse/TINKERPOP-1841
Pretty easy one - was gong to CTR but figured I'd already created the branch to test in travis so may as well run it through the normal process of things. 
VOTE +1
=> TINKERPOP-1841 Configure python tests in travis

CHANGELOG.asciidoc, gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java
https://issues.apache.org/jira/browse/TINKERPOP-1962
Pretty self-explanatory change....easy fix.
VOTE +1
=> TINKERPOP-1962 GroovyTranslator handles empty maps properly now.

docs/src/reference/transpilers.asciidoc
Changes:
- fixed non-working queries (queries which returned no results)
- updated documentation with more examples in the limitations section
- updated execution tags for queries which are for reference only
- commented out the pattern filter examples for now
To Do:
- fix OPTIONAL queries 
- fix Pattern filter queries
- inspect and patch special cases in code
=> Updated transpilers.asciidoc

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
=> TINKERPOP-1995 Return the Promise on Close

CHANGELOG.asciidoc, gremlin-server/src/main/bin/gremlin-server.bat, gremlin-server/src/main/bin/gremlin-server.sh
https://issues.apache.org/jira/browse/TINKERPOP-2031
VOTE +1
=> TINKERPOP-2031 Removed support for -i in gremlin-server.sh

CHANGELOG.asciidoc, gremlin-python/glv/TraversalSource.template, gremlin-python/src/main/jython/gremlin_python/process/traversal.py, gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
https://issues.apache.org/jira/browse/TINKERPOP-1921
Adds `hasNext()` to gremlin-python - pretty self explanatory. Would be nice to get the rest of the GLVs done too. Also fixed some PEP8 formatting nags.
VOTE +1
=> TINKERPOP-1921 Added hasNext() in gremlin-python

gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs, gremlin-dotnet/src/Gremlin.Net/Driver/Exceptions/ResponseException.cs, gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs, gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClientExtensions.cs, gremlin-dotnet/src/Gremlin.Net/Driver/IConnection.cs, gremlin-dotnet/src/Gremlin.Net/Driver/IGremlinClient.cs, gremlin-dotnet/src/Gremlin.Net/Driver/Messages/ResponseStatus.cs, gremlin-dotnet/src/Gremlin.Net/Driver/Messages/ResponseStatusCode.cs, gremlin-dotnet/src/Gremlin.Net/Driver/ProxyConnection.cs, gremlin-dotnet/src/Gremlin.Net/Driver/ResultSet.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientTests.cs
Adding support to de-serialize status attribute for gremlin dotnet.
More details : https://issues.apache.org/jira/browse/TINKERPOP-1913
Following up from the original PR : https://github.com/apache/tinkerpop/pull/868
=> Tinkerpop 1913-Followup

gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java, gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java
Preface:
There's character escaping issue when translating.
What's changed:
- Merge the changes from tp33
=> Apply StringEscapeUtils in GroovyTranslator#convertToString(String) [master]

CHANGELOG.asciidoc, docs/src/upgrade/release-3.2.x-incubating.asciidoc, gremlin-javascript/src/main/javascript/gremlin-javascript/index.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/remote-connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/bytecode.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/translator.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/helper.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/client-tests.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/graphson-test.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/translator-test.js, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
https://issues.apache.org/jira/browse/TINKERPOP-1959
=> TINKERPOP-1959 submit scripts in javascript [master]

CHANGELOG.asciidoc, docs/src/upgrade/release-3.2.x-incubating.asciidoc, gremlin-javascript/src/main/javascript/gremlin-javascript/index.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/remote-connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/bytecode.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/translator.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/helper.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/client-tests.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/graphson-test.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/translator-test.js, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
https://issues.apache.org/jira/browse/TINKERPOP-1959
=> TINKERPOP-1959 submit scripts in javascript [tp33]

CHANGELOG.asciidoc, docs/src/upgrade/release-3.2.x-incubating.asciidoc, gremlin-javascript/src/main/javascript/gremlin-javascript/index.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/remote-connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/bytecode.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/translator.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/helper.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/client-tests.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/graphson-test.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/translator-test.js, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
https://issues.apache.org/jira/browse/TINKERPOP-1959
Follow on PR to #922 - more details there. This branch now contains a fix for the test failure that was referenced in the comments toward the end.
VOTE +1
=> TINKERPOP-1959 submit scripts in javascript

gremlin-dotnet/glv/GraphTraversal.template, gremlin-dotnet/glv/GraphTraversalSource.template, gremlin-dotnet/glv/generate.groovy, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/TraversalEvaluation/TraversalParser.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/BytecodeGeneration/BytecodeGenerationTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-1972
=> TINKERPOP-1972 Fix inject step in Gremlin.Net [master]

gremlin-dotnet/glv/GraphTraversal.template, gremlin-dotnet/glv/GraphTraversalSource.template, gremlin-dotnet/glv/generate.groovy, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/TraversalEvaluation/TraversalParser.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/BytecodeGeneration/BytecodeGenerationTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-1972
=> TINKERPOP-1972 Fix inject step in Gremlin.Net [tp33]

CHANGELOG.asciidoc, docs/src/dev/provider/index.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DropStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStartStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStartStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AddPropertyStep.java
https://issues.apache.org/jira/browse/TINKERPOP-2060
Pretty straightforward - builds with `mvn clean install`.
VOTE +1
=> TINKERPOP-2060 Removed final modifier on Mutating steps

gremlin-console/src/main/static/NOTICE, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java, gremlin-server/src/main/static/NOTICE, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2066
Nothing fancy here...
VOTE +1
=> TINKERPOP-2066 Bump to Groovy 2.5.3

docs/preprocessor/awk/tabify.awk
https://issues.apache.org/jira/browse/TINKERPOP-2073
Tested with the sample code blocks shown in the Jira ticket - looked good.
VOTE +1
=> TINKERPOP-2073 Generate tabs for static code blocks

CHANGELOG.asciidoc, spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/io/PersistedOutputRDD.java
call rdd.count() action to trigger the caching
=> TINKERPOP-2081: Fix PersistedOutputRDD to eager persist RDD

CHANGELOG.asciidoc, docs/src/reference/gremlin-variants.asciidoc, gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py, gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py, gremlin-test/features/map/Select.feature
If there is additional documentation you would like somewhere... please, point me where.
=> TINKERPOP-2071: gremlin-python: g:Set graphson deserializer should return a python set

gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2067
=> TINKERPOP-2067 Allow getting raw JToken data from Gremlin.Net.Driver.GremlinClient.

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bytecode.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalStrategies.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/TraversalStrategiesTest.java
tested locally with `mvn clean install`
=> some improvements

docs/src/recipes/anti-patterns.asciidoc, docs/src/recipes/index.asciidoc
https://issues.apache.org/jira/browse/TINKERPOP-2114
This PR adds a documentation that discusses common anti-patterns.
Docs built with `docker/build.sh -d` look good.
VOTE +1
=> TINKERPOP-2114 Document common Gremlin anti-patterns

CHANGELOG.asciidoc, docs/src/reference/the-traversal.asciidoc, docs/src/upgrade/release-3.4.x.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/IndexStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/WithOptions.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/IndexStepTest.java, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/WithOptions.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal.js, gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py, gremlin-python/src/main/jython/gremlin_python/process/traversal.py, gremlin-test/features/map/Index.feature, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/IndexTest.java, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/projects/TINKERPOP/issues/TINKERPOP-1849
`docker/build.sh -t -i -n` passed and the docs built with `docker/build.sh -d` look good.
VOTE +1
=> TINKERPOP-1849 Provide a way to fold() with an index

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/package.json
https://issues.apache.org/jira/browse/TINKERPOP-1889
- Update ws package
- adding ping interval and pong timeout on websocket to avoid timeout
- auto-reconnection if connection drop
Vote: +1
=> TINKERPOP-1889 - Upgrade ws, adding ping and reconnection javascript

gremlin-python/src/main/jython/gremlin_python/driver/client.py, gremlin-python/src/main/jython/gremlin_python/driver/connection.py, gremlin-python/src/main/jython/tests/driver/test_client.py
@spmallette as discussed in https://github.com/apache/tinkerpop/pull/1013
=> TINKERPOP-2105 fix for TP33

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/kryoshim/KryoShimServiceLoader.java
https://issues.apache.org/jira/browse/TINKERPOP-2129
VOTE +1
=> TINKERPOP-2129 Mask security secret or password

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/InlineFilterStrategy.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/InlineFilterStrategyTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2124
Fixed the bug, added a test case.
`docker/build.sh -t -i` passed.
VOTE +1
=>  TINKERPOP-2124 Fixed and/or folding in InlineFilterStrategy (master)

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/InlineFilterStrategy.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/InlineFilterStrategyTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2124
Fixed the bug, added a test case.
VOTE +1
=> TINKERPOP-2124 Fixed and/or folding in InlineFilterStrategy

gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SerializationExceptionTest.java
In terms of testing, wasn't really sure what more I could have put in there... Open to other suggestions.
Will open an additional separate master PR as there are things I'd like to suggest in some of the GraphBinary exceptions thrown
=> TINKERPOP-2179: Have SerializationException extend IOException

CHANGELOG.asciidoc, docs/src/upgrade/release-3.3.x.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/CoreImports.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/EdgeLabelVerificationStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoVersion.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/EdgeLabelVerificationStrategyTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2191
Implemented `EdgeLabelVerificationStrategy` to allow providers to encourage (or enforce) users to always specify edge labels.
VOTE +1
=> TINKERPOP-2191 Implement EdgeLabelVerificationStrategy

CHANGELOG.asciidoc, docs/src/reference/the-traversal.asciidoc, docs/src/upgrade/release-3.3.x.asciidoc, gremlin-javascript/glv/GraphTraversalSource.template, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/anonymous-traversal.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/graph.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2089
Pretty straightforward, but it feels a bit hacked together with my limited javascript skills. I imagine cleanup from the experts will be needed before this is all said and done. Submitting this as a draft for now - will complete docs and such once the code is "right".
=> TINKERPOP-2089 Added DSL support to gremlin-javascript

CHANGELOG.asciidoc, gremlin-console/src/main/static/NOTICE, gremlin-server/src/main/static/NOTICE, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2242
VOTE +1
=> TINKERPOP-2242 Bump to netty 4.1.36

docs/src/reference/gremlin-applications.asciidoc
Removed the first "that" in "will simply stop processing on the line that of the script that failed" -- right? -- and fixed some minor spelling/punctuation things.  (I checked a few authorities on hyphenating "ad hoc," and they all said not to hyphenate it.)
=> typo and wording fixes to tp33

CHANGELOG.asciidoc, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
https://issues.apache.org/jira/browse/TINKERPOP-2237
=> TINKERPOP-2237: Prevent exception when closing a session that doesn't exist

docs/src/tutorials/getting-started/index.asciidoc
(a smaller, less-picky set of changes than I proposed for tp34; for notes, please see the set I proposed for tp34)
=> tp33 Getting Started, Minutes 6-30

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/OptionalStep.java, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java
https://issues.apache.org/jira/browse/TINKERPOP-1619
VOTE +1
=> TINKERPOP-1619 Fix optional() with TinkerGraphComputer

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
Refer:
https://issues.apache.org/jira/browse/TINKERPOP-2257?filter=-2
=> Fix itty.hasNext() and commit invoking disordering

CHANGELOG.asciidoc, docs/src/upgrade/release-3.3.x.asciidoc, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/DefaultTraversal.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/ITraversal.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/TraversalTests.cs, gremlin-javascript/glv/TraversalSource.template, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/traversal-test.js
https://issues.apache.org/jira/browse/TINKERPOP-1921
Python was done a long time ago, but I never returned to deal with Javascript and .NET  - so, that's done now. Gremlin Language Variants gain a bit more consistency as a result of this change. Happy to hear other takes on how to do this nicer (i don't particularly like what I did with .NET). Perhaps I'll see it differently tomorrow and make some adjustments.
VOTE +1
=> TINKERPOP-1921 Added hasNext() to javascript and .NET

tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphIterator.java
Minor change.
**Motivation**
Follow up of discussion in #1144
=> Make TinkerGraphIterator implement Closeable iterator

docs/site/home/index.html
L: 276 - added `github.com/northwesternmutual/grammes` in list of language drivers.
=> Include Grammes in language drivers

CHANGELOG.asciidoc, gremlin-archetype/gremlin-archetype-dsl/src/main/resources/archetype-resources/src/main/java/SocialTraversalSourceDsl.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/GremlinDslProcessor.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/GremlinDslProcessorTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/SocialPackageTraversalSourceDsl.java, gremlin-core/src/test/resources/org/apache/tinkerpop/gremlin/process/traversal/dsl/RemoteDslTraversal.java, gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/dsl/credential/CredentialTraversalSourceDsl.java
https://issues.apache.org/jira/browse/TINKERPOP-2276
=> Generate constructor to use DSL with remote connection

gremlin-driver/pom.xml, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Host.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/HostTest.java, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2289
=> TINKERPOP-2289 Use ip address instead of hostname for connection

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
and prevent the program from exiting whenever the db disconnects
=> TINKERPOP-2290 Add a way to catch a connection error

CHANGELOG.asciidoc, docs/src/upgrade/release-3.5.x.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraversalVertexProgram.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/decoration/VertexProgramStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/optimization/MessagePassingReductionStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/traversal/strategy/decoration/RemoteStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bytecode.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/RequirementsStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SackStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SideEffectStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/finalization/ProfileStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IncidentToAdjacentStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/InlineFilterStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategy.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalStrategies.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/EmptyTraversalStrategies.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalExplanation.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/InlineFilterStrategyTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/ComplexTest.java, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/TranslationStrategy.java, sparql-gremlin/src/main/java/org/apache/tinkerpop/gremlin/sparql/process/traversal/strategy/SparqlStrategy.java, tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/optimization/TinkerGraphCountStrategy.java
https://issues.apache.org/jira/browse/TINKERPOP-1568
Please refer to the JIRA issue for details as well as the Upgrade Docs on this PR for more information about this one. I'm generally happy with how few changes were actually involved in making this happen - if you take away my light refactoring for inclusion of the `IsRoot()` method very few files had to really change and for the most part the changes themselves were fairly straightforward. It didn't always look this way - took a fair amount of effort to get to the root of why certain changes were necessary to then refactor for greater simplicity. 
I think the only thing I wasn't really able to sort out "nicely" was `MessagePassingReductionStrategy`. It seems to need to know a lot about `profile()` for some reason and I wasn't quite …
=> TINKERPOP-1568 Changed Strategy Application Methodology

CHANGELOG.asciidoc, gremlin-driver/pom.xml, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Host.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/HostTest.java
See:
1.  [User list](https://groups.google.com/d/msg/gremlin-users/A9rr9jLh5AY/DLguF9QmAQAJ)
2. [Dev list](https://lists.apache.org/thread.html/5a606bb428941faaac5c41c4df1526351406ec1ca90574dc9ced7fcd@%3Cdev.tinkerpop.apache.org%3E)
`mvn clean install`  success.
=> Reverts TINKERPOP-2289 resolve ip address

sparql-gremlin/src/main/java/org/apache/tinkerpop/gremlin/sparql/SparqlToGremlinCompiler.java, sparql-gremlin/src/main/java/org/apache/tinkerpop/gremlin/sparql/WhereTraversalBuilder.java
I modified only the class "WhereTrafersalBuilder" and some row in SparqlToGremlinCompiler in respect to the branch master.
Please note that my optimization tecnique involves looking into all source triples for creating a more concise one. For this reason it has to be evaluated if this kind of optimization has to be done in this classes (where formally you have to translate the single triple in the single traversal step) or in the SparqlTraversalStrategy that optimize the whole traversal.
=> TINKERPOP-2325 - Modifications for use of indexes in FILTER

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/graph.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/type-serializers.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/structure-types-test.js
Fix 2 issues detailed in:
- https://issues.apache.org/jira/browse/TINKERPOP-2332
- https://issues.apache.org/jira/browse/TINKERPOP-2333
VOTE +1.
=> TINKERPOP-2332 JavaScript GLV: Fix structure toString() methods

gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/JsonMessageSerializerTests.cs
fix null reference for https://issues.apache.org/jira/browse/TINKERPOP-2192
=> fix for https://issues.apache.org/jira/browse/TINKERPOP-2192

CHANGELOG.asciidoc, gremlin-groovy/pom.xml, gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/ast/InterpreterModeASTTransformation.groovy, gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTest.java, gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/util/DependencyGrabberIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2373
pretty straightforward..........
VOTE +1
=> Bump to Groovy 3.0

gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Bytecode.cs
https://issues.apache.org/jira/browse/TINKERPOP-2377
I think this addresses the issue.
=> TINKERPOP-2377 .NET GLV: Check for null earlier

gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/dsl/credential/CredentialGraphTokens.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpBasicAuthenticationHandler.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAndHttpBasicAuthenticationHandler.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/AbstractGremlinServerChannelizerIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2374
=> TINKERPOP-2374 fix missing authorization with SaslAndHttpBasicAuthenticationHandler

CHANGELOG.asciidoc, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/translator.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/translator-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2403
All tests pass with `mvn clean install`
VOTE +1
=> TINKERPOP-2403 Fixed bug in child tranversal translation for js

gremlin-test/features/map/Select.feature, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectTest.java, pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2412
VOTE +1
=> TINKERPOP-2412 Added tests to trigger labelled path requirements

CHANGELOG.asciidoc, docs/src/reference/gremlin-variants.asciidoc, gremlin-python/glv/GraphTraversalSource.template, gremlin-python/glv/generate.groovy, gremlin-python/src/main/jython/gremlin_python/driver/client.py, gremlin-python/src/main/jython/gremlin_python/driver/driver_remote_connection.py, gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py, gremlin-python/src/main/jython/gremlin_python/process/strategies.py, gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py, gremlin-python/src/main/jython/tests/process/test_strategies.py
https://issues.apache.org/jira/browse/TINKERPOP-2296
VOTE +1
=> TINKERPOP-2296 support per-request options in python

CHANGELOG.asciidoc, gremlin-javascript/glv/TraversalSource.template, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/bytecode.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/bytecode-test.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/translator-test.js
Traversal class now contains toJSON() method which causes JSON.stringify() to properly serialize the Traversal object. Unit tests for bytecode serialization are also included
=> TINKERPOP-2432 + TINKERPOP-2439: fix bytecode toString() and fix P and TextP toString()

docs/src/recipes/looping.asciidoc
My fork was all messed up so I had to redo this pull request from a clean fork.
=> TINKERPOP-2446 - Added recipe to show how to do optional looping

CHANGELOG.asciidoc, docs/src/upgrade/release-3.5.x.asciidoc, gremlin-driver/pom.xml, gremlin-tools/gremlin-io-test/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2460
All tests pass with `docker/build.sh -t  -i`
VOTE +1
=> TINKERPOP-2460 Made groovy provided scope for gremlin-driver

CHANGELOG.asciidoc, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2409
A replacement for #1362 that includes a test for the behavior we want to see.
VOTE +1
=> TINKERPOP-2409 Better error handling for socketError

gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2468
The test failed intermittently because it expects the results to be returned in same order in which they were sent to the server. However, sessions guarantee that the requests would be executed "in-order" on the server but they don't guarantee that the results would be returned in order as well because the results are handled by different executor threads completing different futures.
I fixed the test to not rely on order of the result but still check for order on the server.
=> TINKERPOP-2468 Fix stochastic nature of shouldProcessSessionRequestsInOrder

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeGlobalStep.java
https://issues.apache.org/jira/browse/TINKERPOP-2490
In FilterStep, the processNextStart() method will first retrieve next traverser and then apply filtering logic. But for RangleGlobalStep, if high limit is already hit, there will be no need to get next traverser.
e.g. g.V().limit(1). This query will touch 2 vertices although only 1 vertex will be returned.
This PR added high limit check before retrieving next traverser for filtering. Functionality is not affected, but we can expect better performance if getting next traverser is heavy.
=> TINKERPOP-2490 RangeGlobalStep check high limit before retrieve next traverser

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/SettingsTest.java, gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/custom-gremlin-server.yaml
Dev list link: https://lists.apache.org/thread.html/r653bc515171e6ad8473aa592e74882f1841f21c2c79af4331c49ee0a%40%3Cdev.tinkerpop.apache.org%3E
Signed-off-by: jan.jansen <jan.jansen@gdata.de>
=> Make server setings extensible

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/translator.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/translator-test.js
=> translate - fix for multiple embedded traversals;

CHANGELOG.asciidoc, docs/src/dev/developer/contributing.asciidoc, docs/src/dev/developer/development-environment.asciidoc, docs/src/dev/developer/for-committers.asciidoc, docs/src/recipes/anti-patterns.asciidoc, docs/src/recipes/looping.asciidoc, docs/src/recipes/recommendation.asciidoc, docs/src/recipes/traversal-induced-values.asciidoc, docs/src/reference/the-traversal.asciidoc, docs/src/upgrade/release-3.5.x.asciidoc, gremlin-language/pom.xml, gremlin-language/src/main/antlr4/Gremlin.g4, gremlin-language/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/AbstractGrammarTest.java, gremlin-language/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/BasicGrammarTest.java, gremlin-language/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/DocumentationReader.java, gremlin-language/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/FeatureReader.java, gremlin-language/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/GremlinErrorListener.java, gremlin-language/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/NegativeGrammarTest.java, gremlin-language/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/ReferenceGrammarTest.java, gremlin-language/src/test/resources/incorrect-traversals.txt, neo4j-gremlin/pom.xml, pom.xml, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2533
This module is currently standalone, meaning it depends on no other TinkerPop modules nor does any module depend on it. It represents an initial body of work which has reasonable coverage of Gremlin and a expansive and flexible test suite.
VOTE +1
=> TINKERPOP-2533 Added gremlin-language module.

docker/scripts/build.sh, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuditLogDeprecatedIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuditLogIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthKrb5IntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/TestClientFactory.java
A WIP PR is the only way to have the changes tested on travis
=> Tinkerpop 2504 WIP: Intermittently failing server/driver integration tests, gremlin-server part

CHANGELOG.asciidoc, gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs, gremlin-dotnet/src/Gremlin.Net/Driver/Tokens.cs
https://issues.apache.org/jira/browse/TINKERPOP-2559
I'm creating the PR already as it was such a trivial change but given that we're in a code freeze, this has to wait for the 3.5.0 release.
VOTE +1
=> TINKERPOP-2559 Gremlin.NET: Stop sending session close message

CHANGELOG.asciidoc, gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/DataType.cs, gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/GraphBinaryMessageSerializer.cs, gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/GraphBinaryReader.cs, gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/GraphBinaryWriter.cs, gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/TypeSerializerRegistry.cs, gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphBinary/Types/CustomTypeSerializer.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphBinary/Types/Sample/SamplePerson.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphBinary/Types/Sample/SamplePersonSerializer.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphBinary/Types/Sample/SamplePersonSerializerTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2570
VOTE +1
=> TINKERPOP-2570 Support custom types in GraphBinary for .NET

CHANGELOG.asciidoc, docs/src/dev/developer/development-environment.asciidoc, docs/src/dev/developer/for-committers.asciidoc, docs/src/dev/developer/release.asciidoc, gremlin-javascript/pom.xml, gremlin-javascript/src/main/javascript/gremlin-javascript/package-lock.json, gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/traversal-test.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/client-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2659
Added some docs as well about runtime upgrades.
VOTE +1
=> TINKERPOP-2659 Bumped to node v16

CHANGELOG.asciidoc, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/translator.js, gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/translator-test.js
https://issues.apache.org/jira/browse/TINKERPOP-2658
VOTE +1
=> TINKERPOP-2658 Fixed array translation in gremlin-javascript

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalMetrics.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalMetricsTest.java, gremlin-dotnet/src/pom.xml, gremlin-javascript/pom.xml, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/features/StepDefinition.java, gremlin-tools/gremlin-io-test/pom.xml, gremlin-tools/gremlin-io-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/Model.java, gremlint/pom.xml, pom.xml
* when testing strings representing file contents cause the expected value to use system line-separators
* escape constructed literal strings representing file paths
=> TINKERPOP-2628 squashed

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js, gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/graph-serializer.js
The idea is to simply extract GraphSON related logic from connection class back to respective serializer implementation. As a result we get a generic “door” for different serializer implementations, e.g. GraphBinary.
As [suggested](https://github.com/apache/tinkerpop/pull/1547#discussion_r784821882) by @divijvaidya.
=> gremlin-javascript: Tune Writer/Reader abstraction border

gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Lambda.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/StringBasedLambda.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/CommonSteps.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/IgnoreException.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/ScenarioData.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Remote/RemoteStrategyTests.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/BytecodeGeneration/StrategiesTests.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/StrategiesTests.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/TestTraversal.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/TestTraversalStrategy.cs, gremlin-server/src/test/scripts/generate-all.groovy, gremlin-server/src/test/scripts/tinkergraph-empty.properties, tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerFactory.java
https://issues.apache.org/jira/browse/TINKERPOP-2688
https://issues.apache.org/jira/browse/TINKERPOP-2689
=> Fixing .NET test failures and adding Gherkin/.NET support for VertexProperty.

gremlin-python/src/main/python/gremlin_python/driver/client.py, gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py, gremlin-python/src/main/python/gremlin_python/driver/protocol.py, gremlin-python/src/main/python/gremlin_python/process/graph_traversal.py
Added logger object "gremlinpython" wherever logging is used in order to adhere to python logging best practices.
Otherwise the logs are recorded in the root logger object which is not practical, as the logs cannot be distinguished.
=> Python logging under a separate logger "gremlinpython"

gremlin-python/src/main/python/gremlin_python/process/strategies.py
https://issues.apache.org/jira/browse/TINKERPOP-2725
Description of changes:
Traversal Strategy Mix Up In Gremlin-Python
=> TINKERPOP-2725 Traversal Strategy Mix Up In Gremlin-Python

gremlin-python/src/main/python/gremlin_python/driver/client.py
Propagating to master - having some CLI login issues right now so doing this through GitHub instead.
**https://github.com/apache/tinkerpop/pull/1587**
=> submitAsync fix for gremlin-python on tinkerpop/master

CHANGELOG.asciidoc, docs/src/index.asciidoc, docs/src/reference/the-traversal.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/DefaultGremlinBaseVisitor.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/GenericLiteralVisitor.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/StructureElementVisitor.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalMethodVisitor.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalPredicateVisitor.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceSelfMethodVisitor.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalSourceSpawnMethodVisitor.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/grammar/TraversalStrategyVisitor.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/GeneralLiteralVisitorTest.java, gremlin-language/src/main/antlr4/Gremlin.g4, gremlin-language/src/main/java/org/apache/tinkerpop/gremlin/language/corpus/DocumentationReader.java, gremlin-language/src/test/java/org/apache/tinkerpop/gremlin/language/grammar/ReferenceGrammarTest.java
Here is an initial PR containing the suggested documentation for `mergeV` and `mergeE`. Given the power, and likely rapid uptake, of these new steps, I have tried to do a fairly detailed coverage. To make the examples a little more fresh, I chose to show adding dogs to the graph and diverge from just showing yet another way to create the "Toy graph".  If people decide that they don't like this approach we can fall back to adding the toy graph.  I just get a lot of comments from users asking why all the examples in our docs use the same graph and felt that a slightly different data set made sense to demonstrate the power of these new steps. 
Not looking for a VOTE right away. Let's discuss and make any changes first.
=> Initial upload of docs for mergeE and mergeV

CHANGELOG.asciidoc, docs/src/reference/the-traversal.asciidoc, docs/src/upgrade/release-3.5.x.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/WithOptions.java, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/EnumWrapper.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Translator/GroovyTranslator.cs, gremlin-dotnet/src/Gremlin.Net/Process/Traversal/WithOptions.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/Translator/GroovyTranslatorTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2367
I still need to generate the docs to inspect the changes, but I think this is ready for review already.
=> TINKERPOP-2367 Add a GroovyTranslator to .NET

CHANGELOG.asciidoc, docs/src/upgrade/release-3.5.x.asciidoc
Upgrade docs for @ihoro 's #1547
=> Upgrade docs for gremlin-javascript GraphBinary support

gremlin-python/src/main/python/gremlin_python/driver/client.py, gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py, gremlin-python/src/main/python/gremlin_python/driver/serializer.py, gremlin-python/src/main/python/gremlin_python/statics.py, gremlin-python/src/main/python/gremlin_python/structure/io/graphbinaryV1.py, gremlin-python/src/main/python/tests/driver/test_client.py, gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py, gremlin-python/src/main/python/tests/structure/io/test_functionalityio.py, gremlin-python/src/main/python/tests/structure/io/test_graphbinaryV1.py
Finish graphbinary support in gremlin-python
https://issues.apache.org/jira/browse/TINKERPOP-2693
=> TINKERPOP-2693 Finish graphbinary support in gremlin-python

gremlin-console/pom.xml, pom.xml
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2746
=> Bump logback version to 1.2.9 or greater

pom.xml
Fixes https://issues.apache.org/jira/browse/TINKERPOP-2748
=> TINKERPOP-2748: Bump netty version to 4.1.77.Final

pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2746
updated logback to latest 1.2.11
=> [TINKERPOP-2746] updated logback to 1.2.11

CHANGELOG.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
Potentially fixes https://issues.apache.org/jira/browse/TINKERPOP-2734
Could not reproduce the issue without given reproduction steps, and also seems that it would require specific server circumstance.
However, investigation of the log traces the reporter included in the ticket gives clues of where to look, and a potential but unlikely NPE was logically deduced. Unsure if this will fix this specific user's problem but worth fixing regardless.
As a side effect, also reduces an unneeded coupling due to inheritance on the Client type.
=> TINKERPOP-2734 Fix potential SessionedClient NPE

gremlin-go/driver/graphBinary_test.go, gremlin-go/driver/serializer.go
Cherry picked the fix & resolved conflicts for 3.6-dev.
=> gremlin-go: fix data race - cherry-pick PR#1744 fix for 3.6-dev

docs/src/dev/developer/development-environment.asciidoc
Updated link to the repository with latest winutils build, and added system info as reference.
=> Minor update to Windows build instruction

.github/workflows/build-test.yml, README.asciidoc, pom.xml
Fixes coverage report generation and adds CodeCov reporting with a badge on the main README
=> Adding CodeCov to Java Modules

docs/src/dev/future/index.asciidoc, docs/src/dev/future/proposal-arrow-flight-2.asciidoc
Added proposal document for Arrow Flight usage
=> Gremlin Arrow Flight Proposal

CHANGELOG.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/NoOpWebSocketServerHandler.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/TestHttpServerInitializer.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/TestWSNoOpInitializer.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java
Same as PR#1833 but with changes for 3.6-dev.
=> TINKERPOP-2814 Remove default SSL handshake timeout for 3.6-dev.

CHANGELOG.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/WebSocketClientBehaviorIntegrateTest.java, gremlin-tools/gremlin-socket-server/src/main/java/org/apache/tinkerpop/gremlin/driver/NoOpWebSocketServerHandler.java, gremlin-tools/gremlin-socket-server/src/main/java/org/apache/tinkerpop/gremlin/driver/TestHttpServerInitializer.java, gremlin-tools/gremlin-socket-server/src/main/java/org/apache/tinkerpop/gremlin/driver/TestWSNoOpInitializer.java
Same PR as https://github.com/apache/tinkerpop/pull/1833 but targeted for master.
=> TINKERPOP-2814 Remove default SSL handshake timeout for master branch.

README.asciidoc
Just a small update that I saw some other projects doing and I thought was cool.
=> Adds badges to README linking to GLV repository pages

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/utils.js
This PR aims to handle null and undefined values properly in `generateUserAgent()`
=> patch: Fixing generateUserAgent() to handle null and undefined properly

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategy.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategyTest.java
https://issues.apache.org/jira/browse/TINKERPOP-2865
```text
gremlin> gB.V().out().hasLabel("person").has('name','stephen').explain()
==>Traversal Explanation
=================================================================================================================================================================================
Original Traversal                    [GraphStep(vertex,[]), VertexStep(OUT,vertex), HasStep([~label.eq(person), name.eq(stephen)])]
ConnectiveStrategy              [D]   [GraphStep(vertex,[]), VertexStep(OUT,vertex), HasStep([~label.eq(person), name.eq(stephen)])]
PartitionStrategy               [D]   [GraphStep(vertex,[]), HasStep([_partition.within([b])]), VertexStep(OUT,vertex), HasStep([~label.eq(person), name.eq(stephen)]), HasStep([ …
```
=> TINKERPOP-2865 Inject partition steps after last has in chain

docs/src/dev/future/index.asciidoc, docs/src/dev/future/proposal-3-remove-closures.asciidoc
Proposal to remove the need for closures by adding the most commonly requested functions as new Gremlin steps
=> Proposal 3 - Replace Closures with String/List/Date functions

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/Gremlin.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/UserAgent.java
A concern was raised over the possibility of an Error being thrown during the initialization of the UserAgent class resulting in the class to fail to load and giving users an obscure NoClassDefFoundError. I'm upgrading the existing catch(Exception)'s to catch(Throwable)'s to catch these potential Error's and ensure that the user agent class will always load correctly. Any missing data due to caught errors will be replaced with a default value of "NotAvailable"
Missing data in the user agent on rare occasions is a small concern and preferable to the driver crashing altogether.
=> Updates Java UserAgent Error Handling

CHANGELOG.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java, gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/FileSandboxExtension.groovy, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/authz/AllowList.java, pom.xml
Resolve https://issues.apache.org/jira/browse/TINKERPOP-2902
=> TINKERPOP-2902 bump snakeyaml to 2.0 and commons-configuration to 2.9.0

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PropertyMapStep.java
Make all private fields and methods as protected to be able to overwrite some of it's functionality. This allows to overwrite some functionality for optimization purposes.
https://issues.apache.org/jira/browse/TINKERPOP-2924
=> [TINKERPOP-2924] Refactor PropertyMapStep for overwrite functionality possibilities

CHANGELOG.asciidoc, gremlin-python/src/main/python/gremlin_python/driver/client.py, gremlin-python/src/main/python/gremlin_python/driver/driver_remote_connection.py, gremlin-python/src/main/python/gremlin_python/process/graph_traversal.py, gremlin-python/src/main/python/tests/driver/test_client.py, gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
Python Client did not close the connection when using session.
https://issues.apache.org/jira/browse/TINKERPOP-2820
=> [TINKERPOP-2820] Fixed connection closing for sessioned client in gremlin-python

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MergeEdgeStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MergeStep.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MergeVertexStep.java
Checking for illegal hidden keys.
Refactoring searchVertices to allow subclasses to override search criteria.
https://issues.apache.org/jira/browse/TINKERPOP-2931
=> Fixing a couple mergeV/E issues.

gremlin-python/src/main/python/gremlin_python/process/translator.py, gremlin-python/src/main/python/tests/process/test_translator.py
This MR improves the python `Translator` class in a few ways:
- handle `TextP` predicates in addition to `P`
- handle quoting for subclasses of `str`
- handle `None` -> `null`
Tests have been added to verify the changes.
=> (new) (gremlin-python) improve translation

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSslIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/TestClientFactory.java
Support SSL connection in WebSocketClient
=> [TINKERPOP-2955] Support SSL in WebSocketClient

CHANGELOG.asciidoc, docs/src/upgrade/release-3.7.x.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Compare.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Contains.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/P.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/PBiPredicate.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Text.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TextP.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/AndP.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/OrP.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java, gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/util/ser/GraphSONMessageSerializerV3RoundTripTest.java, neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/traversal/LabelP.java
Introduced `PBiPredicate` interface to reduce serialization issues like [INKERPOP-2945](https://issues.apache.org/jira/browse/TINKERPOP-2945)
JIRA https://issues.apache.org/jira/browse/TINKERPOP-2949
=> [TINKERPOP-2949] added PBiPredicate interface

docs/src/reference/implementations-tinkergraph.asciidoc, docs/src/upgrade/release-3.7.x.asciidoc, gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/TransactionMultiThreadedTest.java, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerTransactionGraphTest.java
Adds some extra testing to ensure read committed isolation level holds in more cases. And some small updates to the documentation in that area.
=> Add extra testing around transaction isolation levels.

CHANGELOG.asciidoc, gremlin-go/driver/error_codes.go, gremlin-go/driver/graphBinary.go, gremlin-go/driver/resources/error-messages/en.json, gremlin-go/driver/serializer.go, gremlin-go/driver/serializer_test.go
JIRA: https://issues.apache.org/jira/browse/TINKERPOP-2802
Working implementation for custom deserializers.
=> TINKERPOP-2802: Add support for custom deserializers

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
=> Fix a javadoc comment in GraphTraversal.not method

gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/DriverRemoteConnectionTests.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientTests.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/MockedLoggerExtensions.cs, gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj, gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/ConnectionPoolTests.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/ConnectionTests.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/DriverRemoteConnectionTests.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Gremlin.Net.UnitTest.csproj, gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Remote/RemoteTransactionTests.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONReaderTests.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONWriterTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-2984
=> TINKERPOP-2984 Replace Moq with NSubstitute

gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/GremlinGroovysh.groovy, gremlin-console/src/test/groovy/org/apache/tinkerpop/gremlin/console/GremlinGroovyshTest.groovy, gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/jsr223/AbstractGremlinServerIntegrationTest.java
https://issues.apache.org/jira/browse/TINKERPOP-3013
VOTE +1
=> TINKERPOP-3013 Add handling for missing property in remote console

bin/run-examples.sh, docs/src/dev/developer/release.asciidoc, gremlin-javascript/examples/package-lock.json, gremlin-javascript/examples/package.json
Moves release note from pre-flight to post-release to allow for latest image to be released before use in run-examples.sh.
=> Minor update to GLV examples

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/GraphOp.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/DotNetTranslator.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GolangTranslator.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslator.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/JavascriptTranslator.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/translator/PythonTranslator.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/BytecodeHelper.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Transaction.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/DotNetTranslatorTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GolangTranslatorTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/GroovyTranslatorTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/JavascriptTranslatorTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/translator/PythonTranslatorTest.java
https://issues.apache.org/jira/browse/TINKERPOP-3031
VOTE +1
=> TINKERPOP-3031 Fixed bug in translation of g.tx() options

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/LoadBalancingStrategy.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestOptions.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultSet.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpGremlinRequestEncoder.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/AbstractClient.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/SimpleClient.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/SimpleHttpClient.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ResultSetTest.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpHandlerUtil.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/driver/ClientConnectionIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSslIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/TestClientFactory.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/handler/HttpHandlerUtilTest.java, gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/message/RequestMessageV4.java
=> Minimal changes to get gremlin-driver working with integration tests

CHANGELOG.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/AbstractClient.java, gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/sasl-authentication-tests.js, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAuthenticationHandler.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/StateKey.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java
This PR is to fix minor PR nits from https://github.com/apache/tinkerpop/pull/2525 so that it can be included in the 3.7.2 release.
=> Parallel Authentication Fix

gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs, gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/Translator/GroovyTranslatorTests.cs
https://issues.apache.org/jira/browse/TINKERPOP-3035
VOTE +1
=> TINKERPOP-3035 Add Property(IDictionary) overload

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/util/ProfilingApplication.java
Updates the internal ProfilingApplication to include a latency test. Some defaults were changed to match the current defaults in the driver.
=> Add latency test to ProfilingApplication

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpContentDecompressionHandler.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpGremlinRequestEncoder.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/SimpleHttpClient.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/handler/HttpContentDecompressionHandlerTest.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/HttpChannelizer.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpContentCompressionHandler.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpRequestMessageDecoder.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/StateKey.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/handler/HttpContentCompressionHandlerTest.java
Currently only supports deflate/zlib.
=> Add support for HTTP content compression.

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/language/translator/GroovyTranslateVisitor.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/GremlinLang.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/language/translator/GremlinTranslatorTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/GremlinLangTest.java
- Added Set handling to GremlinLang.
- Updated Groovy translator and tests.
=> Added Set handling to GremlinLang

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/RepeatStep.java
=> Adding a public getter for Repeat Loop Name

CHANGELOG.asciidoc, tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/AbstractTinkerGraph.java, tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/IdManagerTest.java
Add an IdManager that creates stringified UUIDs and accepts any non-empty string
=> Add String IdManager

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Bytecode.java, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/BytecodeHelper.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/BytecodeTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/BytecodeHelperTest.java
JIRA: https://issues.apache.org/jira/browse/TINKERPOP-3110
=> [TINKERPOP-3110] Fix Bytecode build logic for strategies

docs/src/dev/io/graphbinary.asciidoc, docs/src/dev/io/graphson.asciidoc, docs/src/upgrade/release-4.x.x.asciidoc
Based on https://lists.apache.org/thread/q7h5yzd2r064lv82njbmt6lmty4s24y7
=> Update IO documentation to V4 serializers.

CHANGELOG.asciidoc, docs/src/upgrade/release-4.x.x.asciidoc, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/HttpRequest.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestInterceptor.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/auth/Auth.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/auth/Basic.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/auth/Sigv4.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/HttpGremlinRequestEncoder.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/interceptor/GraphBinarySerializationInterceptor.java, gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/SimpleHttpClient.java, gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ClusterTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java, gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java
The interceptor is updated to run for every request to allow modifying each HTTP request. It works on a newly created abstraction of a request called HttpRequest to prevent breaking changes in the event the underlying library ever changes.
=> Update RequestInterceptor to better work with HTTP.

gremlin-dotnet/src/.config/dotnet-tools.json, gremlin-dotnet/src/.gitignore, gremlin-dotnet/src/docfx.json, gremlin-dotnet/src/pom.xml
https://issues.apache.org/jira/browse/TINKERPOP-2085
Removes dependency on Mono for docfx
=> TINKERPOP-2085 Remove dependency on mono for docfx

gremlin-python/src/main/python/gremlin_python/driver/serializer.py, gremlin-python/src/main/python/gremlin_python/structure/io/graphsonV4.py, gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py
Enables connecting to TP4 server with GraphSONV4 for testing purposes. 
This PR enables basic connectivity. The remaining type changes introduced in GraphSONV4 will be included in subsequent PRs.
=> Enable basic graphSONV4 in python driver for testing purposes

gremlin-python/docker-compose.yml, gremlin-python/src/main/python/gremlin_python/driver/serializer.py, gremlin-python/src/main/python/gremlin_python/statics.py, gremlin-python/src/main/python/gremlin_python/structure/io/graphbinaryV4.py, gremlin-python/src/main/python/gremlin_python/structure/io/graphsonV4.py, gremlin-python/src/main/python/tests/driver/test_driver_remote_connection.py, gremlin-python/src/main/python/tests/structure/io/model.py, gremlin-python/src/main/python/tests/structure/io/test_graphbinaryV4.py, gremlin-python/src/main/python/tests/structure/io/test_graphsonV4.py, gremlin-python/src/main/python/tests/structure/io/test_graphsonv4model.py
Update GraphSONV4 in Python for elements and datetime according to format specified in https://github.com/apache/tinkerpop/blob/master-http/docs/src/dev/io/graphson.asciidoc
VOTE +1
=> Update GraphSONV4 extended types, element, and datetime in gremlin-python

README.asciidoc, docs/src/reference/gremlin-applications.asciidoc, docs/src/reference/implementations-hadoop-start.asciidoc, docs/src/reference/intro.asciidoc, docs/src/tutorials/getting-started/index.asciidoc, gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/Gremlin.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/jsr223/ImportGremlinPluginTest.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/util/GremlinTest.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
Updated gremlin console ASCII art to show version 4 instead of 3.
=> Update gremlin console to display version 4

gremlin-test/pom.xml, hadoop-gremlin/pom.xml, pom.xml, spark-gremlin/pom.xml
Just a version bump for spark/hadoop to use latest versions.  Might have done CTR but holding for code freeze.
VOTE +1
=> Bump spark/hadoop to latest versions.

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpRequestMessageDecoder.java, gremlin-util/src/main/java/org/apache/tinkerpop/gremlin/util/ser/GraphBinaryMessageSerializerV4.java
Revert changes to gremlin-server and gremlin-util that were added for local testing.
=> Revert changes to gremlin-server and gremlin-util

docs/src/dev/future/index.asciidoc, docs/src/dev/future/proposal-asbool-step-7.asciidoc
As another addition to the existing set of conversion steps (i.e. `asString()`, `asDate()`), this proposal aims to define a new `asBool()` step for Boolean parsing.
VOTE +1
=> Proposal for asBool() Step

CHANGELOG.asciidoc, gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/CallStep.java, gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/CallStepTest.java
Fixed serialization of `CallStep`.
https://issues.apache.org/jira/browse/TINKERPOP-3163
=> TINKERPOP-3163 fixed CallStep serialization

CHANGELOG.asciidoc, docs/src/reference/gremlin-applications.asciidoc, docs/src/upgrade/release-3.8.x.asciidoc, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/UnifiedChannelizer.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractSession.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/MultiTaskSession.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SessionException.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SessionTask.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SingleTaskSession.java, gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/UnifiedHandler.java
https://issues.apache.org/jira/browse/TINKERPOP-3168
VOTE +1
=> TINKERPOP-3168 Deprecated UnifiedChannelizer
