gremlin-core/src/main/java/com/tinkerpop/gremlin/process/graph/traversal/strategy/RangeByIsCountStrategy.java
gremlin-test/src/main/java/com/tinkerpop/gremlin/process/graph/traversal/strategy/RangeByIsCountStrategyTest.java

added support for ```Contains.within``` and ```Contains.without``` in ```RangeByIsCountStrategy```
Fixes tinkerpop/tinkerpop3#559

added support for Contains.within and Contains.without

---

docs/src/the-traversal.asciidoc

Removed/Replaced almost all of the remaining lambda samples from the docs. The only lambdas left now are those in ```.map()```,  ```.filter()```, etc..
Moreover ```.fold()``` and  ```.sack()``` doesn't seem to make much sense without lambdas.

lambda cleanup

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/ElementTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/__.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/step/filter/HasTraversalStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/graph/traversal/step/filter/GroovyHasNotTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/step/filter/HasNotTest.java

Only minor changes were necessary to have `.hasNot(traversal)` working. Merge if you like it.

added `.hasNot(traversal)`

---

hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/graphson/GraphSONRecordReader.java
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/script/ScriptRecordReader.java

* local bindings for `ScriptInputFormat`
* no more `new VertexWritable()` for each vertex

optimized ScriptInputFormat and GraphSONInputFormat

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/graph/traversal/step/Mutating.java
pom.xml

Adds an `<executions>` section to the RAT plugin configuration so any
build verifies the release for licenses
Fixes the one missing license header found by RAT

Enable RAT plugin on builds

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/util/TraverserSet.java

A JMH microbenchmark on a TP3 traversal that hit thousands of vertices showed the use of exceptions for flow control in `TraverserSet` as a hotspot.  Using `FastNoSuchElementException` dramatically improved the performance of the benchmark.
Thanks to @danielthomas for identifying the root issue and providing an initial patch.

Use FastNoSuchElementException on TraverserSet.remove()

---

gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java

Fixes [TINKERPOP3-600](https://issues.apache.org/jira/browse/TINKERPOP3-600).

Fixes TINKERPOP3-600: invoke{Function|Method} should be varargs

---

gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineOverGraphTest.java

TINKERPOP3-629
Removed user defined IDs as they do not add to the test and prevent graphs that do not support them from running it.

Remove user defined IDs from vertices.

---

tinkergraph-gremlin/pom.xml

Not every use of Tinkergraph is Groovy based.

Make gremlin-groovy a provided dependency of tinkergraph-gremlin

---

docs/src/the-traversal.asciidoc

Also adds doc for `limit(local)` and `range(local)`, since they are related.
BTW, the documentation tool chain is really nice!  I like being able to write Groovy samples and have them executed during preprocessing.

TINKERPOP3-670 tail step doc

---

gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/groovy/plugin/gremlin-server-integration.yaml
gremlin-driver/pom.xml
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerGremlinV1d0Test.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV1d0Test.java

Removed org.json dependency in pom.xml, made appropriate code adjustments for Jackson, and also made the Test class names consistent with GraphSONMessageSerializer.

TINKERPOP3-711 Use Jackson in JsonMessageSerializerV1d0Test.java

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Path.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ImmutablePath.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ImmutablePathImpl.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/MutablePath.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/PathTest.java

As requested in the comments of TINKERPOP3-700.  I also reversed the sense of `Pop` to align with `tail(local)`.  Thus `Pop.tail` now means the most recent value.

TINKERPOP3-700 Path getSingle/getList improvements

---

docs/src/the-traversal.asciidoc

Documentation update.
Additional 'has' step examples that show the usage of within and without in the has step.

TINKERPOP3-725: add additional 'has' step examples

---

gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovySelectTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectTest.java

Here are some tests that I think show the desired behavior.  They permute the various select signatures:
* no-labels, one-label, two-labels
* Scope
* Pop
However, a few of them fail now like so:
`The current step was compiled to an invalid local scope and this is a compilation error.`

TINKERPOP3-619: Add SelectTest cases for 'select should not throw'

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/ProfileTest.java

Remove some of the profile tests have been inconsistent on powerful multi-processor machines.

Remove inconsistent profile timer tests.

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/EdgeTest.java

I'm not supporting property deletes yet in my TP implementation, and this test requires that feature. Thus, indicate it with the FeatureRequirement annotation.

trivial patch to add extra feature requirement on EdgeTest.shouldGetPropertyKeysOnEdge()

---

tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerIoRegistry.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphSerializerTest.java

Let the tinker graph serializer reuse an existing kryo instance instead of creating a new one.
Tests assert that the same kryo instance is being used inside the Gryo reader/writer classes.
https://groups.google.com/forum/#!topic/gremlin-users/apFfQW3DkK4

Changed TinkerGraphSerializer to reuse existing Kryo instance

---

tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/TinkerGraphProvider.java

… as needed for persistence testing
https://issues.apache.org/jira/browse/TINKERPOP3-867

TINKERPOP3-867: TinkerGraphProvider.getBaseConfiguration creates temp dir

---

CHANGELOG.asciidoc
docs/preprocessor/preprocess-file.sh
docs/src/the-graphcomputer.asciidoc
gremlin-console/conf/neo4j-standalone.properties
gremlin-console/conf/tinkergraph-gryo.properties
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoaderVertexProgram.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoaderVertexProgramTest.java
hadoop-gremlin/conf/hadoop-grateful-gryo.properties
tinkergraph-gremlin/pom.xml

`BulkLoaderVertexProgram` now supports
* several inputs (`HadoopGraph` with all its supported `InputFormat`s and any TinkerPop3 enabled graph, like TinkerGraph or Neo4j)
* any TinkerPop3 enabled graph, even if it only supports single threaded access
Samples are provided in the docs. Tests were added to ensure proper functionality of `BulkLoaderVertexProgram`s configuration options.

BulkLoaderVertexProgram for generalized batch loading across graphs

---

docs/src/the-traversal.asciidoc

Result from the Gremlin console for the added `match()`-step query:
```groovy
:> g.V().match(__.as('creators').out('created').has('name', 'lop').as('projects'),__.as('projects').in('created').has('age', 29).as('cocreators')).select('creators','cocreators').by('name')
==>{creators=marko, cocreators=marko}
==>{creators=josh, cocreators=marko}
==>{creators=peter, cocreators=marko}
```

Enhance match()-step and where()-step documentation

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/AndStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/ConnectiveStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/OrStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/WherePredicateStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/WhereTraversalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ConnectiveStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/AdjacentToIncidentStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RangeByIsCountStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/AndP.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/ConnectiveP.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/OrP.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStepTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ConnectiveStrategyTest.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/TinkerGraphNoStrategyComputerProvider.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/TinkerGraphNoStrategyProvider.java

https://issues.apache.org/jira/browse/TINKERPOP3-898
In logic, "conjunction" implies AND. The general term for both AND and OR is "connective."
* Renamed all `ConjunctionXXX` to `ConnectiveXXX`.
* This is a breaking change but very internal to TinkerPop steps and given that we are not exposing the "instruction set" paradigm yet, its best this happens now than later.
* I ran `mvn clean install` and everything built. This does NOT effect docs nor integration testing.
* I updated the `CHANGELOG.asciidoc`.
I VOTE +1 (binding).

TINKERPOP3-898: Rename ConjuctionP and ConjuctionStep to ConnectiveP and ConnectiveStep

---

docs/src/gremlin-applications.asciidoc
gremlin-driver/pom.xml
gremlin-server/pom.xml
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java

This patch checks if the the OS is linux and uses netty epoll based event loops which perform better than NIO based event loops.
More details at:
http://netty.io/wiki/native-transports.html
Not sure if you guys have already tried it out. I saw a reduced GC pressure using epoll.

Use Epoll based netty eventloop when possible

---

gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/AbstractResultQueueTest.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ResultQueueTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-905
Now that the test relies on a CountDownLatch to explicitly block until a specified number of items are in the queue, the test should not randomly fail if items are slow to get to that queue. 
If you've seen this test fail before please run the standard `mvn clean install` test suite a few times to see if there are problems.

TINKERPOP3-905 Harden time oriented tests in ResultQueueTest

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/LoopTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/RepeatStep.java

These getters are required for providers to access the state of the RepeatStep when optimizing it.

Getters for RepeatStep.emitTraversal / untilTraversal and LoopTraversal.maxLoops

---

gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

Add a test to validate that results of all sizes stream properly.
This is an amendment to 
https://issues.apache.org/jira/browse/TINKERPOP3-903 
which was already merged and closed.  As @rjbriody was describing the problem he was seeing, it would be cool if he could review this test to see if it is sufficient for covering the problems he had.  I'd like to have more tests in this area if he can think of holes in this one.  We can vote to merge once we get his :+1:

TINKERPOP3-903 - amend a test

---

tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerFactory.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/TinkerGraphProvider.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphIdManagerTest.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-926
Renamed the `public statics` to use the standard TinkerPop pattern of spelling out the full property name is capital case with new words (and or camel case) having a `_` split.

TINKERPOP3-926: Renamed TinkerGraph public statics to common pattern used for other statics.

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/TraversalComparator.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/ComputerVerificationStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyOrderTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderTest.java

@dkuppitz found a restrictive verification that has now been loosened up. I added the two examples that Kuppitz demonstrated that should be allowed but were not. In the process, I found a bug in how MapReduce comparators work and fixed it. 
I ran `mvn clean install`. I also did Spark integration testing and tested the known tests that this effects in Giraph.
When merged, I will updated CHANGELOG.
VOTE +1.

TINKERPOP3-918: ComputerVerificationStrategy is too restrictive

---

CHANGELOG.asciidoc
neo4j-gremlin/pom.xml
neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jHelper.java

https://issues.apache.org/jira/browse/TINKERPOP3-899
This has been implemented and tested with `-DincludeNeo4j`. Note the `<exclusions>` I had to do in `<scope>test</scope>` as Neo4j doesn't use enforcer-plugin and they have self conflicts. I picked the highest version number of the self-conflict as the version to use.
Again, tested with `mvn clean install -DincludeNeo4j`.
My VOTE is +1.

TINKERPOP3-899: Bump to the latest version of Neo4j.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStepTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-768
The previous implementation of MatchStep was not biased to patterns that start at the current vertex. In OLTP, this is good. In OLAP, this is really really really bad as you are incuring a massive overhead with inter process communication. Thus, optimization, in OLAP, will sort the patterns first by whether the traverser needs to leave the current object location and then by TraversalType and then by multiplicity of the pattern. In the process, I cleaned up a few things here and there in MatchStep.
Ran `mvn clean install` and all is good.
VOTE +1.

TINKERPOP3-768: MatchStep in OLAP should be smart about current vertex.

---

CHANGELOG.asciidoc
docs/src/implementations.asciidoc
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/LocalPropertyTest.java

When running in persistent context mode, the configuration for the Spark
Context is always inherited from the origin configuration. This can be
overridden for select properties using setLocalProperty. By enabling
this for SparkGraphComputer a user will be able to take advantage of the
FairScheduler system with spark or add custom Spark JobGroupIDs to jobs in the
same JVM.

TINKERPOP-911: Lets SparkGraphComputer Set ThreadLocal Properties

---

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java

increases scope of various OpProcessor implementation to make them more extensible. Added javadoc.
https://issues.apache.org/jira/browse/TINKERPOP3-931

TINKERPOP3-931 modified the scopes of OpProcessor

---

CHANGELOG.asciidoc
docs/src/gremlin-applications.asciidoc
docs/src/upgrade-release-3.1.x-incubating.asciidoc
gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/DriverRemoteAcceptor.java
gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/DriverRemoteAcceptorIntegrateTest.java
gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/DriverRemoteAcceptorTest.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java

https://issues.apache.org/jira/browse/TINKERPOP3-914
Added a "alias" option to :remote config that lets the user supply key/value pairs representing the aliases.  Included "show" and "reset" options as well.  Updated docs which generate nicely. 
Unit tests were added as well as integration tests so build/test should be:
```text
mvn clean install -DskipIntegrationTests=false -pl gremlin-console
```
Test manually after starting gremlin server with:
```text
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Connected - localhost/127.0.0.1:8182
gremlin> :> TinkerFactory.generateModern(graph)
==>null
gremlin> :> graph
==>tinkergraph[vertices:6 edges:6]
gremlin> :> g.V()
==>v[1]
==>v[2]
==>v[3]
==>v[4]
==>v[5]
==>v[6]
gremlin> :remote config alias x g
==>x=g …
```

TINKERPOP3-914 Gremlin Console :remote to Gremlin Server supports alias

---

gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/plugin/Artifact.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/plugin/ArtifactTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-953
Corrected bug in artifact.equal where a local variable was overriding a member variable with the same name.

TINKERPOP3-953 Artifact equality is not evaluating properly

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoMapper.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinResultSetIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-955
Note that this class had to be registered via reflection as it is a private class of HashMap. Added tests to validate that the change works with the code specified in the issue. 
Please review as it pertains to area of serialization that you are familiar with.  To test with gremlin-server you need to run the integration tests:
```text
mvn verify -pl gremlin-server -DskipIntegrationTests=false
```
VOTE: +1
btw, we _could_ postpone this to 3.1.1 if we wanted - i think. there is a workaround to the bug in that the person just doesn't have to `next()` the result to get it to serialize.

TINKERPOP3-955 Registered HashMap$Node to GryoMapper.

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphTest.java

GraphTests.shouldPersistDataOnClose checked that *edges* supported String type properties before adding String type properties to *vertices*. Changed this check to be consistent with the operation being performed.
Additional Notes:
1) This unit test adds properties to vertices, but does not *explicitly* make the check for Graph.Features.VertexFeatures.FEATURE_ADD_PROPERTY support in its feature requirements. The feature requirement set SIMPLE does not include Graph.Features.VertexFeatures.FEATURE_ADD_PROPERTY, but rather includes the feature Graph.Features.VertexPropertyFeatures.FEATURE_ADD_PROPERTY, which is a check for being able to add meta properties. Therefore, since meta properties cannot be supported without basic add property support for vertices, the check for adding properties …

Fixed feature check in shouldPersistDataOnClose()

---

gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/loaders/SugarLoaderTest.groovy
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineIntegrateTest.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineOverGraphTest.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineSandboxedStandardTest.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTinkerPopSandboxTest.java

Made possible to use GraphProvider to convert ids into Strings
The idea is to prevent this:
````
Script1.groovy: 1: unexpected char: '#' @ line 1, column 5.
g.V(#11:0).next()
````

TINKERPOP3-984

---

.travis.yml
pom.xml

Hey guys, 
This isn't so much ready for merge. I just wanted to put it out there for review and suggestions.
This PR aims at adding travis support. It currently checks:
-  `mvn clean install` 
- `bin/process-docs.sh --dryRun` (will fail if an error occurs, doesn't actually check docs)
- `mvn process-resources -Djavadoc` (will fail if an error occurs, doesn't actually check docs)
And the checks [pass](https://travis-ci.org/PommeVerte/incubator-tinkerpop/builds/92270450) and take about 20mn to run. There are however a few issues mentioned bellow.
I also ran into some rat-check issues early on. Excluded the `.travis.yml` from the checks but I don't know if any work needs to be done with licensing here? I'm guessing not but shout out if it's required.
Suggestions
=========
- adding support …

initial travis setup

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderLocalStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyOrderTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-941
Instead of fixing the error message, I simply made it such that if you don't provide a comparator, it assumes you mean `Order.incr`. Added a test for both `OrderLocalStep` and `OrderGlobalStep` that demonstrate things working. Finally, I also realized we didn't have a proper `clone()` method for `OrderLobalStep`. Eek! Added it.
Ran `mvn clean install` and `SparkGraphComputerIntegrationTest` (for `OrderTest` only) and all is golden.
VOTE +1.

TINKERPOP3-941: Improve error message for wrong order().by() arguments

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/ProfileStepTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-970
A couple things.
* `Traversal.profile()` now exists. The point of the ticket.
* `__.profile()` does not exist. This shouldn't have been there to begin with.
Ran `mvn clean install` and all is golden. 
VOTE +1.

TINKERPOP3-970: ProfileStep should be off Traversal, not GraphTraversal

---

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/standard/StandardOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/ServerGremlinExecutor.java

https://issues.apache.org/jira/browse/TINKERPOP3-912
I folded in a couple of changes related to general refactoring that were above and beyond the scope described in the JIRA ticket.  Most notably was the removal of more code related the deprecated "rebinding" term.  
I thought this ticket was going to be much bigger when i started, but it seemed to be less so for 3.1.1 anyway. Anyway, it is pretty deep in the guts of Gremlin Server, so reviewers should focus mostly on ensuring that there are no regressions as a result of this refactoring work.
I tested with:
```text
```
VOTE: +1

TINKERPOP3-912 Improve the ability to embed Gremlin Server with Channelizer injection

---

gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineOverGraphTest.java

Tested on TinkerGraph, which does not support transactions.
Tested on Sqlg, which does support transactions, passes the test.

TINKERPOP3-1000 Rollback the implicit transaction on multi threaded tests.

---

gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/loaders/SugarLoaderPerformanceTest.groovy

The hardcoded integer ids fail on providers that do not have integer ids.

use the GraphProvider to convert hardcoded ids

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONReader.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTokens.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONUtil.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONWriter.java
gremlin-server/conf/gremlin-server-min.yaml
gremlin-server/conf/gremlin-server-neo4j.yaml
gremlin-server/conf/gremlin-server-rest-modern.yaml
gremlin-server/conf/gremlin-server-rest-secure.yaml
gremlin-server/conf/gremlin-server-secure.yaml
gremlin-server/conf/gremlin-server-spark.yaml
gremlin-server/conf/gremlin-server.yaml
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinResultSetIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerIoRegistry.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphGryoSerializerTest.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-978
We already had this feature for Gryo but it wasn't built for GraphSON as the original idea was to mostly support serialization over `:remote`.  That was a bit short-sighted in thinking so I've added the same capability for GraphSON as will be especially useful to non-JVM languages.
you can test with `mvn clean install` followed by the Gremlin Server integration tests:
```text
```
my vote is +1
@PommeVerte @jbmusso @davebshow - this one may be interesting to you and your driver work

TINKERPOP3-978 Native GraphSON Serialization for Gremlin Server

---

docs/src/reference/gremlin-applications.asciidoc
gremlin-server/conf/gremlin-server-rest-secure.yaml
gremlin-server/conf/gremlin-server-secure.yaml
gremlin-server/conf/tinkergraph-credentials.properties
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/auth/SimpleAuthenticator.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateOldTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-981
Fixed up docs and altered packaged config files. This is a non-breaking change as the setting is still supported.  It offers a warning when it is used. Kept tests in place and added new ones to test both features.
```text
```
Did the above tests and some manual testing of REST as well as the driver in the console.
VOTE: +1

TINKERPOP3-981 - Deprecate credentialsDbLocation setting for gremlin server simple auth.

---

giraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/giraph/process/computer/GiraphGraphComputer.java
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/process/computer/util/ComputerSubmissionHelper.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java

This supersedes https://github.com/apache/incubator-tinkerpop/pull/154.
This PR is similar to its predecessor, but with two differences:
* This PR shuts down executors it creates in a finally block instead of leaking them
* This PR covers both SparkGraphComputer and GiraphGraphComputer

TINKERPOP3-988 Change GraphComputer executors

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traverser.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ComputerAwareStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/O_Traverser.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/util/EmptyTraverser.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStepTest.java

https://issues.apache.org/jira/browse/TINKERPOP3-1013
We have had a hack in `MatchStep` this whole time where we use path labels to store branch history. This is not only semantically awkward (as labels are added that were not provided via `as()`), it also means we will not be able to do https://issues.apache.org/jira/browse/TINKERPOP3-736. Also, this will allow us to cleanly implement `IntersectStep` and `SymetricDifferenceStep` (down the road).
The implementation is really simple. `Traverser.getTags()`. This method returns a mutable set and thus, we can remove, add, size, contains, etc. tags associated with a traverser.
Ran `mvn clean install` and all is golden.
VOTE +1.

TINKERPOP3-1013: Traverser tags as a safer way of using path labels

---

gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutorTest.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTest.java

Adjust tests to be a bit more bulletproof with respect to thread timing. Not sure if i've fixed anything with this change as these tests have never failed for me on my system.  I would have CTR'd this but I'd like to see if there is any validation that this is working correctly now. I guess runs in Travis and those who have macs would be the best judge of whether or not this issue is resolved.
VOTE +1

TINKERPOP3-1006 Random error during builds: shouldReloadClassLoaderWhileDoingEvalInSeparateThread()

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/auth/AllowAllAuthenticator.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/auth/Authenticator.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/auth/SimpleAuthenticator.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAuthenticationHandler.java

https://issues.apache.org/jira/browse/TINKERPOP3-995
This change is non-breaking despite the deprecation. Reviewers should focus on validating that there are no regressions:
```text
```
VOTE: +1

TINKERPOP3-995 Add Authenticator.newSaslNegotiator(InetAddress)

---

docs/src/reference/implementations.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IncidentToAdjacentStrategy.java
hadoop-gremlin/conf/hadoop-gryo.properties
spark-gremlin/src/main/groovy/org/apache/tinkerpop/gremlin/spark/groovy/plugin/SparkLoader.groovy
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/groovy/plugin/SparkGremlinPlugin.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkExecutor.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/Spark.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkHadoopGraphProvider.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/groovy/plugin/SparkGremlinPluginTest.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/groovy/plugin/SparkHadoopGremlinPluginTest.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/structure/SparkTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1023
Like `hdfs` there is now `spark` which allows the user to manage their persisted contexts. In essence, the Spark Server looks like a file system with (named) RDDs accessible. For instance, you can `spark.ls()`, `spark.rm()`, `spark.describe()`. I added a `SparkGremlinPluginTest` which ensures that all the proper imports/etc. work in the Console. I also added the information the reference docs. I published the reference docs so people can see it in action:
http://tinkerpop.apache.org/docs/3.1.1-SNAPSHOT/reference/#sparkgraphcomputer  (scroll down to "Using A Persisted Context" section)
VOTE +1. (`mvn clean install` and Spark integration tests)

TINKERPOP-1023: Add a spark variable in SparkGremlinPlugin like we do hdfs for HadoopGremlinPlugin

---

docs/src/upgrade/release-3.1.x-incubating.asciidoc
giraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/giraph/groovy/plugin/GiraphGremlinPlugin.java
gremlin-console/conf/log4j-console.properties
gremlin-server/conf/log4j-server.properties
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/groovy/plugin/HadoopGremlinPlugin.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/groovy/plugin/SparkGremlinPlugin.java

https://issues.apache.org/jira/browse/TINKERPOP-859
Logging setup shouldn't be hardcoded anywhere especially since we use slf4j.  With this approach the user has the ultimate control over what they want logged and what they don't.  TinkerPop provides a sensible default in the provided logging properties files using log4j.
I tested the console manually copying the examples in the reference documentation after these changes and didn't see any difference in the output to the console.
VOTE: +1

TINKERPOP-859 Moved logging setup to configuration in HadoopGremlinPlugin

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1035
Sessionless requests now have special handling for `GraphTraversal` return results.  Gremlin Server now force iterates those results (when they include `Mutating` steps) to a `List`.  It then commits and then iterates that `List`. For all other results the commit occurs in the same spot, but doesn't force iterate which allows results to stream as they always have.
Tested manually and with:
```text
```
VOTE: +1

TINKERPOP-1035 Improved consistency of transaction management in gremlin server.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-server/conf/gremlin-server-classic.yaml
gremlin-server/conf/gremlin-server-min.yaml
gremlin-server/conf/gremlin-server-modern-readonly.yaml
gremlin-server/conf/gremlin-server-modern.yaml
gremlin-server/conf/gremlin-server-neo4j.yaml
gremlin-server/conf/gremlin-server-rest-modern.yaml
gremlin-server/conf/gremlin-server-rest-secure.yaml
gremlin-server/conf/gremlin-server-secure.yaml
gremlin-server/conf/gremlin-server-spark.yaml
gremlin-server/conf/gremlin-server.yaml
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GraphManager.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/HttpChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/standard/StandardOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-performance.yaml

https://issues.apache.org/jira/browse/TINKERPOP-930
Basically forces the user to pass the aliases argument.  Gremlin Server then uses that to determine the scope of the transactions to close.  This setting is false by default so as to be backward compatible.
Tested with:
```text
mvn verify -DskipIntegrationTests=false -DincludeNeo4j -pl gremlin-server
```
VOTE +1

TINKERPOP-930 Added a strictTransactionManagement setting to Gremlin Server.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/GroovyEnvironmentSuite.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineFileSandboxTest.java
gremlin-groovy-test/src/main/resources/org/apache/tinkerpop/gremlin/groovy/jsr223/sandbox.yaml
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/AbstractSandboxExtension.groovy
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/FileSandboxExtension.groovy
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/PropertyExpressionEvaluator.groovy
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/SandboxExtension.groovy
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/SandboxHelper.groovy
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/SimpleSandboxExtension.groovy
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/TinkerPopSandboxExtension.groovy
gremlin-server/scripts/empty-sample-secure.groovy

https://issues.apache.org/jira/browse/TINKERPOP-891
Deprecated the `SandboxExtension` and replaced it with the `AbstractSandboxExtension`.  Took existing implementations and had them extend from the new `AbstractSandboxExtension`.  Added a new "useful" implementation called `FileSandboxExtension` which gets its white list configuration from a file.  Updated appropriate docs and wrote a number of tests for the new `FileSandboxExtension`.
Both unit and integration tests pass.  Also tested manually by configuring Gremlin Server to use the different sandboxes.  
VOTE: +1

TINKERPOP-891 Refactored the sandboxing abstractions for Gremlin Server

---

gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/LambdaSideEffectStepTest.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineIntegrateTest.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinAdditionPerformanceTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGraphProvider.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/algorithm/generator/CommunityGeneratorTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/AbstractGremlinProcessTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/GremlinProcessRunner.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ElementIdStrategyProcessTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/FeatureSupportTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoIntegrateTest.java
gremlin-test/src/test/java/org/apache/tinkerpop/gremlin/structure/ExceptionCoverageTest.java
hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/RecordReaderWriterTest.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/process/NativeNeo4jCypherTest.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/structure/NativeNeo4jIndexTest.java
pom.xml
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/AbstractSparkTest.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java

Removed the `muteTestLog` system property because logging can now be controlled by config file.
Ran `mvn clean install` and `mvn clean install -Dci`
Logging appear appropriate in both cases.

TINKERPOP-1019 Replaced all system.out.println and system.out.error with logger.

---

CHANGELOG.asciidoc
docs/src/reference/the-graphcomputer.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoader.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoaderVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/IncrementalBulkLoader.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/OneTimeBulkLoader.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessComputerSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoaderVertexProgramTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1026
BLVP (in particular `IncrementalBulkLoader`) now stores the `toString()` version of vertex IDs in the temporary `bulkLoader.vertex.id` property. I also added another `BulkLoader` implementation (`OneTimeBulkLoader`), to a) be able to add more test cases and b) verify that the `toString()` update doesn't interfere with something else.
Successfully ran `mvn clean install` and integration tests.
VOTE: +1

TINKERPOP-1026 BVLP should store vertex IDs as String

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphManager.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/PropertyTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexTest.java

Doing a test PR to see if Travis will build, there might be something wrong with my local environment. If Travis doesn't pass, I will rescind my PR.
Refactor tests to use member variables for `graphProvider`
Added Java docs
https://issues.apache.org/jira/browse/TINKERPOP-983

TINKERPOP-983 - Provide a way to track open Graph instances in tests

---

CHANGELOG.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy

https://issues.apache.org/jira/browse/TINKERPOP-1055
Some relatively minor refactoring required to get this working.  Tested manually only as I wasn't sure how to write tests around the console when it was calling `System.exit(1)` on error.  I first tested a "good" script:
```text
$ cat test.groovy
x=1
addItUp = {x,y -> x+y}
$ bin/gremlin.sh test.groovy
\,,,/
(o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
==>1
==>groovysh_evaluate$_run_closure1@5536379e
gremlin> addItUp(1,10)
==>11
```
Then I tested a script that wasn't present on the file system:
```text
$ bin/gremlin.sh test1.groovy
\,,,/
(o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities …
```

TINKERPOP-1055 Gremlin Console FileNotFoundException can be misleading

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DependantMutableMetrics.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/MutableMetrics.java

https://issues.apache.org/jira/browse/TINKERPOP-1075
Fix the way DependantMutableMetrics profile durations are calculated.

TINKERPOP-1075: Profile duration of cap step seems broken.

---

CHANGELOG.asciidoc
bin/process-docs.sh
docs/src/dev/developer/contributing.asciidoc

Clear the local Grapes directory and HDFS in `bin/process-docs.sh`.
Also added an option (`--no-clean`) to avoid the cleanup.
VOTE: +1

TINKERPOP-938 Add a "clear SNAPSHOT jars" section to the process-docs.sh.

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/DefaultGraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/AbstractLambdaTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/ConstantTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/IdentityTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/LoopTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/lambda/TrueTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/EmptyStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/EmptyTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalRing.java

https://issues.apache.org/jira/browse/TINKERPOP-1083
We had a lot of inconsistencies around `hashCode()`/`equals()` for `Traversal`. Moreover, I pretty much gutted a crap load of pointless internals in `AbstractLambdaTraversal` (much simpler, safer, and more efficient).
`mvn clean install` as well as Spark integration tests (and the first 10 minutes of Giraph integration tests).
VOTE +1.

TINKERPOP-1083: Traversal needs a hashCode() and equals() definition.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoMapper.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/JavaTimeSerializers.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoMapperTest.java

These classes did not have serializers native to kryo and were also not in the semi-standard contrib package of serializers.  GraphSON serialization works out of the box with `FieldSerializer` - it's verbose output for JSON but I dont' think we need to build special serializers for that yet.
Ran both unit and integration tests successfully.  Also did a manual test in the console via `:remote`:
```text
gremlin> :> java.time.Instant.now()
==>2016-01-15T19:39:16.569Z
gremlin> :> java.time.Duration.ZERO
==>PT0S
gremlin> :> java.time.Duration.ofDays(10)
==>PT240H
```
VOTE +1

TINKERPOP-1086 Added gryo serializers for virtually all java.time classes.

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderLocalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ComparatorTraverser.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/util/TraverserSet.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/function/ChainedComparator.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderGlobalStepTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderLocalStepTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1089
This required some refactoring. We have lots of `Comparator` wrappers everywhere so things get a little nasty. However, I added some solid test cases that ensure that the order violation doesn't happen with `Order.shuffle`.
VOTE +1.

TINKERPOP-1089: Order.shuffle implementation is too fragile

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/FeatureRequirementSet.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/FeatureSupportTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/PropertyTest.java

As they were very closely related, this PR covers:
https://issues.apache.org/jira/browse/TINKERPOP-997
https://issues.apache.org/jira/browse/TINKERPOP-998
it deprecates a `Feature` that was basically a duplicate of another.  It also opens up a good number of test cases to graphs that don't support meta-properties as there was a mis-definition of the `SIMPLE` requirement set.
Tested with `mvn clean install -DincludeNeo4j` and all was good. Also temporarily modified the TinkerGraph feature for meta-property support and manually noted that the right test cases opened up and closed down based on this change.  Would be nice to get some verification from other graphs that this change is all good.  
@jdellithorpe please take a look at this change when you get a moment, as you were the one who …

TINKERPOP-997 - Feature and FeatureRequirement adjustments

---

giraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/giraph/process/computer/GiraphComputation.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraverserExecutor.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/CountGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupCountStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupStepV3d0.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MaxGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MinGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SumGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/TreeStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ReducingBarrierStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/iterator/DoubleIterator.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/iterator/IteratorUtils.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/iterator/MultiIterator.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/iterator/SingleIterator.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/computer/TinkerMessenger.java

https://issues.apache.org/jira/browse/TINKERPOP-1131
This will go into TinkerPop 3.1.2. I will then upmerge it to master/ (3.2.0) and when https://github.com/apache/incubator-tinkerpop/pull/210 is merged to master/ (3.2.0), we will have a lean-mean OLAP processing machine!
I realized that I was copying `TraverserSets` instead of draining one into the other. By draining, for every traverser put into one set, it is removed from the other. In the worst case, we could have up to 3 sets of equivalent size all in memory at one vertex in OLAP. If you do any sort of `outE()`-type traversal, thats ALOT of data. Moreover, I reorganized the flow of processing as previously I was determining if messages needed to be sent right after received messages! Pointless waste of CPU cycles. Finally, I create …

TINKERPOP-1131: TraversalVertexProgram traverser management is inefficient memory-wise.

---

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/AbstractClient.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/NioClient.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/SimpleClient.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-916
These implementations provide for a no-frills way to test Gremlin Server. Added methods to collect all messages returned from the server as opposed to just capturing messages via callback.  Updated all integration tests that were using the old methods.
I will update CHANGELOG after the merge for this one.
Tested with: `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE: +1

TINKERPOP-916 Provide more robust SimpleClient implementations.

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphManager.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphProvider.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/AbstractNeo4jGraphProvider.java

https://issues.apache.org/jira/browse/TINKERPOP-1146
Was formerly just calling `Graph.close()` which wasn't enough to actually empty graphs of data. This led to test errors for some graph providers.  This change actually calls `GraphProvider.clear()` which by definition should empty a graph of data at the end of a test.
To test you technically need a graph that is persistent (e.g. Neo4j). Ran `mvn clean install -DincludeNeo4j` without problems.
VOTE +1

TINKERPOP-1146 Use GraphProvider.clear() to auto-clear graphs created in tests

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializers.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/JavaTimeSerializers.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/JavaUtilSerializers.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoMapperTest.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1135
Serialized all classes currently serialized by Gryo using ISO-8061 format.  Using the embedded type option actually allows serialization back to `java.time.*` classes rather than coercing them to other types. 
All good with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-1135 Improved GraphSON support of java.time.* packages.

---

CHANGELOG.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/TimedInterruptCustomizerProvider.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/TimedInterruptTimeoutException.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutorTest.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTimedInterruptTest.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1138
Provide distinct messaging for the different kinds of timeouts that Gremlin Server can generate.
Tested with: `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE: +1

TINKERPOP-1138 Improve messaging on server timeouts

---

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java

TINKERPOP-1125
Rather than creating a new iterator so skipping over a host in the pool.

TINKERPOP-1125 Use the existing Host iterator

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Tokens.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1039
Added a per request argument called manageTransaction to allow an in-session client to signal that it would like Gremlin Server to commit/rollback at the end of the request. This basically allows a session to behave much like the sessionless request does by default.
Did a `--dryRun` of the docs for quick review and `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false -DincludeNeo4j` and all looked good.
@PommeVerte this one might be of interest to you for review.
VOTE +1

TINKERPOP-1039 Allowed for transaction management in sessions.

---

CHANGELOG.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/ConcurrentBindings.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutorTest.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1148
This Bindings implementation is used with the global bindings of the GremlinExecutor so that it can allow for concurrent modification.
Ran `mvn clean install`
VOTE: +1

TINKERPOP-1148 Added ConcurrentBindings implementation for Gremlin ScriptEngine.

---

gremlin-server/pom.xml
neo4j-gremlin/pom.xml

Neo4j 2.3.0 changed the format of the neostore.nodestore.db 
This causes Neo4j databases created w/ Gremlin-server (e.g.  /tmp/neo4j) and neo4j databases created by the neo4j server from neo4j.com to be incompatible with each other.   Also Gremlin-server/console cannot open databases created by the newer Neo4j code (2.3.0 and higher)
The fix is two one line each in the gremlin pom files:
gremlin-server/pom.xml
neo4j-gremlin/pom.xml

Tp31  - fix for gremlin server and console to open Neo4j 2.3.* databases

---

pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1165
Add -parameters to maven compile args.
This can be manually verified w/ something like this
```
System.out.println(GraphTraversal.class.getDeclaredMethods()[0].getParameters()[0].getName());
```
This used to print "arg0", but should now print "column".

TINKERPOP-1165:Tooling Support: Compile with -parameters

---

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java

This commit[1] broke HTTP keepalive support by introducing a
double-negation on the call to Netty's isKeepAlive.
[1]: https://github.com/apache/incubator-tinkerpop/commit/c0121aae8266e9ff2c70c1517e809b5ecf1dd07a

Fix HTTP keepalive support

---

CHANGELOG.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/LoadBalancingStrategy.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1172
The `ConnectionPool` wasn't getting initialized properly when the host was dead which then lead to a null pointer exception when trying to reconnect.  Also fixed the possibility of a connection leak if the pool was partially initialized but the host died in the middle of that. Those partial connections were never properly closed.
I performed multiple successful runs of `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`.
VOTE +1

TINKERPOP-1172 Fixed bug with driver connecting to an initially dead server.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalExplanation.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializers.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTokens.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoMapper.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoSerializers.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoMapperTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1147
Covers both gryo and graphson. Gryo uses standard Java serialization as the object graph is mighty deep and building a native kryo serializer would have been a lot. GraphSON serializes to a JSON format which pretty much just allows you to get the data required to build what would have come from TraversalExplanation.toString().  It's mostly just for display purposes. Basically looks like this:
```js
{
"original": ["GraphStep([],vertex)", "VertexStep(OUT,edge)", "EdgeVertexStep(IN)", "VertexStep(OUT,vertex)"],
"intermediate": [{
"traversal": ["GraphStep([],vertex)", "VertexStep(OUT,edge)", "EdgeVertexStep(IN)", "VertexStep(OUT,vertex)"],
"strategy": "ConnectiveStrategy",
"category": "DecorationStrategy"
}, {
"traversal": …
```

TINKERPOP-1147 Added serialization support for TraversalExplanation

---

CHANGELOG.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultQueue.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-956
Implemented a method of refreshing a connection when notification was received that it was closed on the server-side. As a result the driver should do a better job of recovering in the face of a server-side closing of a channel.  
Had a good build with `mvn clean install && mvn verify -DskipIntegrationTests=false -DincludeNeo4j`
VOTE +1

TINKERPOP-956 Connection errors tend to force a complete close of the channel

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java

https://issues.apache.org/jira/browse/TINKERPOP-1160
Added the new `maxWaitForSessionClose` configuration option to the driver.  For all the code changes here, the only one that matters is this:
https://github.com/apache/incubator-tinkerpop/compare/tp31...TINKERPOP-1160?expand=1#diff-9aa3bff55e6c3f840ceded2dd2ad2d88R234
where I replaced an indefinitely blocking {{get()}} call on a future to one with a timeout that uses the new setting. 
all good with: `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false` 
VOTE +1

TINKERPOP-1160 Add timeout configuration for time to wait for connection close

---

CHANGELOG.asciidoc
docs/src/dev/provider/index.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/reference/implementations-hadoop.asciidoc
docs/src/reference/implementations-neo4j.asciidoc
docs/src/reference/intro.asciidoc
docs/src/reference/the-graph.asciidoc
docs/src/reference/the-traversal.asciidoc
docs/src/upgrade/index.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/GremlinGroovysh.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Mediator.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/RemoteCommand.groovy
gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/DriverRemoteAcceptor.java
gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/DriverRemoteAcceptorIntegrateTest.java
gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/GephiRemoteAcceptorIntegrateTest.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/plugin/RemoteAcceptor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/groovy/plugin/HadoopRemoteAcceptor.java

https://issues.apache.org/jira/browse/TINKERPOP-1096
https://issues.apache.org/jira/browse/TINKERPOP-1097
This PR introduces several things:
1. `SessionedClient.alias()` is now implemented so that you can do aliases on a session-based connection
1. The console's `:remote connect` now allows you to append "session" to the end of it so that it starts that remote with a session
1. The console now has `:remote console` which allows the console to be put into a mode where all scripts are sent to remote and the `:>` is no longer required
Tested the console manually in an abundance of ways but here's an example:
```text
gremlin> :remote connect tinkerpop.server conf/remote.yaml session
==>Connected - localhost/127.0.0.1:8182-[98bc7cf9-1c7b-451a-acbd-124a53a811d3]
gremlin> :remote config alias a …
```

TINKERPOP-1096 TINKERPOP-1097 Session Aliases, Console Sessions and Remote Console

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Operator.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/CountGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupCountStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupCountSideEffectStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupSideEffectStep.java

https://issues.apache.org/jira/browse/TINKERPOP-1180
This is simple. Added `Operator.sumLong` which bypasses using `NumberHelper`. Smart when you know you are summing longs as in `CountGlobalStep`. I also tweaked the initial capacity of the singleton maps of the `GroupXXXSteps`. As we need more Operators, we can just CTR add them. Its trivial.
`mvn clean install`.
VOTE +1.

TINKERPOP-1180: Add more optimized binary operators to Operator

---

hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/Constants.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/AbstractSparkTest.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/structure/io/gryo/GryoSerializerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1173
If the user does not specify a serializer, then default to using `GryoSerializer` instead of Spark's default of `JavaSerializer`. Updated a test case to verify the behavior.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:00.006s
[INFO] Finished at: Wed Mar 09 11:00:50 MST 2016
[INFO] Final Memory: 133M/806M
[INFO] ------------------------------------------------------------------------
```
VOTE +1.

TINKERPOP-1173: If no Serializer is provided in Configuration, use GryoSerializer by default (Spark)

---

CHANGELOG.asciidoc
bin/init-tp-spark.sh
docs/src/reference/implementations-hadoop.asciidoc
spark-gremlin/pom.xml
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/io/gryo/WrappedArraySerializer.java

https://issues.apache.org/jira/browse/TINKERPOP-1069
Bumped.
* Integration tests passed.
* Tested manually with `local[4]`.
* Tested manually against SparkServer.
* Docs built successfully (and publishing right now...).
VOTE +1.

TINKERPOP-1069: Support Spark 1.6.0

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PageRankVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PeerPressureVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/TraversalVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GraphStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/PureTraversal.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyHasTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasTest.java
neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/traversal/step/sideEffect/Neo4jGraphStep.java
neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/traversal/strategy/optimization/Neo4jGraphStepStrategy.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/step/sideEffect/TinkerGraphStep.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/optimization/TinkerGraphStepStrategy.java

https://issues.apache.org/jira/browse/TINKERPOP-1219
OLTP providers that have custom `GraphStep` implementations should have `g.V(1)` and `g.V().hasId(1)` compile to the same representation. Likewise for `g.V(1,2)` and `g.V().hasId(1,2)` and `g.V().has(T.id,within(1,2))`. This ensures that random-access databases are using not using linear scans with `g.V().hasId(…)`. I added `GraphStep.processHasContainerIds()` which makes it easy for providers to update their respective `XXXGraphStepStrategy` to `GraphStep.addIds()` is appropriate.
I found a few `hashCode()`-bugs in the process and fixed them up. 
CHANGELOG
```
* Added `GraphStep.addIds()` which is useful for `HasContainer` "fold ins."
* Added a static `GraphStep.processHashContainerIds()` helper for handling id-based `HasContainers`.
* …
```

TINKERPOP-1219: Create a test case that ensures the provider's compilation of g.V(x) and g.V().hasId(x) is identical

---

hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/HadoopPools.java

https://issues.apache.org/jira/browse/TINKERPOP-1217
This is a simple fix. However, the more troubling thing for me (and what could be another ticket) is why are you (@rspitzer) getting that? I don't know where in Spark the pool isn't being initialized and I haven't seen that in my experiments with Friendster/etc. 
Perhaps we can discuss on the mailing list about where in Spark this WARN is popping up for you.
For this issue VOTE +1.

TINKERPOP-1217: Repeated Logging of "The HadoopPools has not been initialized, using the default pool"

---

gremlin-console/src/main/static/NOTICE
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializers.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerGremlinV1d0Test.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV1d0Test.java
gremlin-server/src/main/static/NOTICE
gremlin-shaded/pom.xml
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/SerializationTest.java

I've had to upgrade jackson in `gremlin-shaded` to version `2.7.2` for this fix. I've made the appropriate changes to the `NOTICE` files.
This makes `tree()` work with the `GraphSON` serializers. I've added tests for `GraphSON` and `Gryo` + driver tests for `GraphSONMessageSerializer` and `GraphSONMessageGremlinSerializer`
What I've done for testing:
- `mvn clean install` **OK**
- `mvn verify -DskipIntegrationTests=false -pl gremlin-server` **OK**
- Ran tests with the php driver against `application/json`  **OK**

TINKERPOP-732 .tree() serialization in GraphSON

---

gremlin-console/src/main/bin/gremlin.sh
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/ConsoleFs.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Mediator.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/InstallCommand.groovy

`gremlin.sh` now handles user-defined `ext/` directories (`tinkerpop.ext`). If the user specified directory doesn't exist, it will
a) create it and
b) copy the contents of `gremlin-console/ext` to it

TINKERPOP-1109 Make Gremlin Console better suited for system level installs

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/Computer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java

https://issues.apache.org/jira/browse/TINKERPOP-1163
GraphComputers can now have their own `TraversalStrategy` registrations in the global cache. Currently, as it stands, all that is registered is `GraphComputer.class` which has `PathProcessStrategy`, `OrderLimitStrategy`, `ComputerVerificationStrategy`. Moving forward, we will be able to have strategies like `SparkCountStrategy` which will convert `g.V().count()` into `inputRDD.count()` and thus, allow us to talk more directly to the `GraphComputer` engine. `TinkerCountStrategy` would do `g.V().count()` as `this.vertices.count()`. Blazin'. .... however, what we have here is the the infrastructure to allow for the distinction between `Graph` and `GraphComputer` strategies. Note that this PR is backwards compatible.
CHANGELOG
```
* …
```

TINKERPOP-1163: GraphComputer's can have TraversalStrategies.

---

giraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/giraph/process/computer/GiraphGraphComputer.java
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/process/computer/AbstractHadoopGraphComputer.java
hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/process/computer/AbstractHadoopGraphComputerTest.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java

https://issues.apache.org/jira/browse/TINKERPOP-1223
If a `HADOOP_GREMLIN_LIBS` directory does not reference a local directory, then check for that directory in HDFS. If its there, copy it to a `java.io.tmp` directory and then process the `jars` from there.
CHANGELOG
```
* `HADOOP_GREMLIN_LIBS` can now reference a directory in HDFS and will be used if the directory does not exist locally.
```  
`mvn clean install` and tested manually via the Gremlin Console.
VOTE +1.

TINKERPOP-1223: Allow jars in gremlin.distributedJars to be read from HDFS

---

docs/src/reference/the-traversal.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProjectStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectStep.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProjectStepTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyProjectTest.groovy
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessComputerSuite.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessStandardSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/AbstractGremlinProcessTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProjectTest.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1237
Added `GraphTraversal.project()` which allows is like the inverse of `select()`. Instead of pulling from this path history, you are pushing into the future. While this can be done with `match()`, `ProjectStep` does not require `LABELED_PATHS` and thus, is more efficient (though, its constrained to local children `by()`-modulation).
EXAMPLE:
```
gremlin> g.V().out("created").
project("a","b").
by("name").
by(in("created").count()).
order().by(select("b"),decr).
select("a")
==>lop
==>lop
==>lop
==>ripple
```
CHANGELOG
```
* Added `GraphTraversal.project()` to allow projecting out a `Map<String,E>` given the current traverser and an arbitrary number of `by()`-modulators.
```
Docs build, `mvn clean install` and Giraph (at `ProjectTest`) …

TINKERPOP-1237: ProjectMap: For the Love of Die Faterland

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PageRankVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PeerPressureVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/ProgramVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/TraversalVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/VertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/RemoteGraph.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/VertexProgramStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/ScriptTraversal.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyProgramTest.groovy
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessComputerSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProgramTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1234
We now have `GraphTraversal.program(VertexProgram)`. This allows users to do things such as:
```
g.V().out("bought").in("bought").program(CollaborativeFilteringVertexProgram.build()....)
```
Behaves just like any other `VertexProgramStep` where:
```
g.V().pageRank() == g.V().program(PageRankVertexProgram...)
```
CHANGELOG
```
* Added `GraphTraversal.program(VertexProgram)` to allow arbitrary user vertex programs in OLAP.
```
VOTE +1. @dkuppitz tested it with his use case as well.

TINKERPOP-1234: program() step that takes arbitrary vertex programs

---

CHANGELOG.asciidoc
bin/process-docs.sh
docs/preprocessor/preprocess-file.sh
docs/preprocessor/preprocess.sh
docs/src/dev/developer/contributing.asciidoc

**Process all docs**:
```sh
bin/process-docs.sh
```
**Dry-run all docs**:
```sh
bin/process-docs.sh -d
bin/process-docs.sh --dryRun
```
**Process only `the-graph.asciidoc` and `the-traversal.asciidoc`** (dry-run the others):
```sh
bin/process-docs.sh -f the-graph,the-traversal
bin/process-docs.sh --fullRun the-graph,the-traversal
```
**Dry-run `the-graph.asciidoc` and `the-traversal.asciidoc`** (process the others):
```sh
bin/process-docs.sh -d the-graph,the-traversal
bin/process-docs.sh --dryRun the-graph,the-traversal
```
VOTE: +1

TINKERPOP-1020 Provide --dryRun selectivity for "half publishing" docs.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java

Pretty boring pull request. Added more SSL configuration options for Gremlin Driver and Server. Existing SSL tests still work and I added a new one to validate the overrides worked. Everything still good with:
```text
$ mvn clean install -DskipTests && mvn verify -pl gremlin-server -DskipIntegrationTests=false 
```
Did some manual testing as well with with the `gremlin-server-secure.yaml` and the console:
```text
gremlin> :remote connect tinkerpop.server conf/remote-secure.yaml
==>Connected - localhost/127.0.0.1:8182
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [localhost/127.0.0.1:8182] - type ':remote console' to return to local mode
gremlin> 1+1
==>2
```
VOTE +1

TINKERPOP-1269 More Configuration Options for SSL

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/DriverRemoteAcceptor.java
gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/DriverRemoteAcceptorTest.java

Added some tests to validate the new timeout setting and did some manual tests:
```text
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Connected - localhost/127.0.0.1:8182
gremlin> :remote config timeout max
==>Set remote timeout to 2147483647ms
gremlin> :remote config timeout none
==>Remote timeout is disable
gremlin> :remote config timeout 10000
==>Set remote timeout to 10000ms
gremlin> :> Thread.sleep(9000)
==>null
gremlin> :> Thread.sleep(11000)
Request timed out while processing - increase the timeout with the :remote command
Display stack trace? [yN] n
```
Successful run of `mvn clean install && mvn verify -pl gremlin-console -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-1267 Added option for "none" on remote timeouts.

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraph.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1284
```
gremlin>
gremlin> v = graph.addVertex()
==>v[0]
gremlin> v.addEdge("self",v)
==>e[1][0-self->0]
==>graphtraversalsource[tinkergraph[vertices:1 edges:1], standard]
gremlin> g.V(0l)
==>v[0]
gremlin>  g.V(0l).bothE()
==>e[1][0-self->0]
==>e[1][0-self->0]
gremlin> g.V(0l).outE()
==>e[1][0-self->0]
gremlin> g.V(0l).inE()
==>e[1][0-self->0]
gremlin>
gremlin>
gremlin> starGraph = org.apache.tinkerpop.gremlin.structure.util.star.StarGraph.of(v)
==>stargraph[starOf:v[0]]
gremlin> sg = starGraph.traversal()
==>graphtraversalsource[stargraph[starOf:v[0]], standard]
gremlin> sg.V(0l)
==>v[0]
gremlin> sg.V(0l).bothE()
==>e[1][0-self->0] …
```

TINKERPOP-1284: StarGraph does not handle self-loops correctly.

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraversalVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraverserExecutor.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphComputerTest.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkExecutor.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/payload/ViewIncomingPayload.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/payload/ViewOutgoingPayload.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/payload/ViewPayload.java

https://issues.apache.org/jira/browse/TINKERPOP-1120
The following PR effects TraversalVertexProgram and SparkGraphComputer. Here is what changed in both:
-------SparkGraphComputer
1. If the vertex doesn't pass any messages, don't serialize an empty list, serialize null.
2. If the vertex doesn't have a view, don't serialize an empty list of detached vertex properties, serialize null.
3. If the vertex doesn't have a view nor messages, don't do anything!
-------TraversalVertexProgram
4. Found a memory bug where halted traversers were still distributed amongst the vertices even though they were sent to the master traversal.
5. If a halted traverser TraverserSet is empty, remove the property (remove the vertex view!).
You can read about the performance gains by doing this here: …

TINKERPOP-1120: If there is no view nor messages, don't create empty views/messages in SparkExecutor

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SubgraphTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/EdgeTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphConstructionTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphWritePerformanceTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/TransactionTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexPropertyTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1300
tested with `mvn clean install -DincludeNeo4j`
VOTE +1

TINKERPOP-1300 Fixed many broken count asserts not being applied in test suite.

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/TestHelper.java

I'm getting `java.lang.IllegalArgumentException: URI is not hierarchical`, on OS/X, but don't get any context, therefore broaden the catch.

Broaden catch for computePath.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/plugin/GephiRemoteAcceptor.groovy
gremlin-console/src/test/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/GephiRemoteAcceptorIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1297
Also Improved output of HTTP request errors to gephi. It is likely that this change will not allow Gephi to work with 0.8.x anymore.
Tested manually and ran tests with: 
```text
mvn clean install && mvn verify -pl gremlin-console -DskipIntegrationTests=false
```
VOTE +1

TINKERPOP-1297 Updated the gephi plugin to work on Gephi 0.9.x

---

docs/src/reference/the-traversal.asciidoc
giraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/giraph/process/computer/GiraphGraphComputer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/ProgramPhase.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/clustering/peerpressure/PeerPressureVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/MemoryTraversalSideEffects.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraversalVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraverserExecutor.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/WorkerExecutor.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/VertexComputing.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PageRankVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PeerPressureVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/ProgramVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/TraversalVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/VertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/optimization/GraphFilterStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/util/EmptyMemory.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/util/SingleMessenger.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ImmutablePath.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyPageRankTest.groovy
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyPeerPressureTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PageRankTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PeerPressureTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProgramTest.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/SparkInterceptorStrategy.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/SparkSingleIterationStrategy.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkStarBarrierInterceptor.java

https://issues.apache.org/jira/browse/TINKERPOP-1305
@dkuppitz found a severe bug in 3.2.0 in OLAP traversal chains. Interestingly enough, all the test cases we had didn't touch this problem (even though they did tangentially, but didn't test particular expectations). As such, two new tests have been added to `pageRank()` and `peerPressure()` which demonstrate the problem has been rectified.
CHANGELOG
```
* Fixed a severe bug around halted traversers in a multi-job OLAP traversal chain.
* Ensure a separation of `GraphComputer` and `VertexProgram` configurations in `SparkGraphComputer` and `GiraphGraphComputer`.
* `PeerPressureVertexProgram` now supports dynamic initial vote strength calculations.
* Added `EmptyMemory` for ease of use when no memory exists.
* Updated …
```

TINKERPOP-1305: HALTED_TRAVERSERS hold wrong information

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SubgraphStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroovySubgraphTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SubgraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1088
Fixes a problem where cardinality is better respected with subgraph step. SubgraphStep now consults the parent graph features to determine cardinality of a property.
`mvn clean install` is all good.
VOTE +1

TINKERPOP-1088 Preserve Cardinality in Subgraph

---

README.asciidoc
bin/publish-docs.sh

https://issues.apache.org/jira/browse/TINKERPOP-1003
Update "current" links as part of `bin/publish-docs.sh`.
VOTE: +1

TINKERPOP-1003 Setting up latest/current links for bins and docs.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/ScriptEngines.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/ConfigurationCustomizerProvider.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/BaseScriptForTesting.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineConfigTest.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/ConfigurationCustomizerProviderTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/BaseScriptForTesting.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1322
This `CustomizerCompiler` implementation makes it possible to set low-level configurations in the `GremlinGroovyScriptEngine` on the Groovy `CompilerConfiguration` which ultimately controls script compilation settings used by the classloader. The most likely feature that someone would use here is the setting of the `ScriptBaseClass` which will let executing scripts inherit some base functionality.
All good with:
```text
mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false
```
Also performed a manual test with Gremlin Server that worked nicely.
VOTE +1

TINKERPOP-1322 Added ConfigurationCustomizerCompiler

---

CHANGELOG.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultQueue.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultSet.java

https://issues.apache.org/jira/browse/TINKERPOP-1196
Result.one() sometimes would hang under rare but possible conditions. This change should prevent that from happening now as it removes the chance of await() futures from being created while a flush of existing waiting futures is occurring. When that happened it seemed to create the possibility where an await() future could get created but never been completed.
I would have CTR'd this as it is a small change but I was hoping for reviewers to do:
```text
mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false
```
so as to validate that the problem is resolved on their systems. This problem didn't typically occur on mine - @okram this seemed to happen a lot to you during test runs so it would be great if you could …

TINKERPOP-1196 Fix for Result.one() which could have blocked indefinitely.

---

gremlin-test/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1318

TINKERPOP-1318: use mockito-core instead of mockito-all to avoid hamcrest conflict

---

docs/src/reference/gremlin-variants.asciidoc
gremlin-variant/src/main/groovy/org/apache/tinkerpop/gremlin/python/GremlinPythonGenerator.groovy
gremlin-variant/src/main/jython/gremlin_python/.gitignore
gremlin-variant/src/main/jython/gremlin_python/gremlin_python.py
gremlin-variant/src/main/jython/gremlin_python/groovy_translator.py

As described on dev@tinkerpop.apache.org thread gremlin_python GLV

add RawExpression to gremlin_python

---

gremlin-variant/pom.xml
gremlin-variant/src/main/java/org/apache/tinkerpop/gremlin/python/GenerateGremlinPython.java
gremlin-variant/src/main/jython/setup.py

Code generation is triggered by Maven before tests are run; dependencies
(currently aenum, requests) are installed, and the generated package is built
into ${project.build.testOutputDirectory}/Lib, which is added to the
classpath for the tests via the python.home property. Jython tests
import the gremlin_python package instead of importing its modules
directly.

gremlin_python: generate/build/deps before tests

---

docs/preprocessor/preprocess-file.sh

https://issues.apache.org/jira/browse/TINKERPOP-1071
To test the changes, I've added an invalid `foo + bar` line in one of the code blocks. Here's how the output looked like:
```
$ bin/process-docs.sh 
==========================
+   Installing Plugins   +
==========================
* tinkerpop-sugar ... done
* hadoop-gremlin ... done
* spark-gremlin ... done
* giraph-gremlin ... done
* neo4j-gremlin ... done
============================
+   Processing AsciiDocs   +
============================
* source:   /projects/apache/tinkerpop/docs/src/reference/index.asciidoc
target:   /projects/apache/tinkerpop/target/postprocess-asciidoc/reference/index.asciidoc
progress: [====================================================================================================] 100%
* source: …
```

TINKERPOP-1071 Enhance pre-processor output

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/BranchStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/AbstractStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RepeatUnrollStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/TraversalStrategyPerformanceTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IdentityRemovalStrategyTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RepeatUnrollStrategyTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProfileTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1349
`RepeatUnrollStrategy` is a Standard-only strategy that will unroll a `repeat()` into a linear form if and only if it has a known loop amount (e.g. `times(2)`). That is `repeat(out()).times(2)` becomes `out().barrier().out().barrier()`. The `barrier()` insertions are necessary as `repeat()` itself is a barrier step and also, the benefit of bulking is leveraged. `RepeatUnrollStrategy` removes the need for `RepeatStep`, `RepeatEndStep`, and `LoopTraversal`.
`RepeatUnrollStrategyTest` ensures that unrolling is faster than not-unrolling. Here are some runtimes. The first item in the Pair is the runtime and the second item is the amount of unique objects being processed. With more unique objects, the faster it gets. Note that at 10 unique …

TINKERPOP-1349: RepeatUnrollStrategy should unroll loops while maintaining equivalent semantics.

---

CHANGELOG.asciidoc
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/step/sideEffect/TinkerGraphStep.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java

https://issues.apache.org/jira/browse/TINKERPOP-1063
Got rid of `Stream` usage in TinkerGraph vertex/edge iteration.  Tests all pass with `mvn clean install`.
VOTE +1

TINKERPOP-1063 TinkerGraph Performance

---

spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/io/gryo/GryoRegistrator.java

https://issues.apache.org/jira/browse/TINKERPOP-1341
GryoRegistrator is missing registrations for three classes registered
in GryoSerializer:
* void
* Void
* CompactBuffer[]
This commit adds all three to GryoRegistrator.getExtraRegistrations().
So far, CompactBuffer[] is the only omission known to cause practical
problems, as detailed by Dylan Bethune-Waddell on the mailing list and
in the referenced issue.  It's not clear whether omitting Void and
void causes practical problems, but they're trivial, so the cost
associated with registering them is tiny.  Might as well.

TINKERPOP-1341 Add missing classes to GryoRegistrator

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1350
Made timeouts schedule closer to when execution of a script actually occurred. All together, this change helps prevent sessions from locking when submitting multiple parallel requests that have the potential to block.
All good with `$ mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false
`
VOTE +1

TINKERPOP-1350 Fixed a problem with how timeouts were scheduled in GremlinExecutor

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Scope.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1354
These "invalid" keys are reserved terms for Gremlin Server as they are statically imported enums and shouldn't be used as binding keys. You get some less than easy to understand error messages if those keys are used. 
I would have CTR'd but wanted to see if anyone had other suggestions for additional validations at play. Also, this change is "breaking" in the sense that users who were somehow successfully using some of these newly reserved keys on previous versions (not fully sure if that was even possible) will have to update their code. I don't think this is a massive problem for someone to fix, so while "breaking" it doesn't seem massively detrimental and shouldn't be widely problematic.
Builds with `mvn clean install -DskipTests && …

TINKERPOP-1354 Added more invalid binding keys to Gremlin Server validation

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoWriter.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/TestHelper.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineFileSandboxTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/TestHelper.java

https://issues.apache.org/jira/browse/TINKERPOP-1320
Passed `mvn clean install -DincludeNeo4j` and integration tests cleanly.
May be CTR worthy. Let me know.
VOTE: +1

TINKERPOP-1320 fix GremlinGroovyScriptEngineFileSandboxTest resource loading

---

CHANGELOG.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
gremlin-server/conf/gremlin-server-neo4j.yaml
gremlin-server/conf/gremlin-server-rest-secure.yaml
gremlin-server/conf/gremlin-server-secure.yaml
gremlin-server/conf/gremlin-server-spark.yaml
gremlin-server/conf/gremlin-server.yaml
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthOldIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-performance.yaml

https://issues.apache.org/jira/browse/TINKERPOP-1352
Also, fixed a bug (an invalid FastNoSuchElementException)  in Gremlin Server that would only appear when the server paused writes to an overwhelmed client. No new tests to validate as the driver doesn't have a good way to inspect the pool size. Had to test manually, however
```text
mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false
```
passed so there were no regressions. I might have CTR'd this but thought it would be helpful if others could run the command above to validate that nothing has gone bad. Plus I was hoping the person who originally reported this on the mailing list could review/comment.
VOTE +1

TINKERPOP-1352 Fixed logic in ConnectionPool that was preventing it from growing.

---

pom.xml

No new dependencies introduced.
No other dependency versions changed.
Successful build and verify with:
mvn clean install -pl gremlin-shaded,gremlin-core,gremlin-test,gremlin-groovy,gremlin-groovy-test,tinkergraph-gremlin,neo4j-gremlin,gremlin-driver,gremlin-console,gremlin-server,gremlin-archetype && mvn verify -pl gremlin-server -DskipIntegrationTests=false -DincludeNeo4j
(excludes giraph-gremlin, hadoop-gremlin,spark-gremlin because I have separate issues building them)

TINKERPOP-1338 Bumped groovy to 2.4.7

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyAddEdgeTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategyProcessTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/EdgeTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/PropertyTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoTest.java

Our provider implementation doesn't allow dashes in property keys. Hence remove them from the gremlin-test.

Remove dashes from labels and property keys

---

gremlin-python/src/main/groovy/org/apache/tinkerpop/gremlin/python/GraphTraversalSourceGenerator.groovy
gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py

previously, in the signature of GraphTraversalSource.__init__, the
bytecode kwarg had a default value of `Bytecode()`. In python, mutable
default kwargs are evaluated at definition time, not when the function
is called. Thus, prior to this commit, the following script would print
`True`:
```python
from gremlin_python.structure import RemoteGraph
from gremlin_python.process import GroovyTranslator
graph = RemoteGraph(GroovyTranslator('g'), None)
traversal_source1 = graph.traversal()
traversal_source2 = graph.traversal()
print(traversal_source1.bytecode is traversal_source2.bytecode)
```
This means that if self.bytecode were mutated, the changes would
persist, and future invocations of `GraphTraversalSource.__init__` would
have created `GraphTraversalSource`s with dirty `self.bytecode`.

revise a mutable default kwarg on GraphTraversalSource

---

gremlin-python/src/main/jython/gremlin_python/process/jython_translator.py

The 'L' suffix on numeric literals is a syntax error in python3. As far
as I can tell, the suffix on the literal in this expression in
JythonTranslator isn't necessary on python2, so removing it restores 2/3
compatibility.

TINKERPOP-1278 : Removed long literal 'L' suffix

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexTest.java

This test uses MetaProperties but didn't require the feature.

Added missing feature requirement

---

CHANGELOG.asciidoc
docs/src/recipes/index.asciidoc
docs/src/recipes/traversal-induced-values.asciidoc

Just a documentation addition. I learned that it's not so good to CTR these as there is sometimes good feedback on Gremlin code that should be incorporated and a PR is the best way to go about gathering that feedback.
VOTE +1

Added new recipe for Traversal Induced Values.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/GremlinResponseFrameEncoder.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

Unfortunately, more testing revealed that the fix for the problem was only masked by the changes in 3.1.3. 
Changed response encoding to not use the session executor when the session has an error condition it is trying to serialize. This should be fine as there is no need to serialized an error condition as part of a transaction and thus no need to have the session thread to do it. That in turn frees up the worker executor to serialize and cancel long run jobs in the session. Removed recommendations for submitting parallel requests on a session from docs.
Works in full with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-1350 was never quite fixed in 3.1.3.

---

docs/src/dev/developer/development-environment.asciidoc
docs/src/dev/developer/for-committers.asciidoc
docs/src/dev/developer/release.asciidoc
docs/src/tutorials/getting-started/index.asciidoc
gremlin-console/bin/gremlin.sh
gremlin-driver/pom.xml

Fixed gremlin.sh and assembly descriptor, updated documentation

Finished renaming distribution from 'apache-' to 'apache-tinkerpop-'

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategyTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategyProcessTest.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkStarBarrierInterceptor.java

https://issues.apache.org/jira/browse/TINKERPOP-1400
There was a severe bug in SubgraphStrategy where the traversal filters that were added for sub-graphing were being recursively applied yielded a StackOverflow. We did not have complex enough tests in SubgraphStrategyProcessTest to illicit the bug. The fix is clever using Step label markers to know if a traversal whose is having their strategy applied is a vertex/edge subgraph filter. Its clever.
* Note: given the differences in strategy application code, this can not easily go into the `tp31`-line without a rewrite. Thus, this is headed to `master/`.
CHANGELOG
```
* Fixed a severe bug in `SubgraphStrategy`.
* Deprecated `SubgraphStrategy.Builder.vertexCriterion()/edgeCriterion()` in favor of `vertices()/edges()`.
```
VOTE +1.

TINKERPOP-1400: SubgraphStrategy introduces infinite recursion if filter has Vertex/Edge steps.

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraph.java

See:
* old PR #372
* JIRA issue https://issues.apache.org/jira/browse/TINKERPOP-1397
As far as I can tell, GraphFilter did not exist in 3.1, and it may not even be possible to induce the buggy traversal behavior describe in #372 (which was all based on master / 3.2).  The underlying datastructure corruption -- putting a StarOutEdge into the `inEdges` map -- does exist on 3.1, and @okram's `addEdge` fix applies cleanly on 3.1, but without `applyGraphFilter`, I'm not sure it even matters for correctness on 3.1.

TINKERPOP-1397 Fix StarGraph.addEdge

---

gremlin-python/src/main/jython/gremlin_python/driver/remote_connection.py
gremlin-python/src/main/jython/gremlin_python/driver/websocket_remote_connection.py
gremlin-python/src/main/jython/gremlin_python/structure/remote_graph.py

Also: Made RemoteConnection into actual abstract base class, fixed typo in remote_graph.
This PR starts the process of adding a websocket driver to the gremlin-python GLV. It is basically working, except I am not sure how you submit the `Bytecode` object and `traversal_source` to the server, since the `Bytecode` object does not serialize to JSON. As is, the the `RESTRemoteConnection` has the same problem. I'm sure there are just a few things missing of which I am not aware. Also, I am not sure how the `traversal_source` should be passed. My initial thought was to pass it as an alias, but this is obviously not correct. Anyway, let me know how to proceed with this and I will move forward.

added simple WebSocketRemoteConnection

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/Io.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphml/GraphMLIo.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONIo.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoIo.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1402
Deprecated IoBuilder.registry() in the process of doing that. This should provide greater flexibility to Graph providers who can now not only supply a custom IoRegistry but also access other non-generalized features of a Mapper.Builder instance.
Tested with `mvn clean install`. I did a one-time test before changing TinkerGraph to stop using the deprecated `registry` method and the build worked fine so I think that even though we can't directly test the old `registry` method anymore, it still should be working ok if provides elect to stick with it.
VOTE +1

TINKERPOP-1402 Added IoBuilder.onMapper() method.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/StandardVerificationStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/StandardVerificationStrategyTest.java

Fixed a small bug in `StandardVerificationStrategy` that caused verification to fail when `withPath` was used in conjunction with `ProfileStep`.  Updated `StandardVerificationStrategyTest` to test traversals with `ProfileStep` and added a test to confirm verification failed on a reducing barrier nested within a repeat while I was at it.
This issue did not arise in TP31 so I took a look and the TP31 `StandardVerificationStrategy` does not have the `ProfileStep` and some other verification verification logic in it that is in master.  Because of this, I pointed this PR only at master but can re-point to TP31 and add the profile step verification in if you guys think that makes sense.
The Travis build appears to have stalled out while downloading artifacts.  Tests passed local with `mvn clean …

TINKERPOP-1405 - profile() doesn't like withPath()

---

gremlin-python/src/main/groovy/org/apache/tinkerpop/gremlin/python/TraversalSourceGenerator.groovy
gremlin-python/src/main/jython/gremlin_python/process/traversal.py

This PR makes some very simple changes to the groovy traversal source generator:
- Removes unnecessary `return` statements (Python returns `None` implicitly)
- Makes the class `TraversalStrategy` into a real base class.

Cleanup of Python code in groovy traversal generator

---

gremlin-python/src/main/groovy/org/apache/tinkerpop/gremlin/python/TraversalSourceGenerator.groovy
gremlin-python/src/main/jython/gremlin_python/driver/driver_remote_connection.py
gremlin-python/src/main/jython/gremlin_python/driver/remote_connection.py
gremlin-python/src/main/jython/gremlin_python/process/traversal.py

This is my first go at implementing a side effects interface for gremlin-python. It allows you to do things like:
```python
from gremlin_python.structure import Graph
from gremlin_python.driver.driver_remote_connection import DriverRemoteConnection
rc = DriverRemoteConnection('ws://localhost:8182', 'g')
graph = Graph()
g = graph.traversal().withRemote(rc)
resp = g.V().aggregate('a')
side_effects = resp.sideEffects()
side_effects.keys()  # a list of keys
for x in side_effects.get('a'):
print(x)
```
Alternately, if the traversal has already been executed, the side effects interface can be accessed like a property:
```python
traversal = g.V().aggregate('a')
results = traversal.toList()
side_effects = traversal.side_effects.get('a')
side_effects = traversal.sideEffects().get('a')
``` 
Now, …

Implemented side effect interface for gremlin-python

---

CHANGELOG.asciidoc
gremlin-driver/pom.xml
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/simple/WebSocketClient.java

https://issues.apache.org/jira/browse/TINKERPOP-1386
Hand to modify the WebSocketClient slightly as it was taking advantage of a bug in netty that was fixed at 4.0.35.final: https://github.com/netty/netty/commit/2e6544fc0e2581f96652be02d86e777e8e0493bc#diff-e4e87d5bebf757b077c19618841f41a6R56
All good with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-1386 Bumped to Netty 4.0.40.final

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy

Looks like:
```
gremlin> 1 +
001    > 2 +
002    > 3 +
003    > x
No such property: x for class: groovysh_evaluate
Display stack trace? [yN] 
003    > 4
==>10
```
Note that the line number remained the same for the correction.
Example from the jira ticket:
```
gremlin> script = """line1
001    > line2
002    > line3
003    > ...
004    > """
==>line1
line2
line3
...
gremlin> 
...
gremlin> 
```
Multi-line query:
```
gremlin> g.V().has(
001    > 'name',
002    > 'marko')
==>v[1]
gremlin>
```

TINKERPOP-1285 added multi-line line number support

---

gremlin-python/pom.xml
gremlin-python/src/main/jython/setup.cfg
gremlin-python/src/main/jython/setup.py

Use `pytest-runner` in order to invoke `pytest` using the `setup.py test` command and properly build dependencies. Otherwise, tests will fail unless all dependencies are installed locally. This PR also specifies versions for `tornado` and `aenum`, as well as removing the custom `PyTest` command from `setup.py` (unneeded due to `pytest-runner`).

Add pytest-runner in order to properly build gremlin-python dependencies.

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypeSerializer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONXModuleV2d0.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphGraphSONSerializerV2d0Test.java

InetAddress serialization/deserialization wasn't working with GraphSON 2.0.
"InetAddress" type has been added to the `GraphSONXModule`.

Fix InetAddress serialization with GraphSON 2.0.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-variants.asciidoc
docs/src/reference/intro.asciidoc
gremlin-python/src/main/jython/gremlin_python/structure/graph.py
gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py
gremlin-python/src/main/jython/tests/structure/test_graph.py

This was easy to implement. Now you get a Path `Path` object back with a `str` that looks like Gremlin-Python.
CHANGELOG:
```
* Added Path to Gremlin-Python with respective GraphSON 2.0 deserializer
```

TINKERPOP-1440: g:Path needs a GraphSON deserializer in Gremlin-Python

---

.gitignore
CHANGELOG.asciidoc
docs/preprocessor/preprocess-file.sh
docs/src/dev/developer/development-environment.asciidoc
docs/src/dev/developer/release.asciidoc
giraph-gremlin/pom.xml
gremlin-console/pom.xml
gremlin-groovy-test/pom.xml
gremlin-groovy/pom.xml
gremlin-python/pom.xml
hadoop-gremlin/pom.xml
neo4j-gremlin/pom.xml
pom.xml
spark-gremlin/pom.xml

Provides implementation for both: 
https://issues.apache.org/jira/browse/TINKERPOP-1449
https://issues.apache.org/jira/browse/TINKERPOP-1431
I'm really happy with this PR. Cleaned up a lot of weird/inconsistent things in the gremlin-python build. Most importantly, I got rid of `-DglvPython` - which I somehow manage to forget to include on more occasions that i care to admit to. The solution is pretty simple - if you have an environment setup to build gremlin-python then you add a `.glv` file to the root of `gremlin-python` (hidden from git). If maven sees that file, it knows that it's OK to activate the profile that builds it.
You can still obviously do:
```text
mvn clean install -pl gremlin-server -Pglv-python
```
which directly activates the profile by its name.
Also note that I bumped …

TINKERPOP-1449 Streamline gremlin-python build

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RangeByIsCountStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RangeByIsCountStrategyTest.java

Enclose filter steps and side-effect steps in `RangeByIsCountStrategy` when `NotStep` is used to wrap part of the traversal.
VOTE: +1

TINKERPOP-1391 issue with where filter

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/JavaTranslator.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1444
GremlinServer caching `Map<Bytecode,Traversal>` is only powerful (really powerful) when bindings are not involved (a solid 50x+ increase in speed). However, given that production systems will typically have bindings in their traversals, then such a cache doesn't help. 
In its place, a update to `JavaTranslator` is provided that makes use of an internal static `METHOD_CACHE` so as to make reflection faster. The speed up is provided below:
```
Prior to method caching:
Bytecode->JavaTranslator call    : 0.13305238800000002
After method caching:
Bytecode->JavaTranslator call    : 0.054839154
```
CHANGELOG
```
* Added a static method cache to `JavaTranslator` to reduce the cost of Java reflection.
```
@spmallette --- if you think that a …

TINKERPOP-1444: Benchmark bytecode->Traversal creation and implement GremlinServer cache if necessary.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Preferences.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/commands/GremlinSetCommand.groovy

https://issues.apache.org/jira/browse/TINKERPOP-1409
This seems like a better use of the empty string setting than to actually just print an empty string line.
```text
gremlin> graph.close()
==>null
gremlin> :set empty.result.indicator ""
gremlin> graph.close()
gremlin> 
```
Pretty small change, but, I didn't CTR this in case someone didn't really like this behavior.  If there are -1s I can just kill this and close the JIRA currently hanging out there as I only kept it open because I saw this dangling issue I wanted to implement.
VOTE +1

TINKERPOP-1409 Print no result line if empty.result.indicator is empty string.

---

CHANGELOG.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1442
While not a perfect implementation, a long run job blocking a close request from the client will now at least get an attempt at interruption rather than consuming the thread indefinitely (or until timeout whenever that is). 
All unit tests are good including gremlin-server integration tests. 
VOTE +1

TINKERPOP-1442 Improved session cleanup on client close [tp31]

---

CHANGELOG.asciidoc
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyDedupTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/AbstractGremlinProcessTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DedupTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1437
Pretty simple - just added a couple of tests - but didn't CTR as I'd feel better with a couple of extra eyes on this as we've had bad tests slip into the suite in the past.  
Runs nicely with `mvn clean install` - doing a `docker/build.sh -t -i -n` now. If anything bad happens I'll post back here.
VOTE +1

TINKERPOP-1437 Added tests for dedup(Scope,String...) overload in DedupTest

---

CHANGELOG.asciidoc
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1451
This is all good now:
```text
gremlin> configuration = new org.apache.commons.configuration.BaseConfiguration()
==>org.apache.commons.configuration.BaseConfiguration@18a3962d
gremlin> configuration.setProperty(TinkerGraph.GREMLIN_TINKERGRAPH_GRAPH_LOCATION, 'test4.gryo')
==>null
gremlin> configuration.setProperty(Graph.GRAPH, TinkerGraph.class.getName())
==>null
gremlin> configuration.setProperty(TinkerGraph.GREMLIN_TINKERGRAPH_GRAPH_FORMAT, 'gryo')
==>null
gremlin> graph = TinkerGraph.open(configuration)
gremlin> v = graph.addVertex('Person')
==>v[0]
gremlin> v.property(list, 'age', 1)
==>vp[age->1]
gremlin> v.property(list, 'age', 2)
==>vp[age->2]
gremlin> v.properties()
==>vp[age->1]
==>vp[age->2] …
```

TINKERPOP-1451 TinkerGraph persistence cannot handle a single file name as the graph location

---

docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasStepTest.java

Made `has[Id|Label|Key|Value]` compatible with the old varargs method signature and added tests to ensure the compatibility.
VOTE: +1

Fixed behavior of has() methods

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/RemoteGraph.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypeSerializer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoSerializers.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1457
Standard tests using lambdas are ignored which is why we didn't catch this in the process tests. I added a single test to `GremlinServerIntegrationTest` to just validate that lambdas could be sent, so we at least have a basic smoke test for that functionality.
Also opened up a few tests by removing some `OptOut` entries on `RemoteGraph`. 
All tests pass with: 
```text
$ mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false
```
Going to kick off a full docker build tonight too.
VOTE +1

TINKERPOP-1457 Fixed Lambda serialization in bytecode for java/groovy.

---

gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py

In python, unless a number is specified with an L, it will be an int whether it's a 32 or 64 bit integer. When a 64 bit integer is serialized, it could potentially be labeled as an int32 which would cause an integer out of bounds error.

Fixed issue in NumberSerializer that could cause integer out of bounds

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializerProvider.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV2d0Test.java

Serialization was broken for unknown objects when creating multiple instances of the GraphSONMapper with different GraphSON versions.
The issue is fixed and I added a test that would be failing if there wasn't this fix.

Fixed SerializerProvider for GraphSON 2.0.

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketGremlinResponseDecoder.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1249
If a connection goes idle, the driver will periodically send a ping to the server to keep the connection alive. 
All good with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`. Also ran some manual tests and did some memory profiling of the driver to make sure there were no leaks.
VOTE +1

TINKERPOP-1249 Add keep-alive functionality to websockets Java Driver

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/TransactionTest.java

https://issues.apache.org/jira/browse/TINKERPOP-944
This exception wasn't used  in the code base at all except for tests. Seems best to just deprecate (in case a graph provider is publically using it). Didn't change the nature of the tests that were using this method, so this should be a non-breaking change.
The change is pretty simple, but I decided not to CTR since "deprecation" was involved. All tests good with `mvn clean install`.
VOTE +1

TINKERPOP-944 Deprecate Graph.Exceptions.elementNotFound()

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/traversal/RemoteTraversalSideEffects.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSourceTest.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteTraversal.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteTraversalSideEffects.java

https://issues.apache.org/jira/browse/TINKERPOP-790
This allowed for `TraversalSource` instances created using `withRemote()` to close out open `RemoteConnection` instances. It also sets up for side-effects created by a "remote" `Traversal` to be cleared from cache on the server. That work is not done yet and is reserved for a different ticket.
Builds with `$ mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
I won't VOTE on this yet as I suspect there might be some feedback from @okram perhaps.
@davebshow note the placeholder for sending the "close" message for side-effects.

TINKERPOP-790 TraversalSource and Traversal implement AutoCloseable.

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.1.x-incubating.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Channelizer.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Handler.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultQueue.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketClientHandler.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthOldIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1467
This was more of a commit than I wanted for `tp31`, but `close()` was really messed up. Fixed a number of race conditions and other logic that would allow the driver to hang on close. Also made it so that the `Cluster` makes an attempt to clean up any `Client` instances that it spawns.
Tested with `mvn clean install` and endlessly with `mvn verify -pl gremlin-server -DskipIntegrationTests=false` (basically ran it for a whole day over and over again).
VOTE +1

TINKERPOP-1467 Corrected a number of problems in close() operations for the driver [tp31]

---

CHANGELOG.asciidoc
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpGremlinEndpointHandler.java

When using Gremlin-Server Client over REST endpoint and the gremlin query results in a groovy script Exception/Error, will output the Throwable class name as well as the Throwable Message in the message body of the HTTP Response

TINKERPOP-1044: Gremlin server REST endpoint - Add Exception Class and Message in Response

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/MasterExecutor.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/WorkerExecutor.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/GraphComputing.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/RepeatStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DedupGlobalStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyDedupTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DedupTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1495
Two bugs fixed. One is simple -- `RepeatStep` wasn't adding labels to the "emit traverser" in OLAP. One line update to `RepeatStep.RepeatEndStep`. The other is related to some `GraphComputing` steps should behave differently if they are being executed at master or workers. In particular, `DedupGlobalStep`. 
Added two new test cases to `DedupTest` provided from the list that demonstrates the two problems (and shows they are now solved).
VOTE +1.

TINKERPOP-1495: Global list deduplication doesn't work in OLAP

---

gremlin-python/src/main/jython/gremlin_python/driver/driver_remote_connection.py
gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py
gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py
gremlin-python/src/test/java/org/apache/tinkerpop/gremlin/python/jsr223/JythonScriptEngineSetup.java
gremlin-python/src/test/java/org/apache/tinkerpop/gremlin/python/jsr223/PythonGraphSONJavaTranslator.java
gremlin-python/src/test/java/org/apache/tinkerpop/gremlin/python/structure/io/graphson/GraphSONReaderTest.java
gremlin-python/src/test/java/org/apache/tinkerpop/gremlin/python/structure/io/graphson/GraphSONWriterTest.java

I have a series of gremlinpython graphson serdes simplifications, followed by a refactor to make type mappings an instance variable, rather than a module-level mapping. I did not attempt to preserve the module API since `gremlinpython` has not entered GA release status.
I welcome any feedback.

Python glv graphson update

---

spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkExecutor.java

This is exactly like #462, except that it tracks a change except it tracks a switch between Spark 1.6 and 2.0 away from functions that manipulate iterables to those that manipulate iterators.
Assuming #462 eventually gets into master, and assuming that TINKERPOP-1389 eventually merges with master, the second merge will conflict.  It still seems marginally safer to make this change in parallel on TINKERPOP-1389 and master/tp32 than just the latter, since the conflict will look more like "oh i better keep one of these two almost-identical edge-case checks" than "oh the Spark 1.x branch had some silly edge case check that I can just delete for 2.0".

TINKERPOP-1525 Avoid starting VP worker iterations that never end (Spark 2.0 version)

---

CHANGELOG.asciidoc
docs/src/dev/io/graphson.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-console/bin/gremlin.sh
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoMapper.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/CoreImports.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyBranchTest.groovy
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyChooseTest.groovy
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java
gremlin-python/src/main/java/org/apache/tinkerpop/gremlin/python/jsr223/PythonTranslator.java
gremlin-python/src/main/jython/gremlin_python/process/traversal.py
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/BranchTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/ChooseTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1507
`Pick.any` and `Pick.none` were not in any of the registered serialization systems -- Java or Python. Nor in the static imports. This has since been rectified and two new test cases add to `BranchTest` and `ChooseTest` to demonstrate that these tokens are now being processed correctly.
CHANGELOG
```
* Added `Pick.none` and `Pick.any` to the serializers and importers.
```
VOTE +1.

TINKERPOP-1507: Pick.any and Pick.none are not in GraphSON or Gremlin-Python

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexProperty.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/FeatureSupportTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexPropertyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-919
That feature allows a graph to specify whether or not it supports multi-properties that allow the same value to be supplied on the same key. Not sure why this wasn't implemented long ago. It was relatively straightforward to put in place. I did take a look at the test suite for existing tests that might have needed this feature included, but I didn't see any.
`mvn clean install -DincludeNeo4j` is all good
VOTE +1

TINKERPOP-919 Added supportsDuplicateMultiProperties()

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/clustering/peerpressure/PeerPressureVertexProgram.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkdumping/BulkDumperVertexProgramTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/TransactionTest.java

These updates resolve issues observed running tinkerpop-3.2.2 tests against Titan. Sorry if this should have been submitted through JIRA.
Failing test was `g_V_peerPressure_byXclusterX_byXoutEXknowsXX_pageRankX1X_byXrankX_byXoutEXknowsXX_timesX2X_group_byXclusterX_byXrank_sumX`
During test execution it was observed at the failing (vote) step that the message scope was `VertexStep(OUT,[knows],edge)`, but this didn't match the message scope, `VertexStep(OUT,edge)`, in the statically initialized set, `VOTE_SCOPE`, returned by `PeerPressureVertexProgram#getMessageScopes`. This caused an error in the custom memory implementation that is resolved by moving the initialization as shown in this PR.
Vertex id checks fail when implementation does not support user-specified ids
Implementation fails …

Message scope initialization in PeerPressureVertexProgram

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/decoration/VertexProgramStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/TraversalStrategiesTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1527
`GraphComputer` strategy registration in `TraversalStrategy.GlobalCache` has been a "uh..I think static{}-blocks load once and only once and when the class is used?" ... This assumption lead to a few errant problems that have been rectified and verified in this PR.
1.) `TraversalStrategies.GlobalCache` strategies can be manipulated without fear of a new instance of the `Graph` or `GraphComputer` class over-writing user manipulations. That is, a test case now proves that `static{}` loads once and only once.
2.) `TraversalStrategies.GlobalCache.getStrategies()` is responsible for ensuring that `static{}` has been called for the particular `Graph` or `GraphComputer` class. A test case now proves that `Class.forName()` is sufficient to …

TINKERPOP-1527: Do not override registered strategies in TraversalStrategies.GlobalCache

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/BranchStep.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/ChooseStepTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyChooseTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/ChooseTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1508
Added `GraphTraversal.choose(predicate,traversal)` and `GraphTraversal.choose(traversal,traversal)`. These are implemented as `choose(traversal,identity())`. Up to this point, `choose()` has been if/then/else-semantics and now with addition, we have if/then-semantics.
VOTE +1

TINKERPOP-1508: Add choose(predicate,trueTraversal)

---

CHANGELOG.asciidoc
docs/src/dev/provider/index.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Tokens.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-932
Allows session close requests to interrupt a long run job at the cost of not closing transactions.
Tested with: `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false -DincludeNeo4j`
VOTE +1

TINKERPOP-932 Added "force" option on session close.

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/OptionalStep.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/OptionalStepTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyOptionalTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/OptionalTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1506
`g.V(1).optional(addV())` created 2 vertices, not one. This is because `optional()` was implemented with the branch-step `ChooseStep`. This has been fixed with a custom `OptionalStep`. Test cases added to verify correct behavior.
Added to `master/` as this is a breaking change. Though, the previous behavior can easily be deemed a bug.
VOTE +1.

TINKERPOP-1506: Optional/Coalesce should not allow sideEffect traversals.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IncidentToAdjacentStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java

https://issues.apache.org/jira/browse/TINKERPOP-1471
Hidden labels can be used by strategies as a way to communicate between "layers" of the compilation tree. This model is now applied to `IncidentToAdjacentStrategy` where if the traversal (as a whole) should NOT be processed by `IncidentToAdjacentStrategy`, then each traversal in the tree is "marked." If the traversal can be processed by `IncidentToAdjacentStrategy`, then there is no need to mark the traversals. This removes the need to, for every traversal, do a recursion from the parent traversal looking for invalidating step classes.
VOTE +1.

TINKERPOP-1471: IncidentToAdjacentStrategy use hidden marker to avoid repeated recursion.

---

neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jGraph.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/step/map/TinkerCountGlobalStep.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/optimization/TinkerGraphCountStrategy.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerHelper.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/optimization/TinkerGraphCountStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1292
Added `TinkerGraphCountStrategy` which will translate `g.V().count()` and `g.E().count()` into direct calls to the underlying `TinkerGraph.vertices/edges` hash maps (`.size()`). Thus, no need to iterate out the vertices/edges and then count the iteration. O(1) time for count.
--- we can extend on this line of reasoning in this branch if people have other ideas for shortcuts.
* Also did some cleanup of some test suites in Neo4jGraph and TinkerGraph that should have been removed long ago when their respective strategy suites were removed.
VOTE +1.

TINKERPOP-1292: TinkerGraphComputer VertexProgramInterceptors

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Path.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ImmutablePath.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/MutablePath.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/B_LP_O_S_SE_SL_Traverser.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/LP_O_OB_S_SE_SL_Traverser.java

https://issues.apache.org/jira/browse/TINKERPOP-1542
Added `Path.isEmpty()` and `Path.head()` with default implementations. Have optimized implementations in `ImmutablePath` and `MutablePath`. These methods are used heavily by the `LP`-class of traversers. A few other random tweaks.
VOTE +1.

TINKERPOP-1542: Add Path.isEmpty() with a default implementation.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/InlineFilterStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/MatchPredicateStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathProcessorStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathProcessorStrategyTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyWhereTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/WhereTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1473
Extended `PathProcessStrategy` to support the following translations which expose more traversals to OLAP processing (works around local star graph violations).
```
where(as(a).out().as(b))    => as(xyz).select(a).where(out().as(b)).select(xyz)
where(as(a).out())          => as(xyz).select(a).filter(out()).select(xyz)
```
Next, given that `PathProcessStrategy` is prior to `InlineFilterStrategy` you get this effect:
```
where(as(a).has(z))          => as(xyz).select(a).has(z).select(xyz)
```
You can see why `PathRetractionStrategy` is important. Without it `xyz` (which are UUIDs in practice) would remain in the traverser's path data.
VOTE +1.

TINKERPOP-1473: Given PathRetractionStrategy, PathProcessorStrategy can be extended to support partial where() inlining.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/traversal/AbstractRemoteTraversalSideEffects.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultQueue.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ResultSet.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteTraversal.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteTraversalSideEffects.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ResultSetTest.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteTraversalSideEffectsTest.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1434
This prevents calls for side-effects that are not yet ready on the server. This was generally a problem in tests, but users could have also run afoul of the issue if they decided to get low-level with the API. It is more likely that they would grab side-effects with a call to `cap()` so this would be a non-issue in that case.
Did multiple runs of `mvn clean install && mvn verify -pl gremlin-server -DincludeNeo4j -DskipIntegrationTests=false` and it passes nicely. I never saw the test failures that triggered the effort to produce a fix for this problem, so @dkuppitz who saw it regularly should give this a review. Also, if travis passes, that would be a good sign - the error was seen there sometimes as well.  Please be sure to use …

TINKERPOP-1434 Block calls on "remote" traversal to get side-effects

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupSideEffectStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalMetrics.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyProfileTest.groovy
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroovyGroupTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProfileTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1428#
`GroupSideEffectStep` is "weird" in that it splits the `valueTraversal` into a pre- and post-traversals where the split is the first `Barrier`-step encountered. This makes it so that its possible for a local child to never be `next()'d` and thus, profiling never initialized for that step. The blanket fix is basically, if a metric is not initialized, don't include it in the profile results. As a side, I fixed a bug in `GroupXXXStep` around empty traverser set values (basically, don't include them).
VOTE +1.

TINKERPOP-1428: profile() throws NPE for union(group, group)

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RangeByIsCountStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RangeByIsCountStrategyTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyMatchTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchTest.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/process/NativeNeo4jCypherCheck.java

https://issues.apache.org/jira/browse/TINKERPOP-1547
Two bugs had always existed because we had commented out tests due to their failure. Fixed the bugs and exposed more tests. Also, some `match()` benchmarks got faster. Finally, I found a bug in `MatchStep.clone()` that only makes itself apparent (and randomly) when there is a `match()`-step within a local child of an OLAP traversal with single processor threading.
VOTE +1.

TINKERPOP-1547: Two bugs found associated with MatchStep: Path retraction and range count.

---

CHANGELOG.asciidoc
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/main/java/Service.java
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/java/ServiceTest.java
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/resources/gremlin-server.yaml
gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/groovy/plugin/gremlin-server-integration.yaml
gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/groovy/plugin/remote.yaml
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerPerformanceTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinAdditionPerformanceTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinResultSetIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthOldIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinTraversalPerformanceTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/TestClientFactory.java
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-performance.yaml

https://issues.apache.org/jira/browse/TINKERPOP-1538
Used something other than 8182 to run the gremlin server tests to avoid port conflicts if gremlin server happens to be running in the background.
Ran `$ mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false -DincludeNeo4j && mvn verify -pl gremlin-console -DskipIntegrationTests=false` to success.
VOTE +1

TINKERPOP-1538 Use non-default port for gremlin server tests

---

CHANGELOG.asciidoc
docker/build.sh

This was a much smaller change than I expected. Originally I was adding some sysctl settings to the dockerfiles. In the end I discovered I could control that and much more from docker itself. So I'm going to go ahead and commit this small change.
example:
```
export DOCKER_OPTS="--cpuset-cpus 0-3 --sysctl net.ipv6.conf.all.disable_ipv6=1 --sysctl net.ipv6.conf.default.disable_ipv6=1"
./docker/build.sh -t -n -i
```

TINKERPOP-1556 allow developers to pass options to docker

---

spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java

Prior to this commit, SGC indiscriminately set the entire job config
as JVM system properties on Spark executors.  It didn't account for
the fact that some config values (e.g. spark.job.description) could
have spaces.  A value with a space wouldn't get quoted.  This led to
Spark workers failing to start, because part of the unquoted value
would be erroneously interpreted as the JVM main class.
This commit makes SGC only pass two config settings as system props:
* gremlin.io.registry
* gremlin.io.kryoShimService

TINKERPOP-1389 Limit JVM system props passed around in Spark jobs

---

CHANGELOG.asciidoc
docker/build.sh
docker/scripts/build.sh
docs/src/dev/developer/development-environment.asciidoc
giraph-gremlin/src/test/resources/giraph-site.xml

Total time went from just over 4 hours to 2:20m. Get back 1:40m of your cycles!
Giraph: startup would wait 3s to connect. solution: wait less. There's still about 7s for shutting down that can be gained back  per test!
Neo4j: very disk IO heavy. solution: work in memory. this benefits the entire build as well. This requires something special below.
In order to build in-memory, you must configure tmpfs with the magical directory name `/usr/src/tinkermem`.
example: 
```
export DOCKER_OPTS="--tmpfs /usr/src/tinkermem:exec,mode=0755,rw,noatime,size=1000m"
```
You can use `1000m` for typical `-t -i -n` usage.  Use `2000m` if building the world plus javadoc, asciidocs.
I will add some of this to the docker contributing / development-environment docs.

TINKERPOP-1557 Improve docker build time with this one weird trick!

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Operator.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/SackFunctions.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MaxLocalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MeanGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MeanLocalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MinLocalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SumGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SumLocalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/NumberHelper.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkStarBarrierInterceptor.java

https://issues.apache.org/jira/browse/TINKERPOP-1399
Moved `NumberHelper` into `org.apache.tinkerpop.gremlin.util`. Note that it's not necessary to add a private constructor, since the only constructor that exists, is already private.
VOTE: +1

TINKERPOP-1399 NumberHelper needs to go into util and have a private constructor

---

CHANGELOG.asciidoc
docs/src/dev/io/graphson.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/main/java/App.java
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/main/java/Service.java
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/java/ServiceTest.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/SingleGremlinScriptEngineManager.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoRegistry.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoPool.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/IoXIoRegistry.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/IoYIoRegistry.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoMapperTest.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGryoMessageSerializerV1d0.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractMessageSerializer.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GryoBaseMessageSerializerV1d0Test.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerIoRegistry.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerIoRegistryV2d0.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphGraphSONSerializerV2d0Test.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1530
Deprecated `getInstance()` usage in favor of `instance()`. This is a non-breaking change for 3.2.0. Will likely remove the deprecated methods for 3.3.0 as a breaking change
All good with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-1530 Consistent use of instance()

---

CHANGELOG.asciidoc
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalInterruptionComputerTest.java

I added a short sleep to prevent traversal from finishing before it can be interrupted during `TraversalInterruptionComputerTest`.
This is a small update but I want to make sure this doesn't cause any build issues for folks.  I was getting this failure before the fix regularly.  After this fix, I've had 10 good runs without issue also `docker/build.sh -t -i -n` succeeded.
VOTE: +1

TINKERPOP-1548: Traversals can complete before interrupted in TraversalInterruptionComputerTest

---

gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py

https://issues.apache.org/jira/browse/TINKERPOP-1561
Added custom `dictify()` method to `Int32IO` that checks for long type. This ensures proper serialization of `long` when using Python 3. Originally in the Jira ticket I proposed a different approach, but after looking more closely this is the simplest approach. 
VOTE +1

TINKERPOP-1561 gremiln-python GraphSONWriter doesn't properly serialize long in Python 3.5

---

CHANGELOG.asciidoc
docker/Dockerfile
docker/build/Dockerfile.template
docker/resources/groovy/grapeConfig.xml
docker/scripts/build.sh
docs/preprocessor/install-plugins.sh
docs/src/reference/gremlin-applications.asciidoc

https://issues.apache.org/jira/browse/TINKERPOP-1363
Now that i squashed all my commits into 2 commits, it looks like this was all done in no time, what a shame!
Anyway, Python stuff is now part of the base image (this change requires that you - the tester - rebuild your Docker images; just drop the old ones).
I've also cleaned up the docs, which contained some dead links to a Groovy site that longer exists. Furthermore I updated `grapeConfig.xml` - in the docs and the one used by the Docker build script. Note that your local `grapeConfig.xml` may look different and still work, but I swear, what we have in this PR is the only way to make it work a) in Docker and b) on brand new development machines. Any other configuration will likely lead to failures when you try to install Console …

TINKERPOP-1363 Cleanup Docker build script for next major release

---

gremlin-python/src/main/groovy/org/apache/tinkerpop/gremlin/python/GraphTraversalSourceGenerator.groovy
gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
gremlin-python/src/main/jython/tests/process/test_traversal.py

https://issues.apache.org/jira/browse/TINKERPOP-1576
This removes the methods `__.__()` and `__.start()` from gremlin-python as they called the respective methods on `GraphTraversal` which doesn't have those methods.

TINKERPOP-1576 gremlin-python calls non-existent methods

---

gremlin-python/src/main/jython/gremlin_python/driver/driver_remote_connection.py

https://issues.apache.org/jira/browse/TINKERPOP-1582
Remote connection driver was encoding the Gremlin Bytecode as a json string, rather than as a dict.  This caused the TraversalOpProcessor to not use the gremlin-server configured deserializers, but rather a non-configurable statically declared serializer to decode the Bytecode string.

TINKERPOP-1582 - Encode Bytecode as a dict, not a string

---

CHANGELOG.asciidoc
gremlin-driver/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1570
Pretty simple, but a version bump so worth a VOTE.  Works with `docker/build.sh -t -i -n` and did a local run of gremlin-server integration tests. Seems all good. I don't see any new dependencies in the packaging so no changes to LICENSE/NOTICE.
VOTE +1

TINKERPOP-1570 Bumped to Netty 4.0.42

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV2d0.java

Issue:
There was a small issue with `ObjectMapper` that was preventing one from doing `objectMapper.readValue(jsonString, Integer.class/Double.class)`. Turns out the issue come from the fact that Jackson normally doesn't uses the `GraphSONTypeResolverBuilder` hook I've introduced for the typing system - and calls directly the default deserializers - for numbers values like `Integer` or `Double`, which led the default deserializers to fail since they are facing a Typed object (`{"@type":..., "@value":....}`) and not simply the value.
Fix: 
Adding simple deserializers for `Integer` and `Double` causes Jackson to use the hook for the typing system and hence deserialization works normally.

Fix numbers deserialization for GraphSON2.

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc

https://issues.apache.org/jira/browse/TINKERPOP-1588
Added a "Terminal Steps" section to the documentation that includes `toList()`, `next(int)`, `tryNext()`, etc.
VOTE +1.

TINKERPOP-1588: Added Terminal Steps section to the docs

---

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV2d0.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV2d0.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV2d0Test.java

Motivation:
`ResponseMessage` used to be deserialized manually via a method on GraphSONMessageSerializerV2d0 (`deserializeResponse()`). Which prevented from using the `Mapper` directly to deserialize a response.
Modification:
Deserialization of `ResponseMessage` is done in a deserializer registered by the `GremlinServerModule` and the GraphSONMessageSerializerV2d0 has been changed accordingly. Also added tests of ser/de for `RequestMessage` and `ResponseMessage` from the `ObjectMapper`.
Result:
Calls like `objectMapper.readValue(jsonString, ResponseMessage.class)` work now.

Add ResponseMessage deserializer for GraphSON2.

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/TraversalParent.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GraphStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/CloseableIterator.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/DefaultCloseableIterator.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/util/CloseableIteratorTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1589
Made it so that the `CloseableIterator` is closed by `GraphStep` if it is provided by the iterator supplier. Furthermore, any steps in a `Traversal` implement `AutoCloseable` then its `close()` method will be called. In this way `Traversal.close()`, the common API a user will work with, has a way to release resources in `Graph` implementations that require it.
Builds with `docker/build.sh -t - i -n`.

TINKERPOP-1589 Re-introduced CloseableIterator

---

gremlin-python/src/main/jython/gremlin_python/driver/driver_remote_connection.py
gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection_threaded.py

https://issues.apache.org/jira/browse/TINKERPOP-1581
This was a simple fix. The `DriverRemoteConnection.__init__` method no longer ignores the `loop` kwarg passed by user. I added two tests using threads as well. One demonstrates how not passing an `IOLoop`, which was in effect the behavior before this PR, will cause a `RuntimeError`. The other shows how you can now pass an `IOLoop` for each thread to avoid this problem.
VOTE +1

TINKERPOP-1581 Gremlin-Python driver connection is not thread safe.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStartStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategy.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyAddVertexTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1521
`AddVertexStartStep` was using an `EmptyTraverser` to compute the `Parameters`. I thus, create a dummy traverser that has respective traversal side-effects. Added two new test cases to `AddVertexTest`.
```groovy
gremlin> g = TinkerGraph.open().traversal()
gremlin> g.withSideEffect("a", "marko").addV().property("name", select("a"))
==>v[0]
gremlin> g.V().valueMap()
==>[name:[marko]]
gremlin>
```
Finally, realized that `PathRetractionStrategy` was adding a `NoOpBarrierStep` to the end of local traversal. This is pointless computation as 99% of local traversals are `by()`-modulators that only need the first `next()`.
VOTE +1.

TINKERPOP-1521: Mutating steps don't recognize side-effects

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/CoreTraversalTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1116
Tweaked the typing of various `__` anonymous traversal steps as various do not need generic typing. This is in master/ as its breaking because user that do `<Vertex>out()` will simply need to do `out()` (and thus, remove the explicit typing).
VOTE +1.

TINKERPOP-1116: Some anonymous traversal steps can be hard typed.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IncidentToAdjacentStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/IncidentToAdjacentStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1545
Implemented changes as discussed in https://github.com/apache/tinkerpop/pull/486.
VOTE: +1

TINKERPOP-1545 IncidentToAdjacentStrategy is buggy

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderGlobalStep.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/StepTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeGlobalStepTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyRangeTest.groovy
gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/RangeTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1549
Added `skip(long)` and `skip((Scope,long)` which call the `range(low,high)` equivalents with -1 as the high.
Also added test cases and fixed the OLAP implementation (which probably never worked before).
Note, that I implemented `equals()` for `RangeGlobalStep`, because hash code collisions are very likely. For the same reason I also removed the hash code inequality check from `StepTest`.
VOTE: +1

TINKERPOP-1549 Implement skip()

---

CHANGELOG.asciidoc
docs/src/dev/io/graphson.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Handler.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAuthenticationHandler.java

This is a small change but I was hoping for some tests by driver providers before merging as this change messes with the authentication scheme a bit. It should be a backward compatible change, but I just wanted to be sure I didn't break anything before merging this.
VOTE +1

TINKERPOP-1600 Added base64 encoded string to sasl challenge

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/SampleGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/CollectingBarrierStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/ComputerVerificationStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/OrderedTraverser.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/ProjectedTraverser.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoVersion.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/function/MultiComparator.java

https://issues.apache.org/jira/browse/TINKERPOP-1248
We now support having the projected data of both `OrderGlobalStep` and `SampleGlobalStep` being co-located with the `Traverser` via a traverser wrapper called `ProjectedTraverser`. This allows us to order traversers based on any projects of the local star graph -- NOT just `PathProcessor.ID`. This also reduces the complexity of ordering with `by()`-modulation as we don't have to constantly apply a projection traversal. Finally, this reduces the chances of problems with serializing the order/sample traversals -- e.g. what if side-effects are accessed and the traversals in the bi-operators are detached from the parent traversal.
--- before I VOTE +1, I'm going to see if I can use this same model for `GroupStep`. If so, huge. If its …

TINKERPOP-1248: OrderGlobalStep should use local star graph to compute sorts, prior to reduction.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroupStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupSideEffectStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroovyGroupTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroupTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1606
This is huge. With this PR and https://github.com/apache/tinkerpop/pull/538 we will no longer have any reducers that require a `Traversal` in its representation. This will remove a great number of problems associated with maintaining state in a reducer. Moreover, OLAP `group()` had peculiarities associated with the fact that the `valueTraversal` was detached from the root traversal and thus, side-effects were not accessible. This is no longer the case. `GroupStep` and `GroupSideEffectStep` have been completely refactored to only require a `BinaryOperator`-based reducer. This is going to make my life soooooooooo much easier (you don't know the troubles I've suffered because of stateful reducers).
Note that this PR is headed to `master/` …

TINKERPOP-1606: Refactor GroupStep to not have the reduction traversal included in its BiOperator.

---

gremlin-console/src/main/bin/gremlin.sh
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy

https://issues.apache.org/jira/browse/TINKERPOP-1605
```
daniel@cube /tmp $ ls *.groovy
test.groovy
daniel@cube /tmp $ /projects/apache/tinkerpop/bin/gremlin.sh -e test.groovy 
2
4
6
daniel@cube /tmp $ /projects/apache/tinkerpop/bin/gremlin.sh -e test2.groovy 
Gremlin file not found at [test2.groovy].
daniel@cube /tmp $  /projects/apache/tinkerpop/bin/gremlin.sh
\,,,/
(o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> graph.io(graphml()).readGraph('data/grateful-dead.xml')
==>null
==>graphtraversalsource[tinkergraph[vertices:808 edges:8049], standard]
```
VOTE: +1

TINKERPOP-1605 gremlin-console 3.2.3 -e can no longer take paths relative to current working directory

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/GroovyEnvironmentIntegrateSuite.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/GroovyEnvironmentSuite.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessComputerSuite.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/process/GroovyProcessStandardSuite.java

https://issues.apache.org/jira/browse/TINKERPOP-1610
Graph Providers no longer need to implement these going forward. Note that the new model for testing groovy will be similar to the approach taken for gremlin-python (which obviously doesn't have all this tests required of the provider). By making this change, we reduce the testing burden on graph providers as this is a whole body of tests they can just ignore now. This is a non-breaking change and will setup for removal and migration of the `gremlin-groovy-test` classes to `gremlin-groovy` (or potentally `gremlin-test` if the test is general enough to aid in testing the `GremlinScriptEngine` environment).
This is a pretty simple PR at this point, but since it was a major deprecation I wanted to go through the vote process rather than …

TINKERPOP-1610 Deprecated Groovy test suites

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategyTest.java

`PathRetractionStrategy` was not pushing `keepLabels` down into sibling traversals of children with label requirements.  Labels were also not being pushed down into `TraversalParents` earlier in the traversal.
@okram I saw you had a `PathRetractionStrategy` issue while doing some other work.  Do you have a traversal you were getting a failure on?  I can make sure this fixes it and adds a test case if so.
`./docker/build.sh -t -i` success
```
[INFO] Apache TinkerPop .................................. SUCCESS [30.949s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [9.462s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [56.670s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [4.887s]
[INFO] Apache TinkerPop :: Gremlin Groovy …
```

TINKERPOP-1583: PathRetractionStrategy retracts keys that are actually needed

---

CHANGELOG.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyClassLoader.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/ManagedConcurrentValueMap.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/jsr223/GremlinGroovyScriptEngineIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1560
By configuring the `ManagedConcurrentValueMap` to have weak references, the `GremlinGroovyClassLoader`, and therefore the `GremlinGroovyScriptEngine`, are now able to "forget" classes that are no longer used. It was determined that the cache of these classes would grow indefinitely for each script passed to the `GremlinGroovyScriptEngine`, thus allowing the metaspace to continue to grow. It isn't really possible to write tests to verify that this change works, but I did test manually by watching memory usage in a profiler and could see that metaspace memory stayed stable and that classes were unloading from the classloader over time.
@BrynCooke could you please give a look at this one when you get a chance?
VOTE +1

TINKERPOP-1560 Used ManagedConcurrentValueMap in GremlinGroovyClassLoader

---

gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py

A good example of the need for this fix is with these types:
datetime.date
datetime.datetime
Since a datetime is a subclass of a date and that a dict is unordered... it might happen that the wrong serializer is selected. (since isinstance(my_datetime_instance, datetime.date) == True)

Fix the serializers lookup to handle the type first, then the class inheritance

---

CHANGELOG.asciidoc
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkGraphComputer.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/Spark.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/io/InputRDDFormat.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/structure/io/PersistedInputRDD.java

org.apache.tinkerpop.gremlin.spark.structure.Spark is a SparkContext holder for SparkGraphComputer.
It was refactored to detect external stop calls and recreate SparkContext in that case.
Context creation process was reordered to make all configuration options take effect.
Spark.create() methods return created context now.
The external stop also requires SPARK-18751 fix, that was integrated into Spark 2.1.
By the way the refactoring and configuration loading part gives effect on all versions.

TINKERPOP-1271: Refactor SparkContext creation and handling of sc.stop()

---

gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py

This fixes the duplicate serialization issue in gremlin-python's PropertySerializer:
[https://issues.apache.org/jira/browse/TINKERPOP-1635](https://issues.apache.org/jira/browse/TINKERPOP-1635)
This pull requests removes the second call to `writer.toDict()` and changes a property value in the respective unit test to an int. That makes the test fail with the duplicate serialization and pass with the fixed version.

TINKERPOP-1635 Fix duplicate serialization of element property in PropertySerializer

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ComputerAwareStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategyTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyChooseTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/ChooseTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1626
`ComputerAwareStep.EndStep` was using `path.extend()` and not `traverser.addLabel()` to append step labels in OLAP and thus, the step label data wasn't being recorded because `path.extend()` is an immutable operation. Also, updated `PathRetractionStrategy` to look like `LazyBarrierStrategy's` recent tweaks to not add a barrier to the end of a traversal -- leave that up to `RemoteStrategy`.
VOTE +1.

TINKERPOP-1626: choose() is buggy in OLAP

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraversalVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/finalization/ComputerFinalizationStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/GraphComputing.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/ComputerVerificationStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/StandardVerificationStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoSerializers.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoVersion.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/UtilSerializers.java
gremlin-python/src/test/java/org/apache/tinkerpop/gremlin/python/jsr223/PythonProvider.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/ComplexTest.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkStarBarrierInterceptor.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/TinkerGraphNoStrategyProvider.java

https://issues.apache.org/jira/browse/TINKERPOP-1640
Split `ComputerVerificationStrategy` into two strategies:
1. `ComputerVerificationStrategy` -- does all the `VerificationException` analyses.
2. `ComputerFinalizationStrategy` -- does all the `GraphComputing` step configurations.
This was enabled so that users who are certain that the verification logic of `ComputerVerificationStrategy` is too strict for their particular traversal, can turn off verification and still have a proper executing OLAP traversal.
VOTE +1.

TINKERPOP-1640: ComputerVerificationStrategy gives false errors

---

pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1645
Just a version bump, but as it is a version bump an explicit vote would be good.  I've only ran tests for 'tp31' at this point, but will run tests on the other branches prior to merge. There really shouldn't be any problems as this release of groovy was pretty small.
VOTE +1

TINKERPOP-1645 Bump to groovy 2.4.9

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AddPropertyStep.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyProcessTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1504
Newly added properties triggered "changed" events when using `EventStrategy` but the specific key that was newly added was not available in the mutation listener. The listener would simply report the new value only. After this change the listener now gets a `DetachedVertexProperty` / `DetachedProperty` with the newly added key and a null value set.
Builds with `mvn clean install` - VOTE +1

TINKERPOP-1504 Added the property key to events for new properties.

---

CHANGELOG.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/jsr223/GephiRemoteAcceptor.groovy
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/plugin/GephiRemoteAcceptor.groovy
gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/groovy/plugin/DriverRemoteAcceptor.java
gremlin-console/src/main/java/org/apache/tinkerpop/gremlin/console/jsr223/DriverRemoteAcceptor.java
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/groovy/plugin/HadoopRemoteAcceptor.java
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/jsr223/HadoopRemoteAcceptor.java

https://issues.apache.org/jira/browse/TINKERPOP-1303
Here's the output for "help" in the plugins that support `:remote` as an option in the console:
```text
gremlin> :remote connect tinkerpop.gephi
==>Connection to Gephi - http://localhost:8080/workspace1 with stepDelay:1000, startRGBColor:[0.0, 1.0, 0.5], colorToFade:g, colorFadeRate:0.7, startSize:10.0,sizeDecrementRate:0.33
gremlin> :remote config help
==>:remote config [host <host>|port <port>|workspace <name>|stepDelay <ms>|startRGBColor <0.0,0.0,0.0>|colorToFade [r|g|b]|colorFadeRate <0.0>|sizeDecrementRate <0.0>|startSize <0.0>|visualTraversal <graph>|help]
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Configured localhost/127.0.0.1:8182
gremlin> :remote config help
==>:remote config [timeout [<ms>|none]|alias …
```

TINKERPOP-1303 Adds help option to :remote config command

---

CHANGELOG.asciidoc
docs/src/dev/developer/development-environment.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-console/pom.xml
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
gremlin-console/src/test/python/setup.cfg
gremlin-console/src/test/python/setup.py
gremlin-console/src/test/python/tests/__init__.py
gremlin-console/src/test/python/tests/test_console.py
gremlin-console/src/test/python/x.groovy
gremlin-console/src/test/python/y.groovy
gremlin-console/src/test/python/z.groovy

https://issues.apache.org/jira/browse/TINKERPOP-1653
This is a non-breaking change and simply allows multiple `-i` and `-e` options on gremlin.sh. The old method for passing a single script name to gremlin.sh remains intact as well. Had to write a custom parser for the command line arguments to do this because it doesn't appear that `CliBuilder` is capable of parsing the in the manner necessary to support this feature unfortunately.
Here's some example usage given these three scripts:
```text
$ more *.groovy
::::::::::::::
x.groovy
::::::::::::::
x = 1 + 1
::::::::::::::
y.groovy
::::::::::::::
y = args.collect{Integer.parseInt(it)}.sum()
::::::::::::::
z.groovy
::::::::::::::
z = "argument=" + args
```
This is old, now deprecated, method that is still supported:
```
$ bin/gremlin.sh …
```

TINKERPOP-1653 Allow multiple scripts to be passed to gremlin.sh

---

docs/src/dev/provider/index.asciidoc
docs/src/reference/the-graphcomputer.asciidoc

Combine two typo PR's (#580 & #581) to one and do it against tp32.

fix typo in docs of OLTP

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/GremlinScriptContext.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java

https://issues.apache.org/jira/browse/TINKERPOP-1095
The issue is about creating a custom `ScriptContext`  for improved usability purposes but it's since morphed to an important performance improvement for the `GremlinScriptEngine` and thus also Gremlin Server.  The change uses the custom `ScriptContext`, named `GremlinScriptContext`, to  prevent usage of the `SimpleScriptContext` which creates `ByteBuffer` instances on every call to `eval()` and those instances were never used making them immediately available to GC. 
For Gremlin Server it seems that it has been cycling GC way more than it should have been. Here's GC activity before my changes:
and GC activity after my changes:
Obviously the amount of memory allocated was greatly reduced in the process. The number of `byte[]` instances …

TINKERPOP-1095 Gremlin Server performance improvement with SimpleScriptContext

---

docs/src/reference/the-traversal.asciidoc
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyHasTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1625
Added tests for `hasKey()` and `hasValue()`. Also tweaked up `HasTest` which had dangling traversers not being tested. Updated docs with `hasKey()` and `hasValue()` examples. Note that in the documentation we do not use Java var args conventions, but instead try and keep it general to all languages. Thus, the "technique" of `hasKey(String,String...)` is simply `hasKey(keys...)`.
VOTE +1.

TINKERPOP-1625: Improvements to has() related steps

---

.gitignore
docker/scripts/build.sh

This lets docker use a local maven proxy for faster download.  Speeds up build time for those of us out in the boonies with slow internet.

TINKERPOP-1659 Docker uses custom maven settings.xml

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-python/src/test/resources/org/apache/tinkerpop/gremlin/python/driver/gremlin-server-modern-secure-py.yaml
gremlin-server/conf/gremlin-server-rest-secure.yaml
gremlin-server/conf/gremlin-server-secure.yaml
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/HttpChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/AbstractAuthenticationHandler.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/HttpBasicAuthenticationHandler.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAuthenticationHandler.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java

Abstracting over the http authentication allows for easy extensibility
for users/implementors to provide their own classes for http auth beyond
basic auth. The general issue is that there is a fixed overhead to
hashing passwords securely. This change allows for implementing things
like HMAC token auth and plugging them in easily to the gremlin server.

TINKERPOP-1657 Provide abstraction to easily allow different HttpAuth schemes

---

gremlin-console/src/test/python/tests/test_console.py
gremlin-python/src/main/jython/tests/process/test_strategies.py
gremlin-python/src/main/jython/tests/process/test_traversal.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py
gremlin-python/src/main/jython/tests/structure/test_graph.py
gremlin-python/src/main/jython/tests/test_statics.py

A simple PR that removes unnecessary `unittest` code from the Gremlin-Python test suite. 
VOTE +1

TINKERPOP-1665 Remove unittest from Gremlin-Python tests

---

docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/OpLoader.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/standard/StandardOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1663
Provides a configuration option to validate the number of parameters that gremlin server will accept on a request for script evaluation.
Ran integration tests for gremlin-server and console.
vOTE +1

TINKERPOP-1663 Validation for maximum number of parameters on a request

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RepeatUnrollStrategy.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyRepeatTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/RepeatTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1668
If the child traversal of `RepeatStep` has a `LoopsStep`, then `RepeatUnrollStrategy` should not be allowed as it the loops will have been linearized and thus, never incremented. Added test case to verify expected working behavior.
VOTE +1.

TINKERPOP-1668: RepeatUnrollStrategy should not execute if there is a LoopStep used.

---

gremlin-python/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1577
I'd forgotten that I'd long ago made this change to the python build. It basically sets up two separate python environments with virtualenv - one for python 2.x and one for 3.x - so that we can test both versions against our code. 
VOTE +1

TINKERPOP-1577 Building gremlin-python with python 2/3

---

CHANGELOG.asciidoc
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineFileSandboxTest.java
gremlin-groovy-test/src/main/resources/org/apache/tinkerpop/gremlin/groovy/jsr223/sandbox-empty-static-variable-types.yaml
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/AbstractSandboxExtension.groovy
gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/jsr223/customizer/FileSandboxExtension.groovy

Check if variable is null to avoid NPE
If staticVariableTypes is an empty list in the YAML file, then we throw
an NPE by trying to run collectEntries() on a null object or trying to
run containsKey() on a null object.
https://issues.apache.org/jira/browse/TINKERPOP-1666

TINKERPOP-1666 YAML file supplied to FileSandboxExtension can have empty staticVariableTypes

---

CHANGELOG.asciidoc
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java

https://issues.apache.org/jira/browse/TINKERPOP-1673
`GroovyTranslator` now uses Groovy `[...]` map notation instead of `new LinkedHashMap(){{ put() }}` notation in order to make the String translation from Bytecode to Gremlin-Groovy cleaner and easier to read.

TINKERPOP-1673: GroovyTranslator produces Gremlin that can't execute on :remote

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/traversal/step/map/RemoteStep.java

For consistency with previous behavior, if an unchecked exception is set on the returned future throw that instead of the wrapped CompletionException.
For [TINKERPOP-1675](https://issues.apache.org/jira/browse/TINKERPOP-1675).

TINKERPOP-1675 Throw underlying unchecked exception in processNextStart

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyRepeatTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/RepeatTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1678
Fixed a typo-bug in `GraphTraversal` where `until(Predicate)` was actually calling `emit(Predicate)`. A very low probability traversal and thus, it was never uncovered until now. However, fixed and added a test case that verifies that the previous behavior was wrong and the new behavior is write.
VOTE +1.
NOTE: This is the work done here https://github.com/apache/tinkerpop/pull/606, but now there is a test case.

TINKERPOP-1678: until(Predicate) is actually calling emit(Predicate)

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraph.java

By default, StarGraph invokes intern() on vertex label and property
key strings.  It also toString()s vertex and edge IDs for comparisons
and existence checks.
This commit introduces a new StarGraph builder with a pair of boolean
options controlling these behaviors.

TINKERPOP-1680 Add string performance options to StarGraph

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GraphStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyHasTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1681
Fixed folding of multiple `hasId()`'s into `GraphStep`.
VOTE: +1

TINKERPOP-1681 Multiple hasId's are or'd into GraphStep

---

gremlin-dotnet/src/Gremlin.Net/Process/Traversal/ITraversal.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/NamingConversions.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/EnumTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/PredicateTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/StrategiesTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-1552
This mainly removes explicit type castings that are now obsolete thanks to changes from the pull request #620 from @jorgebay. It also makes the Dictionary CSharpToJavaEnums in NamingConversions private to avoid direct access to it as GetEnumJavaName should be used instead.

TINKERPOP-1552: Minor code cleanup for Gremlin.Net

---

gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionFactory.cs
gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs
gremlin-dotnet/src/Gremlin.Net/Driver/GremlinServer.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Messages/ResponseStatusCode.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Tokens.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientAuthenticationTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/appsettings.json
gremlin-dotnet/test/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1552
This adds support for authentication with Plain SASL (username + password) to the Gremlin.Net driver. The functionality was originally implemented for the pre-GLV version of Gremlin.Net by @TigerSun-MS from the @CosmosDB team (see FlorianHockmann/Gremlin.Net#7).
The Gremlin Server instance used for the authentication related integration tests complains during startup about some duplicate metric name, but everything works as expected and all tests pass. This is the beginning of the stack trace:
```
[WARNING] Could not initialize gremlin-groovy GremlinScriptEngine as init script could not be evaluated
java.lang.IllegalArgumentException: A metric named org.apache.tinkerpop.gremlin.server.GremlinServer.gremlin-groovy.sessionless.class-cache. …
```

TINKERPOP-1552: Add support for authentication (Plain SASL) to Gremlin.Net

---

gremlin-dotnet/glv/AnonymousTraversal.template
gremlin-dotnet/glv/Enum.template
gremlin-dotnet/glv/GraphTraversal.template
gremlin-dotnet/glv/GraphTraversalSource.template
gremlin-dotnet/glv/NamingConversions.template
gremlin-dotnet/glv/P.template
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Barrier.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Bytecode.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Cardinality.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Column.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/DefaultTraversal.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Direction.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphSONVersion.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GryoVersion.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/NamingConversions.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Operator.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Order.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/P.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Pick.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Pop.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Scope.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/T.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs
gremlin-dotnet/src/Gremlin.Net/Structure/Graph.cs

https://issues.apache.org/jira/browse/TINKERPOP-1552
This change adds many comments to Gremlin-DotNet, especially for the GLV part. Some comments where taken from the respective Java classes. It also adds comments to most of the auto-generated methods to tell the user what the method does.
Example for the anonymous class `__`:
```cs
/// <summary>
///     Spawns a <see cref="GraphTraversal{SType, EType}" /> and adds the out step to that traversal.
/// </summary>
public static GraphTraversal<object, Vertex> Out(params object[] args)
{
return new GraphTraversal<object, object>().Out(args);
}
```
And for a `GraphTraversal` step:
```cs
/// <summary>
///     Adds the aggregate step to this <see cref="GraphTraversal{SType, EType}" />.
/// </summary>
public GraphTraversal< S , E > Aggregate …
```

TINKERPOP-1552: Improve comments in Gremlin-DotNet

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalInterruptionComputerTest.java

The change in https://github.com/apache/tinkerpop/commit/9983fd210872d57750d49191c391ba8e380e6023 included decreasing the maximum total test time threshold from 5 seconds to 1 second in TraversalInterruptionComputerTest. This PR proposes to revert the timeout back to the original 5 seconds to resolve test failures observed in some custom graph computer implementations.

Restore 5 second cutoff time in TraversalInterruptionComputerTest

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalMetrics.java

https://issues.apache.org/jira/browse/TINKERPOP-1688
See the example of what the revised pretty print looks like if annotations are present in the metrics in the link to the issue above (it's in the comments).
VOTE +1

TINKERPOP-1688 Add annotations to TraversalMetrics pretty print

---

CHANGELOG.asciidoc
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyProcessTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1691
Tests no longer assume that element state is sync'd in memory. @pietermartin can you please review this one? I think this does what you need.
Builds with `mvn clean install -DincludeNeo4j`
VOTE +1

TINKERPOP-1691 Changed semantics of EventStrategyProcessTest

---

CHANGELOG.asciidoc
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Channelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GremlinServer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/HttpChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/NioChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/ServerGremlinExecutor.java

https://issues.apache.org/jira/browse/TINKERPOP-999
Pretty simple - I probably could have CTR'd this but since it was a breaking change on 3.3.0 I wanted folks to be more aware of it in case someone was using this class in some way I'm not imagining.
Builds with `mvn clean install -DskipTests && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-999 Removed generics from ServerGremlinExecutor

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Transaction.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/AbstractTransaction.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/TransactionException.java
neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jGraph.java

https://issues.apache.org/jira/browse/TINKERPOP-1004
`TransactionException` is no longer bound to usage by `AbstractTransaction`.  Prescribed a more general usage of it with the Transaction interface.
Builds with `mvn clean install -DincludeNeo4j && mvn verify -pl gremlin-server -DskipIntegrationTests=false -DincludeNeo4j`
VOTE +1

TINKERPOP-1004 Expand usage of TransactionException

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/StringFactory.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/PropertyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1445
This was an easy change but I decided to do this as a PR so that the change would be noted as it does affect something that is user facing. I did this change for 3.3.0 only in case someone is depending on the `toString()` value of `Property` for some reason.
```text
gremlin> g.addV().property('short','pretty short').property('long','this one is much longer so it is going to get truncated a bit').as('a').
......1>   addE('self').property('short','pretty short').property('long', 'this one is much longer so it is going to get truncated a bit').from('a').to('a') …
```

TINKERPOP-1445 Add ellipses for long property values

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphComputerTest.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/computer/TinkerMessageBoard.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/computer/TinkerMessenger.java

https://issues.apache.org/jira/browse/TINKERPOP-1519
This change modifies the tinker graph computer so that each message sent in a vertex program remembers its scope. Previously when the receiveMessages method on TinkerMessenger was called it would loop through ALL message scopes and then ALL messages, which is incorrect. Now the method loops over each scope, and then each message within that scope.
I have added the regression test suggested in the JIRA ticket and run mvn clean install locally to confirm everything passes OK.
I had a quick look at the latest master, and this bugfix may need to be merged there too.

TINKERPOP-1519: tinker graph computer does not handle multiple scopes

---

CHANGELOG.asciidoc
docs/src/reference/the-graph.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Transaction.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/AbstractTransaction.java

https://issues.apache.org/jira/browse/TINKERPOP-741
Deprecated  methods related to transaction retry in preparation for removal in 3.3.0.  Builds with `mvn clean install`.
VOTE +1

TINKERPOP-741 Deprecated Transaction.submit(Function)

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/resources/gremlin-server.yaml
gremlin-console/conf/remote-objects.yaml
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV1d0.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGraphSONMessageSerializerV2d0.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/AbstractGryoMessageSerializerV1d0.java
gremlin-python/src/test/resources/org/apache/tinkerpop/gremlin/python/driver/gremlin-server-modern-secure-py.yaml
gremlin-server/conf/gremlin-server-classic.yaml
gremlin-server/conf/gremlin-server-modern-py.yaml
gremlin-server/conf/gremlin-server-modern-readonly.yaml
gremlin-server/conf/gremlin-server-modern.yaml
gremlin-server/conf/gremlin-server-neo4j.yaml
gremlin-server/conf/gremlin-server-rest-modern.yaml
gremlin-server/conf/gremlin-server-rest-secure.yaml
gremlin-server/conf/gremlin-server-secure.yaml
gremlin-server/conf/gremlin-server-spark.yaml
gremlin-server/conf/gremlin-server.yaml
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/driver/remote/gremlin-server-integration.yaml
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-performance.yaml

https://issues.apache.org/jira/browse/TINKERPOP-1694
Pretty simple - the `ioRegistries` option isn't new - we're just promoting that now as the preferred (and in the future only) way to add `IoRegistry` instances to the serializers.
Builds with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false && mvn verify -pl gremlin-console -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-1694 Deprecated useMapperFromGraph

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/JavaTranslator.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java

https://issues.apache.org/jira/browse/TINKERPOP-1704
`JavaTranslator` would convert `Tree` to `HashMap` and `BulkSet` to `HashSet`. While passing in such objects through `Bytecode` is low probability, it is still good to cover this corner case (especially for `Tree`, where the semantics are a bit different than `Map`).
VOTE +1

TINKERPOP-1704: XXXTranslators are not being respective of BulkSet and Tree.

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedFactory.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceFactory.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedVertexTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceVertexTest.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/structure/io/gryo/GryoSerializerIntegrateTest.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/decoration/HaltedTraverserStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1701
`HaltedTraverserStrategy` is used by serializing systems (e.g. GremlinServer, OLAP) to decide how to format the result set. For instance, are the objects `DetachedXXX` or `ReferenceXXX`. In order to make this functionality generalized to objects within collections, `DetachedFactory` and `ReferenceFactory` were updated to handle `Tree`, `Map`, `BulkSet`, `Set`,  and `List` (in any arbitrarily nested configuration). Test cases added, and stuff passes.
VOTE +1.

TINKERPOP-1701: HaltedTraverserStrategy should recurse into collections for detachment.

---

docs/src/tutorials/getting-started/index.asciidoc

Gremlin Server is started without REST channel (so next attempt to POST Gremlin query fails).

Minor tutorial fix

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/AndP.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/ConnectiveP.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/OrP.java

https://issues.apache.org/jira/browse/TINKERPOP-1289
Removed deprecated constructors. (for TinkerPop 3.3.0).
VOTE +1

TINKERPOP-1289: Remove deprecated ConnectiveP, AndP, and OrP constructors.

---

docs/src/reference/the-traversal.asciidoc

https://issues.apache.org/jira/browse/TINKERPOP-1710
There was confusion as to what should happen what `tree()` sees duplicate objects in the same depth of the tree. The behavior is as expected and not a "bug." Tree is constructed using path objects that are "horizontally" linked. If two objects are the same at the same depth, then they are merged into one none in the tree data structure.
VOTE +1

TINKERPOP-1710: Add a note on tree() by-modulation and uniqueness of tree branches.

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Order.java
gremlin-python/src/main/jython/gremlin_python/process/traversal.py

https://issues.apache.org/jira/browse/TINKERPOP-1142
Removed deprecated `valueIncr`, `valueDecr`, `keyIncr`, and `keyDecr`. These were deprecated long ago and replaced with `Column.values` and `Column.keys` along with the use of `Order.incr` and `Order.decr` accordingly.
VOTE +1

TINKERPOP-1142: Remove deprecated valueIncr, valueDecr, keyIncr, keyDecr.

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyTest.java
gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ElementIdStrategyProcessTest.java

https://issues.apache.org/jira/browse/TINKERPOP-832
Removed deprecated `addV()`, `addE()`, `addInE()`, and `addOutE()` methods that are no longer supported given the introduction of the `to()` and `from()` modulators. This is actually a very good deprecation to remove as there is a lot of extraneous testing (and bug proneness) around these methods given the complicated interactions with the desired overloaded methods of the same name -- lots of parameter type checking and validation (gross).
VOTE +1.

TINKERPOP-832: Remove deprecated addV/E/InE/OutE methods

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WsAndHttpChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAndHttpBasicAuthenticationHandler.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WebSocketHandlerUtil.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/WsAndHttpChannelizerHandler.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/AbstractGremlminServerChannelizerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/HttpChannelizerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/NioChannelizerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/channel/WsAndHttpChannelizerIntegrateTest.java

[TINKERPOP-915](https://issues.apache.org/jira/browse/TINKERPOP-915)
Most of this is tests. I added an integration test that goes over the
functionality of both the http and websocket channelizers using the new
`WsAndHttpChannelizer`. I added an additional test on top of that to
switch between using WebSockets and http.
The change itself leverages the existing `WebSocketChannelizer` to
provide the base pipeline setup. It has everything needed handler-wise
to service both http and ws connections. The
`WsAndHttpChannelizerHandler` then detects whether the incoming request
is a plain http connection or a WebSockets connection. If it's an http
connection, the channelizer handler swaps out the request handler
appropriately for whether or not authentication has been enabled.

TINKERPOP-915 Add combined handler for Http and Websockets

---

CHANGELOG.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java

https://issues.apache.org/jira/browse/TINKERPOP-1714
Prior to this change timeouts were considered from the time the script started evaluation which probably isn't in line with user expectations but also made it hard to clear the job queue on an overloaded server. This change also has the benefit of simplifying the code as well as reducing the number of jobs submitted to the various thread pools.
VOTE +1

TINKERPOP-1714 GremlinExecutor checks for timeout from time script submitted

---

docs/src/reference/the-traversal.asciidoc

https://issues.apache.org/jira/browse/TINKERPOP-1709
Listed and referenced (linked to) those steps that support the various "modulations." The only one not added was `as()`, given that its not really a modulator and works for all steps.
VOTE +1

TINKERPOP-1709: Add a list of all the steps that support by()/from()/to()/as()/option()

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/VertexComputing.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/TraversalVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/VertexProgramStep.java
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/Constants.java
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/HadoopConfiguration.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkHadoopGraphProvider.java

https://issues.apache.org/jira/browse/TINKERPOP-1720
Removed Constants and VertexComputing method. Created another ticket for the `ScriptElementFactory` deprecation (@dkuppitz area of work).
VOTE +1.

TINKERPOP-1720: Remove deprecated Hadoop code

---

CHANGELOG.asciidoc
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ProfileTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1385
Assertions were too stringent for graph providers who had complex strategies.
VOTE +1

TINKERPOP-1385 Bind profile test assertions to TinkerGraph

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/reference/gremlin-variants.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GryoLiteMessageSerializerV1d0.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GryoMessageSerializerV1d0.java
gremlin-python/src/test/resources/org/apache/tinkerpop/gremlin/python/driver/gremlin-server-modern-secure-py.yaml
gremlin-server/conf/gremlin-server-classic.yaml
gremlin-server/conf/gremlin-server-modern-py.yaml
gremlin-server/conf/gremlin-server-modern-readonly.yaml
gremlin-server/conf/gremlin-server-modern.yaml
gremlin-server/conf/gremlin-server-neo4j.yaml
gremlin-server/conf/gremlin-server-secure.yaml
gremlin-server/conf/gremlin-server-spark.yaml
gremlin-server/conf/gremlin-server.yaml
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java

https://issues.apache.org/jira/browse/TINKERPOP-1718
This is the "old" way of specifying detachment. Detachment is now best specified by `HaltedTraverserStrategy`.
VOTE +1

TINKERPOP-1718 Deprecated GryoLiteMessageSerializerV1d0

---

gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py

@spmallette the goal of this PR is simply to avoid inconsistency between different executions, as we experienced.

Ensure serializers iteration is consistent

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalTest.java

Added an explicit deep copy of `bytecode` in `DefaultTraversal.clone()`
VOTE: +1
```
[INFO] Apache TinkerPop ................................... SUCCESS [  7.372 s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................. SUCCESS [  3.981 s]
[INFO] Apache TinkerPop :: Gremlin Core ................... SUCCESS [01:56 min]
[INFO] Apache TinkerPop :: Gremlin Test ................... SUCCESS [ 18.989 s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................. SUCCESS [04:20 min]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ............ SUCCESS [ 10.580 s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ............ SUCCESS [03:51 min]
[INFO] Apache TinkerPop :: Gremlin Benchmark .............. SUCCESS [  9.258 s]
[INFO] Apache TinkerPop :: Gremlin Driver ................. SUCCESS [ …
```

TINKERPOP-1727: Bytecode object shallow copied when traversals are cloned

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/RemoteGraph.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyAddEdgeTest.groovy
gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py
gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1679
This was occurring because Gremlin-Python did not have serializers for the Graph elements. I created serializers which are of the `ReferenceXXX` form. I added serializer tests as well as add an `AddEdgeTest` and specific Gremlin-Python test for the traversal specified in the ticket. I also exposed two `ProjectTest` `OPT_OUTs` in `RemoteGraph`. I don't know why those were `OPT_OUT` as OLAP will automatically fail accordingly beyond the star graph.
VOTE +1.

TINKERPOP-1679: Detached side-effects aren't attached when remoted

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/NumberHelper.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroovySackTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SackTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1736
Fixed a bug in `BigDecimal` divisions in `NumberHelper` that potentially threw an `ArithmeticException`.
`docker/build.sh -t -i` succeeded.
VOTE: +1

TINKERPOP-1736 Sack step evaluated by groovy interprets numbers in an unexpected way

---

CHANGELOG.asciidoc
giraph-gremlin/pom.xml
giraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/giraph/process/computer/GiraphMessageCombiner.java

https://issues.apache.org/jira/browse/TINKERPOP-1535
I bumped Giraph from 1.1.0 to 1.20. It was a pretty straight forward upgrade. There was only a single class that needed some tweaking -- `MessageCombiner` is now an interface in Giraph instead of a class.
VOTE +1.

TINKERPOP-1535: Bump to support Giraph 1.2.0.

---

CHANGELOG.asciidoc
data/script-input.groovy
docs/src/reference/implementations-hadoop-end.asciidoc
gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/structure/io/script/script-input-grateful-dead.groovy
gremlin-test/src/main/resources/org/apache/tinkerpop/gremlin/structure/io/script/script-input.groovy
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/script/ScriptRecordReader.java

https://issues.apache.org/jira/browse/TINKERPOP-1724
Removed previously deprecated `ScriptElementFactory`.
`mvn clean install -DskipIntegrationTests=false` succeeded. (Docker ran out of memory for some reason, but I'm sure that was not related to my changes)
VOTE: +1

TINKERPOP-1724 Remove deprecated ScriptElementFactory

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStartStep.java
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs
gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1740
Is it me or is it hot out? Oooooowwww...
```
a = g.V(1).next()
b = g.V(2).next()
g.addE('knows').from(a).to(b)
```
We now support `addE()` as a `GraphTraversalSource` method and we support `to(Vertex)` and `from(Vertex)` which simply default to `to(__.constant(vertex))` (and `from()` respectively). Gonna vote on it a bit later, want to get some feedback from @newkek and Jeremy first.

TINKERPOP-1740: Add vertex parameter overload to to() and from()

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SackValueStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/LambdaRestrictionStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/LambdaRestrictionStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1743
Fixed a lambda-leak in `SackValueStep` where `BiFunction` must be tested for true lambda status.

TINKERPOP-1743: LambdaRestrictionStrategy does not catch lambdas passed to sack()

---

gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Remote/DriverRemoteTraversalSideEffects.cs
gremlin-dotnet/src/Gremlin.Net/Process/Remote/RemoteStrategy.cs
gremlin-dotnet/src/Gremlin.Net/Process/Utils.cs
gremlin-dotnet/src/Gremlin.Net/Structure/Utils.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Remote/RemoteStrategyTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-1744
Includes a test expecting the underlying exception (`ResponseException`) to be thrown.
Builds with `mvn clean install -P gremlin-dotnet`

TINKERPOP-1744 Unwrap AggregateException for sync io operations

---

CHANGELOG.asciidoc
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1749
Many SSL updates, bug fixes.
`docker/build.sh -i -t -n` SUCCESS
VOTE +1

TINKERPOP-1749  Bump to Netty 4.0.50

---

docs/postprocessor/processor.awk

https://issues.apache.org/jira/browse/TINKERPOP-1748
Made callouts in docs prettier and copy+paste friendly.
Tested with `docker/build.sh -d`. Looks great and all snippets can now be pasted into the console w/o producing any syntax errors due to callout comments.
VOTE: +1

TINKERPOP-1748 Callout comments break code snippets

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/NumberHelper.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Order.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyOrderTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/OrderTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1753
Fixed ordering of collections / streams containing mixed number types.
I decided to go with `try / catch`, since this should really be an exceptional case. Usually number types shouldn't be mixed up, hence I didn't want this PR to have a negative impact on the overall order performance by always checking the types upfront.
VOTE: +1

TINKERPOP-1753 OrderStep not able to order by non-integer numbers

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/ComputerVerificationStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/ComputerVerificationStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1760
The more general problem was in `ComputerVerificationStrategy`. The problem was the nested traversals were being analyzed prior to full strategy compilation. The solution actually simplified the code a bit.
```
gremlin> g = TinkerFactory.createModern().traversal().withComputer()
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], graphcomputer]
gremlin> g.V().where(out("created").and().out("knows")).values("name")
==>marko
```
VOTE +1

TINKERPOP-1760: OLAP compilation failing around ConnectiveStrategy

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyMatchTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1762
There was a bug in `MatchStep` where if you had a mid-clause `where()`, its variable was not being considered as part of the determination of the matching start-variables. This led to traversers going down clause paths when they didn't have all the subsequent data.
```
gremlin> graph.io(graphml()).readGraph("data/grateful-dead.xml")
==>null
==>graphtraversalsource[tinkergraph[vertices:808 edges:8049], standard]
gremlin> g.V().match(
......1>     __.as("sunshine").has("song", "name", "HERE COMES SUNSHINE"),
......2>     __.as("sunshine").map(inE("followedBy").values("weight").mean()).as("avg_weight"),
......3> …
```

TINKERPOP-1762: Make MatchStep analyze mid-clause variables for executing ordering purposes.

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyMatchTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1764
Prior to this moment, only reducing barrier steps in a `match()`-clause forced the clause to be computed locally (via a `flatMap()`-wrap). However, it has been deemed important to generalize this behavior to all barriers (e.g. `order()`, `limit()`, etc.) as identified by @doanduyhai (Gremlin power user). As such, the generalization has been done, but at the expense of a breaking change. However, realize that this breaking change would only be breaking behavior that is "random" (and most users should not be doing anyways -- but you never know).
*PREVIOUSLY*
```
gremlin> g.V().match(
......1>   __.as('a').outE('created').order().by('weight',decr).limit(1).inV().as('b'),
......2>   __.as('b').has('lang','java')
......3> …
```

TINKERPOP-1764: Generalize MatchStep to localize all barriers, not just reducing barriers.

---

CHANGELOG.asciidoc
gremlin-shaded/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1768
Adds some key bug fixes.
All tests pass with `docker/build.sh -t -n -i` for both tp32 and master
VOTE +1

TINKERPOP-1768 Bump to Jackson 2.8.10

---

CHANGELOG.asciidoc
docs/src/reference/the-graph.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/api-changes.json
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/Io.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphml/GraphMLIo.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONIo.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoIo.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/SerializationTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoCustomTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoEdgeTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoGraphTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoPropertyTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoVertexTest.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1767
Allows the graph provider to determine type and version of the Io being constructed so that they can properly choose the right IoRegistry to assign. Also set the defaults for GraphSON and Gryo to 3.0 when doing `graph.io()` (should have been done for 3.3.0 unfortunately).
VOTE +1

TINKERPOP-1767 Added Io.requiresVersion(Object)

---

gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketConnection.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj
gremlin-dotnet/test/Gremlin.Net.UnitTest/Gremlin.Net.UnitTest.csproj

https://issues.apache.org/jira/browse/TINKERPOP-1766
This avoids `Connections` from being added back to the `ConnectionPool` when they were closed which happens when the server gets unavailable. In that case all existing `Connections` are removed from the `ConnectionPool` and closed as they are most likely also not `Open` anymore. This is in line with the handling for closed connections in `gremlin-driver`.
Unfortunately, I don't know of a good way to test something like this. We probably would have to make internal classes like `Connection` public which isn't that nice as users shouldn't see them in my opinion.
VOTE +1

TINKERPOP-1766 Gremlin.Net: Add handling for closed connections

---

CHANGELOG.asciidoc
docs/src/reference/implementations-neo4j.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-console/conf/neo4j-standalone.properties
gremlin-server/conf/neo4j-empty.properties
neo4j-gremlin/pom.xml
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/process/NativeNeo4jCypherCheck.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/structure/NativeNeo4jStructureCheck.java

https://issues.apache.org/jira/browse/TINKERPOP-1692
Bumps to Neo4j 3.2.2 and is the revision to #674 which needed some additional `pom.xml` work. That's the only real change here. Going forward for review/vote purposes, we'll use this PR over the other one.
Running full tests now....will udpate when complete.

TINKERPOP-1692 Neo4j 3.2.2

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/RepeatStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/RepeatUnrollStrategy.java

Simply added a proper error message when `repeatTraversal` is null. This provides a better user experience than `NullPointerException`.
VOTE +1

TINKERPOP-1746: Better error message on wrong ordering of emit()/until()/has()

---

gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Messages/ResponseMessage.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Messages/ResponseResult.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Remote/DriverRemoteTraversalSideEffects.cs
gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/GraphSON3Reader.cs
gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/Path3Deserializer.cs
gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/PathDeserializer.cs
gremlin-dotnet/src/Gremlin.Net/Structure/Path.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/SideEffectTests.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONReaderTests.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/PathTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-1730

TINKERPOP-1730 Gremlin .NET: add support for GraphSON3

---

CHANGELOG.asciidoc
docs/src/reference/the-graphcomputer.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/ranking/pagerank/PageRankVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/PageRankVertexProgramStep.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/ranking/pagerank/PageRankVertexProgramTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PageRankTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PeerPressureTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1783
There were a couple of problems with `PageRankVertexProgram`. In order to describe the problems, its necessary to explain PageRank.
***
Initially, every vertex gets `1.0/vertexCount` amount of energy. Thus, the total energy in the system is 1.0.
At every iteration, 0.85 of that energy is distributed amongst adjacent neighbors and 0.15 is distributed amongst all vertices (this is the `alpha` parameter w/ the default being 0.85). If a vertex does not have outgoing edges and it can not distribute its 0.85 energy amongst its neighbors, then all that energy is teleported amongst all vertices.
The algorithm above ensures strong connectivity because the 0.15 energy distribution simulates a strongly connected graph via the concept of …

TINKERPOP-1783: PageRank gives incorrect results for graphs with sinks

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/api-changes.json
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/GremlinDslProcessor.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStartStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStartStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStep.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1793
There are a few changes here:
1. `addV(traversal)` and `addE(traversal)` added to both `GraphTraversal` and `GraphTraversalSource`. Thus, the label of the respectively created element can be dynamically determined.
2. Added the above methods as well as `addE(String)` to the traversal source of `GremlinDslProcessor`. The missing `addE(String)` method was a bug.
3. Changed `to()` and `from()` from taking a `Traversal<E,Vertex>` to `Traversal<?,Vertex>`. This reduces type coercion.
Added various test cases to validate proper functioning.
VOTE +1.

TINKERPOP-1793: addE() should allow dynamic edge labels

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceEdge.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceElement.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceVertexProperty.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/GryoLiteMessageSerializerV1d0Test.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinResultSetIntegrateTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceEdgeTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceVertexPropertyTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceVertexTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1789
Fixed a bug where `ReferenceVertex` was always returning an `EMPTY_STRING` `label()`. `ReferenceEdge` and `ReferenceVertexProperty` were behaving correctly, but I needed to make a change at `ReferenceElement` for general handling of all element labels. Thus, those other two classes changed. And thus, the Gryo. I updated all the `ReferenceXXXTest` classes to check for `label()` accordingly. Updated CHANGELOG and upgrade docs.
VOTE +1

TINKERPOP-1789: Reference elements should be represented by id and label

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/GremlinScriptEngine.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/ScriptEngines.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java
gremlin-python/src/main/java/org/apache/tinkerpop/gremlin/python/jsr223/GremlinJythonScriptEngine.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/jsr223/GremlinEnabledScriptEngineTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/jsr223/MockGremlinScriptEngine.java

https://issues.apache.org/jira/browse/TINKERPOP-1792
GremlinScriptEngine instances should now properly select the appropriate TraversalSource from bindings rather than select a random one. The TraversalSource is locally aliased to a "hidden" variable at the time of evaluation to avoid naming clashes with local variables defined in the bytecode itself. Added a number of validations to be sure that users get appropriate errors if they try to use the eval() method the wrong way. Included new tests to ensure that GremlinScriptEngine have the appropriate behavior.
VOTE +1

TINKERPOP-1792 Fixed GremlinScriptEngine bug in lambda processing

---

docker/scripts/build.sh

https://issues.apache.org/jira/browse/TINKERPOP-1661
That was much easier than I thought. I started by pushing directories around and updating links in most of the asciidoc files. Then I realized, that this can be a simple 2 line change in Docker's build script (it's basically just a global `sed` replacement and a symlink).
VOTE: +1

TINKERPOP-1661 Docker-built documentation does not always point locally

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/LambdaRestrictionStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/LambdaRestrictionStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1795
Some objects are hard to check for "lambdaness" and require a `toString()` analysis. We checked for `@` but that doesn't work for named steps within `order()` (when using `profile()`). That is, its error prone. I came up with a new way to check for lambdas that works for Java, Groovy, and Python/Jython. 
@spmallette -- can you please verify that a "toString()" of a lambda in C# will hold as well for the pattern.
VOTE +1

TINKERPOP-1795: Getting Lambda comparator message for .profile() step

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/PathProcessor.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DedupGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/PathFilterStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/WherePredicateStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/WhereTraversalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MatchStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PathStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectOneStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/TreeStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/TreeSideEffectStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategyTest.java

This bug was a result of an unintentionally shared set between a MatchStep and WhereStep's. This caused the `p` label to be incorrectly pulled into the `matchStartLabels` for the following query:
` g.V().hasLabel("person").as("p").match(__.as("a").out("created").as("sw"), __.as("sw").has("lang", "java").as("java")).where("sw", neq("a")).select("p")`
As a result, when the match step was attempting to pick a `startLabelsBundle`, it failed to grab one because the incoming traverser already had the `p` label in its path. This fix added defensive copying to all of the `setKeepLabels` calls to prevent the possibility of this unintentional sharing of a mutable collection.
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] …
```

TINKERPOP-1650: PathRetractionStrategy makes Match steps unsolvable

---

CHANGELOG.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutor.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/engine/GremlinExecutorTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1761
I basically added the code again which was wrongly removed in TINKERPOP-1714, plus added a test. All unit tests passed and I confirmed manually that this fixes the issue I experienced.

TINKERPOP-1761: Cancel script evaluation timeout

---

gremlin-python/src/main/jython/setup.py

In setup.py, strongly freezing deps is not recommended since it can easily create a conflict with other packages in a user environment. 
Also, If you know that gremlinpython works well with a lower package version (e.g six 1.6), I recommend to just change it to the minimum required to be more flexible.

Do not strong-freeze dependencies

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/pom.xml
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MathStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MathStepTest.java
gremlin-dotnet/glv/generate.groovy
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs
gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MathTest.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1632
This is an implementation of lambda-less math capabilities in Gremlin leveraging the String-based calculator model proposed by @twilmes. This model deviates from Gremlin's standard function composition and nesting model to provide a easy to read "math processor" that leverages Gremlin scopes for data access (e.g. path data, map keys, and side-effects). The feature is encapsulated in `MathStep` which implements `PathProcessor` and `Scoping`. Furthermore, `by()`-modulation is supported. `by()`-modulators are applied in the order in which the variable is first used in the equation. Thus:
```
g.V().as("a").out("knows").by("b").
math("b + a").
by(out().count()).
by("age")
```
In the above: `a` -> `age` and `b` -> `out().count()`. More …

TINKERPOP-1632: Create a set of default functions

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SackValueStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/LambdaRestrictionStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/StringFactory.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/verification/LambdaRestrictionStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1797
We have had too many problems with `LambdaRestrictionStrategy` because it is difficult to know what is a true lambda. I have now simply hardcoded the lambda determination as a `String` analysis of the lambda object for Java, Groovy, and Python. As we add more GLVs, we can add more string mappers. Every other solution thus far has either been too lenient or too restrictive.
VOTE +1

TINKERPOP-1797: LambdaRestrictionStrategy and LambdaMapStep in by()-modulation.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/StartStep.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/InjectStepTest.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/GroovyInjectTest.groovy
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java
gremlin-python/src/main/java/org/apache/tinkerpop/gremlin/python/jsr223/PythonTranslator.java
gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/InjectTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1803
Fixed an "attachement"-bug in `InjectStep` with a solution generalized to `StartStep`.
VOTE +1

TINKERPOP-1803: inject() doesn't re-attach with remote traversals

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-archetype/gremlin-archetype-dsl/src/main/resources/archetype-resources/src/main/java/SocialTraversalDsl.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/GremlinDsl.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/GremlinDslProcessor.java
gremlin-core/src/test/resources/org/apache/tinkerpop/gremlin/process/traversal/dsl/SocialTraversalDsl.java

https://issues.apache.org/jira/browse/TINKERPOP-1791
Allows the ability to bypass the type inference system and provides for direct specification of the type parameters when generating anonymous methods.
VOTE +1

TINKERPOP-1791 Added GremlinDsl.AnonymousMethod annotation

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoaderVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/event/ConsoleMutationListener.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/event/Event.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/event/MutationListener.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyProcessTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1798
This method was referencing a Property when it should have been referencing a VertexProperty. Implemented by way of deprecation of the old method so that this ends up being a non-breaking change.
VOTE +1

TINKERPOP-1798 Fix signature of MutationListener.vertexPropertyChanged()

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyVertexTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/VertexTest.java
neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/structure/Neo4jVertex.java

https://issues.apache.org/jira/browse/TINKERPOP-1821
Added test for self-edges and fixed a semantic issue in `Neo4jGraph` regarding self edges not being repeated on `BOTH`.
VOTE +1.

TINKERPOP-1821: Consistent behavior of self-referencing edges

---

docs/src/reference/gremlin-variants.asciidoc
gremlin-dotnet/glv/AnonymousTraversal.template
gremlin-dotnet/glv/GraphTraversal.template
gremlin-dotnet/glv/GraphTraversalSource.template
gremlin-dotnet/glv/generate.groovy
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Bindings.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Bytecode.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Decoration/HaltedTraverserStrategy.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Decoration/PartitionStrategy.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Decoration/SubgraphStrategy.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Decoration/VertexProgramStrategy.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs
gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/ClassSerializer.cs
gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/GraphSONWriter.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/BytecodeGeneration/BytecodeGenerationTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/BytecodeGeneration/StrategiesTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/StrategiesTests.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/BytecodeTests.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/Strategy/StrategyTests.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONWriterTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-1752
All steps are now (basically) type-safe and the original argument names from Gremlin-Java are used. However, we currently don't support some Java types like `Comparator`. Those were simply replaced by `object` until we find a better solution. A problem with this workaround is that some overloads from Gremlin-Java are not supported in Gremlin.Net as they would result in the same method signature.
The implementation of `Bindings` is now basically the same as in Gremlin-Java. This change was necessary as `Bindings.Of()` can no longer return a `Binding` object
These changes also revealed a bug in the tests where the `WithoutStrategies` source step was called with objects of strategies instead of just with their types. However, …

TINKERPOP-1752: Gremlin.Net: Generate completely type-safe methods

---

CHANGELOG.asciidoc
gremlin-console/src/main/static/NOTICE
gremlin-server/src/main/static/NOTICE
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1824
Latest bug-fix release.
VOTE +1

TINKERPOP-1824 Bump netty to 4.0.52

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GraphStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/HasContainer.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyHasTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasTest.java
neo4j-gremlin/src/main/java/org/apache/tinkerpop/gremlin/neo4j/process/traversal/step/sideEffect/Neo4jGraphStep.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/step/sideEffect/TinkerGraphStep.java

https://issues.apache.org/jira/browse/TINKERPOP-1802
If `hasId([])` is specified, then an `ArrayOutOfBoundsException` occurs. This has been fixed by simply filtering out (`filter(true)` in essence) all vertices once a `hasId([])` is reached. cc/ @rjbriody 
VOTE +1.

TINKERPOP-1802: hasId() fails for empty collections

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/CoreTraversalTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategyProcessTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1814
Fixed assertions in the test cases outlined by @BrynCooke that use the structure API when they should stick with the process API. I found more areas than specified in the ticket. I also suspect that other process test cases will have similar problems. As these are exposed, please just make a new ticket accordingly - besides being monotonously boring, these are easy to fix.
VOTE +1.

TINKERPOP-1814: Some process tests require the graph API

---

CHANGELOG.asciidoc
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerIndex.java

My colleage @fabsx00 discovered a race condition in tinkergraph's index creation. He fixed it by simply replacing `parallelStream` with `stream`. Quoting his analysis:
> So, reading the code, you see that this.put is called in parallel, but that method seems to contain a race as get is called on the index, checked for null, and a subsequent write is performed. It still seems like using stream here fixes the problem we've been seeing, and the performance hit is not significant.
Ticket: https://issues.apache.org/jira/browse/TINKERPOP-1830
After initial feedback I can backport this onto tp32.

TINKERPOP-1830: fix race condition in TinkerIndex

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SubgraphTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1813
This ticket wanted `SubgraphStep` to not use the structure API. This is not something we will support in TinkerPop3. The structure API is a fundamental layer to our step API. It was advised to the provider to simply write their own custom `ProviderSubgraphStep` which avoids the structure API as they see fit. However, what was accomplished in this ticket was to change `SubgraphTest` to only use traversals (process API) in its assertions. This theme is good -- our process test suite should never rely on the structure API (beyond `ReferenceXXX` data).
VOTE +1

TINKERPOP-1813: Subgraph step requires the graph API

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/DropStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddEdgeStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStartStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AddPropertyStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceProperty.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/reference/ReferenceVertexProperty.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyProcessTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1831
The default behavior is representative of how EventStrategy currently works so there is no breaking change here. In the interest of avoiding breaking changes, I didn't want to shift the API to make the change cleaner and thus created TINKERPOP-1831 for future consideration.
VOTE +1

TINKERPOP-1829 Made detachment configurable in EventStrategy

---

.travis.yml

https://issues.apache.org/jira/browse/TINKERPOP-1820
Adds `gremlin-dotnet` integration tests to travis build as a separate job.

TINKERPOP-1820 TravisCI: Add Gremlin.Net as job

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/TraversalHelper.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/util/TraversalHelperTest.java

`TraversalHelper.replaceStep` needs to first remove the step before adding in the new step. Else it gets its `previousStep` pointer wrong.
Added `TraversalHelperTest.shouldSetPreviousStepToEmptyStep` which was the scenario that originally made me aware of the issue.
Ran `mvn clean install` and tested Sqlg's tests with the fix.

TINKERPOP-1832: TraversalHelper.replaceStep sets previousStep to the wrong step

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-python/src/main/jython/gremlin_python/statics.py
gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV2d0.py
gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py
gremlin-python/src/main/jython/tests/structure/io/test_graphsonV2d0.py
gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py

https://issues.apache.org/jira/browse/TINKERPOP-1807
This PR follows #741, adding support for core types Date, Timestamp, and UUID in GraphSON3

Tinkerpop 1807 Gremlin-Python doesn't support GraphSON types g:Date, g:Timestamp and g:UUID

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-python/src/main/jython/gremlin_python/statics.py
gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py

https://issues.apache.org/jira/browse/TINKERPOP-1807
This PR add support for GraphSON types `UUID`, `Date`, and `Timestamp` as well as associated tests. `UUID` and `Date` are straightforward, as the Python standard library includes `Date` (`datetime.datetime`) and `UUID` (`uuid.UUID`) objects. However, in Python, a timestamp is just a float, so in order to support serialization to a GraphSON type Timestamp, I added a dummy class `timestamp` to the `statics` module, similar to the `long` class for Python 3.
Note, another PR will be required for master with implementations for both GraphSON2 and 3. I will open upon approval of this one.

TINKERPOP-1807 Gremlin-Python doesn't support GraphSON types g:Date, g:Timestamp and g:UUID

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Traversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/NoneStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/LazyBarrierStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/PathRetractionStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalTest.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/CoreTraversalTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1834
This is a re-issuing of a previously closed commit. In this model, a `NoneStep` was added as well as a `Traversal.none()`. `Traversal.iterate()` calls `Traversal.none()` if the traversal has not been fully compiled. The benefit of this is that `iterate()` will add a full filter and thus, for remote systems (non-embedded), all data is "iterated" server-side before being sent back to the client. This is a novel play in that `iterate()`, while being a terminal step, is now effecting the bytecode representation.
cc/ @BrynCooke 
VOTE +1

TINKERPOP-1834: Consider iterate() as a first class step

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/JavaTranslator.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java

As the original issue description suggests the error message wasn't very helpful. Seems there was a mistype in the log message that prevented a better output and also some error handling that wasn't quite being dealt with properly.
Error now presents as:
```text
gremlin> bytecode = g.V().asAdmin().bytecode
==>[[], [V()]]
gremlin> bytecode.addStep("broken")
gremlin> bytecode
==>[[], [V(), broken()]]
gremlin> conn.submit(bytecode).next()
org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Could not locate method: DefaultGraphTraversal.broken([])
Type ':help' or ':h' for help.
Display stack trace? [yN]n
```
On the server you now get this:
```text
[ERROR] TraversalOpProcessor - Could not deserialize the Traversal instance
java.lang.IllegalStateException: Could not locate method: …
```

TINKERPOP-1811 Fixed bytecode deserialization error messaging

---

docs/src/dev/provider/index.asciidoc
docs/src/reference/gremlin-variants.asciidoc

https://issues.apache.org/jira/browse/TINKERPOP-1806
This change really just applies to documentation. Directory structures, links and other identifiers have been left as "dotnet". I will do a search for similar changes to master and update accordingly when I merge this.
VOTE +1

TINKERPOP-1806 Consistent use of Gremlin.Net instead of Gremlin-DotNet

---

.travis.yml
gremlin-dotnet/glv/generate.groovy
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/__.cs

https://issues.apache.org/jira/browse/TINKERPOP-1825
Addressed the issue where generic parameter types generated as `object` in Gremlin.Net.
VOTE +1

TINKERPOP-1825 Gremlin.Net: fix generation of Constant() and Fold() steps

---

gremlin-test/features/branch/Local.feature

As part of fixing conflicts and understanding GLV test failures on the last `tp32->master` merge, I've removed most scenarios from `Local.feature` and mistakenly push them as part of the merge commit a7d01e2e2ff0b958e11662998b901633a6a88a8a.
This commit restores the file in master branch (`tp32` is not affected).

GLV Test Suite: Restore Local feature scenarios to master branch

---

gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py

https://issues.apache.org/jira/browse/TINKERPOP-1848

TINKERPOP-1848 use generated datetime to ignore timezone, DST differences in test

---

CHANGELOG.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
gremlin-console/src/test/python/tests/test_console.py

https://issues.apache.org/jira/browse/TINKERPOP-1851
There was some special handling of the short forms that wasn't accounted for with the long forms. Pretty simple fix. Added lots of tests to ensure the different options were covered.
I could have probably CTR'd this, but since we're in code freeze technically, I thought I'd ask for reviews.
VOTE +1

TINKERPOP-1851 Minor fix to allow long forms of -e and -i to work

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ComputerAwareStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyUnionTest.groovy
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/UnionTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1867
Implemented `reset()` in `ComputerAwareStep` to reset the `previousIterator`, and reset the `finalStep` in `DefaultTraversal`.
This fixes the false behavior, mainly seen in reducing barrier steps.
```
$ docker/build.sh -t -i
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache TinkerPop .................................. SUCCESS [1:45.623s]
[INFO] Apache TinkerPop :: Gremlin Shaded ................ SUCCESS [21.575s]
[INFO] Apache TinkerPop :: Gremlin Core .................. SUCCESS [57.690s]
[INFO] Apache TinkerPop :: Gremlin Test .................. SUCCESS [6.146s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................ SUCCESS [3:03.207s]
[INFO] Apache …
```

TINKERPOP-1867 union() can produce extra traversers 

---

gremlin-dotnet/glv/GraphTraversal.template
gremlin-dotnet/glv/GraphTraversalSource.template
gremlin-dotnet/glv/generate.groovy
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs

https://issues.apache.org/jira/browse/TINKERPOP-1868
This adds the `Inject` step to `GraphTraversalSource` for Gremlin.Net. While working on this I also noticed that the interface wasn't optimal for the existing `GraphTraversal` `Inject` step as it accepted a `params object[] injections` although it should only except `injections` of the generic type `E`. So I also fixed that.
Method signature before:
```
public GraphTraversal< S , E > Inject (params object[] injections)
```
and after:
```
public GraphTraversal< S , E > Inject (params E[] injections)
```
Now, a traversal like the following isn't possible any more in Gremlin.Net:
```
g.V().Values<string>("name").Inject(1).ToList();
```
as `Inject` now only accepts strings here (just like Gremlin-Java does).

TINKERPOP-1868 Gremlin.Net: Add Inject step to GraphTraversalSource

---

docs/src/dev/io/graphson.asciidoc
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperV2d0PartialEmbeddedTypeTest.java
gremlin-dotnet/glv/P.template
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/P.cs
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/filter/GroovyHasTest.groovy
gremlin-test/features/filter/Has.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/HasTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1874
Added  bunch of tests for this and found that .NET was still working, but that was just because of how the gherkin processor was generating the traversals (it was always converting `P` args to lists basically). I modified the `P` template for .NET and made it so that `within` and `without` are handled differently from the other enums - `within` and `without` will always pass a collection rather than an individual object if there is only one item present in the arg array.
I also updated the IO docs to include `within` and `without` so that it was clear to implementers what was expected for them. I may have to come back and do some cleanup here, but I already went deep on my PR to master for this so I'd rather just CTR in the doc fixes …

TINKERPOP-1874 P does not appear to be serialized consistently in GraphSON

---

gremlin-python/src/main/jython/gremlin_python/driver/protocol.py
gremlin-python/src/main/jython/tests/conftest.py
gremlin-python/src/main/jython/tests/driver/test_client.py
gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py

https://issues.apache.org/jira/browse/TINKERPOP-1875
This PR fixes server response message deserialization in Gremlin-Python. Improper deserialization was leading to `aggregate_to` always resulting in a list as well as API comparability issues between GraphSON2 and GraphSON3 message serializers.
This PR also improves testing--all Gremlin-Python tests using a remote connection are now run with both GraphSON 2 and 3 serializers.

TINKERPOP-1875 Gremlin-Python only aggregates to list when using GraphSON3

---

CHANGELOG.asciidoc
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphComputerTest.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkMessenger.java
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/SparkMessengerTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1872
This pull request basically adds an integration test for the fix presented in #788 and indeed this test fails for Spark (while passing for TinkerGraph and Giraph). After merging the change from that branch here, Spark passes, so this all looks good now. 
Thanks to @Stargazer4869 for the original pull request - #788 can be closed at this point.
VOTE +1

TINKERPOP-1872 Apply edgeFunction in SparkMessenger

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategy.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategyProcessTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1586
This change allows the user to turn off an aspect of `SubgraphStrategy` that prevents it from working properly in OLAP situations. Added some better javadoc to explain the settings for this strategy. 
VOTE +1

TINKERPOP-1586 Added checkAdjacentVertices option to SubgraphStrategy

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/Scoping.java
gremlin-test/features/map/Select.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1522
This PR changes the order of `select()` scope from 
* side-effects, maps, paths
to
* maps, side-effects, paths
`docker/build.sh -t -i` passed.
Note that I discovered a bug in OLAP while writing the test case, that's why there is an extra `barrier()` step. I'll create another ticket to address this issue.

TINKERPOP-1522 Order of select() scopes

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypeSerializer.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperV2d0PartialEmbeddedTypeTest.java
gremlin-shaded/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1738
This fixes a problem where Jackson was missing an error in GraphSON type information depending on the order of the JSON elements. It required some internal changes to the GraphSONTypeSerializer given API shifts in jackson - should not really affect TinkerPop  users. Modified the original test that demonstrated this problem to be a bit more robust.
VOTE +1

TINKERPOP-1738 Bump to jackson 2.9.4

---

CHANGELOG.asciidoc
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineCompileStaticTest.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTypeCheckedTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1908
Bump to Groovy 2.4.14
VOTE +1

TINKERPOP-1908 Bump to Groovy 2.4.14

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/EmptyPath.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ImmutablePath.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/MutablePath.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/StringFactory.java
gremlin-dotnet/src/Gremlin.Net/Structure/Path.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONReaderTests.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/PathTests.cs
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/graph.js
gremlin-python/src/main/jython/gremlin_python/structure/graph.py
gremlin-python/src/main/jython/tests/structure/io/test_graphsonV2d0.py
gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py
gremlin-python/src/main/jython/tests/structure/test_graph.py

https://issues.apache.org/jira/browse/TINKERPOP-1446
Only applying this to 3.4.x as people might be relying on the old string representations of `Path` objects for some reason. 
VOTE +1

TINKERPOP-1446 Added standard string representation for Path objects

---

CHANGELOG.asciidoc
gremlin-benchmark/src/main/java/org/apache/tinkerpop/jsr223/JavaTranslatorBenchmark.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/JavaTranslator.java

https://issues.apache.org/jira/browse/TINKERPOP-1911
Cached methods that were being reflected on every translation which improved performance a bit. Here's how it runs before the change:
```text
Benchmark                                             Mode  Cnt        Score        Error  Units
JavaTranslatorBenchmark.testTranslationLong          thrpt   20    13267.284 ±   1166.704  ops/s
JavaTranslatorBenchmark.testTranslationMedium        thrpt   20   334756.147 ±  23429.373  ops/s
JavaTranslatorBenchmark.testTranslationShort         thrpt   20  1381906.511 ± 141710.801  ops/s
JavaTranslatorBenchmark.testTranslationWithStrategy  thrpt   20    36350.729 ±  2518.351   ops/s
```
and here's how it runs after:
```text
Benchmark                                             Mode  Cnt        Score …
```

TINKERPOP-1911 Refactored JavaTranslator

---

CHANGELOG.asciidoc
gremlin-python/src/main/java/org/apache/tinkerpop/gremlin/python/jsr223/GremlinJythonScriptEngine.java
gremlin-python/src/main/java/org/apache/tinkerpop/gremlin/python/jsr223/JythonTranslator.java
gremlin-python/src/main/java/org/apache/tinkerpop/gremlin/python/jsr223/PythonTranslator.java
gremlin-python/src/test/java/org/apache/tinkerpop/gremlin/python/jsr223/JythonTranslatorTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1896
When a lambda is in a traversal, the bytecode gets pushed to a scriptengine for evaluation. For python that means, using the JythonTranslator. Prior to this change the JythonTranslator largely relied on the PythonTranslator to convert bytecode to Jython-syntaxed Gremlin. The problem there is that in the JythonScriptEngine, the Traversal bindings are Java objects and so if translated to pure Python syntax, traversal steps like as() become as_() and thus not part of the Java API that is expected - and then errors. Not sure why this didn't come up sooner, but it really only ends up being an issue if you are using bytecode, use gremlin server, use jython in gremlin server and then submit a traversal with a lambda - so perhaps that hasn't …

TINKERPOP-1896 Fixed bug in lambda processing for python

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-variants.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-dotnet/glv/generate.groovy
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/ISupplier.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/IUnaryOperator.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Lambda.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/StringBasedLambda.cs
gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/GraphSONWriter.cs
gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/LambdaSerializer.cs
gremlin-dotnet/src/Gremlin.Net/Structure/IO/GraphSON/StringBasedLambdaSerializer.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/CommonSteps.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/IgnoreException.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/TraversalEvaluation/TraversalParser.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONWriterTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-1854
Since we don't have a way to parse C# lambdas on server side, this PR simply allows to send lambdas in other languages with Gremlin.Net:
- For a Groovy lambda: `Lambda.Groovy("it.get().value('name').length()")`
- and for a Python lambda: `Lambda.Python("lambda x: len(x.get().value('name'))")`
All features are passing now - no features are ignored any more. Therefore I also removed the functionality to ignore features in Gremlin.Net. (I hope that we won't need to ignore any features in Gremlin.Net in the future, but if we have to then it shouldn't be an issue to get this functionality back.)
Unfortunately, it's not possible to use this new `Lambda` type for arguments in the traversal API due to the fact that in Java the type `Function` …

TINKERPOP-1854 Add Lambdas for Gremlin.Net

---

CHANGELOG.asciidoc
gremlin-dotnet/glv/P.template
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/P.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/IgnoreException.cs

https://issues.apache.org/jira/browse/TINKERPOP-1920
Made the logic the same as what we have in Java currently for `P.within()` and `P.without()` for handling single collection values. I pretty much just made this work so open to input from C# experts for a nicer handling of `P`, but for now in terms of fixing the problem:
Builds with `mvn clean install -pl :gremlin-dotnet,:gremlin-dotnet-source,:gremlin-dotnet-tests -DskipIntegrationTests=false`
VOTE+1

TINKERPOP-1920 Fixed P.within/without() handling for collections

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/traversal/strategy/decoration/RemoteStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java

https://issues.apache.org/jira/browse/TINKERPOP-1758
Played around with a few ways to test this, but none seemed especially good. Everything I try to do seems fairly contrived or redundant. In the end, I ended up feeling like it was safe to just rely on the TraversalStrategies sorting system with posts/priors. That's pretty solidly tested so perhaps that is enough...
Here's the result of a quick manual test:
```text
gremlin> g = TinkerGraph.open().traversal().withRemote('conf/remote-graph.properties').withStrategies(SubgraphStrategy.build().vertices(identity()).create())
gremlin> g.V().out().out().values('name').explain()
==>Traversal Explanation
============================================================================== …
```

TINKERPOP-1758 Apply RemoteStrategy before all DecorationStrategy instances

---

gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/CommonSteps.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/IgnoreException.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/ScenarioData.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/RemoteConnectionFactory.cs
gremlin-test/features/map/Order.feature

https://issues.apache.org/jira/browse/TINKERPOP-1865
The tests simply failed because of the traversal used in `ScenarioData.GetEdges()`. I didn't dig deep into why it failed, but it had something to do with the deserialization of the keys of the received dictionary. I also couldn't get the traversal used there to work with gremlin-python, so I simply replaced it by two simpler traversals. This increases the runtime a bit as the second traversal now has to be executed for every edge, but I think that it improves the readability a lot.
Unfortunately, I had to add 3 more tests to the list of ignored ones. One failed due to the missing `T` deserializer (TINKERPOP-1866) and two failed because the data received from the server didn't match the expected data:
- …

TINKERPOP-1865 Run Gremlin.Net tests with GraphSON 3.0

---

.travis.yml
docker/Dockerfile
docs/src/dev/developer/development-environment.asciidoc
gremlin-dotnet/glv/Gremlin.Net.csproj.template
gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gremlin.Net.IntegrationTest.csproj
gremlin-dotnet/test/Gremlin.Net.UnitTest/Gremlin.Net.UnitTest.csproj

With the latest .NET Core SDK (2.1.101), its now possible to sign assemblies from Linux and macOS.
We should update our own local installation to use 2.1.101+ to run the .NET test locally.
The Gremlin.NET package still targets .NET Standard 1.3, there isn't any change for our users.
VOTE +1

TINKERPOP-1880 Sign assembly on Linux and macOS

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Operator.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MaxGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MaxLocalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MinGlobalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MinLocalStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/NumberHelper.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/OperatorExceptionTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/OperatorTest.java
gremlin-test/features/map/Max.feature
gremlin-test/features/map/Min.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MaxTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MinTest.java
spark-gremlin/src/main/java/org/apache/tinkerpop/gremlin/spark/process/computer/traversal/strategy/optimization/interceptor/SparkStarBarrierInterceptor.java

https://issues.apache.org/jira/browse/TINKERPOP-1888
Extended `min()` and `max()` to support all comparable data types.
From the docs:
```
gremlin> g.V().values('name').min()
==>josh
gremlin> g.V().values('name').max()
==>vadas
```
And another example:
```
gremlin> x = [new Date()]; sleep 1000; x << new Date()
==>Mon Apr 02 15:43:01 MST 2018
==>Mon Apr 02 15:43:02 MST 2018
gremlin> __(x).min(local)
==>Mon Apr 02 15:43:01 MST 2018
gremlin> __(x).max(local)
==>Mon Apr 02 15:43:02 MST 2018
gremlin> __(x).unfold().min()
==>Mon Apr 02 15:43:01 MST 2018
gremlin> __(x).unfold().max()
==>Mon Apr 02 15:43:02 MST 2018
```
`docker/build.sh -t -i` passed and the result of `docker/build.sh -d` looked good.
VOTE: +1

TINKERPOP-1888 Extend max and min to all Comparable properties, not just Numbers

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypeSerializerV3d0.java
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/IgnoreException.cs

https://issues.apache.org/jira/browse/TINKERPOP-1927
Since GLVs don't have `BulkSet` infrastructure and the need to include it doesn't seem high the most direct fix here is to coerce to `g:List` as the behavior for `BulkSet` iteration is basically that same as a List.
VOTE +1

TINKERPOP-1927 Coerced BulkSet to g:List in GraphSON 3.0

---

bin/validate-distribution.sh
docs/site/home/downloads.html
docs/src/dev/developer/release.asciidoc

https://issues.apache.org/jira/browse/TINKERPOP-1912
This PR adds another step to the release process, that removes the auto-generated MD5 checksums, and updates the instructions about release artifact verifications.
See: http://www.apache.org/dev/release-publishing.html#distribution_maven
VOTE: +1

TINKERPOP-1912 Remove MD5 checksums (tp33)

---

bin/validate-distribution.sh
docs/src/dev/developer/release.asciidoc

https://issues.apache.org/jira/browse/TINKERPOP-1912
This PR basically just adds another step to the release process, that removes the auto-generated MD5 checksums.
See: http://www.apache.org/dev/release-publishing.html#distribution_maven
VOTE: +1

TINKERPOP-1912 Remove MD5 checksums

---

CHANGELOG.asciidoc
gremlin-console/pom.xml
gremlin-console/src/main/static/NOTICE
gremlin-server/pom.xml
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1934
Removed httpcore NOTICE entry as this more recent version does not contain that designation in its NOTICE.
VOTE +1

TINKERPOP-1934 Bumped httpclient to 4.5.5

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/dsl/credential/CredentialGraph.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/dsl/credential/CredentialGraphGremlinPlugin.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/dsl/credential/CredentialTraversalDsl.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/dsl/credential/CredentialTraversalSourceDsl.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/dsl/credential/CredentialGraphTest.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/dsl/credential/CredentialTraversalDslTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1903
The old CredentialGraph approach to the Credential DSL has been deprecated in favor of the preferred method for DSL development which was published long after the original DSL was developed.
VOTE +1

TINKERPOP-1903 Migrated Credential DSL to annotation processor

---

docs/src/reference/gremlin-variants.asciidoc

Several fixes to the JavaScript GLV documentation:
- Use 'gremlin' package name
- Include information regarding Promises
- Fix method names

Improve JavaScript Gremlin documentation

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/Parameters.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyAddVertexTest.groovy
gremlin-test/features/map/AddVertex.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/AddVertexTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1947
When a key of a mutation was a traversal it was not being integrated to the parent traversal and tracked in the Parameters. Works now with:
```text
gremlin> g.withSideEffect('k','name').addV('person').property(select('k'),'stephen')
==>v[3]
```
VOTE +1

TINKERPOP-1947 Fixed path history problem with mutations

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Element.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java

https://issues.apache.org/jira/browse/TINKERPOP-1941
These were related to elements not being found and were deprecated a long long time ago. Pretty easy one, but since it's a breaking change I figured it should go through review.
Builds with `mvn clean install`.
VOTE +1

TINKERPOP-1941 Removed deprecated structure api exception

---

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/graph-serializer.js
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/type-serializers.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/world.js

Add support for GraphSON3 to the JavaScript GLV.
https://issues.apache.org/jira/browse/TINKERPOP-1943
All gherkin scenarios are passing: `465 scenarios (27 skipped, 438 passed)`
VOTE +1

TINKERPOP-1943 Support GraphSON3 in Gremlin-JavaScript

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/resources/gremlin-server.yaml
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/GraphManager.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/Settings.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/OpSelectorHandler.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/traversal/TraversalOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/util/DefaultGraphManager.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuditLogIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthKrb5IntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

This PR actually covers these three related issues which all involve deprecation removal related to Gremlin Server:
https://issues.apache.org/jira/browse/TINKERPOP-1296
https://issues.apache.org/jira/browse/TINKERPOP-1707
https://issues.apache.org/jira/browse/TINKERPOP-1954
Builds with `mvn clean install && mvn verify -pl gremlin-server -DskipIntegrationTests=false'
VOTE +1

TINKERPOP-1296 Remove previously deprecated Gremlin Server infrastructure

---

pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1961
The asciidoc plugin copies all files in the source directories of its execution. The asciidoc plugin was upgraded between 3.2.5 and 3.2.6 which introduced this new behavior.
VOTE +1

TINKERPOP-1961 Removed duplication of images in binaries.

---

gremlin-python/src/main/jython/gremlin_python/driver/connection.py
gremlin-python/src/main/jython/gremlin_python/driver/protocol.py

https://issues.apache.org/jira/browse/TINKERPOP-1933
Recursive calls to the `data_received` were causing max recursion depth error with large streaming responses. This PR remove the recursion in favor of a simple loop. I didn't add any new tests. Locally, I tested like this:
```python
from gremlin_python.driver import client
groovy = """
def num_nodes = 1..100000
for (n in num_nodes) {
g.addV().next()
}
"""
c = client.Client('ws://localhost:8182/gremlin', 'g')
results = c.submit(groovy)
results.all().result()
results = c.submit("g.V().count()")
print("Added %d nodes to graph" % results.all().result()[0])
print("Ok up to len: %d" % len(c.submit("g.V().limit(61888)").all().result()))
try:
print("Retrieved %d nodes, no more recursion issue" % …
```

TINKERPOP-1933 gremlin-python maximum recursion depth exceeded on large responses

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/GraphTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/VertexTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1685
Added `supportsUpsert()` to both `VertexFeatures` and `EdgeFeatures`. Gives graph providers a more explicit option for providing this type of capability.
VOTE +1

TINKERPOP-1685 Added supportUpsert() feature

---

CHANGELOG.asciidoc
giraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/giraph/process/computer/GiraphGraphComputer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/MemoryComputeKey.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/TraversalVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/TraversalVertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/step/map/VertexProgramStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/util/VertexProgramHelper.java

https://issues.apache.org/jira/browse/TINKERPOP-1595
I did as the issue requested and optimized `TraversalVertexProgram`. Definitely some hotspots in there that have been removed. I'd say that the main fixes involved the direct lookup of `clone()` in `MemoryComputeKey` rather than cycling all methods and the use of Base64 encoding instead of CSV style string/regex derser for traversals in OLAP.
Feel free to VOTE but this change will not be merged until we open development for 3.2.10.
VOTE +1

TINKERPOP-1595 Optimize TraversalVertexProgram

---

CHANGELOG.asciidoc
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovySelectTest.groovy
gremlin-test/features/map/Select.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/SelectTest.java
tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/optimization/TinkerGraphCountStrategy.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/optimization/TinkerGraphCountStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1958
The strategy did not consider, that certain map steps may not emit an element.
`docker/build.sh -t -i` passed.
VOTE: +1

TINKERPOP-1958 Fixed a bug in TinkerGraphCountStrategy

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/BranchStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ReducingBarrierStep.java
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/branch/GroovyChooseTest.groovy
gremlin-test/features/branch/Choose.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/ChooseTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1963
Not sure I fixed this in the best way possible, but I added an `IdentityStep` to the front of each option:
https://github.com/apache/tinkerpop/compare/tp32...TINKERPOP-1963?expand=1#diff-546a91c51e7b731ccea30f0e4aff5d83R68
and then later checked that step to see if anything had been injected into it to determine if the choice had evaluated to `true` or not (since that was the existing way in which that was done).  I'm open to better approaches to resolving this problem if they can be suggested. Also ready to hear that "this way won't work because..." In the mean time.....
VOTE +1

TINKERPOP-1963 Fixed branch() problems with reducing steps as options

---

CHANGELOG.asciidoc
docs/src/dev/provider/index.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphManager.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphProvider.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/AbstractNeo4jGraphProvider.java

https://issues.apache.org/jira/browse/TINKERPOP-1518
For graphs that have an expensive startup time but a static set of `Graph.Features` the new `GraphProvider.getStaticFeatures()` method should help speed their test times as it will prevent creation of a new `Graph` instance for the test if the graph does not support the requisite features. For testing purposes, this capability was implemented for Neo4j, but it didn't do much to speed the execution time of the test suite - saved a couple minutes or so. It's generally pretty cheap to create Neo4j instances themselves, so I guess that is expected.
VOTE +1

TINKERPOP-1518 Cache Graph.Features for tests

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoaderVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/AddPropertyStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/event/ConsoleMutationListener.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/event/MutationListener.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/EventStrategyProcessTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1831
Removed deprecated method. Used `VertexProperty.empty()` and `Property.empty()` to represent the "old" value for new property events. Created an enum for configuring detachment on the `EventStrategy` builder. Upgrade docs describe this change in more detail.
VOTE +1

TINKERPOP-1831 Refactored EventStrategy

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MathStep.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/MathTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1979
Should be working now - just a serialization problem and fix to dealing with requirements for `PathProcessor` on `MathStep`. Note that you still can't access path labels with `math()` in OLAP after this fix or you will run afoul of standard behavior of `ComputerVerificationStrategy`. I think that's just a limitation of the overall design with OLAP and path.
VOTE +1

TINKERPOP-1979 Fix math() on OLAP/Spark

---

.gitignore
.travis.yml
CHANGELOG.asciidoc
docker/Dockerfile
docs/src/dev/developer/development-environment.asciidoc
docs/src/dev/developer/release.asciidoc
docs/src/reference/gremlin-applications.asciidoc
gremlin-dotnet/Gremlin.Net.sln
gremlin-dotnet/glv/Gremlin.Net.Template.csproj.template
gremlin-dotnet/glv/Gremlin.Net.Template.nuspec.template
gremlin-dotnet/glv/generate.groovy
gremlin-dotnet/src/Gremlin.Net.Template/.template.config/template.json
gremlin-dotnet/src/Gremlin.Net.Template/Gremlin.Net.Template.csproj
gremlin-dotnet/src/Gremlin.Net.Template/Gremlin.Net.Template.nuspec
gremlin-dotnet/src/Gremlin.Net.Template/Program.cs
gremlin-dotnet/src/Gremlin.Net.Template/README.md
gremlin-dotnet/src/Gremlin.Net.Template/Service.cs
gremlin-dotnet/src/pom.xml
gremlin-dotnet/test/Gremlin.Net.Template.IntegrationTest/Gremlin.Net.Template.IntegrationTest.csproj
gremlin-dotnet/test/Gremlin.Net.Template.IntegrationTest/ServiceTests.cs
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1836
This adds a dotnet template that can be installed and then used to create a simple dotnet console application ready to be used together with a Gremlin Server.
We need to release the template just like Gremlin.Net itself as a NuGet package to nuget.org.
**IMPORTANT**: The Maven `package` now **requires Mono** when .NET should be built as it's not possible to pack dotnet templates without Nuget (`dotnet pack` doesn't work for this unfortunately).
`./docker/build.sh -t -i` ran successfully until it failed due to some Giraph tests and the .NET projects were already built successfully. Since the Giraph tests are known to be flaky and we already deprecated Giraph, I didn't look further into that.
VOTE +1

TINKERPOP-1836 Add Gremlin.Net.Template project

---

CHANGELOG.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy

https://issues.apache.org/jira/browse/TINKERPOP-1989
Use the order presented in the configuration file to enforce the load order.
VOTE +1

TINKERPOP-1989 Enforce order of plugin load in Gremlin Console

---

CHANGELOG.asciidoc
docs/src/dev/provider/index.asciidoc
docs/src/reference/implementations-spark.asciidoc
docs/src/reference/the-graphcomputer.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/CoreImports.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoader.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/BulkLoaderVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/IncrementalBulkLoader.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/OneTimeBulkLoader.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/clone/CloneVertexProgram.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/RemoteGraph.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/CoreImports.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/AbstractImportCustomizerProvider.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/computer/clone/CloneVertexProgramTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1985
Deprecated `BulkLoaderVertexProgram` and `BulkDumperVertexProgram`. BLVP is not replaced, but BDVP has been renamed to `CloneVertexProgram` which is more aptly named for what it does. Modified docs to discuss all these changes.
VOTE +1

TINKERPOP-1985 Changing position on bulk import/export

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-variants.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/GremlinScriptEngine.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/ImportCustomizer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategyTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategyTraverseTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategyTraverseTest.java
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Decoration/SubgraphStrategy.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/StrategiesTests.cs
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/PartitionStrategyProcessTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategyProcessTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/TranslationStrategy.java

https://issues.apache.org/jira/browse/TINKERPOP-1986
Pretty minor deprecation removal, but as it is a breaking change so I offered a PR for it.
VOTE +1

TINKERPOP-1986 Removed deprecated methods

---

CHANGELOG.asciidoc
docs/src/dev/developer/development-environment.asciidoc
giraph-gremlin/src/test/resources/log4j-silent.properties
giraph-gremlin/src/test/resources/log4j-test.properties
gremlin-core/src/test/resources/log4j-silent.properties
gremlin-core/src/test/resources/log4j-test.properties
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/TestHelper.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/io/IoIntegrateTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/detached/DetachedGraphTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraphTest.java
gremlin-test/src/test/resources/log4j-silent.properties
gremlin-test/src/test/resources/log4j-test.properties
hadoop-gremlin/src/test/java/org/apache/tinkerpop/gremlin/hadoop/HadoopGraphProvider.java
hadoop-gremlin/src/test/resources/log4j-silent.properties
hadoop-gremlin/src/test/resources/log4j-test.properties
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/AbstractNeo4jGraphProvider.java
neo4j-gremlin/src/test/resources/log4j-silent.properties
neo4j-gremlin/src/test/resources/log4j-test.properties
spark-gremlin/src/test/resources/log4j-silent.properties
spark-gremlin/src/test/resources/log4j-test.properties
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/TinkerGraphComputerProvider.java
tinkergraph-gremlin/src/test/resources/log4j-silent.properties
tinkergraph-gremlin/src/test/resources/log4j-test.properties

https://issues.apache.org/jira/browse/TINKERPOP-1365
Each test suite now uses the same instance of Random which prints the seed given to it so that if there is a failure, we can easily try to recreate it by taking the seed and passing it in as a system property with -DtestSeed. The output logs as:
```text
[INFO] org.apache.tinkerpop.gremlin.TestHelper - *** THE RANDOM TEST SEED IS 1529585621517 ***
```
I didn't replace all of the old use of `Random` - there were a couple places where I felt like a true `Random` was still necessary and just left it alone despite the horror it might cause. Going forward we'll want to use the `TestHelper.RANDOM` whenever possible (or, better, just not use a `Random` at all).
VOTE +1

TINKERPOP-1365 Refactored use of Random in tests

---

gremlin-python/pom.xml
gremlin-python/src/main/jython/radish/terrain.py
gremlin-python/src/main/jython/setup.py

https://issues.apache.org/jira/browse/TINKERPOP-1864
There was about a 10 second time increase for adding the additional test execution option. Seems worthwhile.
VOTE +1

TINKERPOP-1864 Run python glv tests on GraphSON 2.0 and 3.0

---

CHANGELOG.asciidoc
gremlin-console/src/main/static/NOTICE
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
gremlin-server/src/main/static/NOTICE
pom.xml
spark-gremlin/pom.xml
spark-gremlin/src/test/java/org/apache/tinkerpop/gremlin/spark/process/computer/LocalPropertyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1987
https://issues.apache.org/jira/browse/TINKERPOP-1993
These really needed to be bumped together because going to netty 4.1.x doesn't work nicely with Spark 2.2.x - Spark only upgraded to that version on 2.3.x. 
That odd change to `gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs` is incidental - that modification is already on master and rebase doesn't seem to to want to get rid of it. Hopefully no one is too turned off by that little stain in change history - doesn't seem like a huge problem.
VOTE +1

TINKERPOP-1987 Bump to Spark 2.3.1 and Netty 4.1.25.Final

---

CHANGELOG.asciidoc
gremlin-shaded/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2016
Bumped to Jackson 2.9.6 for CVE.
All tests pass with `docker/build.sh -i -t -n`
The CI build errors are Grapes related. I built several times locally and through docker with no issues.
VOTE +1

TINKERPOP-2016 Bumped to Jackson 2.9.6

---

gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/message/ResponseStatusCode.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/message/ResponseStatusCodeTest.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/ResponseHandlerContext.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/AbstractGremlinServerIntegrationTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/ResponseHandlerContextTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessorTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/op/AbstractOpProcessorTest.java

Address [TINKERPOP-2005](https://issues.apache.org/jira/browse/TINKERPOP-2005) by ignoring more than one "final" response messages from `AbstractEvalOpProcessor`.
Add `isFinalResponse()` getter to `ResponseStatusCode`
Introduce `ResponseHandlerContext` to allow tracking the final response
status per request message.
Update `AbstractOpProcessor`, `AbstractEvalOpProcessor` and related classes
to write response messages through `ResponseHandlerContext` methods as
opposed to `ChannelHandlerContext` methods.
----
In addition to the failure mode described in [TINKERPOP-2005](https://issues.apache.org/jira/browse/TINKERPOP-2005) non-timeout script evaluation exceptions in AbstractEvalOpProcessor may occur after the script has started executing. In this situation it it critical to prevent …

TINKERPOP-2005: Intermittent NullPointerException in response handling

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/RemoteGraph.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/TraversalSerializersV2d0.java
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/TraversalEvaluation/ModernGraphTypeInformation.cs
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteTraversalSideEffects.java
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyPageRankTest.groovy
gremlin-groovy-test/src/main/groovy/org/apache/tinkerpop/gremlin/process/traversal/step/map/GroovyPeerPressureTest.groovy
gremlin-javascript/src/main/javascript/gremlin-javascript/test/cucumber/feature-steps.js
gremlin-python/glv/GraphTraversalSource.template
gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
gremlin-test/features/map/PageRank.feature
gremlin-test/features/map/PeerPressure.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/AbstractGremlinProcessTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PageRankTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/PeerPressureTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/TranslationStrategyProcessTest.java
gremlin-test/src/test/java/org/apache/tinkerpop/gremlin/process/FeatureCoverageTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1976
Added GLV tests for `pageRank()` and `peerPressure()` (i.e. "computer" tests). Apparently we had good support for this already in the GLVs (except gremlin-javascript - which will need that support added). Got rid of some remote test `OptOut` declarations too.
VOTE +1

TINKERPOP-1976 GLV testing for computer tests

---

gremlin-dotnet/glv/Gremlin.Net.csproj.template
gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj

https://issues.apache.org/jira/browse/TINKERPOP-2012
This simply adds .NET Standard 2.0 as an additional target for Gremlin.Net. Since it doesn't really require any additional effort to target multiple frameworks, it doesn't make much sense to drop the existing .NET Standard 1.3 target. That way, we don't drop support for any .NET implementations or versions, especially the current .NET Core LTS versions 1.0 and 1.1 as @jorgebay mentioned in the JIRA issue.
VOTE +1

TINKERPOP-2012 Add .NET Standard 2.0 target to Gremlin.Net

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Client.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/RequestOptions.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1342
Deprecated a couple of overloads of `Client.submit()` as they seem clumsy now given that we have the nicer `RequestOptions`. Now with `RequestOptions` users can submit a per-request script timeout as well as other settings.
VOTE +1

TINKERPOP-1342 Allow for more per-request options in Java driver

---

CHANGELOG.asciidoc
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/README.asciidoc
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/main/java/App.java
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/main/java/Service.java
gremlin-archetype/gremlin-archetype-server/src/main/resources/archetype-resources/src/test/java/ServiceTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2024
Since we're promoting remote traversals over scripts it would be better for the archetype to use them.
Builds with `mvn clean install` 
VOTE +1

TINKERPOP-2024 Make server archetype use remote traversal

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/AbstractGremlinScriptEngineFactory.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/GremlinDslProcessor.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversalMetrics.java

String concatenation in loops. As every String concatenation copies the whole String, usually it is preferable to replace it with explicit calls to StringBuilder.append() or StringBuffer.append().

String loop to String builder [tp32]

---

gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/util/TinkerGraphProvider.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphProvider.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/AbstractNeo4jGraphProvider.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/TinkerGraphProvider.java

What's changed [master]:
Classes that have implemented `GraphProvider#clear` must note that the parameter `graph` and `config` are nullable, so that a proper `null` checking and handling is needed. Otherwise, test cases that have extended `org.apache.tinkerpop.gremlin.AbstractGremlinTest.java` may throw exception when it comes to `tearDown()`
* Update comments in `GraphProvider#clear`, `GraphProvider#openTestGraph`.
* Add `null` checking in the `clear` method of the three implemented `GraphProvider`:
- `org.apache.tinkerpop.gremlin.neo4j.AbstractNeo4jGraphProvider.java`
- `org.apache.tinkerpop.gremlin.tinkergraph.TinkerGraphProvider.java`
- `org.apache.tinkerpop.gremlin.util.TinkerGraphProvider.java`
* `org.apache.tinkerpop.gremlin.AbstractGremlinTest`
- Set `graph` to `null` when …

Update comments in GraphProvider clear() and openTestGraph() [master]

---

gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphProvider.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/AbstractNeo4jGraphProvider.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/TinkerGraphProvider.java

What's changed [tp32]:
Classes that have implemented `GraphProvider#clear` must note that the parameter `graph` and `config` are nullable, so that a proper `null` checking and handling is needed. Otherwise, test cases that have extended `org.apache.tinkerpop.gremlin.AbstractGremlinTest.java` may throw exception when it comes to `tearDown()`
* Update comments in `GraphProvider#clear`, `GraphProvider#openTestGraph`.
* Add `null` checking in the `clear` method of the two implemented `GraphProvider`:
- `org.apache.tinkerpop.gremlin.neo4j.AbstractNeo4jGraphProvider.java`
- `org.apache.tinkerpop.gremlin.tinkergraph.TinkerGraphProvider.java`
* `org.apache.tinkerpop.gremlin.AbstractGremlinTest`
- Set `graph` to `null` when `tearDown()`
- Add comment at `tearDown()`
- Remove unused imports

Update comments in GraphProvider clear() and openTestGraph() [tp32]

---

gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/util/TinkerGraphProvider.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/AbstractGremlinTest.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphProvider.java
neo4j-gremlin/src/test/java/org/apache/tinkerpop/gremlin/neo4j/AbstractNeo4jGraphProvider.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/TinkerGraphProvider.java

What's changed [tp33]:
Classes that have implemented `GraphProvider#clear` must note that the parameter `graph` and `config` are nullable, so that a proper `null` checking and handling is needed. Otherwise, test cases that have extended `org.apache.tinkerpop.gremlin.AbstractGremlinTest.java` may throw exception when it comes to `tearDown()`
* Update comments in `GraphProvider#clear`, `GraphProvider#openTestGraph`.
* Add `null` checking in the `clear` method of the three implemented `GraphProvider`:
- `org.apache.tinkerpop.gremlin.neo4j.AbstractNeo4jGraphProvider.java`
- `org.apache.tinkerpop.gremlin.tinkergraph.TinkerGraphProvider.java`
- `org.apache.tinkerpop.gremlin.util.TinkerGraphProvider.java`
* `org.apache.tinkerpop.gremlin.AbstractGremlinTest`
- Set `graph` to `null` when …

Update comments in GraphProvider clear() and openTestGraph() [tp33]

---

docs/src/recipes/cycle-detection.asciidoc

Not sure if it is worth it but I figured out that self loops weren't detected in the given example.

Add self loop example to Cycle Detection recipe.

---

CHANGELOG.asciidoc
docs/src/reference/the-traversal.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ConnectiveStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ConnectiveStrategyTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/InlineFilterStrategyTest.java
gremlin-test/features/filter/And.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/filter/AndTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2029
To fix the original issue, I basically rewrote `ConnectiveStrategy`. The infix notation of `and()` and `or()` now supports an arbitrary number of traversals and `ConnectiveStrategy` produces a traversal with correct `AND` and `OR` semantics.
The reason for targeting `master/` is that there were no strict semantics before and thus this needs to be considered a breaking change.
```
Input: a.or.b.and.c.or.d.and.e.or.f.and.g.and.h.or.i
Output: or(a, or(and(b, c), or(and(d, e), or(and(and(f, g), h), i))))
Output: or(a, and(b, c), and(d, e), and(f, g, h), i)
```
VOTE +1

TINKERPOP-2029 ConcurrentModificationException for InlineFilterStrategy

---

CHANGELOG.asciidoc
gremlin-python/pom.xml

https://snyk.io/vuln/SNYK-JAVA-ORGPYTHON-31451
Overview
org.python:jython-standalone Affected versions of this package are vulnerable to Arbitrary Code Execution by sending a serialized function to the deserializer, which in turn will execute the code.
References
[CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-4000)
[Jython Bug Report](http://bugs.jython.org/issue2454)
[Fix Commit](https://hg.python.org/jython/rev/d06e29d100c0)

TINKERPOP-2032 bump jython-standalone 2.7.1

---

gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketConnection.cs

https://issues.apache.org/jira/browse/TINKERPOP-2026
This should solve the problem described in the ticket where apparently the server already initiated closing of the connection when the driver tries to close it which led to an exception.
VOTE +1

TINKERPOP-2026 Make closing of connections more robust in Gremlin.Net.Driver 

---

gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java

Preface:
There's character escaping issue when translating.
What's changed:
- Merge the changes from tp32
- org.apache.tinkerpop.gremlin.groovy.jsr223.GroovyTranslatorTest
Adjust the test case to verify the changes in tp33.

Apply StringEscapeUtils in GroovyTranslator#convertToString(String) [tp33]

---

gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java

Preface:
There's character escaping issue when translating.
What's changed:
- `org.apache.tinkerpop.gremlin.groovy.jsr223.GroovyTranslator#convertToString`
Apply `StringEscapeUtils.escapeJava(String)` for String object.
- `org.apache.tinkerpop.gremlin.groovy.jsr223.GroovyTranslatorTest`
Add a few test cases to verify the changes.

Apply StringEscapeUtils in GroovyTranslator#convertToString(String) [tp32]

---

bin/validate-distribution.sh
docs/src/dev/developer/release.asciidoc
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2025
Unfortunately, upgrading the Apache parent pom didn't solve the problem completely. With the upgrade we get the sha512 checksum file for the source release, but not for the other artifacts.
This PR upgrades the parent pom, but also adds a step in the release process to replace any remaining sha1 checksum file with its sha512 counterpart.
The release validation script was adjusted to reflect those changes; the validation will fail if there exists
* a md5 file
* a sha1 file
* no asc file
* no sha512 file
... for any of the release artifacts.
VOTE +1

TINKERPOP-2025 Change to SHA-256/512 and drop SHA-1 for releases

---

CHANGELOG.asciidoc
gremlin-console/pom.xml
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
gremlin-dotnet/pom.xml
gremlin-javascript/pom.xml
gremlin-python/pom.xml
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2039
Required some minor changes to the Console as the CliBuilder is no longer the recommended approach for Groovy - had to use picocli classes instead. Still couldn't make the command line parsing work exclusively under picocli - I think we have somewhat nonstandard options in our command line.
Performed manual tests and builds with `mvn clean install && mvn verify -pl gremlin-console -DskipIntegrationTests=false`.
VOTE +1

TINKERPOP-2039 Bump to Groovy 2.5.2

---

CHANGELOG.asciidoc
gremlin-driver/pom.xml
gremlin-groovy/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2045
Exclude non-indy transitive dep on groovy core.
`mvn clean install` success
VOTE +1

TINKERPOP-2045 removed duplicate non-indy groovy core dep

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/sideEffect/SideEffectCapStep.java

Copying of array contents to a collection where each element is added individually using a for a loop. We can be replaced by a call to Collections.addAll().
As the documentation says:
> Adds all of the specified elements to the specified collection. Elements to be added may be specified individually or as an array. The behavior of this convenience method is identical to that of c.addAll(Arrays.asList(elements)), but this method is likely to run significantly faster under most implementations.
When elements are specified individually, this method provides a convenient way to add a few elements to an existing collection:
https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#addAll-java.util.Collection-T...-
In my experience using either Collections.addll or Collections.addAll …

optmizes collection copy with Collections addAll

---

CHANGELOG.asciidoc
gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionFactory.cs
gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs
gremlin-dotnet/src/Gremlin.Net/Driver/WebSocketConnection.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-2015
Users can now provide a delegate to the Gremlin.Net driver that will be used to configure WebSocket connections. Using a delegate for this has the advantage that it's extensible as the options available via [`ClientWebSocketOptions`](https://docs.microsoft.com/dotnet/api/system.net.websockets.clientwebsocketoptions) change between different .NET implementations, e.g., as mentioned in the ticket, a `RemoteCertificateValidationCallback` was added with .NET Core 2.1.
When #903 is merged first, then we need to add this new option also to the docs when merging this into `master` as #903 adds descriptions for the config options to the docs.
VOTE +1

TINKERPOP-2015 Expose WebSocket configuration in Gremlin.Net driver

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/TranslatorCustomizer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Translator.java
gremlin-groovy-test/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java

https://issues.apache.org/jira/browse/TINKERPOP-2040
Handled all of the core GraphSON types in the `GroovyTranslator`. Included a new `TypeTranslator` to allow the behavior of the `ScriptTranslator` to be modified and allowed the `GremlinGroovyScriptEngine` to accept a `TranslatorCustomizer` to allow that custom `TypeTranslator` to be used.
VOTE +1

TINKERPOP-2040 Improve flexibility of GroovyTranslator to handle custom types

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalTest.java
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
gremlin-test/features/map/ShortestPath.feature
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/ShortestPathTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2049
Makes flag-like uses of with() a bit more succinct. Basically, the shorthand of `with(k,true)` is simply `with(k)`.
VOTE +1

TINKERPOP-2049 Added with(k) overload

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ConnectionPool.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/SettingsTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2044
The user can now configure the script used to validate the operations of the remote.
```text
Cluster cluster = Cluster.build().validationRequest("g.inject()").create()
```
Builds with `mvn clean install -pl gremlin-driver && mvn verify -pl gremlin-server -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-2044 Configurable traversal to validate host connectivity.

---

CHANGELOG.asciidoc
docs/src/dev/io/graphson.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONSerializersV2d0.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapperEmbeddedTypeTest.java
gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONReaderTests.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Structure/IO/GraphSON/GraphSONWriterTests.cs
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/structure/io/type-serializers.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/graphson-test.js
gremlin-python/src/main/jython/gremlin_python/structure/io/graphson.py
gremlin-python/src/main/jython/tests/structure/io/test_graphson.py

https://issues.apache.org/jira/browse/TINKERPOP-2055
GraphSON wasn't supporting NaN and Infinity but Gryo was. Merging to tp33 and forward will require some additional commits for GraphSON 3.0.
VOTE +1

TINKERPOP-2055 Support NaN and Infinity in GraphSON

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphFilter.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/strategy/optimization/GraphFilterStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/util/star/StarGraphGryoSerializer.java

This PR replaces the HashMap implementation to [EnumMap](https://docs.oracle.com/javase/8/docs/api/java/util/EnumMap.html) that as its documentation says:
> A specialized Map implementation for use with enum type keys. All of the keys in an enum map must come from a single enum type that is specified, explicitly or implicitly, when the map is created. Enum maps are represented internally as arrays. This representation is extremely compact and efficient.

Optimizes Map with enum using the EnumMap implementation [tp32]

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Compare.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/PTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2056
Instead of converting all numbers to `BigDecimal`, `Compare` predicates now use `NumberHelper` for numerical comparisons.
VOTE +1

TINKERPOP-2056 Use NumberHelper in Compare

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-driver/pom.xml

Removed unused groovy-sql dependency.
https://issues.apache.org/jira/browse/TINKERPOP-2037
`sh docker/build.sh -i -t` BUILD SUCCESS
VOTE +1

TINKERPOP-2037 removed groovy-sql

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/OptionsStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/SubgraphStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoVersion.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/OptionsStrategyTest.java
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Decoration/OptionsStrategy.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
gremlin-python/src/main/jython/gremlin_python/process/strategies.py
gremlin-python/src/main/jython/tests/driver/test_client.py
gremlin-python/src/main/jython/tests/process/test_strategies.py
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/decoration/OptionsStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2053
`OptionsStrategy` lets users pass arbitrary configurations at a traversal level. At first I thought this might be a first class object, but decided instead to try it out as a `TraversalStrategy`. In that way it was implemented with little overhead. If it becomes useful and popular in the future then we can consider making it more integrated into the `TraversalSource` and `Traversal` itself. I didn't implement this for javascript because I don't think we have all the infrastructure there for supporting `TraversalStrategy` stuff yet. 
VOTE +1

TINKERPOP-2053 Support for OptionsStrategy

---

gremlin-dotnet/glv/GraphTraversal.template
gremlin-dotnet/glv/GraphTraversalSource.template
gremlin-dotnet/glv/generate.groovy
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversal.cs
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/GherkinTestRunner.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Gherkin/TraversalEvaluation/TraversalParser.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/BytecodeGeneration/BytecodeGenerationTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-1972
We had two issues with the `inject` step in Gremlin.Net. The first one prevented the Gherkin test runner from executing scenarios that included an `inject` step. This was fixed by @jorgebay with the first commit in this PR. Thanks for that, Jorge!
The second issue was that the arguments passed to the `inject` step were always wrapped in an array which was caused by the fact that the `inject` step takes a `params` array with a generic member type. We created a `List<S>` for these arguments and provided that to the method `ByteCode.AddStep()` which expects a `params object[]` argument. Since the compiler can't convert `List<S>` into `object[]`, it simply treated the `List<S>` as the first argument which resulted in an `object[]` with just …

TINKERPOP-1972 Fix inject step in Gremlin.Net

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Contains.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/ContainsTest.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/PTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2058
If the object to be filtered is a number, `Contains` predicates will now scan the provided collection, comparing each element using `Compare.eq`. For non-numeric values `Contains.within` will still use `collection.contains()` in order to make use of search-optimized data types (e.g. `Set`).
This is a breaking change as the test suite previously ensured that number types had an effect on `Contains` predicates. This, however, was inconsistent with `Compare` predicates which ignore the number type.
VOTE +1

TINKERPOP-2058 Contains predicates should rely on Compare predicates

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/GraphTraversalSource.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/graph-traversal.js
gremlin-python/src/main/jython/gremlin_python/process/graph_traversal.py
gremlin-python/src/main/jython/tests/driver/test_client.py
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/process/traversal/strategy/decoration/OptionsStrategyTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2061
Basically just shorthands the direct use of `OptionStrategy` which is much more verbose and less nice to look at. See the upgrade doc changes in this PR for an example of usage.
VOTE +1

TINKERPOP-2061 Added with() option for traversal configuration

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/CoreImports.java

https://issues.apache.org/jira/browse/TINKERPOP-2062
Not really worth a PR, could have been a CTR, but just in case someone has any complaints about adding this import.
VOTE +1

TINKERPOP-2062 added Traversal class to CoreImports

---

CHANGELOG.asciidoc
gremlin-shaded/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2068
security fix
`docker/build.sh -i -t -n` SUCCESS
VOTE +1

TINKERPOP-2068 bump jackson-databind to 2.9.7 [master]

---

CHANGELOG.asciidoc
gremlin-shaded/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2068
security fix
`docker/build.sh -i -t -n` SUCCESS
VOTE +1

TINKERPOP-2068 bump jackson-databind to 2.9.7 [tp33]

---

CHANGELOG.asciidoc
gremlin-shaded/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2068
security fix
`docker/build.sh -i -t -n` SUCCESS
VOTE +1

TINKERPOP-2068 bump jackson-databind to 2.9.7 [tp32]

---

docs/src/reference/gremlin-variants.asciidoc
docs/src/upgrade/release-3.2.x-incubating.asciidoc
gremlin-javascript/pom.xml
gremlin-javascript/src/main/javascript/gremlin-javascript/index.js
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/client.js
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/remote-connection.js
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/result-set.js
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/utils.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/helper.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/client-tests.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/remote-connection-tests.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/integration/sasl-authentication-tests.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/exports-test.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/result-set-test.js

https://issues.apache.org/jira/browse/TINKERPOP-2070
Extract `Connection` implementation out of the `DriverRemoteConnection`.
The `DriverRemoteConnection` now uses a `Client` instance, a `Client` instance may contain one or more `Connection` instances, similar to the Python and .NET glv.
Introduce `ResultSet` that is aligned to other GLVs: 
- `Client` and `Connection` `submit()` methods return a `ResultSet` instance
- `DriverRemoteConnection` submissions returns an instance of `RemoteTraversal`.
This is a large-ish refactor but it doesn't represent a breaking change for the user.
Additionally, I've identified an issue when we introduced script submission support in gremlin-javascript (my bad!): We exposed a property named `traversers` (see previous code examples). I've maintained that …

TINKERPOP-2070: Introduce Connection and ResultSet abstractions

---

CHANGELOG.asciidoc
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/DefaultTraversal.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Process/Traversal/TestTraversal.cs
gremlin-javascript/glv/TraversalSource.template
gremlin-javascript/src/main/javascript/gremlin-javascript/lib/process/traversal.js
gremlin-javascript/src/main/javascript/gremlin-javascript/test/unit/traversal-test.js
gremlin-python/glv/TraversalSource.template
gremlin-python/src/main/jython/gremlin_python/process/traversal.py

https://issues.apache.org/jira/browse/TINKERPOP-2065
Fixed this for python, .NET and js. This means that results will no longer be sent back from the server to the client (i.e. no client side iteration).
VOTE +1

TINKERPOP-2065 iterate() now sends NoneStep

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/Translator.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslator.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyTranslatorTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2072
This approach makes it much easier to extend `TypeTranslator` as the core functionality of the `GroovyTranslator` is itself a `TypeTranslator`. Simply extend that and go. Probably should have been this way from the beginning. This is a breaking change but on a fairly hidden/internal component - should only affect providers.
VOTE +1

TINKERPOP-2072 Refactored TypeTranslator for direction extension

---

docs/src/dev/provider/index.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/reference/gremlin-variants.asciidoc
gremlin-dotnet/src/Gremlin.Net/Driver/GremlinServer.cs

https://issues.apache.org/jira/browse/TINKERPOP-2069
This simply adds documentation on how to configure the Gremlin.Net driver to the reference docs. It also fixes a small mistake in the provider docs where we forgot to change the classes for GraphSON3 and it adds `localhost` as the default `hostname` to be consistent with the Java driver.
I built the docs with `./docker/build.sh -d`.
VOTE +1

TINKERPOP-2069 Document Gremlin.Net driver config

---

CHANGELOG.asciidoc
docs/src/tutorials/gremlin-language-variants/index.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-console/src/test/resources/org/apache/tinkerpop/gremlin/console/jsr223/gremlin-server-integration.yaml
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerGremlinV2d0.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV2d0.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphSONMessageSerializerV3d0.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/Serializers.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerHttpIntegrateTest.java
gremlin-server/src/test/resources/org/apache/tinkerpop/gremlin/server/gremlin-server-integration.yaml

https://issues.apache.org/jira/browse/TINKERPOP-1984
Making `GraphSONMessageSerializerV2d0` handle both typed and untyped formats allows it to be used in a fashion where users can choose to add serializers with `application/json` at the same time for HTTP use cases. It also generally seemed to make more sense than how it was before. Not sure what changed to allow this now and not in the past.
Note the upgrade docs for why this is considered a breaking change - fairly minor I think.
VOTE +1

TINKERPOP-1984 Enable GraphSON serializers to no longer conflict

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/CompilationOptionsCustomizer.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyCompilerGremlinPlugin.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineCompilationOptionsTest.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyCompilerGremlinPluginTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2038
Exposed as a configuration option on the GroovyCompilerGremlinPlugin where the config is set via a Caffeine specification string.
VOTE +1

TINKERPOP-2038 Made the GremlinGroovyScriptEngine cache configurable

---

CHANGELOG.asciidoc
gremlin-console/src/main/groovy/org/apache/tinkerpop/gremlin/console/Console.groovy
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/CoreGremlinPlugin.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/CoreImports.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/DefaultImportCustomizer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/ImportCustomizer.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/jsr223/DefaultImportCustomizerTest.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/ImportGroovyCustomizer.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyScriptEngineSetup.java

https://issues.apache.org/jira/browse/TINKERPOP-2104
We can now import `Field` instances to the `ScriptEngine` which allows for import of public fields from classes like `WithOptions`:
```text
gremlin> labels
==>2
```
Note that I only allowed for the ability to do this and didn't bother to add any new imports. For `WithOptions` it would just create a bunch of conflicts with existing tokens (e.g. keys, values, etc).
VOTE +1

TINKERPOP-2104 Allow ImportCustomizer to handle fields

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/AnonymousTraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSourceTest.java
sparql-gremlin/src/main/java/org/apache/tinkerpop/gremlin/sparql/process/traversal/dsl/sparql/SparqlTraversalSource.java
sparql-gremlin/src/test/java/org/apache/tinkerpop/gremlin/sparql/process/traversal/dsl/sparql/SparqlTraversalSourceTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2080
Users should now be using `AnonymousTraversalSource` which is the more unified way to create the `TraversalSource` instance.
VOTE +1

TINKERPOP-2080 Removed withRemote from TraversalSource

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/EmbeddedRemoteConnection.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/RemoteConnection.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.java

https://issues.apache.org/jira/browse/TINKERPOP-2103
These methods were long ago deprecated and aren't used anywhere within TinkerPop core.
VOTE +1

TINKERPOP-2103 Remove deprecated submit() on RemoteConnection

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/remote/RemoteConnection.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalSource.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/remote/DriverRemoteConnection.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2102
These fields were related to remoting and have no place there really since `AnonymousTraversalSource` has now come into the picture and `TraversalSource.withRemote()` is set for removal.
VOTE +1

TINKERPOP-2102 Deprecate static fields on TraversalSource

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/AbstractGremlinScriptEngineFactory.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/DefaultGremlinScriptEngineManager.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/GraphFilter.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/bulkloading/IncrementalBulkLoader.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/traversal/MemoryTraversalSideEffects.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/computer/util/ComputerGraph.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/P.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/branch/RepeatStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/map/GraphStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ReducingBarrierStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphml/GraphMLWriterHelper.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/AbstractGraphSONTypeSerializer.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONMapper.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONTypeIdResolver.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/util/function/Lambda.java

Hello everyone, I still studying the code to help more in the project, then I found a small performance improvement. That is access the field directly instead of using the getter setter.
```java
@Warmup(iterations = 5, time = 1, timeUnit = TimeUnit.SECONDS)
@Measurement(iterations = 20, time = 1, timeUnit = TimeUnit.SECONDS)
@Fork(3)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
public class ClientBenchmark {
private final ObjectMapper mapper = GraphSONMapper.build().version(GraphSONVersion.V3_0).create().createMapper();
private final Graph graph = TinkerFactory.createModern();
private final Optional<Vertex> vertex = graph.traversal().V().tryNext();
@Setup
public void setup() {
}
@Benchmark
public String write() throws JsonProcessingException …
```

uses the directly field instead of getter method

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/CoreImports.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/finalization/ReferenceElementStrategy.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/decoration/ReferenceElementStrategyTest.java
gremlin-server/scripts/empty-sample-secure.groovy
gremlin-server/scripts/empty-sample.groovy
gremlin-server/scripts/generate-classic.groovy
gremlin-server/scripts/generate-modern-readonly.groovy
gremlin-server/scripts/generate-modern.groovy
gremlin-server/scripts/load-sample.groovy
gremlin-server/scripts/spark.groovy
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinResultSetIntegrateTest.java
gremlin-server/src/test/scripts/generate-all.groovy

https://issues.apache.org/jira/browse/TINKERPOP-2075
This strategy converts all graph elements to references. Configured this strategy in Gremlin Server by default for the example graphs. Made a few minor updates to tests that were assuming the return of "detached" elements.
VOTE +1

TINKERPOP-2075 Added ReferenceElementStrategy

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/AbstractGremlinScriptEngineFactory.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/DefaultGremlinScriptEngineManager.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/P.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSource.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/ReducingBarrierStep.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/util/DefaultTraversal.java

Reverted changes where field access might have caused class extensions to misbehave. Made methods final where possible to prevent extension followed by improper operations of methods that now use fields. No need to VOTE on this.

Minor fixups to #1001 performance enhancements

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Cluster.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Host.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Settings.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/HostTest.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/AbstractChannelizer.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/channel/WebSocketChannelizer.java

https://issues.apache.org/jira/browse/TINKERPOP-2110
Builds with `mvn clean install && mvn verify -pl gremlin-driver,gremlin-server -DskipIntegrationTests=false`
VOTE +1

TINKERPOP-2110 Added option to change path for java driver

---

gremlin-dotnet/glv/P.template
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/P.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/PredicateTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-2113
This was apparently pretty much the same bug as with the problems we had earlier with the `inject()` step ([TINKERPOP-1972](https://issues.apache.org/jira/browse/TINKERPOP-1972)). So, the fix was also basically the same.
All .NET tests pass.
VOTE +1

TINKERPOP-2113 Fix P.Within() for list arguments in Gremlin.NET

---

CHANGELOG.asciidoc
gremlin-shaded/pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2121
Fixes: CVE-2018-19360, CVE-2018-19361, CVE-2018-19362,  CVE-2018-1000873
```
$ docker/build.sh -i -t -n
[INFO] Apache TinkerPop ................................... SUCCESS [01:10 min]
[INFO] Apache TinkerPop :: Gremlin Shaded ................. SUCCESS [  9.105 s]
[INFO] Apache TinkerPop :: Gremlin Core ................... SUCCESS [01:10 min]
[INFO] Apache TinkerPop :: Gremlin Test ................... SUCCESS [  6.737 s]
[INFO] Apache TinkerPop :: Gremlin Groovy ................. SUCCESS [03:32 min]
[INFO] Apache TinkerPop :: Gremlin Groovy Test ............ SUCCESS [  4.568 s]
[INFO] Apache TinkerPop :: TinkerGraph Gremlin ............ SUCCESS [03:49 min]
[INFO] Apache TinkerPop :: Gremlin Benchmark .............. SUCCESS [  3.470 s] …
```

Bump Jackson Databind 2.9.8

---

CHANGELOG.asciidoc
gremlin-console/src/main/static/NOTICE
gremlin-server/src/main/static/NOTICE
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-2118
VOTE +1

TINKERPOP-2118 Bump to groovy 2.4.16

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-variants.asciidoc
docs/src/upgrade/release-3.4.x.asciidoc
gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs
gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPoolSettings.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Exceptions/NoConnectionAvailableException.cs
gremlin-dotnet/src/Gremlin.Net/Driver/GremlinClient.cs
gremlin-dotnet/src/Gremlin.Net/Driver/SingleMessageResultReceiver.cs
gremlin-dotnet/src/Gremlin.Net/Process/Utils.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/ConnectionPoolTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/GremlinClientTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/GraphTraversalTests.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Process/Traversal/DriverRemoteConnection/RemoteConnectionFactory.cs
gremlin-dotnet/test/Gremlin.Net.UnitTest/Driver/ConnectionPoolSettingsTests.cs
pom.xml

https://issues.apache.org/jira/browse/TINKERPOP-1774
https://issues.apache.org/jira/browse/TINKERPOP-1775
This allows connections to be reused for different requests in parallel which should lead to better utilization of connections / lower resource usage. The `ConnectionPool` now also has a fixed size whereas it could previously create an unlimited number of connections. Each `Connection` can handle up to `MaxInProcessPerConnection` requests in parallel.
If this limit is reached for all connections, then a `NoConnectionAvailableException` is thrown which makes this a breaking change.
This change fixes both issues together as discussed in PR #903.
All tests pass with `./docker/build.sh -t -i` and I verified that the changed docs look as expected with `./docker/build.sh -d`.

Add request pipelining and a fixed ConnectionPool size TINKERPOP-1775 and TINKERPOP-1774

---

docs/src/reference/compilers.asciidoc

The rendering was off due to the `|` characters in the table, this seems to fix it

Fix table rendering in Sparql reference docs.

---

CHANGELOG.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/traverser/util/TraverserSet.java

https://issues.apache.org/jira/browse/TINKERPOP-2126
This PR replaces the `LinkedHashMap` used by `TraverserSet` with a `SynchronizedMap`. I haven't added a test case, cause I really don't know how to consistently provoke a `ConcurrentModificationException`; however, a `ConcurrentModificationException` did happen several times in a provider implementation and it was caused by the `TraverserSet::toString()` method while Spark was a) processing a query and b) concurrently logging the current state. The way `TraverserSet::toString()` is implemented, it totally makes sense that this scenario would sooner or later hit a `ConcurrentModificationException` if we don't use a synchronized map.
`docker/build.sh -t -i` passed.
VOTE +1

TINKERPOP-2126 Made TraverserSet internals thread-safe

---

gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/connection.js

Fixes the bug reported [here](https://issues.apache.org/jira/browse/TINKERPOP-2130).
The issue was that default empty options object was directly assigned to this.options instead of to the options argument itself.

TINKERPOP-2130 Fix default parameter assignment in Connection ctor

---

CHANGELOG.asciidoc
gremlin-dotnet/src/Gremlin.Net/Driver/ConnectionPool.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Exceptions/ConnectionPoolBusyException.cs
gremlin-dotnet/src/Gremlin.Net/Driver/Exceptions/ServerUnavailableException.cs
gremlin-dotnet/test/Gremlin.Net.IntegrationTest/Driver/ConnectionPoolTests.cs

https://issues.apache.org/jira/browse/TINKERPOP-2131
Two new exception classes are added to better reveal the reason for a `NoConnectionAvailableException`:
* The pool is empty because the server is unavailable
-> `ServerUnavailableException`
* All connections have reached the max in-flight requests limit
-> `ConnectionPoolBusyException`
Both extend `NoConnectionAvailableException` so this is a non-breaking change.
VOTE +1

TINKERPOP-2131 Gremlin.Net: Better explain connection pool exceptions

---

.travis.yml
docker/Dockerfile
docs/src/dev/developer/development-environment.asciidoc
gremlin-dotnet/glv/Gremlin.Net.csproj.template
gremlin-dotnet/src/Gremlin.Net/Gremlin.Net.csproj

https://issues.apache.org/jira/browse/TINKERPOP-2088
This requires contributors to update to .NET Core SDK 2.1.300 or newer.
Travis and the Docker build now use the most recent SDK 2.2.
SourceLink should make it easier for users to debug Gremlin.Net within their application as they get better access to the source code of Gremlin.Net during debugging. That is why the .NET open-source library guidance recommends to enable it for libraries.
The generated NuGet package includes a reference to our git repository as well as the commit that belongs to the version included in the package:
I verified that the Docker build still works with `docker/build.sh`.
VOTE +1
NOTE: We don't need to merge this for the upcoming release, especially since we have have a code freeze (although we don't strictly …

TINKERPOP-2088 Enable SourceLink for Gremlin.Net

---

gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/AbstractStep.java

This PR removes the redundant `Objects.nonNull(id);` call for `setId` method.

Fix NPE is not thrown when null id is set to AbstractStep

---

CHANGELOG.asciidoc
gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV2d0.py
gremlin-python/src/main/jython/gremlin_python/structure/io/graphsonV3d0.py
gremlin-python/src/main/jython/tests/driver/test_driver_remote_connection.py
gremlin-python/src/main/jython/tests/structure/io/test_graphsonV2d0.py
gremlin-python/src/main/jython/tests/structure/io/test_graphsonV3d0.py

We only deserialize those types as a dict. Also, this should probably target tp34 when created.

TINKERPOP-2127: Add Python TraversalMetrics/Metrics deserializers

---

.travis.yml
docker/scripts/build.sh

https://issues.apache.org/jira/browse/TINKERPOP-2140
This additional Travis build job checks whether the Docker build still works.
The job took 21 minutes [on Travis](https://travis-ci.org/apache/tinkerpop/builds/484445855) which is still faster than the Spark job which took 26 minutes. So, this doesn't negatively impact our build times on Travis.
This could also have been a CTR commit, but maybe someone wants to review. Otherwise I'll merge it with lazy consensus.
VOTE +1

TINKERPOP-2140 Add CI smoke test for Docker build on Travis

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/CompilationOptionsCustomizer.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngine.java
gremlin-groovy/src/main/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GroovyCompilerGremlinPlugin.java
gremlin-groovy/src/test/java/org/apache/tinkerpop/gremlin/groovy/jsr223/GremlinGroovyScriptEngineTest.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/Session.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/session/SessionOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerSessionIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2138
Added a new `globalFunctionCacheEnabled` configuration to the `GroovyCompilerGremlinPlugin` and an overriding setting for sessions on `SessionOpProcessor` that disables the global function cache.  In cases where you don't need the cache (i.e. don't use global functions) it does remove a bit of reflection based processing from every single script request and obviously saves on memory formerly used by the cache. 
VOTE +1

TINKERPOP-2138 Provide way to disable the global function cache

---

bin/validate-distribution.sh

https://issues.apache.org/jira/browse/TINKERPOP-2125
Added source file check in release validation script.
VOTE +/-0
At this point, the validation does not pass. We need to make a decision on what to do with the following files:
```
./docs/static/images/gremlin-characters.pdf
./docs/static/images/gremlintron.pdf
./docs/static/images/gremlin-sacks.pdf
./docs/static/images/gremlin-gym.pdf
```
Do we whitelist them or should they be removed from the repository?

TINKERPOP-2125 Extend release validation script

---

CHANGELOG.asciidoc
docs/src/dev/provider/index.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/Connection.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/NioGremlinRequestEncoder.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/handler/WebSocketGremlinRequestEncoder.java
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/message/ResponseStatusCode.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinDriverIntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2139
Prior to this change serialization exceptions were basically just logged because any failure would signal a bad host and mark it as dead, but that's not really what was happening obviously if the client was never even able to try to send the message to the host in the first place. These sorts of client exceptions are now handled better and actually throw an exception that the calling client can see and utilize while not killing the host.
VOTE +1

TINKERPOP-2139 Properly handle client side serialization exceptions

---

CHANGELOG.asciidoc
docker/Dockerfile
hadoop-gremlin/src/main/java/org/apache/tinkerpop/gremlin/hadoop/structure/io/ObjectWritable.java

https://issues.apache.org/jira/browse/TINKERPOP-2126
So, apparently, Spark 2.4.0 has some background logging going on, where it takes objects out of memory and dumps their `toString()` into the log. I don't think we can control when Spark is going to do that, so we have to work around it by making our `toString()` methods thread-safe or handle each `ConcurrentModificationException`. Guaranteeing thread-safety was easy for `TraverserSet` but turned out to be tricky (impossible?) for `ObjectWritable` as it's totally unclear where the objects are coming from and/or where they get modified while Spark is trying to log them.
I don't think we can make any arbitrary object thread-safe, but we can easily catch the `ConcurrentModificationException` and retry until we succeed. `while (true)` looks …

TINKERPOP-2126 Fixed concurrency issue in `ObjectWritable::toString()`.

---

gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/ResponseHandlerContext.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/ResponseHandlerContextTest.java

A Frame may wrap a ReferenceCounted buffer, which is normally released
when it is written back to the client. However, if the Frame is dropped
by ResponseHandlerContext the buffer also has to be released.
---
This is a follow-up fix for #899
----
Testing performed:
* Full suite of unit tests (i.e. `mvn clean install`)
* Full suite of gremlin-server integration tests (`mvn verify -pl gremlin-server -DskipIntegrationTests=false`)
* Manual testing with the Gremlin Server started with `-Dio.netty.leakDetection.level=PARANOID`

Release dropped response Frames in ResponseHandlerContext

---

CHANGELOG.asciidoc
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/auth/Krb5Authenticator.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/handler/SaslAuthenticationHandler.java
gremlin-server/src/main/java/org/apache/tinkerpop/gremlin/server/op/AbstractEvalOpProcessor.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuditLogIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthIntegrateTest.java
gremlin-server/src/test/java/org/apache/tinkerpop/gremlin/server/GremlinServerAuthKrb5IntegrateTest.java

https://issues.apache.org/jira/browse/TINKERPOP-2144
Failures occurred on the first round of a SASL request when the negotiator was being created and if an exception was tossed there neither the server nor driver handled the situation well. By explicitly capturing and handling it, we can now properly assert results in kerberos tests without having to try to assert server logs which wasn't always dependable for some reason. This change should prevent random failures around kerberos tests which has long been a problem.
VOTE +1

TINKERPOP-2144 Better handle Authenticator failures

---

CHANGELOG.asciidoc
docs/src/upgrade/release-3.3.x.asciidoc
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/CoreImports.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategies.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/EarlyLimitStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/LazyBarrierStrategy.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/graphson/GraphSONModule.java
gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/io/gryo/GryoVersion.java
gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/EarlyLimitStrategyTest.java
gremlin-dotnet/src/Gremlin.Net/Process/Traversal/Strategy/Optimization/EarlyLimitStrategy.cs
gremlin-python/src/main/jython/gremlin_python/process/strategies.py
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessComputerSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java
gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/strategy/optimization/EarlyLimitStrategyProcessTest.java
tinkergraph-gremlin/src/test/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerGraphPlayTest.java

https://issues.apache.org/jira/browse/TINKERPOP-1882
VOTE +1

TINKERPOP-1882 Apply range and limit steps as early as possible

---

CHANGELOG.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/binary/TypeSerializerRegistry.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/binary/TypeSerializerRegistryTest.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/binary/types/sample/SamplePerson.java

Provide a way to resolve the `TypeSerializer` instance to use when there isn't any direct match.
VOTE +1

TINKERPOP-2149 Add fallback resolver to TypeSerializerRegistry

---

CHANGELOG.asciidoc
docs/src/reference/gremlin-applications.asciidoc
gremlin-driver/src/main/java/org/apache/tinkerpop/gremlin/driver/ser/GraphBinaryMessageSerializerV1.java
gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/binary/GraphBinaryMessageSerializerV1Test.java

https://issues.apache.org/jira/browse/TINKERPOP-2150
VOTE +1

TINKERPOP-2150 Support configuring the registry builder in config
